### ISSUE TITLE
ImportString serialization fails for `sys.stdout`

### ISSUE THREAD

**Issue by dmder** [pydantic/pydantic#10122]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`ImportThings(obj='sys.stdout')` fails to serialize (see example below)

### Example Code

```Python
from pydantic import BaseModel, ImportString


class ImportThings(BaseModel):
    obj: ImportString


ImportThings(obj='math.cos').model_dump_json()  # ok
ImportThings(obj='sys.stdout').model_dump_json()

Traceback (most recent call last):
  File "...", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File ".../python3.12/site-packages/pydantic/main.py", line 415, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: UnsupportedOperation: not readable
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: .../python3.12/site-packages/pydantic
               python version: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 14:43:12) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.12.1 fastapi-0.111.0 pydantic-settings-2.4.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@dmder,

Good find! I'll root around for a fix.

**Comment by sydney-runkle** [comment]
I should be able to submit a PR tomorrow with a fix for this 👍

**Comment by dmder** [comment]
Thank you @sydney-runkle for such a quick turnaround on this 👍
