### ISSUE TITLE
AttributeError when using __future__ import with PrivateAttr in Pydantic

### ISSUE THREAD

**Issue by Lemminkyinen** [pydantic/pydantic#10153]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using the `__future__` import for annotations in a Pydantic model, the `PrivateAttr` attribute does not get initialized correctly, resulting in an `AttributeError`. The issue does not occur when the `__future__` import is commented out.

### Example Code

```Python
# from __future__ import annotations
import os

from pydantic import BaseModel, PrivateAttr
from typing_extensions import Annotated

class ParentModel(BaseModel):
    name: str
    age: int

class ChildModel(ParentModel):
    _cpu_count: Annotated[int, PrivateAttr(default_factory=os.cpu_count)]

child_instance = ChildModel(name="John Doe", age=30)
count = child_instance._cpu_count
print(count)
# > 16

# -----------------

from __future__ import annotations
import os

from pydantic import BaseModel, PrivateAttr
from typing_extensions import Annotated

class ParentModel(BaseModel):
    name: str
    age: int

class ChildModel(ParentModel):
    _cpu_count: Annotated[int, PrivateAttr(default_factory=os.cpu_count)]

child_instance = ChildModel(name="John Doe", age=30)
count = child_instance._cpu_count
print(count)

# >Traceback (most recent call last):
# >  File "/home/xx/xx/testing/venv/lib/python3.12/site-packages/pydantic/main.py", line 807, in # >__getattr__
# >    return self.__pydantic_private__[item]  # type: ignore
# >           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
# >KeyError: '_cpu_count'
# >
# >The above exception was the direct cause of the following exception:
# >
# >Traceback (most recent call last):
# >  File "/home/xx/xx/testing/pydanticbugg.py", line 19, in <module>
# >    count = child_instance._cpu_count
# >            ^^^^^^^^^^^^^^^^^^^^^^^^^
# >  File "/home/xx/xx/testing/venv/lib/python3.12/site-packages/pydantic/main.py", line 809, in # >__getattr__
# >    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
# > AttributeError: 'ChildModel' object has no attribute '_cpu_count'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/xx/xx/testing/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, May  2 2024, 07:44:29) [GCC 13.2.0]
                     platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Should be fixed by https://github.com/pydantic/pydantic/pull/10157
