### ISSUE TITLE
Unable to subclass model with @computed_field(deprecated=True)

### ISSUE THREAD

**Issue by rossmacarthur** [pydantic/pydantic#10384]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I would expect to be able to subclass this model containing a deprecated computed field.

The error is 
```
Traceback (most recent call last):
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 382, in get_attribute_from_bases
    return getattr(tp, name)
           ^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 262, in __getattr__
    raise AttributeError(item)
AttributeError: resolved_name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/example.py", line 12, in <module>
    class B(A): ...
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 154, in __new__
    cls.__pydantic_decorators__ = DecoratorInfos.build(cls)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 450, in build
    res.computed_fields.update({k: v.bind_to_cls(model_dc) for k, v in existing.computed_fields.items()})
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 450, in <dictcomp>
    res.computed_fields.update({k: v.bind_to_cls(model_dc) for k, v in existing.computed_fields.items()})
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 278, in bind_to_cls
    return self.build(
           ^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 252, in build
    func = get_attribute_from_bases(cls_, cls_var_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 384, in get_attribute_from_bases
    return get_attribute_from_bases(mro(tp), name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_decorators.py", line 377, in get_attribute_from_bases
    return attribute_get(None, tp)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/bikeshed/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 650, in __get__
    raise AttributeError(self.field_name)
AttributeError: resolved_name
```

### Example Code

```Python
from pydantic import BaseModel, computed_field


class A(BaseModel):
    name: str

    @computed_field(deprecated=True)
    def resolved_name(self) -> str:
        return self.name.upper()


class B(A): ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: ~/.pyenv/versions/3.11.7/envs/bikeshed/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec 12 2023, 09:52:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.6.9-arm64-arm-64bit
             related packages: fastapi-0.112.2 pyright-1.1.378 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Thanks for the bug report, I'll work on fix.
