### ISSUE TITLE
`Unable to serialize unknown type: <class 'pydantic._internal._model_construction.ModelMetaclass'>`

### ISSUE THREAD

**Issue by Danipulok** [pydantic/pydantic#10420]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi. Not really sure it's a bug, but we have a use case when we need to specify a field that's other BaseModel type.
So it would be really good if somehow we could dump the type, I guess

### Example Code

```Python
from pydantic import BaseModel


class Foo(BaseModel):
    pass


class Bar(BaseModel):
    foo: type[Foo]


bar = Bar(foo=Foo)
dumped = bar.model_dump(mode="json")
print(dumped)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: D:\Code\project\.venv\Lib\site-packages\pydantic
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.112.1 mypy-1.11.1 pydantic-settings-2.4.0 typing_extensions-4.12.2
                       commit: unknown
```

### Traceback
```
D:\Code\project\.venv\Scripts\python.exe D:\Code\project\.pydantic_mre.py 
Traceback (most recent call last):
  File "D:\Code\project\.pydantic_mre.py", line 13, in <module>
    dumped = bar.model_dump(mode="json")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\project\.venv\Lib\site-packages\pydantic\main.py", line 364, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic._internal._model_construction.ModelMetaclass'>

Process finished with exit code 1
```

**Comment by Viicos** [comment]
You will have to define your own serializer, as many output formats could be used:

```python
from typing import Annotated, Any, TypeVar

from pydantic import BaseModel, PlainSerializer


def ser_type(value: type[Any]) -> str:
    return value.__name__


T = TypeVar('T')

JSONSerializableType = Annotated[type[T], PlainSerializer(ser_type, when_used='json-unless-none')]


class MyType:
    pass


class Test(BaseModel):
    a: JSONSerializableType[MyType]


print(Test(a=MyType).model_dump(mode='json'))
```

**Comment by Danipulok** [comment]
Got it. Thanks a lot for the reply!
