### ISSUE TITLE
Inconsistent validation with complex number

### ISSUE THREAD

**Issue by AntoineD** [pydantic/pydantic#10430]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A field expecting a list of float number is valid for a numpy array of complex number, but a field expecting a float number is not valid for a complex number.

I would expect the behavior to be the same, i.e. the complex number is a valid float number.

The output of the example code below is (forget about the `ComplexWarning`):
```console
/x/python3.11/site-packages/pydantic/main.py:211: ComplexWarning: Casting complex values to real discards the imaginary part
  validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
Traceback (most recent call last):
  File "/x/scratch_10.py", line 10, in <module>
    Model(x=1j, y=array([1.]))
  File "/x/python3.11/site-packages/pydantic/main.py", line 211, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x
  Input should be a valid number [type=float_type, input_value=1j, input_type=complex]
    For further information visit https://errors.pydantic.dev/2.9/v/float_type
```

### Example Code

```Python
from numpy import array
from pydantic import BaseModel


class Model(BaseModel):
    x: float
    y: list[float]

Model(x=1., y=array([1.]))
Model(x=1j, y=array([1.]))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0
        pydantic-core version: 2.23.2
          pydantic-core build: profile=release pgo=false
                 install path: /x/python3.11/site-packages/pydantic
               python version: 3.11.10 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)]
                     platform: Linux-6.10.9-200.fc40.x86_64-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yep, looks like a bug 👍. Can take a look later this week.

**Comment by rawwar** [comment]
I would like to work on this issue. @sydney-runkle, can you please assign me this issue so that others don't duplicate the effort?

**Comment by ambroseling** [comment]
hi @sydney-runkle may I try tackling this issue, thanks!

**Comment by changhc** [comment]
So I just actually tried out the sample code and played around with that complex coercion when I was reading https://github.com/pydantic/pydantic-core/pull/1574. It seems that this is a numpy-only behaviour and thus I'm not sure if we should implement this for all complex numbers _in pydantic_.

> A field expecting a list of float number is valid for a numpy array of complex number

For example, `numpy.array([1j])` has `dtype=complex128`, not the builtin complex type. These numpy complex types perform the coercion and raises a numpy `ComplexWarning` in such cases. If you try your sample code with

```py
Model(x=numpy.complex128(1, 2), y=array([1.]))
```
pydantic won't raise any error either and you'll see the coercion.

> a field expecting a float number is not valid for a complex number

It is not valid for a complex number instantiated with the builtin complex type but such fields do accept `numpy.complex64/complex128`. This, however, is because numpy handles the coercion, not pydantic.

I don't think we should follow this numpy case because coercions can be done differently:
* Simply dropping the imaginary part: this is how numpy does it
* Accepting only complex numbers with a zero imaginary part: this is what I imagine coercion to be like for complex numbers
* No coercion at all: this is the default behaviour of the builtin float type, e.g. `float(complex(1, 2))` gives an error, even when the imaginary part is 0

and there's no point for pydantic to simply follow how it's done in numpy. Users might expect different outcomes.

**Comment by davidhewitt** [comment]
> Accepting only complex numbers with a zero imaginary part: this is what I imagine coercion to be like for complex numbers

I agree fully with this. `numpy` raises a warning for the coercion for dropping the imaginary part, we should not repeat the same design.

I think I will close this issue as the `numpy` behaviour is not caused by us and is I think not a bug.

If someone wants the coercion, please re-open as a new feature request, and we can implement.
