### ISSUE TITLE
Python 3.12 Enum Class Validated Initialization TypeError

### ISSUE THREAD

**Issue by Lemminkyinen** [pydantic/pydantic#10593]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using Pydantic's `@validate_call` decorator on the `__init__` method of an Enum-based class, a `ValidationError` is raised during member initialization in Python 3.12, and the process fails with a `TypeError: No constructor defined`.

### Example Code

```Python
from enum import Enum
from typing import Annotated

from pydantic import Field, validate_call


class ValidateEnumBase(Enum):
    @validate_call
    def __init__(self, value1: str, value2: Annotated[int, Field(ge=0)]):
        self.value1 = value1
        self.value2 = value2


class MyValidatedEnum(ValidateEnumBase):
    VARIANT1 = ("something", 1)
    VARIANT2 = ("else", -1)


# (venv) $ /xxx/venv/bin/python /xxx/enum_example.py
# Traceback (most recent call last):
#   File "/usr/local/lib/python3.12/enum.py", line 596, in __new__
#     enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
#                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/usr/local/lib/python3.12/enum.py", line 287, in __set_name__
#     enum_member.__init__(*args)
#   File "/xxx/venv/lib/python3.12/site-packages/pydantic/validate_call_decorator.py", line 60, in wrapper_function
#     return validate_call_wrapper(*args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/xxx/venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 96, in __call__
#     res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# pydantic_core._pydantic_core.ValidationError: 1 validation error for __init__
# 2
#   Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-1, input_type=int]
#     For further information visit https://errors.pydantic.dev/2.8/v/greater_than_equal
# Error calling __set_name__ on '_proto_member' instance 'VARIANT2' in 'MyValidatedEnum'

# During handling of the above exception, another exception occurred:

# Traceback (most recent call last):
#   File "/xxx/enum_example.py", line 14, in <module>
#     class MyValidatedEnum(ValidateEnumBase):
#   File "/usr/local/lib/python3.12/enum.py", line 601, in __new__
        # try:
        #     exc = None
        #     enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
        # except Exception as e:
        #     # since 3.12 the line "Error calling __set_name__ on '_proto_member' instance ..."
        #     # is tacked on to the error instead of raising a RuntimeError
        #     # recreate the exception to discard
        #     exc = type(e)(str(e))
#           ^^^^^^^^^^^^^^^
# TypeError: No constructor defined
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/xxx/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, May  2 2024, 07:44:29) [GCC 13.2.0]
                     platform: Linux-6.8.0-41-generic-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
@Lemminkyinen, this just got fixed and backported to 3.12, so upgrading to the latest Python 3.12 patch release once it gets released will fix the issue.
