### ISSUE TITLE
(🐞) `RecursionError` when object has a reference to itself

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10630]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
  [Previous line repeated 370 more times]
  File "C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic\main.py", line 961, in __eq__
    if isinstance(other, BaseModel):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 273, in __instancecheck__
    return hasattr(instance, '__pydantic_validator__') and super().__instancecheck__(instance)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 119, in __instancecheck__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Example Code

```Python
from __future__ import annotations

from pydantic import BaseModel


class A(BaseModel):
    a: A = None


a = A()
a.a = a
a2 = A()
a2.a = a2

a == a2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Indeed, a bug. Quite the edge case here 😉. PRs welcome with a fix, would require some sort of recursion guard in the `__instancecheck__` logic.

**Comment by jmin-pingu** [comment]
Hello! I'm a first-time contributor and I was wondering I could work on this issue. I'll begin looking into it.

**Comment by vodkar** [comment]
It behaves similar, if we create python dictionary:

```python
d = {}
d["d"] = d
d2 = {}
d2["d"] = d2
d == d2
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded in comparison
```

Is this really pydantic issue? Looks like cpython behaves in this manner.
It's possible to add a recursion check, but it might lead to performance degradation.

**Comment by joabreu** [comment]
Potential fix is in `__eq__` from BaseModel, avoiding using direct `__dict__` comparison and sanitize first for self referencing:

```
class A(BaseModel):
    a: A | None = None
    b: int

    def __eq__(self, other):
        self_dict = { }
        for k, v in self.__dict__.items():
            if isinstance(v, BaseModel) and id(v) != id(self):
                self_dict[k] = v

        other_dict = { }
        for k, v in other.__dict__.items():
            if isinstance(v, BaseModel) and id(v) != id(self):
                other_dict[k] = v

        return self_dict == other_dict
```

Test Case:
```
mA = A(b=10)
mA.a = mA

mB = A(b=10)
mB.a = mB

mC = A(b=15)
mC.a = mC

mD = A(b=10)
mD.a = mA

mE = A(b=10)
mE.a = mB

assert not mA == mB # Same params and using self ref -> different
assert not mA == mC # Different params and using self ref -> different
assert mA == mD # Same params, same ref -> equal
assert not mA == mE # Same params, different ref -> different
```

But, I'm not confident about performance here with this approach.

**Comment by ZeroIntensity** [comment]
Note that this was referenced in a CPython upstream report: https://github.com/python/cpython/issues/126749. We're pretty sure it's not an issue on our end (or at least, anything we'd want to fix). Let me know if there's anything else that's problematic here, but as I said in that issue: play stupid circular games, win stupid `RecursionError`s.

**Comment by Zeckie** [comment]
In our case, our objects had references to other objects (parents had list of children, children had reference back to parent) that we didn't need to be included in the comparison. Dataclass's `field(compare=False)` or https://github.com/pydantic/pydantic/discussions/6717 would solve it for us.

**Comment by Zeckie** [comment]
Also, is this a duplicate of #4780 ?

**Comment by TathagataSen06** [comment]
Hi! I'm new to Pydantic and interested in contributing. Can you confirm if this issue is still open and help me understand the expected fix?
