### ISSUE TITLE
TypeAdapter gives weird exception.

### ISSUE THREAD

**Issue by stefanodvx** [pydantic/pydantic#10636]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! I think I'm using TypeAdapters in the wrong way :(
I can't use a `TypeAdapter` as type of a field in my `BaseModel` (see `BackgroundTypeFill`)
How can I fix this without allowing arbitrary data in the model?

Here's the full exception (`botapi` is my own package):
```
Traceback (most recent call last):
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ste/uvd-v3/main.py", line 4, in <module>
    from botapi.api import BotAPI
  File "/home/ste/.local/lib/python3.11/site-packages/botapi/__init__.py", line 1, in <module>
    from .api import BotAPI
  File "/home/ste/.local/lib/python3.11/site-packages/botapi/api.py", line 4, in <module>
    from botapi.methods import Methods
  File "/home/ste/.local/lib/python3.11/site-packages/botapi/methods.py", line 9, in <module>
    from botapi.types import (
  File "/home/ste/.local/lib/python3.11/site-packages/botapi/types.py", line 3210, in <module>
    BackgroundType = TypeAdapter(
                     ^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 650, in generate_schema
    from_property = self._generate_schema_from_property(obj, obj)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 821, in _generate_schema_from_property
    schema = get_schema(
             ^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/main.py", line 671, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ste/.local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <pydantic.type_adapter.TypeAdapter object at 0x7f21b0246590>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type

```

### Example Code

```Python
...
BackgroundFill = TypeAdapter(
    Union[
        BackgroundFillSolid,
        BackgroundFillGradient,
        BackgroundFillFreeformGradient,
    ]
)

class BackgroundTypeFill(BaseModel):
    type: Literal["fill"] = "fill"
    fill: BackgroundFill
    dark_theme_dimming: int

class BackgroundTypeWallpaper(BaseModel):
    type: Literal["wallpaper"] = "wallpaper"
    document: Document
    dark_theme_dimming: int
    is_blurred: Optional[bool] = Field(default=None)
    is_moving: Optional[bool] = Field(default=None)

class BackgroundTypePattern(BaseModel):
    type: Literal["pattern"] = "pattern"
    document: Document
    fill: BackgroundFill
    intensity: int
    is_inverted: Optional[bool] = Field(default=None)
    is_moving: Optional[bool] = Field(default=None)

class BackgroundTypeChatTheme(BaseModel):
    type: Literal["chat_theme"] = "chat_theme"
    theme_name: str

BackgroundType = TypeAdapter(
    Union[
        BackgroundTypeFill,
        BackgroundTypeWallpaper,
        BackgroundTypePattern,
        BackgroundTypeChatTheme,
    ]
)
...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/ste/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.10 (main, Sep  7 2024, 18:35:42) [GCC 9.4.0]
                     platform: Linux-5.4.0-186-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.12.2 fastapi-0.115.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Yes, `TypeAdapter`s aren't meant to be used as a field annotation. What are you trying to achieve?

**Comment by stefanodvx** [comment]
@Viicos Thank you for your reply.
I'm trying to create a type that stores an Union, for example `BackgroundFill` which is an Union of different `BaseModel`s. I'm using `TypeAdapter` so I can directly use `BackgroundFill.validate_python(...)` and it will return the right model based on the input data. Maybe I can take a better approach? What do you suggest?

**Comment by Viicos** [comment]
By

> will return the right model based on the input data

do you mean _the right model_ class? As is, not an instance of the model, but the model class itself?

**Comment by stefanodvx** [comment]
I mean the proper model instance, like `TypeAdapter` does.

**Comment by sydney-runkle** [comment]
Marking as resolved. I think you can just use `Union[A, B, ...]` as your annotation.
