### ISSUE TITLE
Circular reference error when serializing custom passthrough class from __pydantic_extra__

### ISSUE THREAD

**Issue by sneakers-the-rat** [pydantic/pydantic#10654]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have an edge case that i swear is an actual problem and not just esoteric bughunting.

To support multiple array backends from a single `NDArray` type in [numpydantic](https://github.com/p2p-ld/numpydantic), I use it as an abstract passthrough class that validates the data but then returns one of potentially multiple types (numpy ndarray, dask array, proxy to an hdf5 array, etc., more info in [docs](https://numpydantic.readthedocs.io/en/latest/interfaces.html)).

This works, including roundtrip json serialization, *except* when the type is specified on the `__pydantic_extra__` field like `__pydantic_extra__: dict[str, NDArray]` . Then pydantic seems to lose the connection between the object that's passed through and the `NDArray` object, and attempts to serialize the object directly (rather than using the serialization schema created by `NDArray.__get_pydantic_core_schema__` ). 

I have been trying to work around this by giving `__pydantic_serializer__` declarations to the passed through types, but i have been running up against a consistent problem with the recursion checker:

```
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: ValueError: Circular reference detected (id repeated)
```

I've dug around in that code a bit, and it seems like it's a very tight check whether or not an id has been seen before, but I can't really tell here where it might have been repeated. I'm not sure what a fix here looks like because i can't tell if this is a bug or i'm doing something wrong. 

I fully acknowledge this is a relatively offroad, nonstandard usages of maybe not fully finished APIs, so apologize in advance.  If it does look like a bug to y'all, i would be happy to help with a patch, as i am always looking for more reasons to learn more about bilingual rust/python projects <3.

Below is a MWE that reproduces the error so you don't have to dig through all the numpydantic code :)

### Example Code

```Python
from pydantic import BaseModel, ConfigDict
from pydantic_core import SchemaSerializer, core_schema


def jsonize(x):
    return [1,2,3]

def passthrough(x):
    return x

class SerializableClass:

    __pydantic_serializer__ = SchemaSerializer(
        core_schema.plain_serializer_function_ser_schema(
            jsonize, when_used="json"
        )
    )
    
class AnnotationClass:
    
    def __get_pydantic_core_schema__(self, *args):
        return core_schema.no_info_plain_validator_function(
            passthrough
        )


class MyModel(BaseModel):
    __pydantic_extra__: dict[str, AnnotationClass]

    model_config = ConfigDict(extra="allow")


instance = MyModel(field=SerializableClass())

instance.model_dump_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jonny/git/p2p-ld/numpydantic/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.6 (main, Oct  2 2024, 16:53:48) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-x86_64-i386-64bit
             related packages: mypy-1.11.2 pydantic-settings-2.5.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sneakers-the-rat** [comment]
I couldn't get the [instructions for debugging](https://www.loom.com/embed/71019f8b92b04839ae233eb70c23c5b5?sid=1ea39ca9-d0cc-494b-8214-159f7cc26190) working, but i have managed to get my own extremely janky print-statements-as-debugger thing happening, and as far as I can tell we are double-tapping the recursion guard for extra fields?

For the above models, if I insert some print statements at the [start of the `Extra::recursion_guard` method](https://github.com/pydantic/pydantic-core/blob/92a259ea10113e0d41dea5b14dc8745e3bf671ef/src/serializers/extra.rs#L191) like this:

```rust
// ...
    ) -> PyResult<RecursionGuard<'x, &'y Self>> {
        println!("-----------");
        println!("value: {:#?}", value);
        println!("backtrace: {}", Backtrace::force_capture());
        RecursionGuard::new(self, value.as_ptr() as usize, def_ref_id).map_err(|e| match e {
// ...
```

then I get the following traceback:

<details>
<summary>expand/collapse traceback</summary>

```
-----------
value: <__main__.SerializableClass object at 0x1049ef140>
backtrace:    0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/backtrace.rs:331:13
   3: std::backtrace::Backtrace::force_capture
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/backtrace.rs:312:9
   4: _pydantic_core::serializers::extra::Extra::recursion_guard
             at ./src/serializers/extra.rs:196:35
   5: _pydantic_core::serializers::infer::infer_serialize_known
             at ./src/serializers/infer.rs:365:27
   6: <_pydantic_core::serializers::infer::SerializeInfer as serde::ser::Serialize>::serialize
             at ./src/serializers/infer.rs:335:9
   7: <_pydantic_core::serializers::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value
             at ./src/serializers/ser.rs:569:22
   8: serde::ser::SerializeMap::serialize_entry
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.210/src/ser/mod.rs:1817:9
   9: <_pydantic_core::serializers::fields::GeneralFieldsSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/fields.rs:453:21
  10: <_pydantic_core::serializers::shared::CombinedSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/shared.rs:261:1
  11: <_pydantic_core::serializers::type_serializers::model::ModelSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/type_serializers/model.rs:242:13
  12: <_pydantic_core::serializers::shared::CombinedSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/shared.rs:261:1
  13: <_pydantic_core::serializers::shared::PydanticSerializer as serde::ser::Serialize>::serialize
             at ./src/serializers/shared.rs:337:9
  14: _pydantic_core::serializers::shared::to_json_bytes
             at ./src/serializers/shared.rs:365:13
  15: _pydantic_core::serializers::SchemaSerializer::to_json
             at ./src/serializers/mod.rs:199:21
  16: _pydantic_core::serializers::SchemaSerializer::__pymethod_to_json__
             at ./src/serializers/mod.rs:87:1
  17: pyo3::impl_::trampoline::fastcall_with_keywords::{{closure}}
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:44:29
  18: pyo3::impl_::trampoline::trampoline::{{closure}}
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:188:54
  19: std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  20: ___rust_try
  21: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  22: std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  23: pyo3::impl_::trampoline::trampoline
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:188:9
  24: pyo3::impl_::trampoline::fastcall_with_keywords
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:44:13
  25: _pydantic_core::serializers::<impl pyo3::impl_::pyclass::PyMethods<_pydantic_core::serializers::SchemaSerializer> for pyo3::impl_::pyclass::PyClassImplCollector<_pydantic_core::serializers::SchemaSerializer>>::py_methods::ITEMS::trampoline
             at ./src/serializers/mod.rs:87:1
  26: _method_vectorcall_FASTCALL_KEYWORDS
  27: _PyObject_Vectorcall
  28: __PyEval_EvalFrameDefault
  29: _PyEval_EvalCode
  30: _run_mod
  31: _pyrun_file
  32: __PyRun_SimpleFileObject
  33: __PyRun_AnyFileObject
  34: _pymain_run_file_obj
  35: _pymain_run_file
  36: _Py_RunMain
  37: _pymain_main
  38: _Py_BytesMain
  39: <unknown>

-----------
value: <__main__.SerializableClass object at 0x1049ef140>
backtrace:    0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/backtrace.rs:331:13
   3: std::backtrace::Backtrace::force_capture
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/backtrace.rs:312:9
   4: _pydantic_core::serializers::extra::Extra::recursion_guard
             at ./src/serializers/extra.rs:196:35
   5: _pydantic_core::serializers::infer::infer_serialize_known
             at ./src/serializers/infer.rs:365:27
   6: _pydantic_core::serializers::infer::infer_serialize
             at ./src/serializers/infer.rs:346:5
   7: <_pydantic_core::serializers::type_serializers::any::AnySerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/type_serializers/any.rs:64:9
   8: <_pydantic_core::serializers::shared::CombinedSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/shared.rs:261:1
   9: <_pydantic_core::serializers::shared::PydanticSerializer as serde::ser::Serialize>::serialize
             at ./src/serializers/shared.rs:337:9
  10: _pydantic_core::serializers::infer::infer_serialize_known
             at ./src/serializers/infer.rs:513:13
  11: <_pydantic_core::serializers::infer::SerializeInfer as serde::ser::Serialize>::serialize
             at ./src/serializers/infer.rs:335:9
  12: <_pydantic_core::serializers::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value
             at ./src/serializers/ser.rs:569:22
  13: serde::ser::SerializeMap::serialize_entry
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.210/src/ser/mod.rs:1817:9
  14: <_pydantic_core::serializers::fields::GeneralFieldsSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/fields.rs:453:21
  15: <_pydantic_core::serializers::shared::CombinedSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/shared.rs:261:1
  16: <_pydantic_core::serializers::type_serializers::model::ModelSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/type_serializers/model.rs:242:13
  17: <_pydantic_core::serializers::shared::CombinedSerializer as _pydantic_core::serializers::shared::TypeSerializer>::serde_serialize
             at ./src/serializers/shared.rs:261:1
  18: <_pydantic_core::serializers::shared::PydanticSerializer as serde::ser::Serialize>::serialize
             at ./src/serializers/shared.rs:337:9
  19: _pydantic_core::serializers::shared::to_json_bytes
             at ./src/serializers/shared.rs:365:13
  20: _pydantic_core::serializers::SchemaSerializer::to_json
             at ./src/serializers/mod.rs:199:21
  21: _pydantic_core::serializers::SchemaSerializer::__pymethod_to_json__
             at ./src/serializers/mod.rs:87:1
  22: pyo3::impl_::trampoline::fastcall_with_keywords::{{closure}}
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:44:29
  23: pyo3::impl_::trampoline::trampoline::{{closure}}
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:188:54
  24: std::panicking::try::do_call
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  25: ___rust_try
  26: std::panicking::try
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  27: std::panic::catch_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  28: pyo3::impl_::trampoline::trampoline
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:188:9
  29: pyo3::impl_::trampoline::fastcall_with_keywords
             at /Users/jonny/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.22.3/src/impl_/trampoline.rs:44:13
  30: _pydantic_core::serializers::<impl pyo3::impl_::pyclass::PyMethods<_pydantic_core::serializers::SchemaSerializer> for pyo3::impl_::pyclass::PyClassImplCollector<_pydantic_core::serializers::SchemaSerializer>>::py_methods::ITEMS::trampoline
             at ./src/serializers/mod.rs:87:1
  31: _method_vectorcall_FASTCALL_KEYWORDS
  32: _PyObject_Vectorcall
  33: __PyEval_EvalFrameDefault
  34: _PyEval_EvalCode
  35: _run_mod
  36: _pyrun_file
  37: __PyRun_SimpleFileObject
  38: __PyRun_AnyFileObject
  39: _pymain_run_file_obj
  40: _pymain_run_file
  41: _Py_RunMain
  42: _pymain_main
  43: _Py_BytesMain
  44: <unknown>

Traceback (most recent call last):
  File "/Users/jonny/git/pydantic-core/test.py", line 43, in <module>
    instance.model_dump_json()
  File "/Users/jonny/git/pydantic/pydantic/main.py", line 471, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: ValueError: Circular reference detected (id repeated)
```

</details>

So we correctly arrive at the infer serialization method, here: https://github.com/pydantic/pydantic-core/blob/92a259ea10113e0d41dea5b14dc8745e3bf671ef/src/serializers/infer.rs#L356

Then we make a recursion guard, which triggers inserting the id of the `value` into the `extra`'s recursion state, and also causes the first print of the traceback: https://github.com/pydantic/pydantic-core/blob/92a259ea10113e0d41dea5b14dc8745e3bf671ef/src/serializers/infer.rs#L365

Then we continue and also correctly match against `ObType::PydanticSerializable`, and that seems to start the serialization process over again, where now through the `AnySerializer` we repeat the same infer loop and land back at `serializers/infer.rs#L365`, instantiating the recursion guard again with the same object twice.

So this leads me to suspect that the passthrough part is irrelevant, and in fact any object that has a `__pydantic_serializer__` in `__pydantic_extra__` will fail.

I confirmed this with this MWE

```python
from pydantic import BaseModel, ConfigDict
from pydantic_core import SchemaSerializer, core_schema

def jsonize(x):
    return [1,2,3]

class SerializableClass:

    __pydantic_serializer__ = SchemaSerializer(
        core_schema.plain_serializer_function_ser_schema(
            jsonize, when_used="json"
        )
    )

    @classmethod
    def __get_pydantic_core_schema__(self, *args):
        return core_schema.any_schema()
    

class MyModel(BaseModel):
    real_field: SerializableClass | None = None
    __pydantic_extra__: dict[str, SerializableClass]

    model_config = ConfigDict(extra="allow")

# Fails - Circular reference
instance = MyModel(real_field=SerializableClass())
instance.model_dump_json()

# Fails - Circular Reference
instance = MyModel(extra_field=SerializableClass())
instance.model_dump_json()
```

Interestingly, that also fails when instantiating the model without having any actual extra field (the `real_field` case above) - it seems as if having an annotation like `__pydantic_extra__: dict[str, SerializableClass]` is enough to trigger the behavior, which is somewhat surprising to me, because my expectation would be that if i didn't pass any extra values that that annotation would be unused (i.e., being an "extra" field, i would expect the value in the dict to always implicitly be `Optional[T]`).

As in the initial set of examples, if i instead declare the serializer function in `__get_pydantic_core_schema__`, i am back to getting "`Unable to serialize unknown type: <SerializableClass>`" on the second case where it is supplied as `extra_field` despite `SerializableClass` having a pydantic core schema.

```python
class SerializableClass:

    def __get_pydantic_core_schema__(self, *args):
        return core_schema.any_schema(serialization=core_schema.plain_serializer_function_ser_schema(
            jsonize, when_used="json"
        ))
```

**Comment by sneakers-the-rat** [comment]
oh holy hell. just after posting that, I went back and read `complete_model_class` again and see that the *whole core schema* is passed to `SchemaSerializer`. 

With this, now the `real_field` case works, but the `extra_field` is still giving `Unable to serialize unknown type: <class '__main__.SerializableClass'>`

```python
from pydantic import BaseModel, ConfigDict
from pydantic_core import SchemaSerializer, core_schema

def jsonize(*args, **kwargs):
    return [1,2,3]

class SerializableClass:
    @classmethod
    def __get_pydantic_core_schema__(self, *args):
        return core_schema.any_schema(
            serialization=core_schema.plain_serializer_function_ser_schema(
                jsonize, when_used="json"
            )
        )
    

class MyModel(BaseModel):
    real_field: SerializableClass | None = None
    __pydantic_extra__: dict[str, SerializableClass]

    model_config = ConfigDict(extra="allow")

# Succeeds!
instance = MyModel(real_field=SerializableClass())
instance.model_dump_json()

# Fails - Unable to serialize unknown type
instance = MyModel(extra_field=SerializableClass())
instance.model_dump_json()
```

And if I do this then both cases work:

```python
from pydantic import BaseModel, ConfigDict
from pydantic_core import SchemaSerializer, core_schema

def jsonize(*args, **kwargs):
    return [1,2,3]

class SerializableClass:

    __pydantic_serializer__ = SchemaSerializer(
        core_schema.any_schema(
            serialization=core_schema.plain_serializer_function_ser_schema(
                jsonize, when_used="json"
            )
        )
    )

    @classmethod
    def __get_pydantic_core_schema__(self, *args):
        return core_schema.any_schema(
            serialization=core_schema.plain_serializer_function_ser_schema(
            jsonize, when_used="json"
            )
        )
    

class MyModel(BaseModel):
    real_field: SerializableClass | None = None
    __pydantic_extra__: dict[str, SerializableClass]

    model_config = ConfigDict(extra="allow")

# Succeeds!
instance = MyModel(real_field=SerializableClass())
instance.model_dump_json()

# Succeeds!
instance = MyModel(extra_field=SerializableClass())
instance.model_dump_json()
```

And returning to the passthrough example from OP, this works for both:

```python
from pydantic import BaseModel, ConfigDict, TypeAdapter
from pydantic_core import SchemaSerializer, core_schema, SchemaValidator


def jsonize(x):
    return [1,2,3]

def passthrough(x):
    return x

class SerializableClass:
    __pydantic_serializer__ = SchemaSerializer(
        core_schema.any_schema(
            serialization=core_schema.plain_serializer_function_ser_schema(
                jsonize, when_used="json"
            )
        )
    )

    
class AnnotationClass:
    
    @classmethod
    def __get_pydantic_core_schema__(self, *args):
        return core_schema.no_info_plain_validator_function(
            passthrough,
            serialization=core_schema.plain_serializer_function_ser_schema(
                 jsonize, when_used="json"
             )
        )


class MyModel(BaseModel):
    real_field: AnnotationClass | None = None
    __pydantic_extra__: dict[str, AnnotationClass]

    model_config = ConfigDict(extra="allow")

# Works!
instance = MyModel(real_field=SerializableClass())
instance.model_dump_json()

# Works!
instance = MyModel(extra_field=SerializableClass())
instance.model_dump_json()
```

And i'm seeing this is also some of what `TypeAdapter` does, though I can't use TypeAdapters here I don't think because i'm wrapping eg. a numpy array and it needs to behave exactly like a numpy array.

OK sorry for making a mess here - I think the actual bug is just that objects with `__get_pydantic_core_schema__`  when used as an annotation in `__pydantic_extra__` don't have their serializers correctly evaluated as they are when used as regular fields - so i need to additionally define `__pydantic_serializer__` manually rather than having pydantic evaluate it when it's defined in `__get_pydantic_core_schema__`
