### ISSUE TITLE
AnyUrl claims to require a host, but doesn't

### ISSUE THREAD

**Issue by cjwatson** [pydantic/pydantic#10684]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The [documentation](https://docs.pydantic.dev/2.9/api/networks/) for `AnyUrl` says "Host required".  However, this isn't actually true if you provide a URL with a scheme where the Rust `url` crate doesn't require a host, which I think is any scheme other than `http`, `https`, `ws`, `wss`, or `ftp`.

Comparing v1 (via the backward-compatibility layer in 2.9.2, but 1.10.4 behaves the same way):

```pycon
>>> import pydantic.v1
>>> pydantic.v1.parse_obj_as(pydantic.v1.AnyUrl, "file:///etc/passwd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pydantic/v1/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ParsingModel[AnyUrl]
__root__
  URL host invalid (type=value_error.url.host)
```

... with v2 (2.9.2):

```pycon
>>> import pydantic
>>> pydantic.TypeAdapter(pydantic.AnyUrl).validate_python("file:///etc/passwd")
Url('file:///etc/passwd')
```

I work on a web application that uses pydantic (currently v1; we'll upgrade to v2 at some point after the next Debian release comes out) to parse and validate parameters for worker tasks.  In a small number of cases, these are allowed to use data from external URLs; we didn't expect this to allow `file://` URLs since it didn't in v1.  I haven't worked out whether this would actually be a security problem for us - the tasks in question are already run in containers so it may be OK - but it was certainly a surprise when I noticed this, and it's contrary to pydantic's own documentation.

Is this a bug in `AnyUrl` or a documentation error?  I'd be inclined to say that `AnyUrl` should include a `host_required=True` constraint to avoid compatibility surprises, but if you think the right thing to do is to change the documentation then I think this deserves an entry in the migration guide too.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /usr/lib/python3/dist-packages/pydantic
               python version: 3.12.6 (main, Sep  7 2024, 14:20:15) [GCC 14.2.0]
                     platform: Linux-6.10.11-amd64-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 mypy-1.12.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yep, looks like a bug, working on a fix now. Thanks!
