### ISSUE TITLE
Cannot create dataclass inheriting from Generic

### ISSUE THREAD

**Issue by jonathanasdf** [pydantic/pydantic#10689]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    @pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/pydantic/dataclasses.py", line 224, in create_dataclass
    generic_base = Generic[cls.__parameters__]  # type: ignore
                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "python3.11/typing.py", line 379, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "python3.11/typing.py", line 1848, in __class_getitem__
    raise TypeError(
TypeError: Parameter list to Generic[...] cannot be empty
```

### Example Code

```Python
import dataclasses
from typing import Generic, TypeVar

import pydantic

T = TypeVar('T')


@dataclasses.dataclass
class Base(Generic[T]):
  pass


@pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
class Derived(Base[int]):
  pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.7-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Seems to be fixed on main (not sure which commit). @jonathanasdf do not hesitate to let me know if this works on your end (you can install `2.12.0a1`).

**Comment by jonathanasdf** [comment]
@Viicos the script above does indeed work now but the issue still persists if I make Derived a dataclass first.

```python
import dataclasses
from typing import Generic, TypeVar

import pydantic

T = TypeVar('T')


@dataclasses.dataclass
class Base(Generic[T]):
  pass


@pydantic.dataclasses.dataclass(config=pydantic.config.ConfigDict(arbitrary_types_allowed=True))
@dataclasses.dataclass
class Derived(Base[int]):
  pass
```
