### ISSUE TITLE
PEP 695 types with reference to `Enum` inside annotation breaks `pydantic_core`

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#10877]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Without annotation it works fine, but whenever it is wrapped inside an annotation it seems to break:
```shell
/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/bin/python /data/can-data/Projects/bikipy/t.py 
Traceback (most recent call last):
  File "/data/can-data/Projects/bikipy/t.py", line 16, in <module>
    class MyClass(BaseModel):
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 595, in complete_model_class
    cls.__pydantic_validator__ = create_schema_validator(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/plugin/_schema_validator.py", line 50, in create_schema_validator
    return SchemaValidator(schema, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Definitions error: definition `__main__.MyEnum:888676848` was never filled
```

### Example Code

```Python
from enum import Enum
from typing import Annotated

from pydantic import BaseModel
from typing_extensions import Doc


class MyEnum(Enum):
    A = "a"
    B = "b"


type MyEnumType = Annotated[MyEnum, Doc("My enum type.")]


class MyClass(BaseModel):
    my_attr: MyEnumType
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0]
                     platform: Linux-6.6.59-x86_64-with-glibc2.40
             related packages: pydantic-settings-2.6.1 pyright-1.1.389 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Also under the scope of https://github.com/pydantic/pydantic/issues/9782

**Comment by Viicos** [comment]
This is fixed on `main` (might be because of https://github.com/pydantic/pydantic/pull/10809), and https://github.com/pydantic/pydantic/pull/11109 fixes it "officially".
