### ISSUE TITLE
PEP 695 syntax is incompatible with `typing.ClassVar` types

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#10875]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`typing.ClassVar` unrecognized when using PEP 695 `type` syntax. Output from code below:
```python
Traceback (most recent call last):
  File "/data/can-data/Projects/bikipy/t.py", line 10, in <module>
    class MyClass(BaseModel):
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 577, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 671, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 991, in match_type
    return self._type_alias_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1412, in _type_alias_type_schema
    schema = self.generate_schema(annotation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1087, in _match_generic_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.ClassVar[typing.Annotated[str, Doc('MyType')]]. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

### Example Code

```Python
from typing import Annotated, ClassVar

from pydantic import BaseModel

from typing_extensions import Doc

type MyType = ClassVar[Annotated[str, Doc("MyType")]]


class MyClass(BaseModel):
    my_attr: MyType
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/can/.cache/pypoetry/virtualenvs/bikipy-mu4xEx7I-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [GCC 13.3.0]
                     platform: Linux-6.6.59-x86_64-with-glibc2.40
             related packages: pydantic-settings-2.6.1 pyright-1.1.389 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
I don't think we are going to support this use case. It is invalid according to the type checking specification, as `ClassVar` should be used as a class annotation. Instead, you can define your class variable this way:

```python
type MyType = Annotated[str, Doc("MyType")]


class MyClass(BaseModel):
    my_attr: ClassVar[MyType]
```

**Comment by caniko** [comment]
@Viicos, if it works with `TypeAlias` it should also work with PEP 695

**Comment by Viicos** [comment]
Quoting the [typing specification section](https://typing.readthedocs.io/en/latest/spec/class-compat.html#classvar) regarding `ClassVar` (emphasis mine):

> A [type qualifier](https://typing.readthedocs.io/en/latest/spec/glossary.html#term-type-qualifier) `ClassVar[T]` exists in the [typing](https://docs.python.org/3/library/typing.html#module-typing) module. It accepts only a single argument that should be a valid type, and is used _to annotate class variables_ that should not be set on class instances.

While it is not explicitly stated that the `ClassVar` type qualifier shouldn't be used outside class definitions, this section describes the intended context: annotating class variables. The conformance tests also [cover this](https://github.com/python/typing/blob/438dc29b11d03ed446209a5f156684b6084fc1ec/conformance/tests/classes_classvar.py#L71-L72) explicitly.

> if it works with TypeAlias it should also work with PEP 695

It works at runtime because it doesn't matter if you annotate with `TypeAlias` or not. At runtime, there's no difference, and it works because this is a simple assignment and at runtime, this is equivalent:

```python
MyType: TypeAlias = ClassVar[Annotated[str, Doc("MyType")]]
# equivalent to:
MyType = ClassVar[Annotated[str, Doc("MyType")]]


class A:
    typ: MyType
    # equivalent to:
    typ: ClassVar[Annotated[str, Doc("MyType")]]
```

So indeed this will work at runtime. But static type checkers will raise an error, and we don't want to unnecessarily deviate from the spec.

Besides, I would suggest avoiding going this way:
- when reading the source code of the model, it is not immediately clear that the variable is a `ClassVar`. You have to check the definition of the type alias first
- type checkers don't understand the alias correctly (see [this example](https://pyright-play.net/?enableExperimentalFeatures=true&code=GYJw9gtgBAJghgFzgYwDZwM4YKYagSwgAcwQFZEV0sBYAKFEigQE8j8A7AcwONPIDC1DADU4IADRQAKm2wBBVPkz16AWRayi2AFwy5i5XgC8UIZlHiA2pwQBdVXXoABeEjQX6HrFHk76UIFQcHoaWtgBQQBGeuZYYiA2HPaO9CDYAG7YcKgA%2BqzaABTyAHRwAJRBVYEAxL4cLGmZ2XkF2MUlUZXVQXW2TVk5%2BXIdubmc%2BAhj3XUARIU4qMB68lIh9SyVALQAfFAAcmAc2LP0QA)).

**Comment by caniko** [comment]
Thank you for providing further information.

The phrases "annotate class variables" and "class annotation" are not equivalent, which means your earlier argument was incorrect and your current argument is new. That said, I would argue that the type checkers are in the wrong and should be patched.

I have created an issue on the [mypy](https://github.com/python/mypy/issues/18226) repository

I have a personal rule: when a debate shifts from facts to opinions, I choose to step back and let those in authority decide. This appears to be one of those situations.

**Comment by Viicos** [comment]
> The phrases "annotate class variables" and "class annotation" are not equivalent, which means your earlier argument was incorrect and your current argument is new.

Yes, "class annotation" is not a properly defined term in the typing specification, but it was obvious that "class annotation" ~ "annotation used in a class definition".

> That said, I would argue that the type checkers are in the wrong and should be patched.
> 
> I have created an issue on the [mypy](https://github.com/python/mypy/issues/18226) repository

If you want to propose such a change, mypy is not the right place. Instead, you should open a discussion on the Python forum [here](https://discuss.python.org/c/typing/32) (as specified in the [typing spec readme](https://github.com/python/typing?tab=readme-ov-file#documentation-and-support)).

But to be honest, I'm pretty confident your request will be rejected, unless you provide compelling arguments. The runtime implementation of the `typing` module even has a type checking mechanism in place to disallow using `ClassVar` in certain contexts ([source](https://github.com/python/cpython/blob/04673d2f14414fce7a2372de3048190f66488e6e/Lib/typing.py#L175)) (in Pydantic, we enforce `allow_special_forms=True` to have more flexibility, but this is not the default behavior when using `typing.get_type_hints`).
