### ISSUE TITLE
Known v2.10 Issues - Fixes in Progress

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10910]
- [ ] https://github.com/pydantic/pydantic/issues/10907
- [ ] https://github.com/pydantic/pydantic/issues/10905

**Comment by dga-nagra** [comment]
Hi,

I just got this error reported from a pipeline:
![image](https://github.com/user-attachments/assets/5bd7c320-5a0b-43a7-8e5c-dcadcf0a1898)


The script has been working for months without changes and today it broke with this error. 
If I fix pydantic to an earlier version than 2.10 (e.g. 2.9.2) , the issue goes away.

**Comment by Viicos** [comment]
@dga-nagra, is your project open source? If not, we'll need a MRE to reproduce.

**Comment by sydney-runkle** [comment]
For folks following along, we anticipate doing a patch release with these fixes in the afternoon today :).

**Comment by sydney-runkle** [comment]
Update: going to kick off a `pydantic-core` release shortly, then will release v2.10.1 with the above fixes :)

**Comment by sydney-runkle** [comment]
For folks following - we've just released v2.10.1!

**Comment by sydney-runkle** [comment]
Going to leave this issue open for a bit just for visibility + to help avoid duplicate issues.

**Comment by domsj-foodpairing** [comment]
regarding
>pydantic.errors.PydanticUndefinedAnnotation: name 'X' is not defined

there's a similar issue in langchain-google-vertexai, see https://github.com/langchain-ai/langchain-google/issues/610
(which is open source, so should be possible to reproduce)

**Comment by Viicos** [comment]
Thanks @domsj-foodpairing, I'm taking a look.

**Comment by rashmi-asml** [comment]
`pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic.networks.AnyUrl'> `
I am getting this error while performing unit test. I am using the same version of pydantic.

**Comment by sydney-runkle** [comment]
@rashmi-asml, can you please open a new issue with a reproducible example? Thanks!

**Comment by sydney-runkle** [comment]
@rashmi-asml, thanks for the report, I'll open an issue.

**Comment by sungmincs** [comment]
Pyadantic 2.10.1 release still deosn't fix this regression in pyairtable
```
Exception has occurred: AttributeError
partially initialized module 'pyairtable' has no attribute 'api' (most likely due to a circular import)
  File "file.py", line 2, in <module>
    from pyairtable import Api
AttributeError: partially initialized module 'pyairtable' has no attribute 'api' (most likely due to a circular import)
```

**Comment by potiuk** [comment]
I created a new issue https://github.com/pydantic/pydantic/issues/10958 - and I think you should seriously consider addresssing it in 2.10.2 @Viicos - I anticipate this will prevent a number of problems by your users and cost and risk of adding `eval-type-backport` as required dependency for Python 3.8/3.9 by Pydantic 2.10+ is very small.

**Comment by RobertCraigie** [comment]
Hey, it looks live `v2.10` & `v2.10.1` are broken for cloudflare-python. In a fresh virtual environment, this fails
```bash
$ pip install cloudflare
$ python -c 'import cloudflare'
```

<details>
<summary>Stack trace</summary>

```
Traceback (most recent call last):
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 815, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, *self._types_namespace)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 534, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 558, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 592, in _eval_type
    return typing._eval_type(  # type: ignore
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 296, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 580, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 298, in _eval_type
    ev_args = tuple(
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 299, in <genexpr>
    _eval_type(a, globalns, localns, recursive_guard) for a in t.__args__
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 296, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 580, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 298, in _eval_type
    ev_args = tuple(
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 299, in <genexpr>
    _eval_type(a, globalns, localns, recursive_guard) for a in t.__args__
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 296, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/Users/robert/.rye/py/cpython@3.9.18/install/lib/python3.9/typing.py", line 575, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'TraceItem' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/__init__.py", line 6, in <module>
    from ._client import (
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/_client.py", line 11, in <module>
    from . import resources, _exceptions
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/resources/__init__.py", line 555, in <module>
    from .request_tracers import (
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/resources/request_tracers/__init__.py", line 3, in <module>
    from .traces import (
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/resources/request_tracers/traces.py", line 24, in <module>
    from ...types.request_tracers import trace_create_params
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/types/request_tracers/__init__.py", line 8, in <module>
    from .trace_create_response import TraceCreateResponse as TraceCreateResponse
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/cloudflare/types/request_tracers/trace_create_response.py", line 23, in <module>
    TraceCreateResponse.model_rebuild()
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/main.py", line 594, in model_rebuild
    return _model_construction.complete_model_class(
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/main.py", line 702, in __get_pydantic_core_schema__
    return handler(source)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 881, in _generate_schema_inner
    return self._model_schema(obj)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 693, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 693, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1073, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1261, in _common_field_schema
    schema = self._apply_annotations(
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2061, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 2042, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 875, in _generate_schema_inner
    return self.generate_schema(self._resolve_forward_ref(obj))
  File "/Users/robert/stainless/stainless/dist/cf2/.venv/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 817, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'TraceItem' is not defined

For further information visit https://errors.pydantic.dev/2.10/u/undefined-annotatio
```

</details>

Sorry I don't have a more minimal reproduction, here's a link to the [source file](https://github.com/cloudflare/cloudflare-python/blob/main/src/cloudflare/types/request_tracers/trace_create_response.py) where we call `.model_rebuild()`. I suspect this is something to do with pydantic evaluating names using the wrong namespace.

Note that everything works with Pydantic `v2.9.2`.

**Comment by Viicos** [comment]
Thanks for reporting the issue. I'm taking a look. Can I open an issue on https://github.com/cloudflare/cloudflare-python so that we can discuss it further?

**Comment by RobertCraigie** [comment]
Thanks, sure!

**Comment by Viicos** [comment]
@RobertCraigie, I commented [here](https://github.com/cloudflare/cloudflare-python/discussions/116#discussioncomment-11372711).

**Comment by rashmi-asml** [comment]
I will check and confirm soon, thanks a lot! @Viicos @sydney-runkle

**Comment by sigma67** [comment]
2.10.2 has been delayed from Nov 25th as stated in OP?

**Comment by potiuk** [comment]
I see 2.10.2 has been released (thanks @Viicos and others). Would you consider yanking 2.10.0/2.10.1 maybe? There is basically no harm in doing so, it's not strictly necessary but from "healthiness" point of view that might be a good idea, to avoid accidental issues - and it gives package managers a bit lighter job on resolving dependencies.

**Comment by jacobbednarz** [comment]
please don't yank/delete/remove bad packages. it creates a shitstorm for downstream consumers that may have that version referenced somewhere; often unintentionally.

if there are issues (which happen in all projects), a new release rectifying the issues is suffice and allows folks to continue the upgrade path without chasing ghost versions.

**Comment by potiuk** [comment]
> please don't yank/delete/remove bad packages. it creates a shitstorm for downstream consumers that may have that version referenced somewhere; often unintentionally.


Absolutely not. You might have bad (and that is understandable) experience with package deletion, but yanking (as opposed to deletion) is absolutely safe. Go and check it @jacobbednarz - https://blog.piwheels.org/new-features-deletion-yanking-and-more/. We've been on both end of yanked packages (yanking them and using yanked packages) multiple times. When you have a yanked package referred somewhere directly, the only side effect you have is that package manager will print a warning with the message you added when you yanked it.

I have not yet seen a scenario where  yanking a package would be problematic. Can you come up with such scenario @jacobbednarz  ?

**Comment by jacobbednarz** [comment]
i don't want to derail the thread for a witch hunt however, even yanking in the past has caused hard to debug and trace issues when explicit versions are defined. perhaps this was a part of tooling that didn't understand or correctly implement yanking, however, i would much rather make transitions from bad versions to good ones, more predictable and remove that potential guess work.

**Comment by potiuk** [comment]
> perhaps this was a part of tooling that didn't understand or correctly implement yanking

Hardly possible to be honest. Yank was just an attribute 'data-yanked` added to metadata for packages and tools that did not have yank support (which was added 5 years ago - in 2019) simply consider that package as "not yanked" - see https://peps.python.org/pep-0592/. I think you might have mistaken it with deletion (which is indeed very bad). I have not seen a single case where it could cause problems. There is this nice video https://www.youtube.com/watch?v=lUFA_WklFII explaining yanking in detail, and I think it's really nice way to signal users they have problematic packages (and explain why)  without really disrupting anything. I am not sure what guesswork is involved in - last time I checked, all the potential scenarios of using yanked packaged worked predictable (for example it won't get automatically upgraded if you do not expicitly specify --upgrade flag - yanking exclusively works at dependency resolution phase when you upgrade or install packages.

**Comment by Viicos** [comment]
Indeed, I do not know any package installer that do not support yanking as of today. However, I see yanking as a better solution when a release is completely broken: broken wheels, package does not import, etc. For Pydantic, patch releases are meant to fix potential new issues raised after a new feature release. I don't see us yanking every `2.x.0` feature release and the following patch releases minus the last one.

Whether we should yank `2.10.0` is debatable, because it accidentally broke dependent libraries making use of `FieldInfo.get_default`. But we are going to release `2.10.3` soon, so I don't know if this is necessary now.

**Comment by sigma67** [comment]
Packages that have pinned pre-patch versions are free to update and packages pulling latest will get the fix anyway. Not sure what problem a yank would solve.

**Comment by rashmi-asml** [comment]
Hi, 
I was applying fixes to my unit tests and it is installing pydantic v2.10.2 and pydantic-core 2.27.1
I see the validation error as invalid URL type as it is not accepting the URL without the `http/https` protocol now.  We were able to run without any issue with that earlier.
We were using AnyURL type intentionally in v2.10.0 so that we could use something like this `abc.com:123` URL with port no and without protocols as we need this for podman login and podman doesn't accept http/https protocol.

**Comment by sydney-runkle** [comment]
@rashmi-asml,

Thanks for the report. This will be fixed in v2.10.3 tomorrow :)

**Comment by dga-nagra** [comment]
> @dga-nagra, is your project open source? If not, we'll need a MRE to reproduce.

Sorry for the delay. My issue is what @RobertCraigie reported.


My code isn't public but the issue can be reproduced by just importing cloudflare

```python
from cloudflare import Cloudflare
```
With the following packages:
```txt
cloudflare==3.1.0
pydantic==2.10.0
pydantic_core==2.27.0
```

Installing pydantic 2.9.2 (`pip install pydantic==2.9.2`) solves the issue...
```txt
cloudflare==3.1.0
pydantic==2.9.2
pydantic_core==2.23.4
```

**Comment by dga-nagra** [comment]
> @dga-nagra if you install `cloudflare==3.1.1` it should work, we've added version constraints for `pydantic` to workaround this issue & it'll be completely fixed when v4 is released.

This works because 3.1.1 uses pydantic<2.10 which is what I did already (I also use pydantic in my project). On my side this is fixed, but what happened on Cloudflare's python SDK could happen in any code base. This is a breaking change on pydantic' side.

I just didn't want to leave the question unanswered and clarify that I don't have anything useful left to add to the table.

**Comment by Viicos** [comment]
@dga-nagra, we are aware of this change. In most if not all cases, it requires a change to the affected code bases, as they were using forward annotations that shouldn't resolve in the first place, but did because of a bogus implementation of the namespace resolving in Pydantic < 2.10. We're trying our best to help affected projects to fix the issue(s), as it is generally not straightforward at all to do so.

**Comment by potiuk** [comment]
Nice @sydney-runkle -> thanks for quick resolution of those teething issues ! Good job!
