### ISSUE TITLE
2.10: Trouble serializing url types (as any), similar to secret types

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10946]
```py
from pydantic import AnyUrl, TypeAdapter
from typing import Any

url = AnyUrl('http://example.com')
ta = TypeAdapter(Any)
print(ta.dump_json(url))
"""
Traceback (most recent call last):
    File "/Users/programming/pydantic_work/pydantic/test.py", line 6, in <module>
    print(ta.dump_json(url))
            ^^^^^^^^^^^^^^^^^
    File "/Users/programming/pydantic_work/pydantic/pydantic/type_adapter.py", line 581, in dump_json
    return self.serializer.to_json(
        ^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic.networks.AnyUrl'>
"""
```

Similar to:

```py
from pydantic import TypeAdapter, SecretStr
from typing import Any

ss = SecretStr("password")
ta = TypeAdapter(Any)
print(ta.dump_json(ss))
"""
Traceback (most recent call last):
  File "/Users/programming/pydantic_work/pydantic/test.py", line 6, in <module>
    print(ta.dump_json(ss))
          ^^^^^^^^^^^^^^^^
  File "/Users/programming/pydantic_work/pydantic/pydantic/type_adapter.py", line 581, in dump_json
    return self.serializer.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'pydantic.types.SecretStr'>
"""
```

**Comment by sydney-runkle** [comment]
Found some related discussion: https://github.com/pydantic/pydantic/issues/9491

**Comment by sydney-runkle** [comment]
Yep, thanks for the report. Works with my above linked fix 👍
