### ISSUE TITLE
Allow using `UrlConstraint`s with unions of `MultiHostUrl`.

### ISSUE THREAD

**Issue by JasonGrace2282** [pydantic/pydantic#11064]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently the following throws an error:
```py
from typing import Annotated

from pydantic import (
    BaseModel,
    UrlConstraints,
    PostgresDsn,
    MySQLDsn
)


class MyModel(BaseModel):
    foo: Annotated[MySQLDsn | PostgresDsn, UrlConstraints(max_length=80)]
```

However, separating it into `Annotated[MySQLDsn, UrlConstraints(...)] | Annotated[PostgresDsn, ...]` suceeds. It would be nice not to have to repeat the `UrlConstraints` here.

<details>
<summary>
Exception
</summary>

```
Traceback (most recent call last):
  File "/home/jasongrace2282/repos/test/pydan.py", line 11, in <module>
    class MyModel(BaseModel):
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 226, in __new__
    complete_model_class(
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/main.py", line 702, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 881, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 693, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1073, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1265, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2062, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2137, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jasongrace2282/repos/test/.venv/lib/python3.12/site-packages/pydantic/networks.py", line 109, in __get_pydantic_core_schema__
    raise PydanticUserError(
pydantic.errors.PydanticUserError: 'UrlConstraints' cannot annotate 'True'.

For further information visit https://errors.pydantic.dev/2.10/u/invalid-annotated-type
```
</details>

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi,

Thanks for your question! Indeed, constraint application to unions could be simplified from a user perspective.

I think this is one of those things where a bit more verbosity on the user side is actually worth having. I believe it might make our schema builds even slower to do constraint application analysis on union types.

Going to mark as not planned for now. If there's high demand here or further engagement from the community, we'd be happy to reconsider.

Thanks again for the clear example and explanation.
