### ISSUE TITLE
validate_call cannot handle parameters annotated with None

### ISSUE THREAD

**Issue by zhudotexe** [pydantic/pydantic#11073]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `validate_call` on a function that has a parameter annotated with `None` (e.g., `foo: None`), Pydantic fails to generate a schema for the function:
```python
>>> @validate_call
... def foo(bar: None):
...     pass

Traceback (most recent call last):
  File "[...]/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-25fd88474159>", line 4, in <module>
    @validate_call
     ^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/validate_call_decorator.py", line 110, in validate_call
    return validate(func)
           ^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/validate_call_decorator.py", line 104, in validate
    validate_call_wrapper = _validate_call.ValidateCallWrapper(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 72, in __init__
    schema = gen_schema.clean_schema(gen_schema.generate_schema(function))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 977, in match_type
    return self._call_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1845, in _call_schema
    arg_schema = self._generate_parameter_schema(name, annotation, p.default, parameter_mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/.venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1537, in _generate_parameter_schema
    assert field.annotation is not None, 'field.annotation should not be None when generating a schema'
AssertionError: field.annotation should not be None when generating a schema
```

This worked in Pydantic v2.9 and earlier, so it seems to have been introduced in v2.10. This came up in a unit test so I'm not sure anyone would actually do this in the wild, but it seemed worth noting.

Replacing the `None` annotation with `type(None)` fixes the issue, but seems unpythonic.

### Example Code

```Python
from pydantic import validate_call

@validate_call
def foo(bar: None):
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /[...]/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-15.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@zhudotexe,

Thank you for reporting this. Definitely something we want to support, I'm surprised to see that this broke / that we didn't have any tests. We'll look into a fix for v2.10.4!

**Comment by sydney-runkle** [comment]
cc @Viicos. I can also take a look if you don't have a chance tomorrow.

**Comment by mpkocher** [comment]
> Replacing the None annotation with type(None) fixes the issue, but seems unpythonic.

Since the early days of Python, the direction of the language design has tried to blur the lines between types and classes. A _pragmatic_ approach in the typing era to decide to use a singleton instance (e.g., `None`) to also be used  as a type was perhaps further pushing this line. Often it's not an issue and semantically `None` means `NoneType`. However, there are some cases where the intent isn't clear. 

This isn't unique to `None`. In the scientific community, `...` has a similar friction point and there are places where you need to explicitly use `types.EllipseType` to avoid confusion. 

It's a reasonable workaround for a user to use the explicit type in these ambiguous cases.
