### ISSUE TITLE
Unexpected validation of annotated enum in strict mode

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#11070]
### Discussed in https://github.com/pydantic/pydantic/discussions/11068

<div type='discussions-op-text'>

<sup>Originally posted by **namezys** December  9, 2024</sup>
I've tried to add wrap validators for the enum field.
Using strict mode is important (without strict everything works).

Let's start with simple code:
```python
import enum
from typing import Annotated
from pydantic import BaseModel, WrapValidator

class E(enum.StrEnum):
    a = 'A'
    x = 'X'

class M(BaseModel, strict=True):
    a: E
    # a: Annotated[E, WrapValidator(lambda v, h: h(v))]

M.model_validate_json('{"a": "X"}')
```

everything works as expected.

Let's add simples validator (identical)
```python
import enum
from typing import Annotated
from pydantic import BaseModel, WrapValidator

class E(enum.StrEnum):
    a = 'A'
    x = 'X'

class M(BaseModel, strict=True):
    # a: E
    a: Annotated[E, WrapValidator(lambda v, h: h(v))]

M.model_validate_json('{"a": "X"}')
```

And this results in an error
```
Traceback (most recent call last):
  File "/Users/namezys/job/pydantic-experements/safe.py", line 17, in <module>
    m = M.model_validate_json('{"a": "X"}')
  File "/Users/namezys/job/pydantic-experements/.venv/lib/python3.13/site-packages/pydantic/main.py", line 656, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for M
a
  Input should be an instance of E [type=is_instance_of, input_value='X', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/is_instance_of
```

Maybe it is described in the documentation but it looks very strange.

</div>

**Comment by sydney-runkle** [comment]
I think this has been reported before, but I can't find the specific issue. It's a problem with the validator using python validation I think.

**Comment by sleiner** [comment]
I looked a bit into this:
- It seems that there was a [similar issue](https://github.com/pydantic/pydantic/issues/8147) in late 2023, fixed by this PR https://github.com/pydantic/pydantic-core/pull/1080. The PR description mentions something along the lines of incorrectly checking for Python mode (similar to what @sydney-runkle mentioned above) in pydantic-core.
- I did a quick `git bisect` using the reproducer code that @Viicos posted. The commit introducing this issue is ac9e6ee3e40845014fc2f9c79d95c5896dc3eca7 (which moves the Enum validation logic to Rust).
- Based on the previous PR, I vaguely suspect that [these are the lines introducing the bug](https://github.com/pydantic/pydantic-core/blob/82b7aa77dcfa66956a7b3164eee45bf31d62a507/src/validators/enum_.rs#L106).
  Unfortunately, I do not understand the `pydantic-core` code base (including that PR from 2023), so I am not able to fix it.

**Comment by Viicos** [comment]
Thanks @sleiner for investigating. I've pushed a fix in https://github.com/pydantic/pydantic-core/pull/1632.
