### ISSUE TITLE
Support for `TypeAliasType` in Pydantic v1

### ISSUE THREAD

**Issue by RobertCraigie** [pydantic/pydantic#11080]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic v1 doesn't seem to support `TypeAliasType`, I get this error when trying to use it
```
$ python script.py
Traceback (most recent call last):
  File "pydantic/validators.py", line 752, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script.py", line 8, in <module>
    class Model(BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__i
  File "pydantic/fields.py", line 555, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 829, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 761, in find_validators
RuntimeError: error checking inheritance of MyData (type: TypeAliasType)
```

Additional context is that I've been working on migrating a lot of code to use `TypeAliasType` as per the recommendation of @Viicos in https://github.com/cloudflare/cloudflare-python/discussions/116#discussioncomment-11372711 & our SDKs support both Pydantic v1 and v2 simultaneously so it'd be very helpful if there was feature parity here. Especially as it looks like we won't be able to drop v1 support anytime soon as its still getting [millions of downloads](https://pepy.tech/projects/pydantic) a day.

### Example Code

```Python
from typing import List
from typing_extensions import TypeAliasType

from pydantic import BaseModel

MyData = TypeAliasType('MyData', List[str])

class Model(BaseModel):
    data: MyData


print(Model.parse_obj({'data': ['foo', 'bar']}))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.19
            pydantic compiled: True
                 install path: /Users/robert/stainless/stainless/dist/anthropic-python/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Aug 26 2023, 08:18:34)  [Clang 16.0.3 ]
                     platform: macOS-15.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```
```


### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
This will require quite some work (at least a full day, being optimistic), and doesn't really fit in our [V1 maintenance policy](https://docs.pydantic.dev/dev/version-policy/#pydantic-v1).

May I ask: did you have explicit requests from users asking for V1 support? We know the usage is still quite high and it can be hard to switch to V2, but instead of trying to keep V1 supported, we'd like to help 3rd party libraries/applications adopt V2.

**Comment by RobertCraigie** [comment]
Hey sorry I missed your response, we haven't gotten many explicit requests for v1 support as we already support both v1 and v2 concurrently, so I wouldn't expect any of our users to ask about v1 support unless something was broken.

I appreciate this doesn't fit the maintenance policy but it could be beneficial in helping libraries migrate to v2 as it'll make it easier to workaround any of the type resolution changes. 

Right now we have to do this:
```py
if TYPE_CHECKING or PYDANTIC_V2:
  Alias = TypeAliasType('Alias', List['SomeType'])
else:
  Alias: TypeAlias = List['SomeType']
```
Which is pretty ugly
