### ISSUE TITLE
Fields with `any` type raise a ValidationError

### ISSUE THREAD

**Issue by amirh** [pydantic/pydantic#11126]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems like starting Pydantic 2.10, fields defined as `bar: any` fail with a ValidationError, prior to 2.10 this triggered just a warning.

You can use this snippet to reproduce:

```python
from pydantic import BaseModel, ConfigDict, SkipValidation

class Foo(BaseModel):
  model_config = ConfigDict(
      arbitrary_types_allowed=True,
  )
  bar: any

Foo(bar = "test")
```

With pydantic==2.9.2 I get the following warning when running the snippet above:

```
…/pydantic/_internal/_generate_schema.py:547: UserWarning: <built-in function any> is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.
  warn(
```

With pydantic>=2.10 I get a validation error (with a message that wasn’t very clear):

```
Traceback (most recent call last):
  File "....py", line 10, in <module>
    Foo(bar = "test")
  File "/usr/local/google/home/amirha/venv2/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
bar
  Arguments must be a tuple, list or a dictionary [type=arguments_type, input_value='test', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/arguments_type
```

Annotating the field with SkipValidation fixes the validation error with 2.10 (interestingly it doesn’t silence the warning with 2.9.2)

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, SkipValidation

class Foo(BaseModel):
  model_config = ConfigDict(
      arbitrary_types_allowed=True,
  )
  bar: any

Foo(bar = "test")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /usr/local/google/home/amirha/venv2/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Jun 19 2024, 00:38:48) [GCC 13.2.0]
                     platform: Linux-6.10.11-1rodete2-amd64-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Did you mean to use [`typing.Any`](https://docs.python.org/3/library/typing.html#typing.Any)? [`any()`](https://docs.python.org/3/library/functions.html#any) is a built-in function that is not related.

**Comment by amirh** [comment]
Huh, I guess 🤦 
This still caught me as a "regression" when we upgraded Pydantic (codebase worked before, now it's failing) and the error message left me a little confused so not sure if there's something to do here or not.

Thanks!

**Comment by Viicos** [comment]
I still get the `UserWarning`, at least on `main`.
