### ISSUE TITLE
Base settings exception messages should include prefix if set

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [pydantic/pydantic#11151]
### Discussed in https://github.com/pydantic/pydantic/discussions/3084

<div type='discussions-op-text'>

<sup>Originally posted by **1oglop1** August 10, 2021</sup>
At the moment the exception messages from BaseSettings do not include the prefix if it's set.
This makes it confusing for operators of an application who do not necessarily need to understand the code just to run the application itself.

Following code 
```python
from pydantic import BaseSettings
class AppSettings(BaseSettings):
    ENV_VARIABLE: str

    class Config:
        env_prefix = "MY_PREFIX_"

print(AppSettings())
```

Produces an exception like this
```
Traceback (most recent call last):
  File "/home/helpers.py", line 86, in <module>
    print(AppSettings())
  File "pydantic/env_settings.py", line 36, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AppSettings
ENV_VARIABLE
  field required (type=value_error.missing)
```

Logical procedure is then `export ENV_VARIABLE=value`, however this leads to the same error because the actual command expected is `export MY_PREFIX_ENV_VARIABLE=value`

This should be either a default behaviour or option for BaseSettings             
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Jun  7 2021, 14:11:45)  [GCC 10.3.0]
                     platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.33
     optional deps. installed: ['email-validator', 'typing-extensions']
```</div>

**Comment by helmut-hoffer-von-ankershoffen** [comment]
As this might help others - built a small utility to have sensible validation error messages for settings sourced from the environment and .env file

Use via ```load_settings(YourSettings)```

The utility:
```
"""Utilities around Pydantic settings."""

import json
from typing import TypeVar

from pydantic import ValidationError
from pydantic_settings import BaseSettings
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

T = TypeVar("T", bound=BaseSettings)

console = Console(stderr=True)


def load_settings(settings_class: type[T]) -> T:
    """Load settings with error handling and nice formatting.

    Args:
        settings_class: The Pydantic settings class to instantiate

    Returns:
        Instance of the settings class

    Raises:
        SystemExit: If settings validation fails
    """
    try:
        return settings_class()
    except ValidationError as e:
        errors = json.loads(e.json())
        text = Text()
        text.append(
            "Validation error(s) - check the environment and .env file:\n\n",
            style="bold red",
        )

        prefix = settings_class.model_config.get("env_prefix", "")
        for error in errors:
            env_var = f"{prefix}{error['loc'][0]}".upper()
            text.append(f"• {env_var}", style="yellow")
            text.append(f": {error['msg']}\n")

        console.print(
            Panel(
                text,
                title="Configuration invalid!",
                border_style="red",
            )
        )
        exit(78)
```
