### ISSUE TITLE
Allow JSON validation of JSON data already loaded using json.load()

### ISSUE THREAD

**Issue by pallgeuer** [pydantic/pydantic#11154]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I searched but didn't find where/how this would be possible already, especially in a simple straightforward way.

Suppose I have a JSON string, then I can do `MyModel.model_validate_json(json_str, strict=True)` to validate the JSON using 'looser' JSON rules to get an instance of MyModel (as per [here](https://docs.pydantic.dev/latest/concepts/conversion_table/)). How can I do exactly the same if I only have access to `json.loads(json_str)`?

Calling `MyModel.model_validate()` uses different (Python) validation rules, and `MyModel.model_validate_json()` only accepts the raw string. Converting the loaded JSON data back to string just to validate it again seems backwards. The feature request would be to have a simple top-level way of passing already-loaded JSON data (Python objects) through JSON-style validation rules.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by pallgeuer** [comment]
Well it's close, but not really the right thing because then every key and value must be a string.
```
>>> json_str = '{"id": 123, "name": "James", "signup_ts": "2024-04-01T12:00:00"}'
>>> User.model_validate_json(json_str)
User(id=123, name='James', signup_ts=datetime.datetime(2024, 4, 1, 12, 0))
>>> json_data = json.loads(json_str)
>>> User.model_validate_strings(json_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.9/site-packages/pydantic/main.py", line 619, in model_validate_strings
    return cls.__pydantic_validator__.validate_strings(obj, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
id
  Input should be a valid string [type=string_type, input_value=123, input_type=int]
```

From the help link you provided (thanks):

> Depending on the types and model configs involved, [model_validate](https://docs.pydantic.dev/dev/api/base_model/#pydantic.BaseModel.model_validate) and [model_validate_json](https://docs.pydantic.dev/dev/api/base_model/#pydantic.BaseModel.model_validate_json) may have different validation behavior. If you have data coming from a non-JSON source, but want the same validation behavior and errors you'd get from [model_validate_json](https://docs.pydantic.dev/dev/api/base_model/#pydantic.BaseModel.model_validate_json), our recommendation for now is to use either use **model_validate_json(json.dumps(data))**, or use [model_validate_strings](https://docs.pydantic.dev/dev/api/base_model/#pydantic.BaseModel.model_validate_strings) if the data takes the form of a (potentially nested) dictionary with **string keys and values**.

The fact that `model_validate_json(json.dumps(data))` is being recommended in the official help suggests to me there is no intended way currently of going straight from the JSON data in Python form to a JSON-style-validated BaseModel?

**Comment by sydney-runkle** [comment]
Hmm @Viicos, I wonder if it's make sense to have a `model_validate(xxx, mode='json')` pattern, like we do for `model_dump`?

Probably introduces some hard to maintain branching in `pydantic-core`...

**Comment by joaohaas** [comment]
Since my understanding is that OP only needs looser strictness rules, another option would be to change `validate` methods to receive either enum variants or objects with custom rules on the `strict` key:
```py
model_validate(value, strict=Strict.JSON)
# or
model_validate(value, strict=Strict(str_int_conv=False, bool_int_conv=True))`
```
We could then fallback non-`Strict` truthy values to the current `strict=True` behavior.
