### ISSUE TITLE
Using `@field_validator` there is an TypeError: no_info_before_validator_function() got an unexpected keyword argument 'json_schema_input_schema'

### ISSUE THREAD

**Issue by alexkudryavtsev88** [pydantic/pydantic#11159]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello!

I've updated my `pydantic` version to 2.10.4, and now, when I use `@field_validator` within some `BaseModel` / `BaseSettings` derived class, the following error is raised upon this class initialization:

```
Traceback (most recent call last):
  File "/Users/me/Projects/my_project/src/settings.py", line 36, in <module>
    class MyModel(BaseModel):
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 226, in __new__
    complete_model_class(
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 658, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/main.py", line 702, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 610, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 879, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 691, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 691, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1071, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1263, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2056, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2131, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic/functional_validators.py", line 142, in __get_pydantic_core_schema__
    return core_schema.no_info_before_validator_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: no_info_before_validator_function() got an unexpected keyword argument 'json_schema_input_schema'
```

### Example Code

```Python
from pydantic import BaseModel, Field, field_validator

class MyModel(BaseModel):
    name: str = Field(default="John")

    @field_validator("name", mode="before")
    @classmethod
    def validate_name(cls, value: str) -> str:
        if not value:
            raise ValueError("name cannot be empty")
        return value
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.4
pydantic-core version: 2.27.1
pydantic-core build: profile=release pgo=false
install path: /Users/me/Projects/my_project/.venv/lib/python3.11/site-packages/pydantic
python version: 3.11.8 (main, Mar 18 2024, 20:12:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
platform: macOS-14.5-arm64-arm-64bit
related packages: fastapi-0.115.6 pydantic-settings-2.7.0 mypy-1.12.0 typing_extensions-4.12.2
commit: unknown
```

**Comment by Viicos** [comment]
You need to upgrade `pydantic-core` as well. Note that you may have to check how you upgraded `pydantic`, as your installer should have taken the constraint into consideration:

https://github.com/pydantic/pydantic/blob/74857250382126c2e50166d64c1ef1d3af8ca8ef/pyproject.toml#L49

**Comment by ARawles** [comment]
For me this issue was fixed by updating my version of `pkginfo` to 1.12.0. It looks like with older versions, it wasn't properly resolving Pydantic's dependencies (I'm using Poetry), leaving out `pydantic-core`

**Comment by alexkudryavtsev88** [comment]
@ARawles Hi! I'm using Poetry too, after applying your suggestion (I've updated internal poetry's `pkginfo` to 1.12.0), I've re-built my local venv and, after that, I see that there is no `pydantic-core` installed at all. 
Does this mean that, from now, `pydantic-core` dependency is required to be specified separatelly from the `pydantic` itself?
(I have `poetry` version 1.8.5)

**Comment by ARawles** [comment]
Hmm that's odd - looking at the current `pyproject.toml` for Pydantic, I can see the `pydantic-core` specification, meaning it looks like it should still be a dependency that Poetry picks up.

One other thing to try would be to delete the Poetry cache with something like `rm -r ~/.cache/pypoetry/cache` and then running `poetry debug resolve pydantic`. Hopefully then you should see `pydantic-core` being listed amonst the dependencies.
