### ISSUE TITLE
URL invalid, extra characters found after valid URL

### ISSUE THREAD

**Issue by JerryJiangjjw** [pydantic/pydantic#1484]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```bash
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /private/tmp/pydantic/pydantic
               python version: 3.6.10 (default, Feb  1 2020, 16:54:53)  [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: []
```

`test.py`
```py
from pydantic import HttpUrl
from pydantic import BaseModel


class TestUrl(BaseModel):
    url: HttpUrl


print(TestUrl(url="https://8.8.8.8www.google.com"))
```
`output`
```bash
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(TestUrl(url="https://8.8.8.8www.google.com"))
  File "/private/tmp/pydantic/pydantic/main.py", line 338, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for TestUrl
url
  URL invalid, extra characters found after valid URL: 'www.google.com' (type=value_error.url.extra; extra=www.google.com)

```
## When I change the domain order ,It does work!

```
$ python test.py
url=HttpUrl('https://8.8.8.8www.google.com', scheme='https', host='8.8.8.8www.google.com', tld='com', host_type='domain')


--- a/pydantic/networks.py
+++ b/pydantic/networks.py
@@ -55,9 +55,9 @@ def url_regex() -> Pattern[str]:
             r'(?:(?P<scheme>[a-z][a-z0-9+\-.]+)://)?'  # scheme https://tools.ietf.org/html/rfc3986#appendix-A
             r'(?:(?P<user>[^\s:/]+)(?::(?P<password>[^\s/]*))?@)?'  # user info
             r'(?:'
+            r'(?P<domain>[^\s/:?#]+)|'  # domain, validation occurs later
             r'(?P<ipv4>(?:\d{1,3}\.){3}\d{1,3})|'  # ipv4
-            r'(?P<ipv6>\[[A-F0-9]*:[A-F0-9:]+\])|'  # ipv6
-            r'(?P<domain>[^\s/:?#]+)'  # domain, validation occurs later
+            r'(?P<ipv6>\[[A-F0-9]*:[A-F0-9:]+\])'  # ipv6
             r')?'
             r'(?::(?P<port>\d+))?'  # port
             r'(?P<path>/[^\s?]*)?'  # path
```

## I notice this  commit[https://github.com/samuelcolvin/pydantic/commit/a4665aa70003e571e72a2c16871e151affd2b535#diff-c284c94c385f13bced4ba8cef1fa453aL236](https://github.com/samuelcolvin/pydantic/commit/a4665aa70003e571e72a2c16871e151affd2b535#diff-c284c94c385f13bced4ba8cef1fa453aL236)

**Comment by samuelcolvin** [comment]
PR welcome, but does it break the opposite? e.g. something like `https://www.google.com8.8.8.8`?

**Comment by ramsrib** [comment]
I see the same error with this url as well: `https://www.google.com/test#`

**Comment by mwgamble** [comment]
Why does Pydantic use a custom regex, instead of functionality available in the stdlib package `urllib.parse`?

**Comment by samuelcolvin** [comment]
Because originally I copied Django.

Urllib parse is no use, it allows too much and doesn't give a useful error on invalid domains.

I'm v2, url are validated with the url rust crate.
