### ISSUE TITLE
Provide a Base and a Config in create_model

### ISSUE THREAD

**Issue by juanjramirez** [pydantic/pydantic#2137]
### Checks

* [x ] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [ x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7
            pydantic compiled: True
                 install path: /home/juan/.virtualenvs/crop-treatment-services/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Sep 25 2020, 09:36:53)  [GCC 10.2.0]
                     platform: Linux-5.9.0-2-amd64-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
...
```

```py
from pydantic import create_model, BaseModel


class ModelA(BaseModel):
    pass


class ModelB(BaseModel):
    class Config:
        pass


ModelC = create_model(
    "ModelC",
    __base__=ModelA,
    __config__=ModelB.Config,
)
...
```
Running above gives:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    ModelC = create_model(
  File "pydantic/main.py", line 888, in pydantic.main.create_model
pydantic.errors.ConfigError: to avoid confusion __config__ and __base__ cannot be used together
```
I cant create a model with a base and a config is there any other way to do this? ModelA is dynamically created and I want to create ModelC with the base of ModelA and the Config of ModelB (in the end I just want to dynamically configure a model after creation but have found no way of doing so)

**Comment by DrnglVrgs** [comment]
So, I ended doing what I wanted the following way:

```py
...
new_config = type("Config", (ModelB.Config, ModelA.Config), {})
namespace = {
    "__annotations__": {},
    "__module__": ModelA.__module__,
    "Config": new_config,
}
ModelC = type("ModelC", (ModelA,), namespace)
```
It works for my use case for now...
Would like to hear if there is a better way of doing this or if it is a good idea to support this use case in create_model

**Comment by samuelcolvin** [comment]
Thanks for using pydantic. 🙏 

As part of a migration to using [discussions](https://github.com/samuelcolvin/pydantic/discussions) and cleanup old issues, I'm closing all open issues with the "question" label. 💭 🆘 🚁 

I hope you've now found an answer to your question. If you haven't, feel free to start a :point_right: [question discussion](https://github.com/samuelcolvin/pydantic/discussions/new?category=question).

**Comment by Viicos** [comment]
I'm not sure why this limitation was added in the first place, but we can now remove it. This will be addressed in 2.12.
