### ISSUE TITLE
Problems using self-referencing model with SQLAlchemy async session

### ISSUE THREAD

**Issue by NEONKID** [pydantic/pydantic#2601]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

When using SQLAlchemy 1.4 / AsyncSession with FastAPI and pydantic you occur issue:
```py
from pydantic import BaseModel
from typing import List


class CategoryModel(BaseModel):
    children: List['CategoryModel'] = []

    class Config:
        orm_mode = True

CategoryModel.update_forward_refs()


async def get_categories(db: AsyncSession):
    results = await db.execute(select(models.Category))
    return results.unique().scalars().all()


@app.get("/categories", response_model=CategoryModel)
async def read_categories(db: AsyncSession):
    categories = await crud.get_categories(db)
    return categories

```

```py
Traceback (most recent call last):
  File "/Users/neonkid/PycharmProjects/blog/admin/run.py", line 6, in <module>
    uvicorn.run(api, host="127.0.0.1", port=8000)
    │       │   └ <fastapi.applications.FastAPI object at 0x7fa73f4e25b0>
    │       └ <function run at 0x7fa7414021f0>
    └ <module 'uvicorn' from '/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-...

  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 386, in run
    server.run()
    │      └ <function Server.run at 0x7fa74147c3a0>
    └ <uvicorn.server.Server object at 0x7fa73f4e10a0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
    │    │                  │    │             └ None
    │    │                  │    └ <function Server.serve at 0x7fa74147c430>
    │    │                  └ <uvicorn.server.Server object at 0x7fa73f4e10a0>
    │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
    └ <uvloop.Loop running=True closed=False debug=False>
> File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0x7fa7438da940>
                   │   │    │      │    │        └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732b0>
                   │   │    │      │    └ <function RequestResponseCycle.receive at 0x7fa7438da9d0>
                   │   │    │      └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732b0>
                   │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   │   └ <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732b0>
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa743886040>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732...
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x7fa73f4e25b0>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa743886040>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732...
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d732...
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fa743886880>
          └ <fastapi.applications.FastAPI object at 0x7fa73f4e25b0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fa743e90ca0>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fa743886880>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
                     │    │             │        │    └ <function BaseHTTPMiddleware.call_next at 0x7fa7420a48b0>
                     │    │             │        └ <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>
                     │    │             └ <starlette.requests.Request object at 0x7fa743d73550>
                     │    └ <bound method TimeHeaderMiddleware.dispatch of <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>>
                     └ <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>

  File "/Users/neonkid/PycharmProjects/blog/shared/middlewares/timeheader/__init__.py", line 10, in dispatch
    res = await call_next(request)
                │         └ <starlette.requests.Request object at 0x7fa743d73550>
                └ <bound method BaseHTTPMiddleware.call_next of <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>>

  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
    │    └ <method 'result' of '_asyncio.Task' objects>
    └ <Task finished name='Task-11' coro=<BaseHTTPMiddleware.call_next.<locals>.coro() done, defined at /Users/neonkid/Library...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method Queue.put of <Queue at 0x7fa743ce1b80 maxsize=0 tasks=1>>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>
          └ <shared.middlewares.timeheader.TimeHeaderMiddleware object at 0x7fa743886820>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
                     │    │             │        │    └ <function BaseHTTPMiddleware.call_next at 0x7fa7420a48b0>
                     │    │             │        └ <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>
                     │    │             └ <starlette.requests.Request object at 0x7fa743d73dc0>
                     │    └ <bound method RequireJSON.dispatch of <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>>
                     └ <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>

  File "/Users/neonkid/PycharmProjects/blog/shared/middlewares/json/__init__.py", line 21, in dispatch
    return await call_next(request)
                 │         └ <starlette.requests.Request object at 0x7fa743d73dc0>
                 └ <bound method BaseHTTPMiddleware.call_next of <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>>

  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
    │    └ <method 'result' of '_asyncio.Task' objects>
    └ <Task finished name='Task-12' coro=<BaseHTTPMiddleware.call_next.<locals>.coro() done, defined at /Users/neonkid/Library...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method Queue.put of <Queue at 0x7fa744088e80 maxsize=0 tasks=1>>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>
          └ <shared.middlewares.json.RequireJSON object at 0x7fa7438867c0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
                     │    │             │        │    └ <function BaseHTTPMiddleware.call_next at 0x7fa7420a48b0>
                     │    │             │        └ <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>
                     │    │             └ <starlette.requests.Request object at 0x7fa743ce1a00>
                     │    └ <bound method LoggerMiddleware.dispatch of <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>>
                     └ <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>

  File "/Users/neonkid/PycharmProjects/blog/shared/middlewares/log/__init__.py", line 10, in dispatch
    res = await call_next(req)
                │         └ <starlette.requests.Request object at 0x7fa743ce1a00>
                └ <bound method BaseHTTPMiddleware.call_next of <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>>

  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
    │    └ <method 'result' of '_asyncio.Task' objects>
    └ <Task finished name='Task-13' coro=<BaseHTTPMiddleware.call_next.<locals>.coro() done, defined at /Users/neonkid/Library...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method Queue.put of <Queue at 0x7fa74402b040 maxsize=0 tasks=1>>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.middleware.cors.CORSMiddleware object at 0x7fa743886580>
          └ <shared.middlewares.log.LoggerMiddleware object at 0x7fa743886760>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method Queue.put of <Queue at 0x7fa74402b040 maxsize=0 tasks=1>>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <starlette.exceptions.ExceptionMiddleware object at 0x7fa743886520>
          └ <starlette.middleware.cors.CORSMiddleware object at 0x7fa743886580>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fa743f3f550>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <fastapi.routing.APIRouter object at 0x7fa7415724f0>
          └ <starlette.exceptions.ExceptionMiddleware object at 0x7fa743886520>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fa743f3f550>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │     └ <function Route.handle at 0x7fa74206cf70>
          └ <fastapi.routing.APIRoute object at 0x7fa743799880>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7fa743f3f550>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fa743d...
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          │    └ <function request_response.<locals>.app at 0x7fa7437c3430>
          └ <fastapi.routing.APIRoute object at 0x7fa743799880>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7fa74402b1c0>
                     └ <function get_request_handler.<locals>.app at 0x7fa7437c33a0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
                          └ <function serialize_response at 0x7fa742061dc0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 116, in serialize_response
    value, errors_ = field.validate(response_content, {}, loc=("response",))
                     │     │        └ {'results': [<shared.models.category.Category object at 0x7fa744a22e20>, <shared.models.category.Category object at 0x7fa744a...
                     │     └ <cyfunction ModelField.validate at 0x7fa7416a0860>
                     └ ModelField(name='Response_get_categories_categories_get', type=Optional[CategoryModel], required=False, default=None)

  File "pydantic/fields.py", line 723, in pydantic.fields.ModelField.validate
    v, errors = self._validate_singleton(v, values, loc, cls)

  File "pydantic/fields.py", line 906, in pydantic.fields.ModelField._validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)

  File "pydantic/fields.py", line 913, in pydantic.fields.ModelField._apply_validators
    v = validator(cls, v, values, self, self.model_config)

  File "pydantic/class_validators.py", line 310, in pydantic.class_validators._generic_validator_basic.lambda12
    return lambda cls, v, values, field, config: validator(v)
                                                 └ <cyfunction validator at 0x7fa741611450>

  File "pydantic/main.py", line 729, in pydantic.main.BaseModel.validate
    return cls(**value)

  File "pydantic/main.py", line 398, in pydantic.main.BaseModel.__init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           └ <cyfunction validate_model at 0x7fa7416caad0>

  File "pydantic/main.py", line 1034, in pydantic.main.validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)

  File "pydantic/fields.py", line 734, in pydantic.fields.ModelField.validate
    v, errors = self._validate_sequence_like(v, values, loc, cls)

  File "pydantic/fields.py", line 767, in pydantic.fields.ModelField._validate_sequence_like
    r, ee = self._validate_singleton(v_, values, v_loc, cls)

  File "pydantic/fields.py", line 899, in pydantic.fields.ModelField._validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)

  File "pydantic/fields.py", line 723, in pydantic.fields.ModelField.validate
    v, errors = self._validate_singleton(v, values, loc, cls)

  File "pydantic/fields.py", line 906, in pydantic.fields.ModelField._validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)

  File "pydantic/fields.py", line 913, in pydantic.fields.ModelField._apply_validators
    v = validator(cls, v, values, self, self.model_config)

  File "pydantic/class_validators.py", line 310, in pydantic.class_validators._generic_validator_basic.lambda12
    return lambda cls, v, values, field, config: validator(v)
                                                 └ <cyfunction validator at 0x7fa741611450>

  File "pydantic/main.py", line 731, in pydantic.main.BaseModel.validate
    return cls.from_orm(value)

  File "pydantic/main.py", line 623, in pydantic.main.BaseModel.from_orm
    values, fields_set, validation_error = validate_model(cls, obj)
                                           └ <cyfunction validate_model at 0x7fa7416caad0>

  File "pydantic/main.py", line 1013, in pydantic.main.validate_model
    value = input_data.get(field.alias, _missing)
                                        └ <object object at 0x7fa74152a590>

  File "pydantic/utils.py", line 418, in pydantic.utils.GetterDict.get
    return getattr(self._obj, key, default)

  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 453, in __get__
    return self.impl.get(state, dict_)
           │    │    │   │      └ {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fa744a27fa0>, 'id': 105, 'post_count': 0, 'name': '공지...
           │    │    │   └ <sqlalchemy.orm.state.InstanceState object at 0x7fa744a27fa0>
           │    │    └ <function AttributeImpl.get at 0x7fa742b83550>
           │    └ <sqlalchemy.orm.attributes.CollectionAttributeImpl object at 0x7fa743c209e0>
           └ <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7fa742dbd9a0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 897, in get
    value = self.callable_(state, passive)
            │    │         │      └ symbol('PASSIVE_OFF')
            │    │         └ <sqlalchemy.orm.state.InstanceState object at 0x7fa744a27fa0>
            │    └ <member 'callable_' of 'AttributeImpl' objects>
            └ <sqlalchemy.orm.attributes.CollectionAttributeImpl object at 0x7fa743c209e0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 874, in _load_for_state
    return self._emit_lazyload(
           │    └ <function LazyLoader._emit_lazyload at 0x7fa742d58940>
           └ <sqlalchemy.orm.strategies.LazyLoader object at 0x7fa743c1f9e0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 1029, in _emit_lazyload
    result = session.execute(
             │       └ <function Session.execute at 0x7fa742cf4ca0>
             └ <sqlalchemy.orm.session.Session object at 0x7fa74402b910>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1662, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             │    │           │          │             └ immutabledict({'_sa_orm_load_options': default_load_options(_invoke_all_eagers=False, _lazy_loaded_from=<sqlalchemy.orm.state...
             │    │           │          └ {'%(140356372971472 param)s': 105}
             │    │           └ LinkedLambdaElement(<code object <lambda> at 0x7fa742d40030, file "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/bu...
             │    └ <function Connection._execute_20 at 0x7fa7428e2f70>
             └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           │    │     │             │               └ immutabledict({'_sa_orm_load_options': default_load_options(_invoke_all_eagers=False, _lazy_loaded_from=<sqlalchemy.orm.state...
           │    │     │             └ immutabledict({})
           │    │     └ ({'%(140356372971472 param)s': 105},)
           │    └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
           └ <bound method StatementLambdaElement._execute_on_connection of LinkedLambdaElement(<code object <lambda> at 0x7fa742d40030, f...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/lambdas.py", line 481, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x7fa7428e2dc0>
           └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x7fa7428e40d0>
          └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x7fa7428e4280>
    └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1933, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
    │    │      │                           └ (<class 'sqlalchemy.exc.MissingGreenlet'>, MissingGreenlet("greenlet_spawn has not been called; can't call await_() here. Was...
    │    │      └ (<class 'sqlalchemy.exc.MissingGreenlet'>, MissingGreenlet("greenlet_spawn has not been called; can't call await_() here. Was...
    │    └ <function raise_ at 0x7fa74233e5e0>
    └ <module 'sqlalchemy.util' from '/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3...
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7fa742ab1040>
    │    └ <sqlalchemy.dialects.postgresql.asyncpg.PGDialect_asyncpg object at 0x7fa74397b8e0>
    └ <sqlalchemy.future.engine.Connection object at 0x7fa74402b7f0>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ (105,)
    │      │       └ 'SELECT category.id AS category_id, category.name AS category_name, category.parent_id AS category_parent_id, category.post_c...
    │      └ <function AsyncAdapt_asyncpg_cursor.execute at 0x7fa743004430>
    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7fa743f86890>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 449, in execute
    self._adapt_connection.await_(
    │    └ <member '_adapt_connection' of 'AsyncAdapt_asyncpg_cursor' objects>
    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7fa743f86890>
  File "/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 47, in await_only
    raise exc.MissingGreenlet(
          │   └ <class 'sqlalchemy.exc.MissingGreenlet'>
          └ <module 'sqlalchemy.exc' from '/Users/neonkid/Library/Caches/pypoetry/virtualenvs/blog-Qk0gdjyh-py3.9/lib/python3....

sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_() here. Was IO attempted in an unexpected place? (Background on this error at: http://sqlalche.me/e/14/xd2s)
```

If the response model is not set, an error does not occur, but if the response model is set, an error occurs.
Upon further checking, it seems that an error occurred in the function ```parse_obj``` in the pydantic model.

**Comment by PetrMixayloff** [comment]
I have the same problem.
My endpoint:
```
@router.post("/", response_model=schemas.User)
async def create_user(user_in: schemas.UserCreate, async_db: AsyncSession = Depends(deps.get_async_db),
                      current_user: models.User = Depends(deps.get_current_active_admin_user)):
    """
    Create new user.
    """
    user = await crud.user.get_by_phone_async(async_db=async_db, phone=user_in.phone)
    if user:
        raise HTTPException(
            status_code=400,
            detail="The user with this phone number already exists in the system.",
        )
    user = await crud.user.create_async(async_db=async_db, obj_in=user_in)
    return user
```
User model:
```
class UserIn(BaseModel):
    id: UUID
    phone: str
    full_name: str
    position: str
    description: Optional[str] = None
    avatar: Optional[str] = None
    shop_id: UUID
    permissions: Optional[Permissions] = None
    last_login: Optional[datetime] = None
    is_superuser: Optional[bool] = False
    is_staff: Optional[bool] = True

    class Config:
        orm_mode = True
```
Permissions model:
```
class PermissionsBase(BaseModel):
    id: UUID
    user_id: UUID
    orders: Optional[str] = None
    products: Optional[str] = None
    raw: Optional[str] = None
    clients: Optional[str] = None
    staff: Optional[str] = None
    warehouse: Optional[str] = None

    class Config:
        orm_mode = True
```
I get this error when i try to do schemas.User.from_orm(user).
If I remove permissions field from User model everything is ok.

**Comment by PetrMixayloff** [comment]
In my case I've solved problem/ This is not problem with pydantic. This is problem with relationship lazy attribute in sql alchemy model. By default is has lazy loading. But if you use AsyncSessions lazy loading will raise an error.

**Comment by samuelcolvin** [comment]
This is fixed on main and will be included in V2, you can try it now on the alpha release.
