### ISSUE TITLE
Pre/Post Validator can have unexpected behavior if combined with class config

### ISSUE THREAD

**Issue by curtiscook** [pydantic/pydantic#2808]
### Checks

* [ x] I added a descriptive title to this issue
* [x] I have searched (google, GitHub) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I was on the fence as to whether this is a bug or a feature request since this is a UX bug with a workaround. 

Basically, I believe that anystr_strip_whitespace should have the option to run before an empty -> none coercion. The workaround is to add the v.strip() to the validator, however, it _seems_ like this is unintended behavior & it would be preferential to process (or be able to process) the class config before running the validator. 

Validator with `pre=False` ignores the title not being optional, as coercion is after field validation
```
In: class TestModel(BaseModel):
   ...:     title: str
   ...: 
   ...:     class Config:
   ...:         anystr_strip_whitespace = True
   ...: 
   ...:     @validator('*')
   ...:     def empty_str_to_none(cls, v):
   ...:         if v == '':
   ...:             return None
   ...:         return v
   ...:     

In: TestModel(title=' ')
Out: TestModel(title=None)

In: TestModel(title='')
Out: TestModel(title=None)

In: TestModel(title=None)
Out: Traceback (most recent call last):
  File "/Users/curtis/repos/cs/user-content-service/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-58-da178497c77c>", line 1, in <module>
    TestModel(title=None)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
title
  none is not an allowed value (type=type_error.none.not_allowed)

```

Validator with `pre=True` fails validation on an empty string (good) but performs the strip after validation (bad)
```
In: class TestModel(BaseModel):
   ...:     title: str
   ...: 
   ...:     class Config:
   ...:         anystr_strip_whitespace = True
   ...: 
   ...:     @validator('*', pre=True)
   ...:     def empty_str_to_none(cls, v):
   ...:         if v == '':
   ...:             return None
   ...:         return v
   ...:     

In: TestModel(title=' ')
Out: TestModel(title='')

In: TestModel(title='')
Traceback (most recent call last):
  File "/Users/curtis/repos/cs/user-content-service/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-50-f9f73f911f79>", line 1, in <module>
    TestModel(title='')
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
title
  none is not an allowed value (type=type_error.none.not_allowed)
```

Workaround - strip the string in the validator with `pre=True`, which doesn't use built-in configs:

```
In: class TestModel(BaseModel):
   ...:     title: str
   ...: 
   ...:     @validator('*', pre=True)
   ...:     def empty_str_to_none(cls, v):
   ...:         if isinstance(v, str):
   ...:             v = v.strip()
   ...:         if v == '':
   ...:             return None
   ...:         return v
   ...: 
    
In: TestModel(title='')
Traceback (most recent call last):
  File "/Users/curtis/repos/cs/user-content-service/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-53-f9f73f911f79>", line 1, in <module>
    TestModel(title='')
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
title
  none is not an allowed value (type=type_error.none.not_allowed)

In: TestModel(title=' ')
Traceback (most recent call last):
  File "/Users/curtis/repos/cs/user-content-service/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-54-b1dfb43e153d>", line 1, in <module>
    TestModel(title=' ')
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestModel
title
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by adriangb** [comment]
I don't think this is a bug. You're describing the behavior as it is. The string stripping happens within string validation, you can choose to do the empty string to None conversion before or after the string conversion. You probably also want `str | None` not just `str` if you're going to put `None` values in that field, either from a validator or constructor.

Here's what your example looks like in V2:

```python
from typing import Annotated, Optional

from pydantic import BaseModel
from pydantic.annotated_arguments import AfterValidator
from pydantic.config import ConfigDict

StrToNone = Annotated[Optional[str], AfterValidator(lambda x: x if x else None)]


class TestModel(BaseModel):
    title: StrToNone

    model_config = ConfigDict(str_strip_whitespace=True)

assert TestModel(title=' ').title is None
assert TestModel(title='').title is None
assert TestModel(title=None).title is None
```
