### ISSUE TITLE
Unable to use validate_arguments decorator with forward/self-referenced types

### ISSUE THREAD

**Issue by gertvdijk** [pydantic/pydantic#2901]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /path/to/my/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.4 (default, Apr 23 2021, 23:41:52)  [GCC 9.3.0]
                     platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
...
```

I'm trying to use the `@validate_arguments` decorator with a forward or self-referencing type, but this fails.

```py
from __future__ import annotations
from pydantic import BaseModel, validate_arguments
import uuid
from typing import ForwardRef


# as per Pydantic example docs, explicit forward ref (see also below)
# https://pydantic-docs.helpmanual.io/usage/postponed_annotations/
MyModel = ForwardRef('MyModel')


class MyModel(BaseModel):
    id: uuid.UUID
    bar: str

    @classmethod
    @validate_arguments
    def custom_copy(cls, in_: MyModel) -> MyModel:
        return MyModel(id=uuid.uuid4(), bar=in_.bar)


MyModel.update_forward_refs(MyModel=MyModel)


if __name__ == "__main__":
    a = MyModel(id=uuid.uuid4(), bar="a")
    print(a)
    b = MyModel.custom_copy(a)
    print(b)
```
yields:
```
id=UUID('c3122f1a-a15f-48d7-b49b-ad1d8d816c75') bar='a'
Traceback (most recent call last):
  File "/path/to/pydantictest2.py", line 26, in <module>
    b = MyModel.custom_copy(a)
  File "pydantic/decorator.py", line 39, in pydantic.decorator.validate_arguments.validate.wrapper_function
    import itertools
  File "pydantic/decorator.py", line 132, in pydantic.decorator.ValidatedFunction.call
    func.__module__ = getattr(self, 'module', callermodule)
  File "pydantic/decorator.py", line 129, in pydantic.decorator.ValidatedFunction.init_model_instance
    callermodule = '?'
  File "pydantic/main.py", line 404, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1040, in pydantic.main.validate_model
  File "pydantic/fields.py", line 699, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "in_" not yet prepared so type is still a ForwardRef, you might need to call CustomCopy.update_forward_refs().
```

I wonder where `CustomCopy` comes from... 🤔 

Without the `@validate_arguments` decorator, the code works well, though.

Using `@validate_arguments(config=dict(arbitrary_types_allowed=True))` does not change anything for me.

I've tried alternatives, e.g. removing the explicit `ForwardRef` (as it's [not supposed to be used directly](https://docs.python.org/3/library/typing.html#typing.ForwardRef)):

```py
from __future__ import annotations
from pydantic import BaseModel, validate_arguments
import uuid


class MyModel(BaseModel):
    id: uuid.UUID
    bar: str

    @classmethod
    @validate_arguments
    def custom_copy(cls, in_: 'MyModel') -> 'MyModel':
        return MyModel(id=uuid.uuid4(), bar=in_.bar)


MyModel.update_forward_refs(MyModel=MyModel)


if __name__ == "__main__":
    a = MyModel(id=uuid.uuid4(), bar="a")
    print(a)
    b = MyModel.custom_copy(a)
    print(b)
```
yields:
```
Traceback (most recent call last):
  File "/path/to/pydantictest2.py", line 6, in <module>
    class MyModel(BaseModel):
  File "/path/to/pydantictest2.py", line 12, in MyModel
    def custom_copy(cls, in_: 'MyModel') -> 'MyModel':
  File "pydantic/decorator.py", line 48, in pydantic.decorator.validate_arguments
    
  File "pydantic/decorator.py", line 35, in pydantic.decorator.validate_arguments.validate
    import re
  File "pydantic/decorator.py", line 77, in pydantic.decorator.ValidatedFunction.__init__
    for a in ('args', 'varargs', 'varkw', 'defaults', 'kwonlyargs',
  File "pydantic/typing.py", line 82, in pydantic.typing.get_all_type_hints
    'SupportsInt',
  File "/pyenv/path/versions/3.9.4/lib/python3.9/typing.py", line 1449, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/pyenv/path/versions/3.9.4/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/pyenv/path/versions/3.9.4/lib/python3.9/typing.py", line 543, in _evaluate
    self.__forward_value__ = _eval_type(
  File "/pyenv/path/versions/3.9.4/lib/python3.9/typing.py", line 283, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/pyenv/path/versions/3.9.4/lib/python3.9/typing.py", line 539, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'MyModel' is not defined
```

Okay, so at this point I'm confused as to how the decorator can be used at all as per the docs, it's not mentioned in [the limitations](https://pydantic-docs.helpmanual.io/usage/validation_decorator/#limitations) at least.

Another related issue is for cases where the arguments aren't forward/self-referencing, but the return type is:

```py
from __future__ import annotations
from pydantic import BaseModel, validate_arguments
import uuid
from typing import ForwardRef


# as per Pydantic example docs, explicit forward ref (see also below)
# https://pydantic-docs.helpmanual.io/usage/postponed_annotations/
MyModel = ForwardRef('MyModel')


class MyModel(BaseModel):
    id: uuid.UUID
    bar: str

    @classmethod
    @validate_arguments
    def custom_copy(cls, in_: str) -> MyModel:
        return MyModel(id=uuid.uuid4(), bar=in_)


MyModel.update_forward_refs(MyModel=MyModel)


if __name__ == "__main__":
    a = MyModel(id=uuid.uuid4(), bar="a")
    print(a)
    b = MyModel.custom_copy(a.bar)
    print(b)
```

This works for Pydantic, but then mypy isn't happy... 🤷🏼 

```
$ python myfile.py 
myfile.py:12: error: Name "MyModel" already defined on line 9
myfile.py:18: error: Variable "myfile.MyModel" is not valid as a type
myfile.py:18: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
myfile.py:19: error: "ForwardRef" not callable
myfile.py:22: error: "ForwardRef" has no attribute "update_forward_refs"
myfile.py:26: error: "ForwardRef" not callable
myfile.py:28: error: "ForwardRef" has no attribute "custom_copy"
```

I've seen https://github.com/samuelcolvin/pydantic/issues/2411#issuecomment-786612002 in a similar issue and that's why I have `MyModel.update_forward_refs(MyModel=MyModel)` after the model declaration, but this does not work for me as you can see.

I believe I'm either running into a limitation of `@validate_arguments` (= documentation bug) or an actual bug.

**Comment by Kludex** [comment]
We currently don't support this.

PR welcome to document it, or to implement it. 🙏

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
