### ISSUE TITLE
output model has module pydantic.main

### ISSUE THREAD

**Issue by iwtu** [pydantic/pydantic#2907]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
ClassModule: pydantic.main
             pydantic version: 1.8.1
            pydantic compiled: False
                 install path: /Users/lad/venv38/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr  8 2021, 23:19:18)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Base on a role I would like to filter out some attributes of the output model. 
```py
import contextvars
from pydantic import BaseModel, root_validator

rbac_model_roles = {}
context_role = contextvars.ContextVar("context_role", default = None)

class RBACBase(BaseModel):
    @root_validator(pre=True)
    def rbac(cls, values):
        print(cls)
        print(cls.__class__)
        role = context_role.get()
        print(f"class fullname: {cls.__module__}.{cls.__name__}")
        fields = rbac_model_roles[f"{cls.__module__}.{cls.__name__}"][role]
        values = {k:v for k,v in values.items() if k in fields}
        return values

class Output_TerrainAnalysis(RBACBase):
    distance: float = None
    z_diff: float = None
    first_obstacle_distance_terrain: float = None
    first_obstacle_distance_clutter: float = None
    is_visible_terrain: bool = None
    is_visible_clutter: bool = None
    geometry_terrain: list = None
    geometry_clutter: list = None
```

Output:
```
<class 'pydantic.main.Output_TerrainAnalysis'>
<class 'pydantic.main.ModelMetaclass'>
class fullname: pydantic.main.ModelMetaclass'
```

I would expect actual module of Output_TerrainAnalysis and not `pydantic.main.Output_TerrainAnalysis`, which of course does not exist.

**Comment by PrettyWood** [comment]
Hi @iwtu
Please share a full example to reproduce the error
Running your code doesn't do anything.
If I add
```py
Output_TerrainAnalysis()
```
at the end of the file to actually create an instance of `Output_TerrainAnalysis` and trigger `root_validator`, I don't have the same output
```console
<class '__main__.OutputTerrainAnalysis'>
<class 'pydantic.main.ModelMetaclass'>
class fullname: __main__.OutputTerrainAnalysis
Traceback (most recent call last):
  File "/Users/ericjolibois/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_38.py", line 30, in <module>
    OutputTerrainAnalysis()
  File "/Users/ericjolibois/pydantic/pydantic/main.py", line 439, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/Users/ericjolibois/pydantic/pydantic/main.py", line 1065, in validate_model
    input_data = validator(cls_, input_data)
  File "/Users/ericjolibois/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch_38.py", line 14, in rbac
    fields = rbac_model_roles[f"{cls.__module__}.{cls.__name__}"][role]
KeyError: '__main__.OutputTerrainAnalysis'
```

**Comment by iwtu** [comment]
Hi @PrettyWood 

I will try so make full example. On simple examples it works OK. I will try to add also fastapi, because the snippet is from the project which use fastapi.

**Comment by iwtu** [comment]
Hi @PrettyWood 

The demo which demonstrates the bug can be found at https://github.com/iwtu/pyfarbac
However, it can be also fastapi bug.

**Comment by iwtu** [comment]
It's FastApi way how to create response model. FastApi creates new object which doesn't not preserve original __module__ .

**Comment by adriangb** [comment]
You're right, FastAPI does create new models for the output. I _think_ they could set the module for that model, but they're also going to be doing this a lot less with Pydantic V2. This won't change for V1.
