### ISSUE TITLE
Sequence-like `Enum`s are not supported

### ISSUE THREAD

**Issue by ypsah** [pydantic/pydantic#3174]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: True
install path: /home/user/.local/share/virtualenvs/tmp.1234/lib/python3.9/site-packages/pydantic
python version: 3.9.6 (default, Jun 30 2021, 10:22:16)  [GCC 11.1.0]
platform: Linux-5.13.13-arch1-1-x86_64-with-glibc2.33
optional deps. installed: ['typing-extensions']
```

The following snippet:

```py
from enum import Enum
from pydantic import BaseModel

class A(list[int], Enum):
    ZERO = [0,]
    ONE = [1,]

class Model(BaseModel):
    a: A

Model(a=A.ZERO).dict()
```

Fails to run with:

```
Traceback (most recent call last):
  File "/tmp/tmp.6wO38STdpJ/reproducer.py", line 11, in <module>
    Model(a=A.ZERO).dict()
  File "pydantic/main.py", line 510, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 875, in _iter
  File "pydantic/main.py", line 816, in pydantic.main.BaseModel._get_value
  File "/usr/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: <generator object at 0x7f8373d279d0> is not a valid A
```

--------------------------------------------------------------------------------

For a real-world example:

```py
from enum import auto, Enum
from pydantic import BaseModel

class Capability(Enum):
    READ = auto()
    WRITE = auto()

class Role(frozenset[Capability], Enum):
    USER = frozenset({Capability.READ,})
    ADMIN = frozenset({Capability.READ, Capability.WRITE,})

class User(BaseModel):
    role: Role

User(role=Role.USER).dict()
```

--------------------------------------------------------------------------------

Thanks for creating and maintaining `pydantic`! :+1:

**Comment by lig** [comment]
@Viicos thanks!

I can confirm the following test passes on Pydantic v2.1.1.

```py
def test_3174():
    from enum import Enum

    from pydantic import BaseModel

    class A(list[int], Enum):
        ZERO = [0,]
        ONE = [1,]

    class Model(BaseModel):
        a: A

    assert Model(a=A.ZERO).model_dump() == {'a': [0,]}
```
