### ISSUE TITLE
Generic model with conlist will not throw an error if items is greater than max_items

### ISSUE THREAD

**Issue by paulogonc** [pydantic/pydantic#3220]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
```

```py
from pydantic import BaseModel, conlist
from pydantic.generics import GenericModel
from typing import Generic, TypeVar

T = TypeVar('T')

class Model_Int_ConList(BaseModel): 
    con_lis: conlist(int, min_items=1, max_items=4)

md_int_cn_ls = Model_Int_ConList(con_lis=[1,2,3,4]) # --> throws error as expected con_lis "ensure this value has at most 4 items (type=value_error.list.max_items; limit_value=4)"
print(md_int_cn_ls.dict())

# same model as above but now as a generic model
class Model_Generic(GenericModel, Generic[T]):
    con_lis: conlist(T, min_items=1, max_items=4)

md_int_cn_ls_custom = Model_Generic[int](con_lis=[1,2,3,4,5]) # --> would expect an error similiar to above model
print(md_int_cn_ls_custom.dict())

{'con_lis': [1, 2, 3, 4, 5]}
```
As shown in the example code the Generic Model accepts a list with more than the allowed 4 items. I would expect a same behavior like using the model ```Model_Int_ConList```. Maybe I'm using the GenericModel concept from pydantic wrong?!?

**Comment by 243f6a8885a308d313198a2e037** [comment]
In Python 3.8, the situation is more serious: `TypeError` is raised.

| Python | pydantic | result |
|---|---|---|
| 3.8.14 | 1.9.2 | `TypeError` |
| 3.9.10 | 1.9.2 | `{'con_lis': [1, 2, 3, 4, 5]}` |
| 3.8.14 | 1.10.2 | `TypeError` |
| 3.9.10 | 1.10.2 | `{'con_lis': [1, 2, 3, 4, 5]}` |

```plaintext
❯ python -V
Python 3.8.14
❯ pip freeze | grep pydantic
pydantic==1.10.2

❯ python issue_3220.py 
{'con_lis': [1, 2, 3, 4]}
Traceback (most recent call last):
  File "issue_3220.py", line 17, in <module>
    md_int_cn_ls_custom = Model_Generic[int](
  File "/home/pydantic/trial_venvs/venv_issue_3220_py38/lib/python3.8/site-packages/pydantic/generics.py", line 137, in __class_getitem__
    _prepare_model_fields(created_model, fields, instance_type_hints, typevars_map)
  File "/home/pydantic/trial_venvs/venv_issue_3220_py38/lib/python3.8/site-packages/pydantic/generics.py", line 356, in _prepare_model_fields
    concrete_type = replace_types(field_type_hint, typevars_map)
  File "/home/pydantic/trial_venvs/venv_issue_3220_py38/lib/python3.8/site-packages/pydantic/generics.py", line 263, in replace_types
    return origin_type[resolved_type_args]
TypeError: 'type' object is not subscriptable
```

**Comment by hramezani** [comment]
I can confirm both problems:

1. Generic model with `conlist` reported by @paulogonc 
2. `TypeError` problem in Python < 3.9 reported by @243f6a8885a308d313198a2e037 

We are working on `v2`. let's consider this bug in `V2`

**Comment by adriangb** [comment]
This works in V2:

```python
from pydantic import BaseModel, conlist, ValidationError
from typing import Generic, TypeVar

T = TypeVar('T')

class Model(BaseModel): 
    con_lis: conlist(int, min_length=1, max_length=4)

try:
    md_int_cn_ls = Model(con_lis=[1,2,3,4,5])
except ValidationError:
    pass
else:
    assert False

# same model as above but now as a generic model
class ModelGeneric(BaseModel, Generic[T]):
    con_lis: conlist(T, min_length=1, max_length=4)


try:
    md_int_cn_ls = ModelGeneric(con_lis=[1,2,3,4,5])
except ValidationError:
    pass
else:
    assert False
```

Runs with no errors.
