### ISSUE TITLE
Union does not work with GenericModel

### ISSUE THREAD

**Issue by povilasb** [pydantic/pydantic#3276]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I've been toying with the master branch since [autocomplete support got merged](https://github.com/samuelcolvin/pydantic/pull/2721) and seems like there is a regression since `1.8.2`.
Consider this example:

```py
from typing import Union, TypeVar, Generic
from pydantic.generics import GenericModel

T = TypeVar("T")


class Request(GenericModel, Generic[T]):
    url: str
    data: Union[str, bytes, None] = None


class PostData(Request[str]):
    url = "https://httpbin.org/anything"
    data = "rand data"

```

With pydantic `1.8.2` it produces such output:
```bash
$ pip3 install git+https://github.com/samuelcolvin/pydantic@v1.8.2
$ python3 -c "import pydantic.utils; print(pydantic.utils.version_info())"
            pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /private/tmp/pyenv2/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Jun 29 2021, 06:20:32)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
     
$ python3 demo.py
TypeError: The type of PostData.data differs from the new default value; if you wish to change the type of this field, please use a type annotation 
```
Which is ok, all I have to do is specify `data` type:
```py
class PostData(Request[str]):
    url = "https://httpbin.org/anything"
    data: str = "rand data"
```

But with latest commit on `master` branch it yields a different error:
```bash
$ pip3 install git+https://github.com/samuelcolvin/pydantic@c256dcc
$ python3 -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /private/tmp/pyeanv/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Jun 29 2021, 06:20:32)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
     
$ python3 demo.py
Traceback (most recent call last):
  File "/private/tmp/demo.py", line 16, in <module>
    class PostData(Request[str]):
  File "/private/tmp/pyeanv/lib/python3.9/site-packages/pydantic/main.py", line 236, in __new__
    if lenient_issubclass(inferred.type_, fields[var_name].type_):
  File "/private/tmp/pyeanv/lib/python3.9/site-packages/pydantic/utils.py", line 153, in lenient_issubclass
    return isinstance(cls, type) and issubclass(cls, class_or_tuple)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 713, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

Any ideas? :)

**Comment by Kludex** [comment]
We don't have `GenericModel` on Pydantic V2 anymore.

For that reason, I'll be closing the issue. 🙏

**Comment by dmontagu** [comment]
I don't think this issue was specific to generic models (you didn't actually use the typevar in your model anyway), but either way, in v2, it seems to be fixed (noting that you just use BaseModel directly in v2, instead of GenericModel):
```python
from typing import Union, TypeVar, Generic
from pydantic import BaseModel

T = TypeVar("T")


class Request(BaseModel, Generic[T]):
    url: str
    data: Union[str, bytes, None] = None


class PostData(Request[str]):
    url: str = "https://httpbin.org/anything"
    data: str = "rand data"
```
No error is raised when you run the code above

**Comment by povilasb** [comment]
Cool! Thanks, will be playing around with v2 soon :)
