### ISSUE TITLE
Typechecking with None type in Union not reported properly

### ISSUE THREAD

**Issue by petrsynek** [pydantic/pydantic#3385]
### Checks

* [x ] I added a descriptive title to this issue
* [x ] I have searched (google, github) for similar issues and couldn't find anything
* [x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
When I have Union of  None and some other type(s) the reporting will go wrong as the option to use None type is not listed when reporting error. 

Code example listed below will produce

```
1 validation error for NoneOnlyModel
simple_list
  value is not None (type=type_error.not_none) # !!! this is good... I want this to be there !!!
====================
2 validation errors for NoneListDictModel
simple_list
  value is not a valid list (type=type_error.list)
simple_list
  value is not a valid dict (type=type_error.dict) # !!! Now None type it is missing! !!!
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: D:\Devel\Exputec\incyght_user\venv_bordel\Lib\site-packages\pydantic
               python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
...
```

Example of python code to reproduce the error:
```py
from typing import Union

from pydantic import BaseModel


class NoneOnlyModel(BaseModel):
    simple_list: Union[None] = None


class NoneListDictModel(BaseModel):
    simple_list: Union[None, list, dict] = None


def main():
    try:
        NoneOnlyModel(simple_list='foo')
    except Exception as e:
        print(e)

    print('=' * 20)

    try:
        NoneListDictModel(simple_list='foo')
    except Exception as e:
        print(e)


if __name__ == "__main__":
    main()
```

**Comment by silversum** [comment]
Hi!
Try to use `Union[Literal[None], list, dict]` - it's works fine for me)

**Comment by petrsynek** [comment]
> Hi! Try to use `Union[Literal[None], list, dict]` - it's working fine for me)

Yeah, well, the whole project is still running on 3.7, and I don't believe that I could force the transition to 3.8 :)

**IMHO, it's still buggy behavior which you won't expect and should be fixed.**

**Comment by silversum** [comment]
> project is still running on 3.7

You can import `Literal` from `typing_extension` package =) (already in `pydantic` requirements)

**Comment by petrsynek** [comment]
Well that's getting me to another error!

```python
class Test(BaseModel):
    a: Union[Literal[None], int]
    class Config:
        validate_assignment = True
```
It produces the right error message when passing the string, but...

when trying to instantiate ...
```
>>> test = Test(a=None)
Traceback (most recent call last):
  File "D:\Devel\Exputec\incyght_user\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-ba82492cfde2>", line 1, in <module>
    test = MBM(a=None)
  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MBM
a
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by adriangb** [comment]
Here's the behavior I'm seeing on Pydantic V2:

```python
from typing import Literal, Union

from pydantic import BaseModel


class Test(BaseModel):
    a: Union[Literal[None], int]


Test(a=None)  # ok
Test(a=1)  # ok
Test(a='a')
"""
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Test
a.literal[None]
  Input should be None [type=literal_error, input_value='a', input_type=str]
a.int
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a', input_type=str]
"""
```

It is true that there is no `None` error if you don't use a literal:

```python
from typing import Union

from pydantic import BaseModel


class Test(BaseModel):
    a: Union[None, int]


Test(a=None)
Test(a=1)
Test(a='a')
"""
Traceback (most recent call last):
  File "/Users/adriangarciabadaracco/GitHub/pydantic/test.py", line 12, in <module>
    Test(a='a')
  File "/Users/adriangarciabadaracco/GitHub/pydantic/pydantic/main.py", line 241, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Test
a
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a', input_type=str]
"""
```

That's just how the behavior is. It has to do with the semantic difference between `Union[None, T]` and `nullable T`. As far as Python is concerned there is no difference, but there is in jsonschema and other things. I take it that you would prefer that it be treated as a union of none and int instead of a nullable int?
