### ISSUE TITLE
pydantic doesn't appreciate property setters

### ISSUE THREAD

**Issue by vincent-lg** [pydantic/pydantic#3395]
# pydantic doesn't like setters on properties

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: C:\Users\...\src\pygasus\pyenv\Lib\site-packages\pydantic
               python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:05:41) [MSC v.1929 32 bit (Intel)]
                     platform: Windows-10-10.0.19042-SP0
     optional deps. installed: ['typing-extensions']
```

`pydantic` seems to tolerate read-only properties on model objects.  However, setters pose an additional challenge.  Although I know they could possibly conflict with pydantic fields, properties (including writable properties) do have their advantages in Python, so using both would be great!

```py
from pydantic import BaseModel

class User(BaseModel):
    last_name: str
    first_name: str
    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    @full_name.setter
    def full_name(self, full_name):
        self.first_name, self.last_name = full_name.split()

user = User(first_name="Vincent", last_name="lg")
print(user.full_name)
user.full_name = "Alex LG"
```

## Error output

The last line raises this exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\src\pygasus\pyenv\lib\site-packages\pydantic\main.py", line 422, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "User" object has no field "full_name"
```

Is there a quick workaround?  I couldn't find any information on this topic... except code that didn't work.

Thanks,

**Comment by victorteokw** [comment]
Hi @vincent-lg, you may use [JSONClasses](https://github.com/fillmula/jsonclasses). It supports ORM and calculated getters and setters.

**Comment by COCOLMAN** [comment]
It seems that pydantic cannot be used with descriptors.

```
from pydantic import BaseModel

class User(BaseModel):
    last_name: str
    first_name: str

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    @full_name.setter
    def full_name(self, full_name):
        self.first_name, self.last_name = full_name.split()

user = User(first_name="Vincent", last_name="lg")


type(user).__dict__['full_name'].__get__(type(user)) # AttributeError: type object 'User' has no attribute 'first_name'

```

**Comment by klamann** [comment]
Had the same problem (#3663), still an issue in pydantic 1.9.0

**Comment by justinjeffery-ipf** [comment]
I found this: https://github.com/justengel/pydantic_property
Would be nice if this was fixed though.

**Comment by adriangb** [comment]
Pydantic V2 has _much_ better support for `@proprty` on models (as well as computed fields!!). This example works great in V2:

```python
from pydantic import BaseModel

class User(BaseModel):
    last_name: str
    first_name: str

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @full_name.setter
    def full_name(self, full_name: str) -> str:
        self.first_name, self.last_name = full_name.split()

user = User(first_name="Vincent", last_name="lg")
print(user.full_name)
user.full_name = "Alex LG"
```

Since this is fixed in V2 and unlikely to be backported to V1, I'm closing this as completed. Please re-open if you have any more questions.
