### ISSUE TITLE
Error using np.ndarray in dataclass

### ISSUE THREAD

**Issue by juergmaier** [pydantic/pydantic#3516]
### Checks

* [ x] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
`(base) juerg@pcjm:~/Projekte/fastAPI$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/juerg/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 (default, Dec 11 2020, 14:32:07)  [GCC 7.3.0]
                     platform: Linux-5.13.0-22-generic-x86_64-with-glibc2.34
     optional deps. installed: ['dotenv', 'typing-extensions']
`

### My Code
`
from pydantic.dataclasses import dataclass
import numpy as np

<at>dataclass
class TestNumpyArray:
    myArray: np.ndarray = np.zeros(10)

testNumpyArray = TestNumpyArray()
print(testNumpyArray.myArray)
`
### Output
`
/usr/bin/python3.9 /snap/pycharm-community/261/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 33431 --file /home/juerg/.config/JetBrains/PyCharmCE2021.3/scratches/scratch.py
Connected to pydev debugger (build 213.5744.248)
Traceback (most recent call last):
  File "/snap/pycharm-community/261/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/261/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/juerg/.config/JetBrains/PyCharmCE2021.3/scratches/scratch.py", line 6, in <module>
    class TestNumpyArray:
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
    if metadata is None else
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
    self.init = init
  File "pydantic/dataclasses.py", line 186, in pydantic.dataclasses._process_class
    # The name of an attribute on the class where we store the Field
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 445, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 473, in pydantic.fields.ModelField._set_default_and_type
  File "pydantic/fields.py", line 345, in pydantic.fields.ModelField.get_default
  File "pydantic/utils.py", line 627, in pydantic.utils.smart_deepcopy
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
python-BaseException
`
...
```

**Comment by ThomAub** [comment]
If you don't need the schema than something 

```python
from pydantic import BaseModel, Field

class TestNumpyArray(BaseModel):
    class Config:
        arbitrary_types_allowed = True
    myArray: np.ndarray = Field(default_factory=lambda: np.zeros(10))

print(TestNumpyArray())
TestNumpyArray(myArray=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))
```

see #380 , #2923 for more info :)

**Comment by Kludex** [comment]
You need to pass the `arbitrary_types_allowed` to the `dataclass`. You can read more about it [here](https://docs.pydantic.dev/latest/usage/model_config/).

On V2, you can write the above as:

```py
from pydantic.dataclasses import dataclass
from pydantic import ConfigDict, Field
import numpy as np


@dataclass(config=ConfigDict(arbitrary_types_allowed=True))
class TestNumpyArray:
    myArray: np.ndarray = Field(default_factory=lambda: np.zeros(10))


testNumpyArray = TestNumpyArray()
print(testNumpyArray.myArray)
```

Also, as a _non-asked tip_... You can highlight your python code on GitHub doing the following:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/7353520/235354150-aba13caa-d864-4a9b-ab48-f14d41f9c8b1.png">
