### ISSUE TITLE
Duplicate inheritance produces forsaking exception message

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#3578]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/can/.cache/pypoetry/virtualenvs/bikipy-Cb5pIUSo-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 24 2021, 19:46:46)  [GCC 11.1.0]
                     platform: Linux-5.15.11-zen1-1-zen-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

In vanilla Python:
```py
class A:
    pass

class B(A, A):
    pass
```
Output:
```
Traceback (most recent call last):
  File "/home/can/Software_Projects/BiKiPy/examples/nort_belhaj_analysis/test.py", line 4, in <module>
    class B(A, A):
TypeError: duplicate base class A
```

The error raised when using `pydantic.BaseModel` is comparatively ambiguous, and logically lacking; of no help for debugging, forsaking the user:
```py
from pydantic import BaseModel


class A(BaseModel):
    pass

class B(A, A):
    pass
```
Output:
```
Traceback (most recent call last):
  File "/home/can/Software_Projects/BiKiPy/examples/nort_belhaj_analysis/test.py", line 7, in <module>
    class B(A, A):
  File "pydantic/main.py", line 244, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 190, in pydantic.main.inherit_config
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Config, Config
```

A related issue is when the inherited classes are wrapped in duplicates. This too produces an ambiguous exception:
```py
from pydantic import BaseModel

class A(BaseModel):
    pass

class B(A):
    pass

class C(A, B):
    pass
```
Output:
```
Traceback (most recent call last):
  File "/home/can/Software_Projects/BiKiPy/examples/nort_belhaj_analysis/test.py", line 10, in <module>
    class C(A, B):
  File "pydantic/main.py", line 244, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 190, in pydantic.main.inherit_config
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Config, Config
```
Vanilla Python:
```
class A:
    pass

class B(A):
    pass

class C(A, B):
    pass
```
Output:
```
Traceback (most recent call last):
  File "/home/can/Software_Projects/BiKiPy/examples/nort_belhaj_analysis/test.py", line 9, in <module>
    class C(A, B):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B
```

## Solution
Improve exception handle messaging:
```
try:
    ...
except TypeError as e:
   msg = "..."
   raise e(msg)

**Comment by Kludex** [comment]
This is solved on V2. 🙏
