### ISSUE TITLE
Cannot use valid dataclass on nested recursive field, only dict

### ISSUE THREAD

**Issue by dnp1** [pydantic/pydantic#3695]
# Bug

Cannot use valid dataclass on recursive nested field, only dict

Given a dataclass "Example", `example.parent_example = valid_example` lead to exception "value is not a valid dict";

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: True
install path: /home/danilo/.local/share/virtualenvs/api-s-_XIluP/lib/python3.9/site-packages/pydantic
python version: 3.9.9 (main, Dec 14 2021, 10:12:13)  [GCC 11.1.0]
platform: Linux-5.15.13-zen1-1-zen-x86_64-with-glibc2.33
optional deps. installed: ['devtools', 'typing-extensions']
```

```py
import logging
from typing import Optional

from pydantic import ValidationError
from pydantic.dataclasses import dataclass


@dataclass
class Category:
    name: str
    slug: str
    parent: Optional['Category'] = None

    def get_root_category(self) -> 'Category':
        if self.parent:
            return self.parent.get_root_category()
        return self


# noinspection Mypy missing this
Category.__pydantic_model__.update_forward_refs() # used in 1.8.2, now does not make difference

try:
    parent = Category(name='fdfsfd', slug='23424242', parent=None)
    data = Category(name='asasa', slug='dsadasda', parent=parent)
except ValidationError:
    logging.exception("use_to_be_valid_until 1.8.2")
    data = Category(name='asasa', slug='dsadasda', parent=dict(name='fdfsfd', slug='23424242', parent=None))

...
```

Exception traceback:
```
Traceback (most recent call last):
  File "/home/danilo/.config/JetBrains/PyCharm2021.3/scratches/scratch_36.py", line 25, in <module>
    data = Category(name='asasa', slug='dsadasda', parent=parent)
  File "<string>", line 6, in __init__
  File "pydantic/dataclasses.py", line 100, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
pydantic.error_wrappers.ValidationError: 1 validation error for Category
parent
  value is not a valid dict (type=type_error.dict)

Process finished with exit code 0
```

Note: It actually works with BaseModel

**Comment by Conchylicultor** [comment]
I'm also impacted by this. Here is a simpler minimal reproduction example:

```python
from __future__ import annotations
import pydantic


@pydantic.dataclasses.dataclass  # Using BaseModel instead of dataclass works
class Foo:
    sibling: Foo = None


foo = Foo(sibling=Foo())  # value is not a valid dict (type=type_error.dict)
```

**Comment by adriangb** [comment]
This seems to work correctly in both v1.10.X and v2, so it seem like it's been fixed:

```python
from __future__ import annotations

import pydantic


@pydantic.dataclasses.dataclass
class Foo:
    sibling: Foo | None = None


foo = Foo(sibling=Foo())


@pydantic.dataclasses.dataclass
class Bar:
    sibling: Foo | None = None


Foo(sibling=Bar())
"""
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
sibling
  instance of Foo, tuple or dict expected (type=type_error.dataclass; class_name=Foo)
"""

Foo(sibling={'sibling': 123})
"""
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
sibling -> sibling
  instance of Foo, tuple or dict expected (type=type_error.dataclass; class_name=Foo)
"""
```
