### ISSUE TITLE
Can't json-encode bytes.

### ISSUE THREAD

**Issue by frobnitzem** [pydantic/pydantic#3756]
The code below results in an error:

```
from pydantic import BaseModel
class Mod(BaseModel):
   f : bytes

Mod(f=b'\x80').json()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 490, in pydantic.main.BaseModel.json
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "pydantic/json.py", line 95, in pydantic.json.pydantic_encoder
  File "pydantic/json.py", line 52, in pydantic.json.lambda
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: $HOME/Library/Caches/pypoetry/virtualenvs/mpi-remote-1mHOhgpU-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 21 2021, 03:23:42)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-11.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

The expected behavior is to encode the bytes following the [json spec](https://www.json.org/json-en.html), `\uNNNN`, where NNNN are hex-digits.
```
>>> print( Mod(f=b'\x00\x10').json() )
{"f": "\u0000\u0010"}
```
Perhaps the error comes from something trying to convert bytes to unicode, then unicode to json-escaping?

**Comment by Syndace** [comment]
Any recommended workaround until this is fixed? I've tried

```Python
from pydantic import BaseModel
class Mod(BaseModel):
   f : bytes
   class Config:
       json_encoders = { bytes: lambda bs: "".join(map(chr, bs)) }

Mod(f=b'\x80').json()
```

which (while not pretty/efficient) seems to give the correct serialization (`{"f": "\u0080"}`), but parsing needs to be adjusted too:

```
> Mod.parse_raw(Mod(f=b'\x80').json())
Mod(f=b'\xc2\x80')
```

Is there a way to hook into parsing the same way you can hook into serialization?

It's a bummer that a workaround is needed for one of the few Python built-in primitive types, hope this gets some priority.

**Comment by cfxegbert** [comment]
> Is there a way to hook into parsing the same way you can hook into serialization?

```python
from pydantic import BaseModel, errors
from typing import Any, Callable, Generator


def hex_bytes_validator(val: Any) -> bytes:
    if isinstance(val, bytes):
        return val
    elif isinstance(val, bytearray):
        return bytes(val)
    elif isinstance(val, str):
        return bytes.fromhex(val)
    raise errors.BytesError()


class HexBytes(bytes):
    @classmethod
    def __get_validators__(cls) -> Generator[Callable[..., Any], None, None]:
        yield hex_bytes_validator



class Mod(BaseModel):
   f : HexBytes
   class Config:
       json_encoders = {bytes: lambda bs: bs.hex()}
```

**Comment by dmontagu** [comment]
For what it's worth, in v2, you can use a `field_serializer` to convert your bytes fields to hex. If you want a custom type that will always have this behavior, you can do that through the use of `Annotated` and `from pydantic.annotated_arguments import PlainSerializer, PlainValidator`:

```python
from typing import Any

from typing_extensions import Annotated

from pydantic import BaseModel, errors
from pydantic.annotated_arguments import PlainSerializer, PlainValidator


def hex_bytes_validator(val: Any) -> bytes:
    if isinstance(val, bytes):
        return val
    elif isinstance(val, bytearray):
        return bytes(val)
    elif isinstance(val, str):
        return bytes.fromhex(val)
    raise errors.BytesError()


HexBytes = Annotated[bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda v: v.hex())]


class Mod(BaseModel):
    f: HexBytes


print(Mod(f=b'abc').model_dump())
#> {'f': '616263'}
print(Mod(f='616263'))
#> f=b'abc'
```

**Comment by frobnitzem** [comment]
Ah - I see now.  Re-rereading the spec, strings contain "any codepoint." Hence, strings can't encode arbitrary bytes without a convention.  The convention has to come from outside json.

**Comment by TQ86** [comment]
Hello. I've just implemented this approach in my fastapi rest service and it works well, but now I'm getting an error on the docs page. The error:  

> Resolver error at responses.200.content.application/json.schema.$ref
> Could not resolve reference: Evaluation failed on token: "components"

And here is a piece of code to reproduce the error:
```
from fastapi import FastAPI
from pydantic import PlainValidator, PlainSerializer, BaseModel, errors
from typing_extensions import Annotated


def hex_bytes_validator(o: Any) -> bytes:
    if isinstance(o, bytes):
        return o
    elif isinstance(o, bytearray):
        return bytes(o)
    elif isinstance(o, str):
        return bytes.fromhex(o)
    raise errors.BytesError()


HexBytes = Annotated[bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda b: b.hex())]


class Item(BaseModel):
    name: str
    data: HexBytes


app = FastAPI()


@app.get('/', response_model=Item)
def get():
    return Item(name='hello', data=bytes([0, 0, 0, 0, 1, 1, 1, 1]))
```

**Comment by dmontagu** [comment]
@TQ86 does this fix your issue?

```python
from typing import Any
from fastapi import FastAPI
from pydantic import PlainValidator, PlainSerializer, BaseModel, errors, WithJsonSchema
from typing_extensions import Annotated


def hex_bytes_validator(o: Any) -> bytes:
    if isinstance(o, bytes):
        return o
    elif isinstance(o, bytearray):
        return bytes(o)
    elif isinstance(o, str):
        return bytes.fromhex(o)
    raise errors.BytesError()


HexBytes = Annotated[bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda b: b.hex()), WithJsonSchema({'type': 'string'})]


class Item(BaseModel):
    name: str
    data: HexBytes

app = FastAPI()


@app.get('/', response_model=Item)
def get():
    return Item(name='hello', data=bytes([0, 0, 0, 0, 1, 1, 1, 1]))
```

**Comment by TQ86** [comment]
Yeah, it does! Thanks!

**Comment by frrijn** [comment]
I have a slightly different scenario in which I run into troubles. 

I have a FastAPI endpoint that has a hexadecimal byte string as input, which is transformed to bytes for internal usage and will be serialised back to hexadecimal when returned.

I changed the code of @dmontagu to: 

```
from fastapi import FastAPI, Depends
from pydantic import PlainValidator, PlainSerializer, BaseModel, WithJsonSchema
from typing_extensions import Annotated
from typing import Any

def hex_bytes_validator(v: Any) -> bytes:
    if isinstance(v, str):
        result = bytes.fromhex(v)
    elif isinstance(v, bytes):
        result = v
    else:
        raise TypeError()

    return result

HexBytes = Annotated[bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda b: b.hex()), WithJsonSchema({'type': 'string'})]

class Item(BaseModel):
    hash: HexBytes

app = FastAPI()

@app.get('/test/{hash}', response_model=Item)
def get(hash: Item = Depends()):
    print(hash)
    # perform some internal magic with the bytes version
    # Maybe create a new hash from bytes
    output = Item.model_validate({"hash": b'\xca\x97\x81\x12\xca\x1b\xbd\xca\xfa\xc21\xb3\x9a#\xdcM\xa7\x86\xef\xf8\x14|Nr\xb9\x80w\x85\xaf\xeeH\xbb'})
    return output  # output it as hexadecimal using the serializer
```
## Problem
The problem is that the line `HexBytes = Annotated[bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda b: b.hex()), WithJsonSchema({'type': 'string'})]` calls the plain validator but any input (`v`) is by definition of type `bytes`, even when it is a string. 

## Solution 1
By changing the line to `HexBytes = Annotated[str | bytes, PlainValidator(hex_bytes_validator), PlainSerializer(lambda b: b.hex()), WithJsonSchema({'type': 'string'})]`, the method on itself works as expected. It sees when it is a string or bytes. The downside is that this implies that the data type of `hash` is either string or bytes, even when it is always bytes. Type checking with Mypy is less happy about that.

## Solution 2
Another solution is to create a new datatype class and move the validation to that class. Works as expected, but it is not as elegant. I also tried to move everything to `HashValue` class, but run into trouble for the serialisation aspect. 

```
from fastapi import FastAPI, Depends
from pydantic import PlainValidator, PlainSerializer, BaseModel, WithJsonSchema
from typing_extensions import Annotated
from typing import Any


class HashValue(bytes):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v, x):
        if isinstance(v, str):
            result = bytes.fromhex(v)
        elif isinstance(v, bytes):
            result = v
        else:
            raise TypeError()

        return result


HexBytes = Annotated[
    HashValue,
    PlainSerializer(lambda b: b.hex()),
    WithJsonSchema({'type': 'string'}),
]


class Item(BaseModel):
    hash: HexBytes


app = FastAPI()


@app.get('/test/{hash}', response_model=Item)
def get(hash: Item = Depends()):
    print(hash)
    # perform some internal magic with the bytes version
    # Maybe create a new hash from bytes
    output = Item.model_validate({"hash": b'\xca\x97\x81\x12\xca\x1b\xbd\xca\xfa\xc21\xb3\x9a#\xdcM\xa7\x86\xef\xf8\x14|Nr\xb9\x80w\x85\xaf\xeeH\xbb'})
    return output  # output it as hexadecimal using the serializer
```

## Questions
1. Any other suggestions on how to solve this in an elegant way?
2. I expected that the first code block should have worked. Is it just a bug or expected behaviour? (of which I miss the logic)
