### ISSUE TITLE
Making a field optional in a derived dataclass

### ISSUE THREAD

**Issue by dimaqq** [pydantic/pydantic#3818]
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/3813

<div type='discussions-op-text'>

<sup>Originally posted by **dimaqq** February 14, 2022</sup>
Here's what I have so far (trimmed down to MRE):

```py
from pydantic.dataclasses import dataclass


@dataclass
class Thing:
    id: int
    dog: bool


@dataclass
class NewThing(Thing):
    id: str | None = None
```

Which fails at import time with:

```command
> python3.10 x.py
Traceback (most recent call last):
  File "/.../x.py", line 11, in <module>
    class NewThing(Thing):
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
    'default',
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
    # When cls._FIELDS is filled in with a list of Field objects, the name
  File "pydantic/dataclasses.py", line 159, in pydantic.dataclasses._process_class
    #    |
  File "/usr/lib/python3.10/dataclasses.py", line 1185, in dataclass
    return wrap(cls)
  File "/usr/lib/python3.10/dataclasses.py", line 1176, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/usr/lib/python3.10/dataclasses.py", line 1025, in _process_class
    _init_fn(all_init_fields,
  File "/usr/lib/python3.10/dataclasses.py", line 546, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'dog' follows default argument
```</div>

**Comment by Kludex** [comment]
This is already working on V2. 🙏

We have no plans to fix it on V1.
