### ISSUE TITLE
Discriminated Unions don't work in subclasses of generic models when placed inside a container

### ISSUE THREAD

**Issue by provinzkraut** [pydantic/pydantic#3917]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /***/lib/python3.7/site-packages/pydantic
               python version: 3.7.11 (default, Sep  1 2021, 16:21:01)  [GCC 9.3.0]
                     platform: Linux-5.13.0-35-generic-x86_64-with-debian-11.0
     optional deps. installed: ['dotenv', 'typing-extensions']

```

When subclassing a generic model, trying to use the generic type in a container results in an error when using discriminated union as the type. It works correctly when either the union is *not* placed in a container within the generic model, or if the generic model isn't a subclass of another generic model.

I think this is probably related to #3782, but I'm not sure if it's exactly the same bug since the behavior is a bit different.

**This produces the error**

```py
from typing import TypeVar, Generic, List, Union
from pydantic.generics import GenericModel
from pydantic import BaseModel, Field

from typing_extensions import Annotated, Literal

T = TypeVar("T")


class Foo(BaseModel):
    name: Literal["foo"]


class Bar(BaseModel):
    name: Literal["bar"]


class GenericBase(GenericModel, Generic[T]):
    data: List[T]


class GenericChild(GenericBase[T], Generic[T]):
    another_field: str


ConcreteModel = GenericChild[Annotated[Union[Foo, Bar], Field(discriminator="name")]]
```

The following error occurs:

```
Traceback (most recent call last):
  File "file.py", line 63, in <module>
    ConcreteModel = GenericChild[Annotated[Union[Foo, Bar], Field(discriminator="name")]]
  File "/***/lib/python3.7/site-packages/pydantic/generics.py", line 136, in __class_getitem__
    _prepare_model_fields(created_model, fields, instance_type_hints, typevars_map)
  File "/***/lib/python3.7/site-packages/pydantic/generics.py", line 358, in _prepare_model_fields
    field.prepare()
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 728, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 776, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 451, in pydantic.fields.ModelField._get_field_info
ValueError: `Field` default cannot be set in `Annotated` for '_data'
```

<details>
<summary><strong>This works</strong></summary>

```py
from typing import TypeVar, Generic, List, Union
from pydantic.generics import GenericModel
from pydantic import BaseModel, Field

from typing_extensions import Annotated, Literal

T = TypeVar("T")


class Foo(BaseModel):
    name: Literal["foo"]


class Bar(BaseModel):
    name: Literal["bar"]


class GenericBase(GenericModel, Generic[T]):
    data: T


class GenericChild(GenericBase[T], Generic[T]):
    another_field: str


ConcreteModel = GenericChild[Annotated[Union[Foo, Bar], Field(discriminator="name")]]
```
</details>

<details>
<summary><strong>This works as well</strong></summary>

```py
from typing import TypeVar, Generic, List, Union
from pydantic.generics import GenericModel
from pydantic import BaseModel, Field

from typing_extensions import Annotated, Literal

T = TypeVar("T")


class Foo(BaseModel):
    name: Literal["foo"]


class Bar(BaseModel):
    name: Literal["bar"]


class GenericBase(GenericModel, Generic[T]):
    data: List[T]
    another_field: str


ConcreteModel = GenericBase[Annotated[Union[Foo, Bar], Field(discriminator="name")]]
```
</details>

**Comment by Kludex** [comment]
This is now solved on V2.

```python
from typing import TypeVar, Generic, List, Union
from pydantic import BaseModel, Field

from typing_extensions import Annotated, Literal

T = TypeVar("T")


class Foo(BaseModel):
    name: Literal["foo"]


class Bar(BaseModel):
    name: Literal["bar"]


class GenericBase(BaseModel, Generic[T]):
    data: List[T]


class GenericChild(GenericBase[T], Generic[T]):
    another_field: str


ConcreteModel = GenericChild[Annotated[Union[Foo, Bar], Field(discriminator="name")]]
```
On V2, the `GenericModel` no longer exists. You can use a plain `BaseModel`, as exemplified above.
