### ISSUE TITLE
Optional[conlist(..., unique_items=True)] raises exception if value is None

### ISSUE THREAD

**Issue by hh-h** [pydantic/pydantic#3957]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/.../code/venvs/.../lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.0.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']

```

```py
from typing import Optional

from pydantic import BaseModel, conlist


class Model(BaseModel):
    fuel_types: Optional[conlist(str, min_items=1, unique_items=True)]


Model(fuel_types=None)

```
```
Traceback (most recent call last):
  File "/Users/.../code/python/.../ttt.py", line 10, in <module>
    Model(fuel_types=None)
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Model
fuel_types
  'NoneType' object is not iterable (type=type_error)
```
This snippet above shouldn't lead to exception, but it does. Probably quick fix is replacing this code
https://github.com/samuelcolvin/pydantic/blob/91ecfd651e2f6f0820b5f12f79b9c33163d309d8/pydantic/types.py#L572-L578
with this one
```python
    @classmethod
    def unique_items_validator(cls, v: 'Optional[List[T]]') -> 'Optional[List[T]]':
        if v is None:
            return None

        for i, value in enumerate(v, start=1):
            if value in v[i:]:
                raise errors.ListUniqueItemsError()

        return v
```

**Comment by Kludex** [comment]
I'm not sure when, but this is fixed in V1.

In V2, the code snippet above is translated to:

```py
from typing import Optional

from pydantic import BaseModel, conset


class Model(BaseModel):
    fuel_types: Optional[conset(str, min_length=1)]


print(Model(fuel_types=None))
```
