### ISSUE TITLE
Deep nesting objects with custom `__getattr__` function gives RecursionError in pydantic 1.9.1

### ISSUE THREAD

**Issue by sevaho** [pydantic/pydantic#4114]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/sevaho/.cache/pypoetry/virtualenvs/trinity-M8VqpuQK-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Jan  9 2022, 13:11:20)  [GCC 11.1.0]
                     platform: Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
...
```

## Description

The following examples produce `RecursionError` when using pydantic 1.9.1, with 1.9.0 all works fine.

## Examples

```python
from pydantic import BaseModel


class State(object):
    def __getattr__(self, key):
        return self._state[key]


class FastAPI(object):
    def __init__(self):
        self.state = State()


class App(BaseModel):
    class Config:
        arbitrary_types_allowed = True

    web: FastAPI


class Test(BaseModel):
    app: App


# Works fine
App(web=FastAPI())

# Nesting another level gives errors
Test(app=App(web=FastAPI()))
```

Same use case with deep nesting fastapi:

```python
from pydantic import BaseModel
from fastapi import FastAPI


class App(BaseModel):
    class Config:
        arbitrary_types_allowed = True

    web: FastAPI


class Test(BaseModel):
    app: App


# Works fine
App(web=FastAPI())

# Nesting another level gives errors
Test(app=App(web=FastAPI()))
```

## Error output

```
web=<__main__.FastAPI object at 0x7f13cc80d5e0>
Traceback (most recent call last):
  File "/home/sevaho/gitlab/auth-trinity/test.py", line 27, in <module>
    Test(app=App(web=FastAPI()))
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1038, in pydantic.main.validate_model
  File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 679, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 605, in pydantic.main.BaseModel._copy_and_set_values
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 151, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
  File "/home/sevaho/gitlab/auth-trinity/test.py", line 6, in __getattr__
    return self._state[key]
  File "/home/sevaho/gitlab/auth-trinity/test.py", line 6, in __getattr__
    return self._state[key]
  File "/home/sevaho/gitlab/auth-trinity/test.py", line 6, in __getattr__
    return self._state[key]
  [Previous line repeated 976 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by lig** [comment]
@sevaho thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by parmenashp** [comment]
@lig I can confirm this is still happening in Pydantic 2.5.1

**Comment by samuelcolvin** [comment]
I very much doubt your getting the same error error as V1, @parmenashp beat to create a new issue with a MRE.

Closing this as we have no plans to work on fixing this in v1.
