### ISSUE TITLE
`pydantic.dataclasses` with `typing.TYPE_CHECKING` has a different behaviour than `dataclasses.dataclass`

### ISSUE THREAD

**Issue by Wicker25** [pydantic/pydantic#4204]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I would expect `pydantic.dataclasses` to work as same as the `dataclasses.dataclass` when we use postponed annotations. Am I missing something? Is there a way to get the same behavior with `pydantic`? Adding the `update_forward_refs()` calls to the main don't fix the issue.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/.../project/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Jan  7 2022, 10:36:15)  [GCC 11.1.0]
                     platform: Linux-5.16.15-arch1-1-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

In `module_a.py`:
```py
from __future__ import annotations

from typing import TYPE_CHECKING
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    from module_b import NodeB


@dataclass
class NodeA:
    node: NodeB
```

In `module_b.py`:
```py
from __future__ import annotations

from typing import TYPE_CHECKING
from pydantic.dataclasses import dataclass

if TYPE_CHECKING:
    from module_a import NodeA


@dataclass
class NodeB:
    node: NodeA

```

File `main.py`:
```py
from module_a import NodeA
from module_b import NodeB

if __name__ == '__main__':
    NodeA(node=None)
    NodeB(node=None)
```

Output:
```
Traceback (most recent call last):
  File "/home/master/Development/bitrodens-platform/bitrodens/test.py", line 5, in <module>
    NodeA(node=None)
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 98, in pydantic.dataclasses._generate_pydantic_post_init._pydantic_post_init
    # +-------+-------+-------+
  File "pydantic/main.py", line 1038, in pydantic.main.validate_model
  File "pydantic/fields.py", line 833, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "node" not yet prepared so type is still a ForwardRef, you might need to call NodeA.update_forward_refs().
```

Thank so much for the help! This is one of the most useful library have been using with Python :)

**Comment by m-revetria** [comment]
Hi there! are there any news around this issue?

**Comment by ilrico** [comment]
Same here (with 1.10.2)
