### ISSUE TITLE
Impossible to use postgres connection with ident authentication

### ISSUE THREAD

**Issue by NL66278** [pydantic/pydantic#4421]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I try to create a postgres connection with ident authentication. That is my postgres is setup to accept this, and my postgres user and linux user have the same name.

I should be able to connect with an url like this: `postgresql:///rwdb` (rwdb is the name of the database).

I get this stacktrace:
```
Traceback (most recent call last):
  File "/home/rportier/git/owl-realworld-app/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./app/db/migrations/env.py", line 12, in <module>
    SETTINGS = get_app_settings()
  File "/home/rportier/git/fastapi-realworld-example-app/app/core/config.py", line 21, in get_app_settings
    return config()
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DevAppSettings
database_url
  userinfo required in URL but missing (type=value_error.url.userinfo)
```
The pydantic version used is: 1.9.2

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /home/rportier/git/owl-realworld-app/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
                     platform: Linux-5.16.0-5mx-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [x] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
user is almost always required when connecting to postgres, so we require it on `PostgresDsn`, see https://pydantic-docs.helpmanual.io/usage/types/#urls.

If you don't want this check, use `AnyUrl`, or another URL type.

I'd be open to a discussion about making `user` optional on `PostgresDsn`, that's more of a change request than a bug, it would need input from others.

Let me know if you think this should be reopened.
