### ISSUE TITLE
utils.smart_deepcopy: WeakMethod cannot be pickled

### ISSUE THREAD

**Issue by miili** [pydantic/pydantic#4951]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

`WeakMethod` cannot be pickled. however `weakref.ref` is in `pydantic.utils.IMMUTABLE_NON_COLLECTIONS_TYPES`.

### Example Code

```Python
import inspect
from copy import deepcopy
from typing import Callable, Optional, Union
from weakref import ReferenceType, WeakMethod, ref

from pydantic import BaseModel, PrivateAttr


def callback(self):
    ...


class Test:
    def callback(self):
        ...


class Model(BaseModel):
    _weak_ref: Optional[Union[ReferenceType, WeakMethod]] = PrivateAttr(None)

    def set_callback(self, func: Callable) -> None:
        func_ref = ref(func)
        if inspect.ismethod(func):
            func_ref = WeakMethod(func)

        self._weak_ref = func_ref


mod = Model()
print(mod.json(indent=2))
mod.set_callback(callback)
deepcopy(mod)

test = Test()
print(mod.json(indent=2))
mod.set_callback(test.callback)
deepcopy(mod)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /home/marius/Development/quakesaver/sensor/ringnes/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.0-18-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I think it is not related to pydantic. take a look at this example:
```py
>>> from weakref import WeakMethod, ref
>>> from copy import deepcopy
>>> class C:
...     def method(self):
...         print("method called!")
... 
>>> c = C()
>>> r = WeakMethod(c.method)
>>> deepcopy(r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/3.11.2/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'WeakMethod' object
```
