### ISSUE TITLE
Json Parse for Environment Variables in sub models does not work

### ISSUE THREAD

**Issue by chaimt** [pydantic/pydantic#4965]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

There is an issue with environment variables using json values for sub modules.
class SubModel(BaseModel):
    v1: str = None
    l1 : list[str] = None

class Settings(BaseSettings):
    sub_model: SubModel = None

    class Config:
        env_nested_delimiter = '__'

os.environ['sub_model'] = '{"v1": "aa", "l1": ["a","b","c"]}'
works

os.environ['sub_model__l1'] = '[1,2,3]'
does not work

After debugging the code i have found the issue:
The method explode_env_vars, extracts the value but does not call parse_env_var for it

### Example Code

```Python
from pydantic import (
    BaseModel,
    BaseSettings,
    Field,
)

import os


class SubModel(BaseModel):
    v1: str = None
    l1 : list[str] = None


class Settings(BaseSettings):
    sub_model: SubModel = None

    class Config:
        env_nested_delimiter = '__'

os.environ['sub_model__l1'] = '[1,2,3]'


global_config = Settings()
print(global_config.dict())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
pydantic compiled: False
python version: 3.9.7 (default, Dec 22 2022, 21:29:13)  [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.1-x86_64-i386-64bit
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Romsik788** [comment]
I also ran into this problem. In my case:
```
import json
import os

from pydantic import BaseSettings, Field


class SubTest(BaseSettings):
    c: dict = Field(default={"a": 1, "b": 2},
                    env_parse=lambda x: json.loads(x))


class Test(BaseSettings):
    a: SubTest = None
    b: dict = Field(default={"a": 1, "b": 2},
                    env_parse=lambda x: json.loads(x))

    class Config:
        env_nested_delimiter = '__'


os.environ["A__C"] = '{"a": 3, "b": 4}'
os.environ["B"] = '{"a": 3, "b": 4}'

print(Test().b)
```
Output:
```
Traceback (most recent call last):
  File "/home/romsik/for_testing/test.py", line 24, in <module>
    print(Test().b)
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Test
a -> c
  value is not a valid dict (type=type_error.dict)
```

**Comment by samuelcolvin** [comment]
Sorry for the slow reply.

Can't read your code, so hard to tell, might be the same as #4982.

**Comment by 91fabbai91** [comment]
I face the exact same issue. Is there a fix to put complex datatypes like in nested classes and fill them with the notation with env_nested_delimiter e.g. `export BASE_CONFIG__NESTED_CONFIG = '["ListElement0", "ListElement1"]'`?
