### ISSUE TITLE
__set_name__ and Type 

### ISSUE THREAD

**Issue by efisoft-elt** [pydantic/pydantic#4981]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am using Pedantic has Factory for other objects I encounter a probably rare problem when having a field as a Type which have a __set_name__ method. 

### Example Code

```Python
from typing import Type
from pydantic.fields import PrivateAttr
from pydantic.main import BaseModel

class MyObject:
    def __init__(self, name, parent,  **kwargs):
        pass 

class Foo(BaseModel):
    arg1: int = 0
    __my_name__ = PrivateAttr
    def __set_name__(self, owner, name):
        self.__my_name__ = name 
    def __get__(self, parent, cls):
        if parent is None: return self 
        # do stuff here with the self.args 
        return MyObject(self.__my_name__, parent, **self.dict()) 

 
class Bar(BaseModel):

    Factory: Type[Foo] = Foo



This raise :

```
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "pydantic/main.py", line 295, in pydantic.main.ModelMetaclass.__new__
TypeError: __set_name__() missing 1 required positional argument: 'name'
```

---
My 2 cents: 

Looking at pydantic.main this is probably due to these lines :

```python 
        # preserve `__set_name__` protocol defined in https://peps.python.org/pep-0487
        # for attributes not in `new_namespace` (e.g. private attributes)
        for name, obj in namespace.items():
            if name not in new_namespace:
                set_name = getattr(obj, '__set_name__', None)
                if callable(set_name):
                    set_name(cls, name)

```
I guess a test of rather this is a class or not should be added: 

```python 
if callable(set_name) and not isinstance(obj, type):
      set_name(cls, name)
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /Users/guieus/anaconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.1 (default, Dec 14 2018, 13:28:58)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-21.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Is `__set_name__` defined in a pep or the standard library somewhere?

**Comment by efisoft-elt** [comment]
> Is `__set_name__` defined in a pep or the standard library somewhere?

https://peps.python.org/pep-0487/

**Comment by samuelcolvin** [comment]
Should be fairly easy to fix the signature. PR welcome.

**Comment by efisoft-elt** [comment]
> Should be fairly easy to fix the signature. PR welcome.

Not sure I understood.  The signature is correct, I mean this work : 

```python
class Bar(BaseModel):
     factory: Foo = Foo()
```

But not this : 

```python
class Bar(BaseModel):
     factory: Type = Foo
```

I may have miss-interpreted what you said, just to be on the clear side.

**Comment by samuelcolvin** [comment]
I'm afk right now, I'll look properly tomorrow.

My initial thought we that we have the wrong signature when we call `set_name`, or at least a brittle signature.

**Comment by dmontagu** [comment]
I read through PEP487, and while I found it a bit mind bending, I think I understand.

I _believe_ the issue is happening because although `Foo` defines `__set_name__`, it should only be called if the attribute is an _instance_ of foo (i.e., if the `__set_name__` is a bound method). I was able to confirm this by fiddling with the PEP487 example:

```python
import weakref

class WeakAttribute:
    def __get__(self, instance, owner):
        return instance.__dict__[self.name]()

    def __set__(self, instance, value):
        instance.__dict__[self.name] = weakref.ref(value)

    # this is the new initializer:
    def __set_name__(self, owner, name):
        print("calling __set_name__")
        self.name = name

class TreeNode:
    parent = WeakAttribute()

    def __init__(self, parent):
        self.parent = parent

print("---")

class TreeNode:
    parent = WeakAttribute

    def __init__(self, parent):
        self.parent = parent

# calling __set_name__
# ---
```
(Note, it doesn't call `__set_name__` in the second case.)

@efisoft-elt's proposal was `if callable(set_name) and not isinstance(obj, type):`, which makes sense; my own reaction was that it might be more appropriate to use `if inspect.ismethod(set_name)`.

However, I stumbled upon the way that `dataclasses.Field` implements `__set_name__`, and figure it might make sense to copy their approach. This is from `dataclasses.Field`:
```python
    def __set_name__(self, owner, name):
        func = getattr(type(self.default), '__set_name__', None)
        if func:
            # There is a __set_name__ method on the descriptor, call
            # it.
            func(self.default, owner, name)
```
I think the analogous change in `pydantic.main.ModelMetaclass.__new__` would be:
```python
                set_name = getattr(type(obj), '__set_name__', None)
                if set_name:
                    set_name(obj, cls, name)
```
And I confirmed this does result in everything behaving correctly in @efisoft-elt's example (i.e., `__set_name__` gets called if you do `Factory: Any = Foo()`, but not if you do `Factory: Any = Foo`).

(So I would propose that as the solution.)

**Comment by samuelcolvin** [comment]
Amazing research, let's definitely fix in V2, also pr welcome to fix in v1.10 if desired.

**Comment by efisoft-elt** [comment]
Nice. Looks good. 


Slightly related to this topic,  mostly for the fun of it, I have implemented a way to access directly fields definition from the model class. This allow to mutate the model easily. I am sure it can have som uncontrolled side effects : 

```python 
from pydantic import BaseModel as _BaseModel 

class FieldAttribute:
    _attr = None
    def __init__(self, attr=None):
        self._attr = attr 
    def __set_name__(self, owner, name):
        if self._attr is None:
            self._attr = name 

    def __get__(self, owner, cls):
        if owner is None:
            return cls.__fields__[self._attr] 
        return cls.__getattr__(self._attr) 

class BaseModel(_BaseModel):
    @classmethod 
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__( **kwargs )
        for attr in cls.__fields__:
            setattr( cls, attr, FieldAttribute(attr) )

class MyModel(BaseModel):
    x: float = 0.0  

MyModel.x.default = 10.0 
assert MyModel.x.get_default() == 10.0 
MyModel.x.field_info.description = "I am x" 
assert MyModel().x == 10.0
 
m = MyModel()
m.x = 20.0 
assert m.x == 20.0
```

**Comment by samuelcolvin** [comment]
Have you looked at V2 where we've completely changed how validation works, there's a much clearer distinction and formal definition.

**Comment by Kludex** [comment]
This is fixed in V2 already.
