### ISSUE TITLE
Support keyword arguments on BaseModel subclasses for config (v2)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5017]
Right now:
```python
from pydantic import BaseModel


class Model(BaseModel, undefined_types_warning=False):
    field: int
```
results in:
```
Traceback (most recent call last):
  File "/Users/davidmontague/repos/pydantic/pydantic/main.py", line 103, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: Model.__init_subclass__() takes no keyword arguments
```

The goal is for it to instead behave as:
```python
from pydantic import BaseModel


class Model(BaseModel):
    field: int
    
    class Config:
        undefined_types_warning = False
```
(similar for other Config fields; also, I know we want to move away from using class-based Config)

**Comment by adriangb** [comment]
This is fixed:

```python
from pydantic import BaseModel


class Model(BaseModel, strict=True):
    field: int

Model(field='1')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
field
  Input should be a valid integer [type=int_type, input_value='1', input_type=str]
"""
```
