### ISSUE TITLE
Incorrect TypeError when setting the default value of inherited attribute that has been initialized with Field

### ISSUE THREAD

**Issue by Bootstrap360** [pydantic/pydantic#5370]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Pydantic raises an incorrect TypeError when setting the default value of an inherited attribute which was initialized with `Field` to a different value but of the same type. This value could even be the same.

The source code in the Example Code section shows the behaviour difference between initializing values with and without `Field` by demonstrating that `ChildModelNoField` does not raise this exception but `ChildModelWithField` does. 

#### Expected Behaviour

1. I would expect pydantic to update the value of the inherited attribute and keep the schema the same.
2. I would expect pydanic to raise a more verbose error specifying the original type if the type was indeed changed.

The source code in the `Example Code` section causes the following exception.

```bash
$ python /tmp/tmp.py
Traceback (most recent call last):
  File "/tmp/tmp.py", line 17, in <module>
    class ChildModel(MyBaseModel):
  File "pydantic/main.py", line 232, in pydantic.main.ModelMetaclass.__new__
TypeError: The type of ChildModelWithField.my_int differs from the new default value; if you wish to change the type of this field, please use a type annotation
```

### Example Code

```Python
# /tmp/tmp.py
from pydantic import BaseModel, Field


class MyBaseModelNoField(BaseModel):
    my_int: int = 10


class ChildModelNoField(MyBaseModelNoField):
    my_int = 2


class MyBaseModelWithField(BaseModel):
    my_int: int = Field(10, gt=0, lt=100)


class ChildModelWithField(MyBaseModelWithField):
    my_int = 10
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /tmp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
Given we are focused on supporting v2, I suspect this will not be addressed in v1.

In v2, we still require the annotation, though we have updated the message a bit:
```
pydantic.errors.PydanticUserError: Field 'my_int' defined on a base class was overridden by a non-annotated attribute. All field definitions, including overrides, require a type annotation.
```

I believe that one of the reasons we have kept this error is that we don't want pydantic to take responsibility for doing the right thing to error/validate non-annotated attributes, as it would require us to attempt to infer the type.

Is there a reason that redeclaring the type annotation is not a good solution for you?

**Comment by dmontagu** [comment]
I realize I missed part of your issue at first — you are also interested in wanting to update just the default value in a subclass, while retaining all the other values passed to the parent `Field`.

The main downside I see with this is that I'm not sure we have a good way to remove things from the schema, so if we made this change today in the "naive" way, you wouldn't be able to remove things from the `Field` in subclasses (whereas you can today, as they aren't retained). That said, I know there are comments in the code indicating we would like to change this.

It seems to me that if we are going to change this, the right approach would be to change the default arguments to the `Field` function to something like `Unset` instead of `None`, and to inherit the existing `Field` data.

I'll defer to others about whether that is the right solution, and whether it's worth incorporating (probably makes sense to get some consensus on this before requesting a PR).

**Comment by Bootstrap360** [comment]
@dmontagu, you are correct, I do just want to update just the default value in a subclass, while retaining all the other values passed to the parent Field.

My strongest argument would be the difference in behaviour below.

```
class MyBaseModelWithField(BaseModel):
    my_int: int = Field(default=10, gt=0, lt=100)

    class Config:
        validate_all = True
        validate_assignment = True


instance = MyBaseModelWithField()
instance.my_int = 400 #### raises an error

class ChildModelWithField(MyBaseModelWithField):
    my_int: int = 400 #### should also raise an error
```

I would argue that if the user wants to change the field attributes, the user should change the entire field


```
class MyBaseModelWithField(BaseModel):
    my_int: int = Field(default=10, gt=0, lt=100)

    class Config:
        validate_all = True
        validate_assignment = True


class ChildModelWithField(MyBaseModelWithField):
    my_int: int = Field(400, lt=500, gt=0) ### Change the Field here
```

**Comment by dmontagu** [comment]
Just to make sure I understand the previous comment correctly, you want:
```python
class MyBaseModelWithField(BaseModel):
    my_int: int = Field(default=10, gt=0, lt=100)

    class Config:
        validate_all = True
        validate_assignment = True

class ChildModelWithField(MyBaseModelWithField):
    my_int: int = 400
```
to raise an error, but
```python
class MyBaseModelWithField(BaseModel):
    my_int: int = Field(default=10, gt=0, lt=100)

    class Config:
        validate_all = True
        validate_assignment = True

class ChildModelWithField(MyBaseModelWithField):
    my_int: int = Field(400, lt=500, gt=0) ### Change the Field here
```
to not raise an error?

Do you want the first case to error because it is redefining the field as just `int`, or because the value is outside the allowed range according to the initial Field definition?

In the first case, I would interpret it as "you can't override a field definition unless you set it to `= Field(<something>)`, which I think is likely to get rejected as I don't think `Field` is meant to serve that role.

If the second, I think it would fairly complicated to add support for validating default values at class creation time against the spec of the field from a parent class. And even if we could, I'm not sure that the consensus would be that the parent field spec should be inherited; I'm happy to be corrected, but I'd want to see broader interest before embarking on the necessary changes.

**Comment by Bootstrap360** [comment]
You understand me 100%.

The thought has occurred to me that I might be using the wrong tool. I was hoping to use pedantic for config management. It seems like a good idea because pedantic does range and type checking as well as includes a description. It also does JSON and back which is useful for saving to disk.

This is why I am asking for this behaviour. Perhaps this request contradicts pydantic's use case which is parsing arbitrary JSON.

**Comment by dmontagu** [comment]
I think it depends on what you mean by config management.

If you mean you want to load a config file and use it, I think pydantic is a great fit for that (I and many others have used it for this purpose for years).

But it seems you are more concerned with trying to enforce behavior in subclasses of one of your classes (I wouldn't generally use the term "config management" for that, but I'm trying to infer what you mean, apologies if I have misunderstood). That can be done, but it needs to be done in a different way — namely, you'll want to implement logic in `__init_subclass__` (which may need to use `__pydantic_init_subclass__` when migrating to v2, as that is not called until after the fields are created, unlike `__init_subclass__`).

In general, while we have functionality that can be used to implement this workflow, pydantic is really designed from the perspective that, while input data for parsing is untrusted, code used to _create_ types _is_ trusted, and we err on the side of letting developers do what they want when creating their own types, rather than applying validation when creating subclasses. (As opposed to parsing inputs, which are _not_ treated as trusted.) But as I said, you can still implement "type validation" through `__init_subclass__` or similar.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
