### ISSUE TITLE
[V2] How to use custom field types

### ISSUE THREAD

**Issue by luolingchun** [pydantic/pydantic#5373]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I have read https://docs.pydantic.dev/blog/pydantic-v2/#changes-to-custom-field-types, but i still don't how to use it.

It seems that `ValidationSchema` cannot be found in `pydantic`.

### Example Code

```Python
from pydantic import ValidationSchema

class Foobar:
    def __init__(self, value: str):
        self.value = value

    __pydantic_validation_schema__: ValidationSchema = {
        'type': 'function',
        'mode': 'after',
        'function': 'validate',
        'schema': {'type': 'str'}
    }

    @classmethod
    def validate(cls, value):
        if 'foobar' in value:
            return Foobar(value)
        else:
            raise ValueError('expected foobar')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
                 install path: D:\workspace\test\venv\Lib\site-packages\pydantic
               python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by tpdorsey** [comment]
@luolingchun stay tuned, we are actively working on updating the documentation.

**Comment by dmontagu** [comment]
@luolingchun yeah that documentation is totally wrong (and as @tpdorsey mentioned should be updated soon).

In the meantime, here's how this is supposed to be done:

```python
from typing import Any

from pydantic_core import core_schema


class Foobar:
    def __init__(self, value: str):
        self.value = value

    @classmethod
    def __get_pydantic_core_schema__(cls, **_kwargs: Any) -> core_schema.PlainValidatorFunctionSchema:
        return core_schema.general_plain_validator_function(
            cls.validate, serialization=core_schema.to_string_ser_schema()
        )

    @classmethod
    def validate(cls, value: Any, info: core_schema.ValidationInfo):
        if 'foobar' in value:
            return Foobar(value)
        else:
            raise ValueError('expected foobar')


from pydantic import BaseModel


class MyModel(BaseModel):
    x: Foobar


m = MyModel(x='foobar')
assert isinstance(m.x, Foobar)
print(m.x.value)
#> foobar
MyModel(x='barfoo')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
x
  Value error, expected foobar [type=value_error, input_value='barfoo', input_type=str]
"""
```

**Comment by luolingchun** [comment]
@dmontagu Thanks, I should be patient and wait for the document to be improved.

I got an error when using `MyModel.model_json_schema()`, 

```python
Traceback (most recent call last):
  File "D:\workspace\test\test_pydantic\test_pydantic.py", line 34, in <module>
    MyModel.model_json_schema()
  File "D:\workspace\test\venv\lib\site-packages\pydantic\main.py", line 367, in model_json_schema
    return model_json_schema(cls, by_alias=by_alias, ref_template=ref_template, schema_generator=schema_generator)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 1164, in model_json_schema
    json_schema = schema_generator(by_alias=by_alias, ref_template=ref_template).generate(cls.__pydantic_core_schema__)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 150, in generate
    json_schema = self.generate_inner(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 214, in generate_inner
    json_schema = generate_for_schema_type(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 591, in model_schema
    json_schema = self.generate_inner(schema['schema'])
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 214, in generate_inner
    json_schema = generate_for_schema_type(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 546, in typed_dict_schema
    return self._named_required_fields_schema(named_required_fields)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 565, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 209, in generate_inner
    json_schema = self.typed_dict_field_schema(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 580, in typed_dict_field_schema
    json_schema = self.generate_inner(schema['schema'])
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 214, in generate_inner
    json_schema = generate_for_schema_type(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 390, in function_plain_schema
    return self._function_schema(schema)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 379, in _function_schema
    return self.handle_invalid_for_json_schema(
  File "D:\workspace\test\venv\lib\site-packages\pydantic\json_schema.py", line 1088, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'general', 'function': <bound method Foobar.validate of <class '__main__.Foobar'>>})

```

**Comment by dmontagu** [comment]
@luolingchun try defining a function with this name and signature:
 https://github.com/pydantic/pydantic/blob/0cd57b3e0c75d9622012de542e5ddc110fe55743/pydantic/networks.py#L146

I *think* it should cause that error to go away and you can set the json schema as you like by returning the dict you want for your type.

If that doesn’t work for you let me know what you want the schema to be and I’ll make sure I get a working example for you tomorrow.

**Comment by luolingchun** [comment]
@dmontagu Thank you very much, it's worked!

```python
from typing import Any, Dict

from pydantic_core import core_schema
from werkzeug.datastructures import FileStorage as _FileStorage


class FileStorage(_FileStorage):
    """
    An uploaded file included as part of the request data.
    """

    @classmethod
    def __get_pydantic_core_schema__(cls, **_kwargs: Any) -> core_schema.PlainValidatorFunctionSchema:
        return core_schema.general_plain_validator_function(cls.validate)

    @classmethod
    def __pydantic_modify_json_schema__(cls, field_schema: Dict[str, Any]) -> Dict[str, Any]:
        field_schema.update(format="binary", type="string")
        return field_schema

    @classmethod
    def validate(cls, value: _FileStorage, _info: core_schema.ValidationInfo) -> _FileStorage:
        if not isinstance(value, _FileStorage):
            raise TypeError('werkzeug.datastructures.FileStorage required')

        return value
```
