### ISSUE TITLE
min_items error in Pydantic v2

### ISSUE THREAD

**Issue by luolingchun** [pydantic/pydantic#5405]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

it's passed the test in Pydantic v1 but not v2.

```python
Traceback (most recent call last):
  File "D:\workspace\test\test_pydantic\test_pydantic.py", line 9, in <module>
    class MyModel(BaseModel):
  File "D:\workspace\test\venv\lib\site-packages\pydantic\main.py", line 149, in __new__
    _model_construction.complete_model_class(
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 166, in complete_model_class
    schema = gen_schema.generate_schema(cls)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 194, in generate_schema
    schema = self._generate_schema(obj)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 310, in _generate_schema
    from_property = self._generate_schema_from_property(obj, obj)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 273, in _generate_schema_from_property
    return get_schema(source=source, gen_schema=self)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\main.py", line 212, in __get_pydantic_core_schema__
    return gen_schema.model_schema(cls)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 239, in model_schema
    {k: self.generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 239, in <dictcomp>
    {k: self.generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 461, in generate_td_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 499, in _common_field_schema
    schema = apply_annotations(schema, field_info.metadata, self.definitions)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1061, in apply_annotations
    schema = apply_single_annotation(schema, metadata, definitions)
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1130, in apply_single_annotation
    raise e
  File "D:\workspace\test\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1126, in apply_single_annotation
    SchemaValidator(schema)
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
list -> min_items
  Extra inputs are not permitted [type=extra_forbidden, input_value=1, input_type=int]
```

### Example Code

```Python
from typing import List

from pydantic import BaseModel, Field


class MyModel(BaseModel):
    x: List[int] = Field(None, min_items=1)


_json = MyModel.model_json_schema()

print(type(_json))
print(_json)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
install path: D:\workspace\test\venv\Lib\site-packages\pydantic
python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
platform: Windows-10-10.0.22621-SP0
optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
Have you tried using min_length instead of min_items? I’m not sure if it’s the same, either way we could probably make it easier to understand what’s going on.

**Comment by luolingchun** [comment]
@dmontagu It's worked, but `minItems` in result, inconsistency input and output.


```python
{'title': 'MyModel', 'type': 'object', 'properties': {'x': {'type': 'array', 'items': {'type': 'integer'}, 'minItems': 1, 'default': None, 'title': 'X'}}}
```

**Comment by samuelcolvin** [comment]
We use the most sensible name in python, then map to the equivalent property in JSON schema.

JSON schema is not the "output", it's a representation on the input format.

We should make a better error message, otherwise this is fine.

**Comment by samuelcolvin** [comment]
I think that just hasn't been updated yet, we need to mark as deprecated.

**Comment by luolingchun** [comment]
I got it! Thanks.
