### ISSUE TITLE
BytesIO is not evaluated as typing.IO by pydantic

### ISSUE THREAD

**Issue by anetbnd** [pydantic/pydantic#5443]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

According to the [typing documentation](https://docs.python.org/3/library/typing.html#typing.IO)  the type `typing.IO` or `typing.BinaryIO` should be used as type hint for file-like objects, which have been opened in binary mode.

However, a pydantic base model, is not accepting an `io.BinaryIO(...)` object as instance for a type defined with that.

Instead the following error is raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestDTO
file
  instance of IO expected (type=type_error.arbitrary_type; expected_arbitrary_type=IO)
```

How can I define a file-like object as type of a pydantic base model?

### Example Code

```Python
import typing
import pydantic
import io

class TestDTO(pydantic.BaseModel):
    file: typing.IO
    class Config:
        arbitrary_types_allowed = True

TestDTO(file=io.BytesIO(b"42"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.8.2
pydantic compiled: True
install path: ...
python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19042-SP0
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
The `typing.IO` annotation is not currently supported in pydantic. This is sort of hinted at by the fact that you need to use `arbitrary_types_allowed = True`, which makes it so that for unrecognized "arbitrary" types, an object `obj` will pass validation for that type `type_` if and only if `isinstance(obj, type_)`. And `isinstance(io.BytesIO(b"42"), typing.IO)` is `False`.

Note: pydantic doesn't support _every_ type in the standard library. In principle I don't think it should be hard to add support for this, PR possibly welcome, but I'll defer to @samuelcolvin about whether we should support this.

**Comment by lig** [comment]
I can confirm the original behavior is the same in Pydantic v2.3.0.

**Comment by alexmojaki** [comment]
It looks like Python itself has made a bit of a mess here for reasons I can't understand, and that seems reflected in https://github.com/python/cpython/issues?q=is%3Aissue+is%3Aopen+%22typing.IO%22

1. The docs (https://docs.python.org/3/library/typing.html#typing.IO) don't actually mention `io.BytesIO` or `StringIO` at all, although type checkers do accept them
2. `isinstance(open(...), typing.IO)` is also False, even though the docs refer to the return type of `open()`.
3. It's not clear how you *would* check the type of a file object at runtime in a 'friendly' way.

> How can I define a file-like object as type of a pydantic base model?

This works:

```python
import io

import pydantic

with open(__file__, "rb") as f:
    BinaryFileType = type(f)


class TestDTO(pydantic.BaseModel):
    file: BinaryFileType | io.BytesIO

    class Config:
        arbitrary_types_allowed = True


TestDTO(file=open(__file__, "rb"))
TestDTO(file=io.BytesIO(b"hello"))
TestDTO(file=io.StringIO("hello"))  # error
```

**Comment by LeonardHd** [comment]
Thanks @alexmojaki, I extended your sample based on the docs <https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types>:
```python
import io
from typing import Annotated, Any, BinaryIO

import pydantic
from pydantic_core import core_schema
from pydantic import GetPydanticSchema


def io_validator(v: Any):
    if not isinstance(v, io.BytesIO) and not isinstance(v, io.BufferedReader):
        raise ValueError(f"Expected an instance of io.BytesIO or io.BufferedReader, got {v}")
    return v


BytesIOType = Annotated[
    io.BytesIO | BinaryIO, GetPydanticSchema(
            lambda tp, handler: core_schema.no_info_after_validator_function(
                function=lambda x: io_validator(x), schema=core_schema.any_schema()
            )
        )
]


class TestDTO(pydantic.BaseModel):
    file: BytesIOType


if __name__ == "__main__":
    _ = TestDTO(file=open(__file__, "rb"))
    _ = TestDTO(file=io.BytesIO(b"hello"))
    _ = TestDTO(file=io.StringIO("hello"))  # error
```

Output:
```text
pydantic_core._pydantic_core.ValidationError: 1 validation error for TestDTO
file
  Value error, Expected an instance of io.BytesIO or io.BufferedReader, got <_io.StringIO object at 0x7f9714b6be20> [type=value_error, input_value=<_io.StringIO object at 0x7f9714b6be20>, input_type=StringIO]
    For further information visit https://errors.pydantic.dev/2.7/v/value_error
```

**Comment by Seluj78** [comment]
@LeonardHd is there any way you could make a PR for this to add it to base pydantic ?

**Comment by Viicos** [comment]
Given the complexity of the `typing` and `io` types (and the fact that some io types rely on external streams, e.g. from files), I'd rather not add support for it directly in Pydantic (the solution provided in https://github.com/pydantic/pydantic/issues/5443#issuecomment-2590904564 is fine, but some users may want to actually validate the whole content of the stream). For this reason, I'll close as not planned (we may consider in-memory streams such as `io.BytesIO` as a supported type, but still I'm not sure if we should just apply `isinstance()` checks).
