### ISSUE TITLE
Incorrect error message and data when attemting to use an `str` for `Sequence[int]`

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5596]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Passing `str` value into a `Sequence[int]` schema results in an error message `Input should be a valid string` which is incorrect.

The message should read `Input should be a valid Sequence`

Note that `list[int]` schema also raises a ValidationError that correctly reads `Input should be a valid list`

### Example Code

```Python
>>> from pydantic import BaseModel
>>> from typing import Sequence
>>> class Model(BaseModel):
...     int_sequence: Sequence[int]
...     int_list: list[int]
... 
>>> m = Model(int_sequence='123', int_list='123')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lig/workspace/pydantic/pydantic/pydantic/main.py", line 231, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Model
int_sequence
  Input should be a valid string [type=string_type, input_value='123', input_type=str]
int_list
  Input should be a valid list [type=list_type, input_value='123', input_type=str]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
               python version: 3.10.11 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230404 (Red Hat 13.0.1-0)]
                     platform: Linux-6.2.12-300.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by lig** [comment]
Fixed in #5599
