### ISSUE TITLE
ForwardRef cannot be evaluated

### ISSUE THREAD

**Issue by ilaner** [pydantic/pydantic#5630]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I have two models.
One model is `BaseContent` model. This model has a `set` containing a set of `RelationshipData` model. In the `RelationshipData` model, there is an attribute which is `BaseContent`.

This worked in Pydantic v1. However, when I switched to pydantic v2 a3, This no longer works, and I get the following traceback:
```
Traceback (most recent call last):
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 296, in _generate_schema
    obj = _typing_extra.evaluate_fwd_ref(obj, globalns=self.types_namespace)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 465, in evaluate_fwd_ref
    return ref._evaluate(globalns=globalns, localns=localns, recursive_guard=frozenset())
  File "/usr/local/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'RelationshipData' is not defined. Did you mean: 'RelationshipType'?
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 179, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, gen_schema.generate_schema)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/main.py", line 246, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 172, in generate_schema
    schema = self._generate_schema(obj, from_dunder_get_core_schema=True)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 308, in _generate_schema
    from_property = self._generate_schema_from_property(obj, obj)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 265, in _generate_schema_from_property
    return get_schema(source, handler)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/main.py", line 246, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 262, in handler
    return self._generate_schema(source, False)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 315, in _generate_schema
    return self.model_schema(obj)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 221, in model_schema
    {k: self._generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 221, in <dictcomp>
    {k: self._generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 482, in _generate_td_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 524, in _common_field_schema
    schema = apply_annotations(generate_schema, field_info.metadata, self.definitions)(field_info.annotation)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 519, in generate_schema
    schema = self.generate_schema(source)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 172, in generate_schema
    schema = self._generate_schema(obj, from_dunder_get_core_schema=True)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 432, in _generate_schema
    return self._dict_schema(obj)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 783, in _dict_schema
    values_schema=self.generate_schema(arg1),
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 172, in generate_schema
    schema = self._generate_schema(obj, from_dunder_get_core_schema=True)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 422, in _generate_schema
    return self._generic_collection_schema(set, obj, origin)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 730, in _generic_collection_schema
    'items_schema': self.generate_schema(get_first_arg(type_)),
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 172, in generate_schema
    schema = self._generate_schema(obj, from_dunder_get_core_schema=True)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 298, in _generate_schema
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'RelationshipData' is not defined
For further information visit <TODO: Set up the errors URLs>/undefined-annotation
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/xsoar/content/.venv/bin/demisto-sdk", line 5, in <module>
    from demisto_sdk.__main__ import main
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 34, in <module>
    from demisto_sdk.commands.content_graph.interface.neo4j.neo4j_graph import (
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/interface/neo4j/neo4j_graph.py", line 20, in <module>
    from demisto_sdk.commands.content_graph.content_graph_commands import (
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/content_graph_commands.py", line 15, in <module>
    from demisto_sdk.commands.content_graph.content_graph_builder import ContentGraphBuilder
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/content_graph_builder.py", line 5, in <module>
    from demisto_sdk.commands.content_graph.interface.graph import ContentGraphInterface
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/interface/graph.py", line 11, in <module>
    from demisto_sdk.commands.content_graph.objects.base_content import BaseContent
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/objects/__init__.py", line 36, in <module>
    from demisto_sdk.commands.content_graph.objects.classifier import Classifier
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/objects/classifier.py", line 6, in <module>
    from demisto_sdk.commands.content_graph.objects.content_item import ContentItem
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/objects/content_item.py", line 23, in <module>
    from demisto_sdk.commands.content_graph.objects.base_content import BaseContent
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/objects/base_content.py", line 58, in <module>
    class BaseContent(ABC, BaseModel, metaclass=BaseContentMetaclass):
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/demisto_sdk/commands/content_graph/objects/base_content.py", line 49, in __new__
    super_cls: BaseContentMetaclass = super().__new__(cls, name, bases, namespace)
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/main.py", line 166, in __new__
    _model_construction.complete_model_class(
  File "/builds/xsoar/content/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 190, in complete_model_class
    raise UserWarning(config_warning_string)
```

I tried to switch between the classes, making the `BaseContent` the ForwardRef, but got a similar issue.
This is not related to the Metaclass, as it happens even if I remove the metaclass or switch between the forward ref annotation.

### Example Code

```Python
from pydantic import BaseModel

class BaseContent(BaseModel):
    database_id: Optional[int] = Field(
        None, exclude=True, repr=False
    )  # used for the database
    object_id: str = Field(alias="id")
    node_id: str

    relationships_data: Dict[str, Set["RelationshipData"]] = Field(
        defaultdict(set), exclude=True, repr=False
    )

class RelationshipData(BaseModel):
    relationship_type: str

    # These are the database ids of the relationships
    source_id: int
    target_id: int

    # this is the attribute we're interested in when querying
    content_item_to: BaseContent
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
                 install path: .venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Mar 28 2023, 15:50:10) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
When you share example code, please ensure the code can be run as-is (this is missing all imports).

**Comment by suharnikov** [comment]
@dmontagu Am I understanding this right `dict(undefined_types_warning=False)` is required for models with postponed field types?

**Comment by dmontagu** [comment]
@suharnikov currently yes though I think we are planning to eliminate that warning before the official v2 release, and behave more like v1 where you'll just get the error when you first attempt to do validation if there are still undefined types.
