### ISSUE TITLE
Self reference models raising `SchemaError`

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#5645]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The code below raises:

```bash
Traceback (most recent call last):
  File "/Users/marcelotryle/dev/pydantic/main.py", line 28, in <module>
    class Data(BaseModel):
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/main.py", line 172, in __new__
    _model_construction.complete_model_class(
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_model_construction.py", line 180, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/main.py", line 267, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 207, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 353, in _generate_schema
    return self.model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 264, in model_schema
    {k: self._generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 264, in <dictcomp>
    {k: self._generate_td_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 520, in _generate_td_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 562, in _common_field_schema
    schema = apply_annotations(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_schema_generation_shared.py", line 176, in __call__
    return self._handler(__source_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 1279, in new_handler
    schema = apply_single_annotation(schema, annotation, definitions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 1342, in apply_single_annotation
    raise e
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_generate_schema.py", line 1338, in apply_single_annotation
    SchemaValidator(schema)
pydantic_core._pydantic_core.SchemaError: Error building "list" validator:
  SchemaError: Error building "definition-ref" validator:
  SchemaError: Slots Error: ref '__main__.Data:4948736928' not found
```

### Example Code

```Python
from typing import List, Annotated
from pydantic import BaseModel, Field


class Data(BaseModel):
    field: Annotated[List["Data"], Field(min_items=1)]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
                 install path: /Users/marcelotryle/dev/pydantic/pydantic/pydantic
               python version: 3.11.1 (main, Apr 20 2023, 11:08:52) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
This has been fixed.
