### ISSUE TITLE
Error building "union" validator: Duplicate ref

### ISSUE THREAD

**Issue by suharnikov** [pydantic/pydantic#5660]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi, 
I tried to move my project to v2 and stacked on the `Duplicate ref` error. I prepared a minimal reproduction example.

### Example Code

```Python
from pydantic import AnalyzedType, BaseModel, ConfigDict

class Nested(BaseModel):
    pass

class SomeData(BaseModel):
    nested1: Nested

class FirstModel(BaseModel):
    nested2: Nested
    data: SomeData

class SecondModel(BaseModel):
    id: int
    some_data: SomeData

AnalyzedType(FirstModel | SecondModel)


ModelVariantListValidator = AnalyzedType(FirstModel | SecondModel)
# Traceback (most recent call last):
#   File "/workspaces/test_analyzedtype.py", line 27, in <module>
#     ModelVariantListValidator = AnalyzedType(FirstModel | SecondModel)
#                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/workspaces/.venv/lib/python3.11/site-packages/pydantic/analyzed_type.py", line 111, in __init__
#     validator = SchemaValidator(core_schema, core_config)
#                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# pydantic_core._pydantic_core.SchemaError: Error building "union" validator:
#   SchemaError: Error building "model" validator:
#   SchemaError: Error building "typed-dict" validator:
#   SchemaError: Field "some_data":
#   SchemaError: Error building "default" validator:
#   SchemaError: Error building "nullable" validator:
#   SchemaError: Error building "model" validator:
#   SchemaError: Error building "typed-dict" validator:
#   SchemaError: Field "some_user":
#   SchemaError: Error building "default" validator:
#   SchemaError: Error building "nullable" validator:
#   SchemaError: Duplicate ref: `__main__.Nested:94251265397456`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
                 install path: /workspaces/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 23 2023, 17:12:29) [GCC 10.2.1 20210110]
                     platform: Linux-5.4.0-1106-azure-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
Definitely a bug, thanks for reporting

**Comment by suharnikov** [comment]
@dmontagu I dug into the issue and found `_get_or_cache_recursive_ref`. The problem is somewhere in this place, am I right?

https://github.com/pydantic/pydantic/blob/34a1c02277140551e6c90dd7241ceb0c1b638353/pydantic/_internal/_generate_schema.py#L242

https://github.com/pydantic/pydantic/blob/34a1c02277140551e6c90dd7241ceb0c1b638353/pydantic/_internal/_generate_schema.py#L1096-L1102

**Comment by suharnikov** [comment]
Should the fields `nested1` and `nested2` have different reference IDs? I am just trying to understand where the problem is, in `_get_or_cache_recursive_ref` or `SchemaValidator`.

**Comment by dmontagu** [comment]
The problem is likely in `_get_or_cache_recursive_ref`, I will try to look at this more closely is the next day or so. (Trying to get caught up on all the other recent activity.)

**Comment by suharnikov** [comment]
It works properly on the current master, thanks :+1:
