### ISSUE TITLE
`Optional[HTTPUrl]` raises `TypeError` on declaration due to unhashable type `UrlConstraints`

### ISSUE THREAD

**Issue by madkinsz** [pydantic/pydantic#5693]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When using a field that is a union of `None` and `HTTPUrl`, they Python typing module throws a type error due to an unhashable type.

```python
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/example.py", line 5, in <module>
    class Foo(BaseModel):
  File "/Users/mz/dev/prefect/example.py", line 6, in Foo
    bar: Optional[HttpUrl] = None
         ~~~~~~~~^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 344, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 463, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 685, in Optional
    return Union[arg, type(None)]
           ~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 344, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 463, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 671, in Union
    parameters = _remove_dups_flatten(parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 313, in _remove_dups_flatten
    return tuple(_deduplicate(params))
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 289, in _deduplicate
    all_params = set(params)
                 ^^^^^^^^^^^
  File "/Users/mz/.pyenv/versions/3.11.2/lib/python3.11/typing.py", line 2114, in __hash__
    return hash((self.__origin__, self.__metadata__))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'UrlConstraints'
```

### Example Code

```Python
from pydantic import HttpUrl, BaseModel
from typing import Optional


class Foo(BaseModel):
    bar: Optional[HttpUrl] = None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.27.0 release build profile
                 install path: /Users/mz/.pyenv/versions/3.11.2/envs/prefect-311/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 15 2023, 09:11:17) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```
```

**Comment by hramezani** [comment]
Thanks @madkinsz for reporting.

I can confirm the problem. it can be fixed by adding a `def __hash__(self) -> int:` to `UrlConstraints`.

Would you like to prepare a patch?

**Comment by madkinsz** [comment]
@hramezani sure I'll give it a shot!
