### ISSUE TITLE
ForwarRef of dataclasses

### ISSUE THREAD

**Issue by shenek** [pydantic/pydantic#5721]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I'm not able to make forward references to work together with dataclasses.

Based on https://docs.pydantic.dev/dev-v2/usage/errors/#undefined-annotation I created a code that should work, but it doesn't.

### Example Code

```Python
import typing
from pydantic.dataclasses import dataclass


class Config:
    undefined_types_warning = False


@dataclass(config=Config)
class AA:
    a1: typing.ForwardRef("A")
    a2: typing.ForwardRef("A")


@dataclass(config=Config)
class A:
    x: int
    double: typing.Optional[AA] = None


AA.__pydantic_model__.model_rebuild()


aa = AA(a1=A(5), a2=A(6))
```

### Exception
```
Traceback (most recent call last):
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 349, in _generate_schema
    obj = _typing_extra.evaluate_fwd_ref(obj, globalns=self.types_namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 465, in evaluate_fwd_ref
    return ref._evaluate(globalns=globalns, localns=localns, recursive_guard=frozenset())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 857, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'A' is not defined. Did you mean: 'AA'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tree.py", line 9, in <module>
    @dataclass(config=Config)
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/dataclasses.py", line 201, in create_dataclass
    _pydantic_dataclasses.complete_dataclass(cls, config_wrapper)
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 80, in complete_dataclass
    schema = gen_schema.generate_schema(cls, from_dunder_get_core_schema=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 209, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 440, in _generate_schema
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1052, in _dataclass_schema
    args = [self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1052, in <listcomp>
    args = [self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 575, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 597, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1222, in _apply_annotations
    return get_inner_schema(source_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 177, in __call__
    return self._handler(__source_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 592, in generate_schema
    schema = self.generate_schema(source, from_prepare_args=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 209, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 351, in _generate_schema
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'A' is not defined

For further information visit https://errors.pydantic.dev/2.0a4/u/undefined-annotation
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /home/stepan/.virtualenvs/NIBBLER/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
                     platform: Linux-6.1.0-7-amd64-x86_64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
Thanks for reporting. In v2, dataclasses are no longer "backed" by a model like this, but we haven't yet implemented recursive dataclasses. This is one of the top remaining priorities, we'll let you know when this is ready, should be soon.
