### ISSUE TITLE
RootModel does not work with Base64Str

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5818]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I was hoping for RootModel to allow using Base64Str as a model, but it fails with:

```
Traceback (most recent call last):
  File "~/.config/JetBrains/PyCharm2023.1/scratches/scratch_42.py", line 8, in <module>
    assert v.model_dump() == 'dGVzdA==\n'
  File "~/venv/openapi3/lib/python3.10/site-packages/pydantic/main.py", line 561, in model_dump
    return self.__pydantic_serializer__.to_python(
AttributeError: 'Base64Root' object has no attribute 'root'
```

### Example Code

```Python
from typing import Union
from pydantic import BaseModel, RootModel, Base64Bytes, Base64Str

class Base64Root(RootModel[Base64Str]):
    pass

v = Base64Root.model_construct("test")
assert v.model_dump() == 'dGVzdA==\n'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.33.0 release build profile
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by commonism** [comment]
It works:
```python
v = Base64Root.model_construct(root="test")
```

is (the requirement to pass root to) RootModel.model_construct open for discussion?
root is invisible anywhere else.

**Comment by commonism** [comment]
Using RootModel[Base64Str] as attribute has similar problems, but passing root= is not an option as string is required not dict.

```python
from typing import Union
from pydantic import BaseModel, RootModel, Base64Bytes, Base64Str


# works as expected
class Base64Property(BaseModel):
    data: Base64Str


v = Base64Property.model_construct(data="test")
assert v.model_dump() == {"data":'dGVzdA==\n'}

# does not work
class Base64RootProperty(BaseModel):
    data: RootModel[Base64Str]

v = Base64RootProperty.model_construct(data="test")
assert v.model_dump() == {"data":'dGVzdA==\n'}
v = Base64RootProperty.model_construct(data="test")
```

**Comment by dmontagu** [comment]
@commonism thank you as always for quickly testing out the new functionality! It seems to me we may be able to resolve some of these issues by doing a bit more method overriding in `RootModel`, but let me think about it for a bit. (For what it's worth, in general, if you have any proposals for how to resolve the issues I would be interested.)

----

My gut reaction to what you've shown is:
* You should be able to do `model_construct` for root models without a keyword argument 
* For non-idempotent types, I think when you call `model_construct`, you should be passing the post-validation value, not pre-validation value. The point of `model_construct` is to avoid the overhead of actually doing validation, so I think it's the responsible of the developer to make sure that what is provided to the call has the appropriate type. In particular, in this case:
```python
class Base64RootProperty(BaseModel):
    data: RootModel[Base64Str]
```
I currently think the most logically consistent thing for us to do would be to require:
```python
v = Base64RootProperty.model_construct(data=RootModel[Base64Str].model_construct('dGVzdA==\n'))
```
(I don't see any reason to _disallow_ `root='dGVzdA==\n'` in `RootModel.model_construct`, but I agree it would be nice if you didn't _have_ to specify it.)

I'd like to think more about this but curious what your reaction is to all of this?

**Comment by commonism** [comment]
I'd say you are basically right with every aspect, I'm just struggling to adapt the behavior to my requirements.

In my case, I currently do not know if a Base64Str is "embedded" in a model/a property or standalone/requires to be a RootModel. Using refs -OpenAPI Schema- it can even be both.

While it is possible to use the type from the models annotation of the property:
```python
v = Base64RootProperty.model_construct(data=Base64RootProperty.model_fields["data"].annotation.model_construct(root="test"))
```
I was hoping for a RootModel[T] attribute to have the same behavior as an attribute of the same type T wrt. model_construct.
e.g.:

```python
class Base64Property(BaseModel):
    data: Base64Str

class Base64RootProperty(BaseModel):
    data: RootModel[Base64Str]
```

As this would allow me to use RootModel[Base64Str] unconditionally and would eliminate the need to create the proper type for  model_construct.

Let's agree on removing the root= requirement and … have this sit, waiting for a good idea.

**Comment by dmontagu** [comment]
>I was hoping for a RootModel[T] attribute to have the same behavior as an attribute of the same type T wrt. model_construct.

I understand where you are coming from. I think the problem with this though is that fundamentally there is "validation" happening to make it so that you get a RootModel instead of the raw value, so I'm not sure how we could get that to behave correctly with `model_construct` in a way that wouldn't have kind of a weird logic fork/be inconsistent with how it works otherwise.

> In my case, I currently do not know if a Base64Str is "embedded" in a model/a property or standalone/requires to be a RootModel. Using refs -OpenAPI Schema- it can even be both.

I think this is unavoidable, is there a reason why you need to infer that a RootModel should be used? I think you could establish a convention that if a RootModel _should_ be used, that there should be a `$comment` in the schema or similar. But yeah I'm not sure in general if this is really possible, I guess the right thing to do depends on what you are trying to do.

**Comment by commonism** [comment]
I work with models, Base64Str is a type annotation. I need to embed this type annotation in a model to have model_validate/construct.
In case the type annotation is a property of a model, fine, there is a model and the model will take care of it's attributes.
In case the type annotation is the "root", I need a RootModel to encapsulate the type annotation so I can work with a model.

Every `type: string; format: byte` value in OpenAPI -which is not a property- qualifies for this treatment.

I've ignored `format: byte` before, so actually there won't be any loss, it's just sad to be unable to make use of this great facility.

**Comment by dmontagu** [comment]
@commonism I think based on this discussion I'll continue to let #5820 close this issue once it gets reviewed+merged, mostly just to try to keep our slate of open issues clean (well, we are trying to clean it up, slowly..). But to be clear, I think we are open to improvements in this area, if there are non-invasive changes we can make that would might help your use case let us know and we'll be happy to discuss further.
