### ISSUE TITLE
Don't raise error on BaseModel kwargs

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#6024]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently, if we use class arguments that are not in `ConfigDict`, like:

```py
from pydantic import BaseModel

class Model(BaseModel, strict=True, potato=123):
    x: int
```

We have the following error, since `potato` is not a valid key on `ConfigDict`:

```
Traceback (most recent call last):
  File "/Users/marcelotryle/dev/pydantic/pydantic/../main.py", line 3, in <module>
    class Model(BaseModel, strict=True, potato=123):
  File "/Users/marcelotryle/dev/pydantic/pydantic/pydantic/_internal/_model_construction.py", line 128, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: Model.__init_subclass__() takes no keyword arguments
```

We should not raise on keys that are not defined on `ConfigDict`, so other libraries can use other kwargs as they wish.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
After investigation, we ideally need to get clarification from pyright first (https://github.com/microsoft/pyright/discussions/10999).

The following patch could be used to add type checking support for this feature:

```diff
diff --git a/pydantic/_internal/_model_construction.py b/pydantic/_internal/_model_construction.py
index c90105094..22ada3dac 100644
--- a/pydantic/_internal/_model_construction.py
+++ b/pydantic/_internal/_model_construction.py
@@ -13,9 +13,10 @@ from types import FunctionType
 from typing import TYPE_CHECKING, Any, Callable, Generic, Literal, NoReturn, TypeVar, cast
 
 from pydantic_core import PydanticUndefined, SchemaSerializer
-from typing_extensions import TypeAliasType, dataclass_transform, deprecated, get_args, get_origin
+from typing_extensions import TypedDict, TypeAliasType, Unpack, dataclass_transform, deprecated, get_args, get_origin
 from typing_inspection import typing_objects
 
+from ..config import ConfigDict
 from ..errors import PydanticUndefinedAnnotation, PydanticUserError
 from ..plugin._schema_validator import create_schema_validator
 from ..warnings import GenericBeforeBaseModelWarning, PydanticDeprecatedSince20
@@ -71,6 +72,11 @@ def NoInitField(
     """
 
 
+# Used to allow extra keyword arguments beyond the configuration ones:
+class _ConfigDictOpen(ConfigDict, extra_items=Any):
+    pass
+
+
 # For ModelMetaclass.register():
 _T = TypeVar('_T')
 
@@ -82,10 +88,11 @@ class ModelMetaclass(ABCMeta):
         cls_name: str,
         bases: tuple[type[Any], ...],
         namespace: dict[str, Any],
+        /,
         __pydantic_generic_metadata__: PydanticGenericMetadata | None = None,
         __pydantic_reset_parent_namespace__: bool = True,
         _create_model_module: str | None = None,
-        **kwargs: Any,
+        **kwargs: Unpack[_ConfigDictOpen],
     ) -> type:
         """Metaclass for creating Pydantic models.
```
