### ISSUE TITLE
Model_name is protected namespace

### ISSUE THREAD

**Issue by chloehabitat** [pydantic/pydantic#6041]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

We have `model_name` in one of SQL tables as a column name and have a matching pydantic interface to match and use the `from_orm` method to transform it. Switching to pydantic v2 breaks this and returns this error

```
Traceback (most recent call last):
  File "/Users/user/pydantic-test/pydantic_test.py", line 15, in <module>
    class MyModel(_Base):
  File "/Users/user/pydantic-test/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 175, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/Users/user/pydantic-test/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 347, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/pydantic-test/venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 104, in collect_model_fields
    raise NameError(f'Field "{ann_name}" has conflict with protected namespace "{protected_namespace}"')
NameError: Field "model_name" has conflict with protected namespace "model_"
```

### Example Code

```Python
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import sqlalchemy as sa
import sqlalchemy.orm

Base = sqlalchemy.orm.declarative_base()


class _Base(BaseModel):
    class Config:
        from_attributes = True
        validate_assignment = True


class MyModel(_Base):
    market: str
    region: str
    model_name: str = Field(..., description="A name for the associated model.")
    start_datetime: datetime


class SQLModel(Base):
    __tablename__ = "sql_table"

    market = sa.Column(sa.String(32))
    region = sa.Column(sa.String(32))
    model_name = sa.Column(sa.String(64), primary_key=True)
    start_datetime = sa.Column(sa.TIMESTAMP)


sql_test = SQLModel(market="market1", region="SA", model_name="mymodel", start_datetime=datetime.now(timezone.utc))

pydantic_test = MyModel.model_validate(sql_test)

print(pydantic_test.model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: /Users/user/pydantic-test/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 24 2023, 00:31:37) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by Viicos** [comment]
See https://docs.pydantic.dev/dev-v2/usage/model_config/#protected-namespaces, `protected_namespaces` could help you here. Otherwise you could use another name on your pydantic model, and use a (validation) alias

**Comment by hramezani** [comment]
`model_` is a protected namespace for pydantic. that's why you've seen this error.

There are two options for your:

1. alias:

```py
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import sqlalchemy as sa
import sqlalchemy.orm

Base = sqlalchemy.orm.declarative_base()


class _Base(BaseModel):
    class Config:
        from_attributes = True
        validate_assignment = True


class MyModel(_Base):
    market: str
    region: str
    modelname: str = Field(..., description="A name for the associated model.", alias='model_name')  # here is the change
    start_datetime: datetime


class SQLModel(Base):
    __tablename__ = "sql_table"

    market = sa.Column(sa.String(32))
    region = sa.Column(sa.String(32))
    model_name = sa.Column(sa.String(64), primary_key=True)
    start_datetime = sa.Column(sa.TIMESTAMP)


sql_test = SQLModel(market="market1", region="SA", model_name="mymodel", start_datetime=datetime.now(timezone.utc))

pydantic_test = MyModel.model_validate(sql_test)

print(pydantic_test.model_dump(by_alias=True))  # here is the change
```

2. changing the `protected_namespaces` config:

```py
from pydantic import BaseModel, ConfigDict, Field
from datetime import datetime, timezone
import sqlalchemy as sa
import sqlalchemy.orm

Base = sqlalchemy.orm.declarative_base()


class _Base(BaseModel):
    class Config:
        from_attributes = True
        validate_assignment = True


class MyModel(_Base):
    model_config = ConfigDict(protected_namespaces=()). # here is the change

    market: str
    region: str
    model_name: str = Field(..., description="A name for the associated model.")
    start_datetime: datetime


class SQLModel(Base):
    __tablename__ = "sql_table"

    market = sa.Column(sa.String(32))
    region = sa.Column(sa.String(32))
    model_name = sa.Column(sa.String(64), primary_key=True)
    start_datetime = sa.Column(sa.TIMESTAMP)


sql_test = SQLModel(market="market1", region="SA", model_name="mymodel", start_datetime=datetime.now(timezone.utc))

pydantic_test = MyModel.model_validate(sql_test)

print(pydantic_test.model_dump())
```

**Comment by chloehabitat** [comment]
Thanks for the quick response! Is there a way to make only `model_name` exempt from the `model_` protected namespace rule? Otherwise it seems like an alias is the quickest solution to this

**Comment by hramezani** [comment]
> Is there a way to make only model_name exempt from the model_ protected namespace rule?

No
