### ISSUE TITLE
pydantic.errors.ConfigError: unable to infer type for attribute when using dataclass with none annotations

### ISSUE THREAD

**Issue by PeterD1524** [pydantic/pydantic#6080]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using dataclass with `None` annotations, a ConfigError is raised.
The example code below raises the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/dataclasses.py", line 231, in pydantic.dataclasses.dataclass
    repr_running = set()
  File "pydantic/dataclasses.py", line 224, in pydantic.dataclasses.dataclass.wrap
    _MODULE_IDENTIFIER_RE = re.compile(r'^(?:\s*(\w+)\s*\.)?\s*(\w+)')
  File "pydantic/dataclasses.py", line 347, in pydantic.dataclasses._add_pydantic_validation_attributes
    self.init = init
  File "pydantic/dataclasses.py", line 400, in pydantic.dataclasses.create_pydantic_model_from_dataclass
    
  File "pydantic/main.py", line 1026, in pydantic.main.create_model
  File "pydantic/main.py", line 221, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 546, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 578, in pydantic.fields.ModelField._set_default_and_type
pydantic.errors.ConfigError: unable to infer type for attribute "a"
```
I think the probably problem comes from "pydantic/main.py", in the function create_model, especially lines 996 to 1013.
https://github.com/pydantic/pydantic/blob/90326480ff1061f690aa193bd112cd17a6d90a70/pydantic/main.py#L996-L1013
For the case of the example code below, `f_def` will be a tuple for attribute "a" and `f_annotation` will be `None`, so the annotation will not be added as a result of line 1011.
Perhaps this problem can be fixed by removing line 1011 and moving line 1012 `annotations[f_name] = f_annotation` under line 999 `if isinstance(f_def, tuple):` block.

### Example Code

```Python
from pydantic.dataclasses import dataclass


@dataclass
class MyDataclass:
    a: None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
            pydantic compiled: True
                 install path: /venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201]
                     platform: Linux-6.3.6-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @PeterD1524 for reporting this.

I can confirm this problem. 

It is working as expected in `Pydantic V2`. 

We are not actively working on `V1` and will accept a fix for it in `V1` if it is an easy one.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
