### ISSUE TITLE
`KeyError: 'required'` when generating schema using `typed_dict_field`

### ISSUE THREAD

**Issue by antonagestam** [pydantic/pydantic#6192]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

It seems like there's a mismatch between expectations of `typed_dict_field` when generating a JSON schema for a model, and its defaults. `SchemaValidator` seemingly interprets omitting the `required` argument as defaulting to `required=True` (see how validation does not pass in the example when omitting the field). But when trying to generate a JSON schema for a model that uses this core schema, it fails with a `KeyError`.

Seemingly related, the failing line ends with `# type: ignore  # required is always populated`.

### Example Code

```python
from pydantic import BaseModel, ValidationError
from pydantic_core import core_schema, SchemaValidator


schema = core_schema.typed_dict_schema(
    {
        "subunits": core_schema.typed_dict_field(
            core_schema.int_schema(),
            # Uncommenting this line makes the example pass.
            # required=True,
        ),
    }
)
validator = SchemaValidator(schema)
result = validator.validate_python({"subunits": 100})
print(f"{result=}")

try:
    result = validator.validate_python({})
except ValidationError:
    pass
else:
    assert False, "did not raise"


class CustomType:
    def __get_pydantic_core_schema__(self):
        return schema


class Model(BaseModel):
    t: CustomType


print(Model.model_json_schema())
```

Running the example outputs:

```
result={'subunits': 100}
Traceback (most recent call last):
  File "/Users/annevoab/projects/immoney/repro.py", line 34, in <module>
    print(Model.model_json_schema())
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/main.py", line 570, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 1586, in model_json_schema
    return schema_generator_instance.generate(cls.__pydantic_core_schema__, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 294, in generate
    json_schema = self.generate_inner(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 409, in generate_inner
    return current_handler(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 386, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 1245, in definitions_schema
    self.generate_inner(definition)
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 409, in generate_inner
    return current_handler(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 402, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/main.py", line 185, in __get_pydantic_json_schema__
    return __handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 402, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 183, in modify_model_json_schema
    json_schema = handler(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 386, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 977, in model_schema
    json_schema = self.generate_inner(schema['schema'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 409, in generate_inner
    return current_handler(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 386, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 1048, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 925, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 409, in generate_inner
    return current_handler(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 402, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 696, in json_schema_update_func
    return {**handler(schema), **json_schema_updates}
              ^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 386, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 969, in model_field_schema
    return self.generate_inner(schema['schema'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 409, in generate_inner
    return current_handler(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 386, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 892, in typed_dict_schema
    named_required_fields: list[tuple[str, bool, CoreSchemaField]] = [
                                                                     ^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 893, in <listcomp>
    (name, self.field_is_required(field), field)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/annevoab/.pyenv/versions/immoney/lib/python3.11/site-packages/pydantic/json_schema.py", line 1076, in field_is_required
    return field['required']  # type: ignore  # required is always populated
           ~~~~~^^^^^^^^^^^^
KeyError: 'required'
```

### Python, Pydantic & OS Version

Tried with both latest beta as well as latest commit from main, 929a8833f2bcf3aff1196c82bfa0c9a20dd7fd43.

```shell
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0b3
        pydantic-core version: 0.40.1 release build profile
                 install path: /Users/annevoab/.pyenv/versions/3.11.0/envs/immoney/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Nov  5 2022, 23:09:18) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.6.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @antonagestam for reporting this.

I can confirm the error.

I think it is a problem in `pydantic-core`(I am not sure that it is a problem) and probably can be fixed by changing the default value of `required` field from `None` to `False` in [typed_dict_field](https://github.com/pydantic/pydantic-core/blob/c8e38786c83ecf09803026f2f7794dfa367d514d/pydantic_core/core_schema.py#L2662)

**Comment by antonagestam** [comment]
@hramezani Yeah, presumably the type-ignore hides a real issue. If the schema should be expected to always have the `"required"` key, that could be reflected in the typing of `TypedDictField` right?

**Comment by hramezani** [comment]
Thanks @adriangb for clearing this up.
