### ISSUE TITLE
Recursive model definitions with discriminated unions fail at import time

### ISSUE THREAD

**Issue by jcrist** [pydantic/pydantic#6273]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

This issue appears when defining a recursive type containing a discriminated union. If you remove the discriminator, then things work fine.

Running the below code results in:

```
$ python pydantic_bug.py
```

<details>
<summary>Output</summary>

```
Traceback (most recent call last):
  File "/home/jcristharif/Code/testing/pydantic_bug.py", line 12, in <module>
    class Foo(pydantic.BaseModel):
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    complete_model_class(
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 405, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/main.py", line 166, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 269, in generate_schema
    return self._generate_schema_for_type(
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 290, in _generate_schema_for_type
    schema = self._generate_schema(obj)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 480, in _generate_schema
    return self._model_schema(obj)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 356, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 356, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 619, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 660, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1272, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1332, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_std_types_schema.py", line 499, in __get_pydantic_core_schema__
    items_schema = handler.generate_schema(self.item_source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 93, in generate_schema
    return self._generate_schema.generate_schema(__source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 268, in generate_schema
    return self._annotated_schema(obj)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1166, in _annotated_schema
    schema = self._apply_annotations(lambda x: x, source_type, annotations)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1272, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1333, in new_handler
    schema = self.apply_single_annotation(schema, annotation)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1283, in apply_single_annotation
    schema = _discriminated_union.apply_discriminator(
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_discriminated_union.py", line 38, in apply_discriminator
    return _ApplyInferredDiscriminator(discriminator, definitions or {}).apply(schema)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_discriminated_union.py", line 134, in apply
    schema = self._apply_to_root(schema)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_discriminated_union.py", line 174, in _apply_to_root
    self._handle_choice(choice)
  File "/home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic/_internal/_discriminated_union.py", line 223, in _handle_choice
    raise ValueError(f"Missing definition for ref {choice['schema_ref']!r}")
ValueError: Missing definition for ref '__main__.Foo:94740906808464'
```
</details>

### Example Code

```Python
from __future__ import annotations

from typing import Union, List, Annotated, Literal

import pydantic


class Bar(pydantic.BaseModel):
    type: Literal["Bar"] = "Bar"


class Foo(pydantic.BaseModel):
    type: Literal["Foo"] = "Foo"
    # data: List[Union[Foo, Bar]]  # <- this works without a discriminator
    data: List[
        Annotated[Union[Foo, Bar], pydantic.Field(discriminator="type")]
    ]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b3
        pydantic-core version: 0.39.0 release build profile
                 install path: /home/jcristharif/miniconda3/envs/testing/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0]
                     platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
This is definitely a bug, thank you for reporting it!
