### ISSUE TITLE
Runtime error when using `TypeAdaptor(Annotated[..., Field(...)])` in other model

### ISSUE THREAD

**Issue by TimDiekmann** [pydantic/pydantic#6350]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I experimented around with custom data types as [described in the documentation](https://docs.pydantic.dev/2.0/usage/types/custom/). I get a runtime error as soon as I try to put this new custom type inside a model.

### Example Code

```Python
from typing import Annotated

from pydantic import Field, TypeAdapter, create_model, ConfigDict

PositiveInt = Annotated[int, Field(gt=0)]

model = create_model(
    "Model",
    __config__=ConfigDict(arbitrary_types_allowed=True),
    inner=(TypeAdapter(PositiveInt), Field(...)),
)
print(model.json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: <REDACTEC>
               python version: 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
    model = create_model(
            ^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/main.py", line 1319, in create_model
    return meta(__model_name, resolved_bases, namespace, __pydantic_reset_parent_namespace__=False, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 172, in __new__
    complete_model_class(
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 420, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/main.py", line 533, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 264, in generate_schema
    return self._generate_schema_for_type(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 285, in _generate_schema_for_type
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 475, in _generate_schema
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 351, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 351, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 614, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 656, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1281, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1249, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 537, in _generate_schema
    return self._arbitrary_type_schema(obj, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 578, in _arbitrary_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <pydantic.type_adapter.TypeAdapter object at 0x109350ad0>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.0/u/schema-for-unknown-type
```

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
I’m not sure what you’re trying to do but TypeAdapter is not meant to be used as a field in a model, it’s not a type.

**Comment by TimDiekmann** [comment]
Basically, I want to associate some metadata (like `title`, `description`, etc) to a data type such as `str` or `int`, so I use an `Annotated` type and annotate it with a `Field` with the desired attributes. As I need to use it in other models as well I cannot add another `Field` there as well as the annotations already contain a `Field` (even if they would be distinct). 

I interpreted `TypeAdaptor` as a _Type_ wrapper type which basically acts as a dedicated model. I guess the correct way then would be to use a `RootModel`? This, however, behaves differently as a `RootModel` is a whole object so the semantic is different than an `Annotated`.

**Comment by adriangb** [comment]
> Basically, I want to associate some metadata (like title, description, etc) to a data type such as str or int, so I use an Annotated type and annotate it with a Field with the desired attributes. As I need to use it in other models as well I cannot add another Field there as the annotations already contain a Field (even if they would be distinct).

Do you mean something like this?

```python
from typing import Annotated

from pydantic import Field, BaseModel

SomeAlias = Annotated[int, Field(description='number')]

class Model(BaseModel):
    foo: Annotated[SomeAlias, Field(title='abc')]
```

It's currently not very well supported, but we've talked about supporting it and would be open to ideas in that space.

**Comment by TimDiekmann** [comment]
Yeah, this is pretty close. One difference for me is that I create these models dynamically but the concept is the same:
```python
from typing import Annotated, Any

from pydantic import Field, create_model

def ty() -> type:
    return int

def annotated() -> Any:
    return Annotated[ty(), Field(description="number")]

model = create_model("Model", foo=(annotated(), Field(title="bar")))
# or
model = create_model("Model", foo=(Annotated[annotated(), Field(title="bar")], ...))
```

So using the second `Annotated` in the static model is not possible: In both cases, I get an error that two `Field`s are not allowed.

To work around this I'm now using `__get_pydantic_core_schema__` and `__get_pydantic_json_schema__` to avoid the inner `Field` so I can use the approach as above (but the `Annotated[ty(), Field(description="number")]` replaced with `Annotated[ty(), MyAnnotation]`.

I don't have any concrete ideas on how to support this better. I'm pretty new to Pydantic and typed Python (I didn't really use Python in years and just came back to it). It feels like generally creating dynamic models is supported but a more advanced topic.

**Comment by adriangb** [comment]
You're right, creating things dynamically is something we _try_ to support but can obviously get very hairy.

> So using the second Annotated in the static model is not possible: In both cases, I get an error that two Fields are not allowed.

This is what we're considering changing :) cc @dmontagu

**Comment by TimDiekmann** [comment]
>  but can obviously get very hairy.

Especially if you cannot distinct between an object and a type 😅 

Thanks for the quick and kind help!

**Comment by awoimbee** [comment]
Hello, I'm having a similar problem, how did you end up working around the issue @TimDiekmann ?
I would like something like:
```python
class InternalIdMixin:
    @classmethod
    def load_id(external: str) -> int: ...
    @classmethod
    def dump_id(internal: int) -> str: ...

def internal_id_field(model: InternalIdMixin):
    return Annotated[
        str,
        BeforeValidator(model.load_id),
        PlainSerializer(model.dump_id),
    ]

class MyObjectSchema(BaseModel):
    id: internal_id_field(MyObject) # err: Call expression not allowed in type expression
    name: str
    #[...]

```
