### ISSUE TITLE
Nested models created with `create_model` with same name results in key error

### ISSUE THREAD

**Issue by TimDiekmann** [pydantic/pydantic#6369]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When using the same model name in `create_model` as an inner model (dynamic or static) this results in a key error when creating the JSON schema:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<REDACTED>/app/__main__.py", line 83, in <module>
    print(model_b.model_json_schema())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/main.py", line 372, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1972, in model_json_schema
    return schema_generator_instance.generate(cls.__pydantic_core_schema__, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 320, in generate
    json_schema = self.resolve_collisions(json_schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1684, in resolve_collisions
    json_schema = self.change_defs_ref(defs_ref, choice, json_schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<REDACTED>/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 1712, in change_defs_ref
    self.definitions[new] = self.definitions.pop(old)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'aInput'
```

When using the same model next to each other this will work:
```python
from pydantic import create_model, BaseModel

class A(BaseModel):
    inner: str

model_a1 = create_model(
    "A",
    inner_a1=(str, ...),
)
model_a2 = create_model(
    "A",
    inner_a2=(str, ...),
)

model_c = create_model(
    "B",
    outer_a1=(model_a1, ...),
    outer_a2=(model_a2, ...),
)

print(model_c.model_json_schema()) # shows two distinct schemas
```

### Example Code

```Python
from pydantic import create_model

model_a = create_model(
    "a",
    inner=(str, ...),
)
model_b = create_model(
    "a",
    outer=(model_a, ...),
)

print(model_b.model_json_schema()) # Key Error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: <REDACTED>
               python version: 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by samuelcolvin** [comment]
Thanks for reporting, confirmed.

@dmontagu as the king of JSON Schema, could you take a look. If you don't have time, feel free to assign back to me and I can have a dig.
