### ISSUE TITLE
Introspection of fields during validation

### ISSUE THREAD

**Issue by ofek** [pydantic/pydantic#6429]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Here is an example of what we are currently doing in v1:

- https://github.com/DataDog/integrations-core/blob/master/apache/datadog_checks/apache/config_models/shared.py
- https://github.com/DataDog/integrations-core/tree/master/datadog_checks_base/datadog_checks/base/utils/models

We define the configuration for each integration as OpenAPI and generate the model code. Basically, we:

1. Set the default based on any manually defined functions that define complex logic like fallbacks
2. Set the default value for each option based on its type e.g. a string would default to an empty string rather than `None`
3. Run any manually defined functions for each option
4. Do a final pass over all values and convert mutable types like lists into immutable types like tuples

Is there a way in v2 to achieve this? Specifically, it looks like we need replacements for `field.required`, `field.shape`, and `always=True`.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by adriangb** [comment]
I couldn't tell immediately from the links what is going on, a self contained example would help.

In v2 you can access some field info via `BaseModel.model_fields`:
https://github.com/pydantic/pydantic/blob/c3fc4e6953d816e0e09c77d6913a6ecf50e19ee0/pydantic/main.py#L100

The `FieldInfo` object has an `is_required()` method:
https://github.com/pydantic/pydantic/blob/c3fc4e6953d816e0e09c77d6913a6ecf50e19ee0/pydantic/fields.py#L471C6-L471C6

For `always=True` you can either use `validate_default=True` in `Field` or `validate_defaults=True` in `model_config`:

```python
from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator


class DemoModel(BaseModel):
    ts: Annotated[datetime | None, Field(validate_default=True)] = None

    @field_validator('ts', mode='before')
    def set_ts_now(cls, v: datetime | None) -> datetime:
        return v or datetime(2032, 1, 2, 3, 4, 5, 6)

    model_config = ConfigDict(validate_default=True)  #  either option works, you don't need both


print(DemoModel())
#> ts=datetime.datetime(2032, 1, 2, 3, 4, 5, 6)
print(DemoModel(ts=datetime(2022, 1, 2, 3, 4, 5, 6)))
#> ts=datetime.datetime(2022, 1, 2, 3, 4, 5, 6)
```

`field.shape` is gone, the whole `shape` thing was a sort of strange IR of the type system. I'd recommend you introspect `BaseModel.__annotations__`, `FieldInfo.annotation` or one of the several other ways to get the type hints / annotations for a given field.


If you're trying to do some of this from within a validator function you can get the field from the model using the field name:

```python
from datetime import datetime
from typing import Any

from pydantic import BaseModel, FieldValidationInfo, field_validator


def validator_func(cls: type[BaseModel], v: Any, info: FieldValidationInfo) -> Any:
    print(repr(cls.model_fields[info.field_name]))
    return v


class DemoModel(BaseModel):
    ts: datetime | None
    val_ts = field_validator('ts', mode='before')(classmethod(validator_func))


DemoModel(ts=None)
#> FieldInfo(annotation=Union[datetime, NoneType], required=True)
```

You could also use a [model_validator](https://docs.pydantic.dev/dev-v2/usage/validators/#model-validators) with `mode='before'` to do this for every field in the model.

Let me know if this helps or if you have any more questions.

**Comment by ofek** [comment]
Thanks! I am at the last step I think. Is there a way to perform validation/update the raw dictionary of fields after all validation right before the model gets created? It looks like the after mode for model validators returns the final object which in our case cannot be modified because we enable frozen. I tried the wrap mode but am getting an error (this might not even provide the dictionary but I was just trying stuff):

```python
    @model_validator(mode='wrap')
    def _final_validation(cls, values, handler):
        return values
```

```
Traceback (most recent call last):
  File "C:\Users\ofek\Desktop\pd.py", line 12, in <module>
    main()
  File "C:\Users\ofek\Desktop\pd.py", line 8, in main
    print(o)
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\main.py", line 859, in __str__
    return self.__repr_str__(' ')
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\_internal\_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\_internal\_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\main.py", line 847, in __repr_args__
    pydantic_extra = self.__pydantic_extra__
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\main.py", line 699, in __getattr__
    pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SharedConfig' object has no attribute '__pydantic_extra__'. Did you mean: '__pydantic_private__'?
```

**Comment by adriangb** [comment]
That implementation would work with `before` mode

**Comment by ofek** [comment]
It looks like that is not true but rather model validation with before mode gets run before field validation

**Comment by adriangb** [comment]
My point was that `wrap` mode expect you to return an instance of the model, eg `return handler(values)` would work. `before` mode let’s you validate / replace the `values` which is what you are doing in the comment above. Also note that `values` isn’t necessarily a dictionary it is the raw input to validation eg in the case of `Model.model_validate_python(Model())` it’ll be a `Model` instance.

**Comment by ofek** [comment]
Is there a way to modify the dictionary at the very end after all field validators have executed?

**Comment by adriangb** [comment]
There is no more dictionary at that point, just the model

**Comment by adriangb** [comment]
I do think there's two very reasonable feature requests here:
1. Don't freeze the model until after `@model_validator`s are done running
2. A way to run validation for individual fields (e.g. `values['x'] = handler.validate_field(values['x'])`)
