### ISSUE TITLE
model_dump_json() big int to json failed

### ISSUE THREAD

**Issue by whitemoon** [pydantic/pydantic#6442]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Error when converting large int to JSON string:
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(test.model_dump_json())
  File "/home/sam/.conda/envs/py38/lib/python3.8/site-packages/pydantic/main.py", line 336, in model_dump_json
    return self.__pydantic_serializer__.to_json(
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: OverflowError: Python int too large to convert to C long
```

### Example Code

```Python
import pydantic


class Test(pydantic.BaseModel):
    test_int: int


test = Test(test_int=14333520998899385340)
print(test.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.1
        pydantic-core version: 2.0.2 release build profile
                 install path: /home/sam/.conda/envs/py38/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
                     platform: Linux-6.4.1-arch2-1-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by kkirsche** [comment]
This also occurred for me when running using hypothesis in unit tests

**Comment by dmontagu** [comment]
I believe this will require changes to pydantic-core, but @davidhewitt is on it and it looks like it might not be too hard to fix.

@davidhewitt as we discussed, maybe we can fix the validation of large ints from JSON while we're at it.

A couple failing tests that might  be useful:
```python
import pydantic


def test_serialize_large_integer():
    class IntModel(pydantic.BaseModel):
        my_int: int

    large_integer = 1433352099889938534014333520998899385340

    test = IntModel(my_int=large_integer)
    assert test.model_dump_json() == f'{"my_int":{large_integer}}'


def test_validate_json_large_integer():
    class IntModel(pydantic.BaseModel):
        my_int: int

    large_integer = 1433352099889938534014333520998899385340

    assert IntModel.model_validate_json(f'{"my_int":{large_integer}}').my_int == large_integer
```
