### ISSUE TITLE
Panic in validation of nested model with unicode strings

### ISSUE THREAD

**Issue by jl-wynen** [pydantic/pydantic#6448]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I get the following error from the code below:
```
Traceback (most recent call last):
  File "/home/jl/Downloads/pydantic-panic.py", line 13, in <module>
    Outer(
  File "/home/jl/Software/mambaforge/envs/pydantic-panic/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
thread '<unnamed>' panicked at 'byte index 27 is not a char boundary; it is inside '°' (bytes 26..28) of `IncorrectInner1(name='\x81°6ÿ\x19õó:=', abc='')`', src/errors/validation_exception.rs:384:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
pydantic_core._pydantic_core.ValidationError: <exception str() failed>
```

This is triggered in the constructor of `Outer`. It goes away if `x` is annotated to take an `IncorrectInner1` instead of `int`.

This seems to happen during string formatting because the panic goes away (turns into a regular validation error) when the inner model is changed, e.g., the length of "IncorrectInner1", the number of fields, or the length of the content of the `name` field.

The concrete input string to trigger this was found by hypothesis. I don't know if it is malformed but Python seems to be happy with it. And Pydantic is mostly happy, too. For example, making the inner model and printing it works fine.

### Example Code

```Python
from pydantic import BaseModel


class IncorrectInner1(BaseModel):
    name: str
    abc: str


class Outer(BaseModel):
    x: int


Outer(
    x=IncorrectInner1(
        name=b"\xc2\x81\xc2\xb06\xc3\xbf\x19\xc3\xb5\xc3\xb3:=".decode(
            encoding="utf-8"
        ),
        abc="",
    ),
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.1
        pydantic-core version: 2.0.2 release build profile
                 install path: /home/jl/Software/mambaforge/envs/pydantic-panic/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
                     platform: Linux-6.1.31-2-MANJARO-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by dmontagu** [comment]
It's erroring on this line of pydantic-core:

https://github.com/pydantic/pydantic-core/blob/4527b8078232afbbf143a3c6f474abee76b477e2/src/errors/validation_exception.rs#L384, which uses this macro: https://github.com/pydantic/pydantic-core/blob/4527b8078232afbbf143a3c6f474abee76b477e2/src/errors/validation_exception.rs#L233-L246

I _believe_ the issue is that that macro is not guaranteed to preserve the validity of the unicode involved. I _suspect_ it shouldn't be too hard to fix in `pydantic-core`.

**Comment by dmontagu** [comment]
(for context:)
```
Traceback (most recent call last):
  File "/Users/davidmontague/Library/Application Support/JetBrains/PyCharm2023.1/scratches/scratch_613.py", line 14, in <module>
    Outer(
  File "/Users/davidmontague/Programming/pydantic/pydantic/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationErrorthread '<unnamed>' panicked at 'byte index 27 is not a char boundary; it is inside '°' (bytes 26..28) of `IncorrectInner1(name='\x81°6ÿ\x19õó:=', abc='')`', src/errors/validation_exception.rs:384:13
stack backtrace:
   0:        0x1037359d8 - _PyInit__pydantic_core
   1:        0x1036a8550 - _PyInit__pydantic_core
   2:        0x10371d278 - _PyInit__pydantic_core
   3:        0x103738b14 - _PyInit__pydantic_core
   4:        0x1037388fc - _PyInit__pydantic_core
   5:        0x103739070 - _PyInit__pydantic_core
   6:        0x103738c94 - _PyInit__pydantic_core
   7:        0x103738c04 - _PyInit__pydantic_core
   8:        0x103738bf8 - _PyInit__pydantic_core
   9:        0x10375bf80 - _PyInit__pydantic_core
  10:        0x1036ad0a4 - _PyInit__pydantic_core
  11:        0x10375c2b4 - _PyInit__pydantic_core
  12:        0x103591d54 - <unknown>
  13:        0x1035d098c - <unknown>
  14:        0x10365a2cc - <unknown>
  15:        0x1035ad550 - <unknown>
  16:        0x102f23ec4 - _PyObject_Str
  17:        0x102ff3db4 - _print_exception_recursive
  18:        0x102ff3608 - __PyErr_Display
  19:        0x102ff402c - _PyErr_Display
  20:        0x102ffeb10 - _sys_excepthook
  21:        0x102f205e4 - _cfunction_vectorcall_FASTCALL
  22:        0x102ff3230 - __PyErr_PrintEx
  23:        0x102ff244c - _PyRun_SimpleFileExFlags
  24:        0x10300f508 - _Py_RunMain
  25:        0x10300f9cc - _pymain_main
  26:        0x10300fa48 - _Py_BytesMain
: <exception str() failed>
```

**Comment by dmontagu** [comment]
I'll note there is a [crate that does the truncation properly](https://docs.rs/unicode-truncate/latest/src/unicode_truncate/lib.rs.html#104-121), not sure how hard it would be to just copy the relevant code (I'm assuming we don't want to add a dependency for this..)

**Comment by dmontagu** [comment]
Slightly more minimal reproduction of the issue:
```python
from pydantic import TypeAdapter

adapter = TypeAdapter(int)
danger_str = 'aaaaaaaaaaaaaaaa°6ÿõó:=aaaaaaaaaaaaaaaa'
adapter.validate_python(danger_str)
"""
pydantic_core._pydantic_core.ValidationErrorthread '<unnamed>' panicked at 'byte index 25 is not a char boundary; it is inside 'ÿ' (bytes 24..26) of `'aaaaaaaaaaaaaaaa\x81°6ÿ\x19õó:=aaaaaaaaaaaaaaaa'`', src/errors/validation_exception.rs:384:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
: <exception str() failed>
"""
```
