### ISSUE TITLE
Unable to (de)serialize a RootModel

### ISSUE THREAD

**Issue by Fokko** [pydantic/pydantic#6478]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

First of all, thanks for the incredible support. This is the third issue; the others are resolved in record time. Thank you for that 🙏🏻 

Unable to (de)serialize a `RootModel` properly. In Pydantic 1.x I used to do:

```python
root@a91f88a8e3a2:/# python3
Python 3.8.17 (default, Jul  4 2023, 22:24:10) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import __version__
>>> __version__
'1.10.10'
>>> from pydantic import BaseModel, Field
>>> from typing import Any, Literal, List
>>> 
>>> class IcebergType(BaseModel):
...     @classmethod
...     def __get_validators__(cls):
...         """Called to validate the input of the Transform class."""
...         # one or more validators may be yielded which will be called in the
...         # order to validate the input, each validator will receive as an input
...         # the value returned from the previous validator
...         yield cls.validate
...     @classmethod
...     def validate(cls, v: Any) -> BaseModel:
...         if isinstance(v, str):
...             if v == "string":
...                 return StringType()
...         return v
... 
>>> class PrimitiveType(IcebergType):
...     __root__: str
... 
>>> class StringType(PrimitiveType):
...     __root__: Literal["string"] = Field(default="string")
... 
>>> class Schema(BaseModel):
...     fields: List[IcebergType]
... 
>>> schema_json = Schema(fields=[StringType()]).json()
>>> 
>>> schema_json
'{"fields": ["string"]}'
>>> Schema.parse_raw(schema_json)
Schema(fields=[StringType(__root__='string')])
```

Which worked as a charm. In 2.0 I'm having trouble with either (de)serialization. In the following example, serialization works as it should. But I'm unable to deserialize it. 

```python
root@f2b844589db5:/# python3
Python 3.8.17 (default, Jul  4 2023, 22:24:10) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import __version__
>>> 
>>> __version__
'2.0.2'
>>> from pydantic import BaseModel, RootModel, Field, SerializeAsAny, GetCoreSchemaHandler
>>> from pydantic_core import core_schema
>>> from typing import Generic, TypeVar, Literal, List, Any
>>> from abc import ABC, abstractmethod
>>> from pydantic_core import core_schema
>>> 
>>> class IcebergType(ABC, BaseModel):
...     pass
... 
>>> class PrimitiveType(IcebergType, RootModel):
...     """Primitive types are a by a string"""
...     pass
... 
>>> class StringType(PrimitiveType):
...     root: Literal["string"] = Field(default="string")
... 
>>> class Schema(BaseModel):
...     fields: List[SerializeAsAny[IcebergType]]
... 
>>> schema_json = Schema(fields=[StringType()]).model_dump_json()
>>> schema_json
'{"fields":["string"]}'
>>> Schema.model_validate_json(schema_json)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pydantic/main.py", line 507, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Schema
fields.0
  Input should be an object [type=model_type, input_value='string', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/model_type
```

According to the docs, `__get_validators__` has been replaced by `__get_pydantic_core_schema__`. So let's give that a try:

```python
root@f2b844589db5:/# python3
Python 3.8.17 (default, Jul  4 2023, 22:24:10) 
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel, RootModel, Field, SerializeAsAny, GetCoreSchemaHandler
>>> from pydantic_core import core_schema
>>> from typing import Generic, TypeVar, Literal, List, Any
>>> from abc import ABC, abstractmethod
>>> from pydantic_core import core_schema
>>> 
>>> class IcebergType(ABC, BaseModel):
...     @classmethod
...     def __get_pydantic_core_schema__(
...         cls, _source_type: Any, _handler: GetCoreSchemaHandler
...     ) -> core_schema.CoreSchema:
...         return core_schema.no_info_after_validator_function(
...             cls.validate,
...             core_schema.str_schema(),
...         )
...     @classmethod
...     def validate(cls, v: str):
...         return str(v)
... 
>>> class PrimitiveType(IcebergType, RootModel):
...     """Primitive types are a by a string"""
...     pass
... 
>>>     
>>> class StringType(PrimitiveType):
...     root: Literal["string"] = Field(default="string")
... 
>>>         
>>> class Schema(BaseModel):
...     fields: List[SerializeAsAny[IcebergType]]
... 
>>> schema_json = '{"fields": ["string"]}'
>>> Schema.model_validate_json(schema_json)
Schema(fields=['string'])
# Now this stopped working
>>> Schema(fields=[StringType()]).json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pydantic/root_model.py", line 51, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(root, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for StringType
  Input should be a valid string [type=string_type, input_value=PydanticUndefined, input_type=PydanticUndefinedType]
    For further information visit https://errors.pydantic.dev/2.1.2/v/string_type
>>> Schema(fields=['string']).json()
<stdin>:1: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.0.2/migration/
'{"fields":["string"]}'
# And it expects it to be a string as well:
>>> Schema(fields=['string']).model_dump_json()
'{"fields":["string"]}'
```

### Python, Pydantic & OS Version

```Text
>>> import pydantic.version; print(pydantic.version.version_info())
             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.17 (default, Jul  4 2023, 22:24:10)  [GCC 12.2.0]
                     platform: Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.34
     optional deps. installed: ['typing-extensions']
```
```


Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
While I'm sure this can be done with `__get_pydantic_core_schema__`, the schema you are currently returning there won't work for it, in particular, it is just validating into a string, not into a model instance.

However, I think you don't need to use that at all here, and can get by with just a `@model_validator`:

```python
from abc import ABC
from typing import Literal, List

from pydantic import BaseModel, RootModel, Field, SerializeAsAny, model_validator


class IcebergType(ABC, BaseModel):
    @model_validator(mode='wrap')
    @classmethod
    def handle_primitive_type(cls, v, handler):
        if isinstance(v, str) and not issubclass(cls, PrimitiveType):
            return StringType(v)
        return handler(v)


class PrimitiveType(IcebergType, RootModel):
    """Primitive types are a by a string"""
    pass


class StringType(PrimitiveType):
    root: Literal["string"] = Field(default="string")


class Schema(BaseModel):
    fields: List[SerializeAsAny[IcebergType]]


schema_json = '{"fields": ["string"]}'
m = Schema.model_validate_json(schema_json)
print(m)
#> fields=[StringType(root='string')]

print(m.model_dump_json())
#> {"fields":["string"]}
```

If that doesn't work for you, let us know what other issues you hit and we can help address those.
