### ISSUE TITLE
Computed field errors during declaration with forward referenced return type

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6489]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Computed fields errors when used with forward referenced types. 

Pydantic errors on model declaration itself stating the type is not defined.

datetime module used for simple example, in reality hit when a forward reference was actually needed due to circular reference constraints.

```
Traceback (most recent call last):

  File "/tmp/ipykernel_44291/634715983.py", line 10, in <module>
    class Foo(BaseModel):

  File "/tmp/ipykernel_44291/634715983.py", line 11, in Foo
    @computed_field
     ^^^^^^^^^^^^^^

  File "python3.11/site-packages/pydantic/fields.py", line 995, in computed_field
    return dec(__f)
           ^^^^^^^^

  File "python3.11/site-packages/pydantic/fields.py", line 978, in dec
    return_type = _decorators.get_function_return_type(f, return_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "python3.11/site-packages/pydantic/_internal/_decorators.py", line 712, in get_function_return_type
    hints = get_function_type_hints(unwrap_wrapped_function(func), include_keys={'return'})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 249, in get_function_type_hints
    type_hints[name] = typing._eval_type(value, globalns, None)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/typing.py", line 371, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/typing.py", line 877, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<string>", line 1, in <module>

NameError: name 'datetime' is not defined
```

### Example Code

```Python
import typing as tp
from pydantic import BaseModel, computed_field

if tp.TYPE_CHECKING:
    from datetime import datetime


class Foo(BaseModel):
    @computed_field
    @property
    def now(self) -> "datetime":
        import datetime

        return datetime.now()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
It's not surprising that this example doesn't work — there's no way for pydantic to infer what the forward referenced type is — but I understand the issue that you are describing.

I think what we need to do is something like what we do when you have an invalid forward reference to a model field, and we produce a mock validator — I guess in this case we'll want a mock serializer.

For what it's worth, you can probably work around this for now by using `@model_serializer` and inserting an extra field onto it, I understand that's a worse experience than if `rebuild_model` would work to get an updated computed_field that works.

**Comment by zakstucke** [comment]
Yes definitely V1-esque ways of getting around it, although I think a big portion of users will hit this eventually if using computed fields enough. 

I've updated the example to include the rebuild section I'd expected to work initially and would use in other circumstances.

```
import datetime

Foo.model_rebuild()

Foo().now
```
