### ISSUE TITLE
Zero-duration `timedelta` cannot be parsed

### ISSUE THREAD

**Issue by miili** [pydantic/pydantic#6491]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

An zero-length timedelta (`timedelta(seconds=0.0)`) can be serialized to `"P"` but not parsed by pydantic.

### Example Code

```Python
from pydantic import BaseModel
from datetime import timedelta


class MyModel(BaseModel):
    delta: timedelta = timedelta(seconds=0.0)


m = MyModel()

print(m.model_dump_json())  # {"delta":"P"}

MyModel.model_validate_json(m.model_dump_json())
```

Above code results in a `time_delta_parsing` error:
```
Traceback (most recent call last):
  File "/tmp/pydantic-timedelta.py", line 13, in <module>
    MyModel.model_validate_json(m.model_dump_json())
  File "/home/marius/Development/lassie-v2/venv/lib/python3.11/site-packages/pydantic/main.py", line 507, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
delta
  Input should be a valid duration, input is too short [type=time_delta_parsing, input_value='P', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/time_delta_parsing
```

### Expected Behavior

Parse zero-length timedeltas as `timedelta(seconds=0.0)`.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
               python version: 3.11.1 (main, Jan 24 2023, 14:16:05) [GCC 10.2.1 20210110]
                     platform: Linux-6.1.0-9-amd64-x86_64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
This does seem like a bug.

**Comment by samuelcolvin** [comment]
Sounds like an issue with serialising timedeltas in speedate.

**Comment by adriangb** [comment]
Indeed: https://github.com/pydantic/speedate/commit/ca9ddc36512a9498a72bbd8f24cebfbc5be15972

**Comment by adriangb** [comment]
This is fixed in `main`:

```python
from pydantic import BaseModel
from datetime import timedelta


class MyModel(BaseModel):
    delta: timedelta = timedelta(seconds=0.0)


m = MyModel()

print(m.model_dump_json())  # {"delta":"PT0S"}

MyModel.model_validate_json(m.model_dump_json())  # no error!
```
