### ISSUE TITLE
Cannot validate datetime without timezone minute

### ISSUE THREAD

**Issue by hyeongguen-song** [pydantic/pydantic#6576]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Pydantic V1, I can validate datetime even if timezone minute is not exists
but V2, raise validation error with
`Input should be a valid datetime, invalid timezone minute [type=datetime_parsing, input_value='2023-07-11 10:00:17.851673+09', input_type=str]`

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel


class DatetimeWithoutTimezoneMinute(BaseModel):
    dt: datetime


DatetimeWithoutTimezoneMinute(dt="2021-11-04T00:00:00+09")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/v/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DatetimeWithoutTimezoneMinute
dt
  Input should be a valid datetime, invalid timezone minute [type=datetime_parsing, input_value='2021-11-04T00:00:00+09', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/datetime_parsing

1 validation error for DatetimeWithoutTimezoneMinute
dt
  Input should be a valid datetime, invalid timezone minute [type=datetime_parsing, input_value='2021-11-04T00:00:00+09', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/datetime_parsing
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/me/Library/Caches/pypoetry/virtualenvs/v/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, May 10 2022, 11:08:53) [Clang 13.1.6 (clang-1316.0.21.2)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']

```

Selected Assignee: @dmontagu

**Comment by hyeongguen-song** [comment]
I'm not sure it is a bug, but I want to know how to handle it without `mode="before"`

**Comment by hramezani** [comment]
Thanks @hyeongguen-song for this 🙏 

> I'm not sure it is a bug, but I want to know how to handle it without mode="before"

It is not a bug. Why don't you want to handle it by `mode='before'`?

**Comment by hyeongguen-song** [comment]
Hi, @hramezani 
I don't think handle with `mode` is elegant.
When I can get `2023-07-11 11:00:00+09` or `2023-07-11 16:59:59.999999+09` - got from postgresql datetime field
It's hard to handle it without 3rd party library (ex, `dateutil`)

**Comment by eric-leblouch** [comment]
Hi,

I am currently updating my project dependencies including pydantic v2 and I got the same exact issue.

I am also using postgresql and I have a lot of datetime fields.

I changed all my datetime fields to AwareDateTime but it did not resolve my issue.

I do not want to add a validator as well as a serializer to all my datetime fields. So I would like to know of a way to accept and return this format globally. I did it in v1 by changing the ENCODERS_BY_TYPE and because v1 validator did accept this format, but this dictionary of serializer does not exist anymore or I did not find it and I did not find a way to modify globally the validation for a type.

If someone has an hint as to how to do it. I did use the main branch of pydantic-core (to get the PostgresDSN.build) and the 2.3.0 of pydantic in my tests.

**Comment by hramezani** [comment]
You can have a custom type with `Annotated`:

```py
from datetime import datetime

from typing_extensions import Annotated
from pydantic import BaseModel, BeforeValidator


# parse datetime 
def fix_postgres_datetime(v: str) -> str:
    if '+' in v:
        dt, tz = v.split('+')
        if len(tz) == 2:
            return f'{dt}+{tz}:00'
    return v
    


PostgresDatetime = Annotated[datetime, BeforeValidator(fix_postgres_datetime)]

class DatetimeWithoutTimezoneMinute(BaseModel):
    dt: PostgresDatetime


print(DatetimeWithoutTimezoneMinute(dt='2021-11-04T00:00:00+09'))
print(DatetimeWithoutTimezoneMinute(dt='2023-07-11 16:59:59.999999+09'))
```

**Comment by alex-pobeditel-2004** [comment]
The issue is still here. If it is an intended change, strange that it is not documented and there is no way to specify timezone parsing mode, because it is a backward-incompatible and at least completely breaks trivial datetime integration with PostgreSQL.  
@hramezani thanks for the decent workaround!
