### ISSUE TITLE
No validation occurred after using Annotated.

### ISSUE THREAD

**Issue by vagreargnatry** [pydantic/pydantic#6612]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Please take a look at this issue first: https://github.com/pydantic/pydantic/issues/5006

TimeOne can make VS Code Python type inference work properly, but TimeOne did not undergo validation.

### Example Code

```Python
from pydantic import BaseModel, conint
from typing import Annotated

Hour = Annotated[int, conint(gt=0, lt=25)]
Minute = Annotated[int, conint(gt=0, lt=61)]


class TimeOne(BaseModel):
    hour: Hour
    minute: Minute


class TimeTwo(BaseModel):
    hour: conint(gt=0, lt=25)
    minute: conint(gt=0, lt=61)


print(TimeOne(hour=-1, minute=10))
print(TimeTwo(hour=-1, minute=10))

# output:
#
# hour=-1 minute=10
# Traceback (most recent call last):
#   File "/home/{{username}}/learn/sample-1/sample_1/main.py", line 19, in <module>
#     print(TimeTwo(hour=-1, minute=10))
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/{{username}}/.cache/pypoetry/virtualenvs/sample-1-wFgLiamH-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
#     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for TimeTwo
# hour
#   Input should be greater than 0 [type=greater_than, input_value=-1, input_type=int]
#     For further information visit https://errors.pydantic.dev/2.1.2/v/greater_than
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/{{username}}/.cache/pypoetry/virtualenvs/sample-1-wFgLiamH-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul 10 2023, 10:28:44) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.2-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by vagreargnatry** [comment]
I am trying to change some of the code to the following code:

``` python
Hour = Annotated[conint(gt=0, lt=25), int]
Minute = Annotated[conint(gt=0, lt=61), int]
```

This can lead to validation and enable vscode Python type inference to work properly, but I'm not sure why.

**Comment by Viicos** [comment]
In v2 `conint` already returns a `Annotated` type:

https://github.com/pydantic/pydantic/blob/c4b40f281657c39d0380f090b80fb7015c59028b/pydantic/types.py#L132-L159

The pylance error is unfortunate, but you can still use the following:

```python
from typing import Annotated

from annotated_types import Interval
from pydantic import BaseModel

Hour = Annotated[int, Interval(gt=0, lt=25)]
Minute = Annotated[int, Interval(gt=0, lt=61)]
```

**Comment by adriangb** [comment]
It might make sense to do something similar to #6605

**Comment by adriangb** [comment]
Here's a runnable version of the approach @Viicos suggested above:

```python
from typing import Annotated

from annotated_types import Interval

from pydantic import BaseModel, Field

Hour = Annotated[int, Field(gt=0, lt=25)]
Minute = Annotated[int, Interval(gt=0, lt=61)]


class TimeOne(BaseModel):
    hour: Hour
    minute: Minute


print(TimeOne(hour=-1, minute=10))
#> hour -> Input should be greater than 0 [type=greater_than, input_value=-1, input_type=int]
```

Note that you can use `Interval` directly or `Field`, whichever you prefer.
