### ISSUE TITLE
Apply `to_upper`, etc. `StringConstraints` before checking for `pattern` (similar to `strip_whitespace`)?

### ISSUE THREAD

**Issue by wcwagner** [pydantic/pydantic#6624]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

## Summary
- String constraints (e.g. via `constr`, or the new `StringConstraints`) are applied in a non-intuitive manner (IMO)
- [`StrConstrainedValidator`](https://github.com/pydantic/pydantic-core/blob/bf0bce0024d38500b823065633c173afc722a606/src/validators/string.rs#L93-L111) does the following (in order):
   1. Strip whitespace
   2. Validates length (i.e. `min_length`, `max_length`)
   3. Checks pattern
   4. Converts case (i.e. `to_upper`, `to_lower`)
 
**Why are a subset of the "transformations" applied before checking pattern and others after?**

Of course, this is "easily" solvable by adding a `re.IGNORECASE` flag, e.g. `(?i)`, but that's only after discovering this behaviour.

## Examples (V1 and V2)
```py
import pydantic as pyd

class UpperWordModel(pyd.BaseModel):
    word: pyd.constr(to_upper=True, strip_whitespace=True,  regex=r'^[A-Z]+%')

if __name__ == '__main__':
    print(pyd.__version__)
    UpperWordModel(word='foo')
    UpperWordModel(word=' FOO ')
```
Outputs
```
 1.10.11
Traceback (most recent call last):
  File "/pdv1/pydantic_str.py", line 8, in <module>
    UpperWordModel(word='foo')
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UpperWordModel
word
  string does not match regex "^[A-Z]+%" (type=value_error.str.regex; pattern=^[A-Z]+%)             
```

Same thing basically for V2
```py
import pydantic as pyd

class UpperWordModel(pyd.BaseModel):
    word: pyd.constr(to_upper=True, strip_whitespace=True,  pattern=r'^[A-Z]+%')

if __name__ == '__main__':
    print(pyd.__version__)
    UpperWordModel(word='foo')
    UpperWordModel(word=' FOO ')
```
Outputs
```
2.0.2
Traceback (most recent call last):
  File "/pdv1/pydantic_str.py", line 8, in <module>
    UpperWordModel(word='foo')
  File "/root/.cache/pypoetry/virtualenvs/pdv1-TFOeYz4K-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for UpperWordModel
word
  String should match pattern '^[A-Z]+%' [type=string_pattern_mismatch, input_value='foo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/string_pattern_mismatch
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by wcwagner** [comment]
One workaround is to add an inline flag to the `pattern`, e.g.
```py
import pydantic as pyd

class UpperWordModel(pyd.BaseModel):
    word: pyd.constr(to_upper=True, strip_whitespace=True,  pattern=r'(?i)^[A-Z]+$')

if __name__ == '__main__':
    print(pyd.__version__)
    UpperWordModel(word='foo')
    UpperWordModel(word=' FOO ')
```

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues by writing pull requests. This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by adriangb** [comment]
@wwzeng1 I disagree, this is not a good issue for a Junior dev never mind an “AI junior dev”. The bottleneck is not contributors it’s out time reviewing contributions. Please be considerate of self promotion like this.

**Comment by wwzeng1** [comment]
@adriangb Apologies if that's the bottleneck! I'm happy to personally help review and test the changes
