### ISSUE TITLE
Cannot define union types with specific field info

### ISSUE THREAD

**Issue by yanyongyu** [pydantic/pydantic#6674]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to define a union field with some specific constrants on one of the union types. The code is working correctly using pydantic v1 but throws an error using pydantic v2.

Here is the minimum re-preduce code:

```python
from typing import Union
from pydantic import BaseModel, Field, ConfigDict

class Test(BaseModel):
    field: Union[int, str] = Field(default=1, pattern="^pkg")

    model_config = ConfigDict(strict=True)
```

The above code represents the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/test/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 172, in __new__
    complete_model_class(
  File "/miniconda3/envs/test/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 438, in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(simplified_core_schema, core_config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.model-fields.fields.field.schema.default.schema.union.pattern
  Extra inputs are not permitted [type=extra_forbidden, input_value='^pkg', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/extra_forbidden
```

But, with the `Annotated` type, it works:

```python
from typing import Union, Annotated
from pydantic import BaseModel, Field, ConfigDict

class Test(BaseModel):
    field: Union[int, Annotated[str, Field(pattern="^pkg")]] = Field(default=1)

    model_config = ConfigDict(strict=True)
```

Is this pydantic's bug or as-designed? May be this should be documented as it is different from pydantic v1.

Related to https://github.com/yanyongyu/githubkit/issues/38

### Example Code

```Python
from typing import Union
from pydantic import BaseModel, Field, ConfigDict

class Test(BaseModel):
    field: Union[int, str] = Field(default=1, pattern="^pkg")

    model_config = ConfigDict(strict=True)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: xxx
               python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
                     platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @yanyongyu for reporting this.

Yes, this is by design because `pattern` can not be applied on `int`.

Agree that the error is not clear enough. You can find a more descriptive answer [here](https://github.com/pydantic/pydantic/issues/6577#issuecomment-1634245104)

**Comment by yanyongyu** [comment]
Thanks for your anwser. Seems `Annotated` is the correct way to defined a constrant on sub type in union or container.
