### ISSUE TITLE
Generic pydantic model has problems with parameter type lists

### ISSUE THREAD

**Issue by favll** [pydantic/pydantic#6740]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to define a Pydantic model with generic type variables based on a `ParamSpec` type variable. In some cases I use the model as a type and pass through the `ParamSpec` type variable. This works as expected. In other cases I want to pass a parameter type list. This fails

The tracebackof the faulty case in the example code:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wbuffett/projects/graphster/graphster/bugy.py", line 29, in <module>
    def some_other_func(inputs: InputsT, outputs: OutputsT) -> MyClass[[InputsT], OutputsT]:
                                                               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/wbuffett/.cache/pypoetry/virtualenvs/graphster-ZGWVPC2x-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 582, in __class_getitem__
    cached = _generics.get_cached_generic_type_early(cls, typevar_values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wbuffett/.cache/pypoetry/virtualenvs/graphster-ZGWVPC2x-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generics.py", line 417, in get_cached_generic_type_early
    return _GENERIC_TYPES_CACHE.get(_early_cache_key(parent, typevar_values))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wbuffett/.pyenv/versions/3.11.2/lib/python3.11/weakref.py", line 198, in get
    wr = self.data[key]
         ~~~~~~~~~^^^^^
TypeError: unhashable type: 'list'
```

### Example Code

```Python
from typing import Callable, Generic, ParamSpec, TypeVar

from pydantic import BaseModel

P = ParamSpec("P")
T = TypeVar("T")

InputsT = TypeVar("InputsT")
OutputsT = TypeVar("OutputsT")


class MyClass(BaseModel, Generic[P, T]):
    func: Callable[P, T]


# This works
def some_func(func: Callable[P, T]) -> MyClass[P, T]:
    return MyClass(func=func)


def my_func(a: int, b: str) -> float:
    return a + float(b)


print(some_func(my_func))


# This fails during runtime
def some_other_func(inputs: InputsT, outputs: OutputsT) -> MyClass[[InputsT], OutputsT]:
    def dynamic_func(inputs: InputsT) -> OutputsT:
        return outputs

    return MyClass(func=dynamic_func)


print(some_other_func(123, "abc"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/wbuffett/.cache/pypoetry/virtualenvs/graphster-ZGWVPC2x-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Apr  5 2023, 10:05:12) [GCC 7.5.0]
                     platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']
```

**Comment by Tishka17** [comment]
Is it a case for pydantic? I gues library is targeting classes storing data with parsing features. `Callables` are not data and cannot be actually _parsed_ or _serialized_.

**Comment by jakemoran** [comment]
Bumping this issue to see if there any plans to add support for `ParamSpec`. My use case is not related to validation of fields but rather define an abstract method on a model with a generic number of arguments. So a simple example would be:

```python
from pydantic import BaseModel
from typing import ParamSpec, Generic, TypeVar

P = ParamSpec("P")
T = TypeVar("T")

class Parent(BaseModel, Generic[P, T]):
    a: int

    def func(self, *args: P.args, **kwargs: P.kwargs) -> T:
        raise NotImplementedError

class ChildA(Parent[[int], int]):
    def func(self, x: int) -> int:
        return x * self.a
    
class ChildB(Parent[[str, str], str]):
    def func(self, x: str, y: str) -> str:
        return (x + y) * self.a
```

Running mypy in strict mode on this code passes, but it fails at runtime due to the same unhashable list error above. `ParamSpec` seems like the only way to do this and keep mypy happy, but I'd also be open to suggestions for getting the same behavior without it (ideally without ignoring override errors on every subclass signature).
