### ISSUE TITLE
Can't see help for RootModel with pydoc or help()

### ISSUE THREAD

**Issue by timj** [pydantic/pydantic#6743]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am unable to see any help for `pydantic.RootModel` or any subclasses or `RootModel`. `help(RootModel)` or `pydoc pydantic.RootModel` both fail with warnings about intantiating BaseModel. 

`pydoc pydantic.BaseModel` works fine (as does pydoc with any subclass of `BaseModel` that is not involving `RootModel`). 

```
 $ pydoc3 pydantic.RootModel
Traceback (most recent call last):
  File "/opt/homebrew/bin/pydoc3", line 5, in <module>
    pydoc.cli()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 2801, in cli
    help.help(arg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 2060, in help
    elif request: doc(request, 'Help on %s:', output=self._output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1784, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1778, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 480, in document
    if inspect.isclass(object): return self.docclass(*args)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1413, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 303, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 685, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 202, in __getattr__
    maybe_mock_validator.force_rebuild()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_mock_validator.py", line 47, in force_rebuild
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: Pydantic models should inherit from BaseModel, BaseModel cannot be instantiated directly

For further information visit https://errors.pydantic.dev/2.0.3/u/base-model-instantiated
```

### Example Code

```Python
>>> from pydantic import RootModel
>>> help(RootModel)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 2002, in __call__
    self.help(request)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 2063, in help
    else: doc(request, 'Help on %s:', output=self._output)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1784, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1778, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 480, in document
    if inspect.isclass(object): return self.docclass(*args)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 1413, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py", line 303, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 685, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 202, in __getattr__
    maybe_mock_validator.force_rebuild()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_mock_validator.py", line 47, in force_rebuild
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: Pydantic models should inherit from BaseModel, BaseModel cannot be instantiated directly

For further information visit https://errors.pydantic.dev/2.0.3/u/base-model-instantiated
```

### Python, Pydantic & OS Version

```Text
$ python3 -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /opt/homebrew/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by timj** [comment]
I must have messed up in my testing because it seems to fail for all subclasses of `BaseModel` and not just `RootModel` and subclasses.

**Comment by hramezani** [comment]
Thanks @timj for reporting this 👍 

I can confirm the problem.

**Comment by hramezani** [comment]
@timj I've created a PR with the help of @dmontagu to fix the problem.

Note: There are some deprecation warnings when calling `help` or using `pydoc` to generate the help because they are accessing all the attributes for generating the doc
