### ISSUE TITLE
PydanticSchemaGenerationError using constr

### ISSUE THREAD

**Issue by Alexndrrr** [pydantic/pydantic#6744]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm working to update my code base to work on v2, and I'm having trouble because constr doesn't seem to be working properly. I'm getting exceptions whenever I create a model with a constr in it, or try to parse something as a constr.

### Example Code

```Python
from pydantic.v1 import constr
from pydantic import TypeAdapter
TypeAdapter(constr(min_length=1)).validate_python("x")


Traceback (most recent call last):
  File "[...]_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 163, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "[...]_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 97, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 165, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
  File "[...]_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 80, in _get_schema
    schema = gen.generate_schema(type_)
  File "[...]_venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 280, in generate_schema
    return self._generate_schema_for_type(
  File "[...]_venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 301, in _generate_schema_for_type
    schema = self._generate_schema(obj)
  File "[...]_venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 586, in _generate_schema
    return self._arbitrary_type_schema(obj, obj)
  File "[...]_venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 638, in _arbitrary_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'pydantic.v1.types.ConstrainedStrValue'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.0.3/u/schema-for-unknown-type
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: [...]/_venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 (main, May 18 2023, 14:15:08) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.6.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by samuelcolvin** [comment]
Import it from `pydantic`, not `pydantic.v1`.

**Comment by Alexndrrr** [comment]
🤦
