### ISSUE TITLE
help function doesn't work on classes inheriting BaseModel

### ISSUE THREAD

**Issue by ZackPlauche** [pydantic/pydantic#6759]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The built-in Python `help` function doesn't work on classes inheriting the BaseModel.

Try it:
```python
from pydantic import BaseModel

class MyModel(BaseModel):
    foo: str
    bar: int

help(MyModel)
```

Error raised:
```
Traceback (most recent call last):
  File "c:\Users\zackp\Desktop\myproject\test2.py", line 8, in <module>
    help(MyModel)
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 2002, in __call__
    self.help(request)
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 2063, in help
    else: doc(request, 'Help on %s:', output=self._output)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 1784, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 1778, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 480, in document
    if inspect.isclass(object): return self.docclass(*args)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 1413, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\pydoc.py", line 303, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 685, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zackp\.virtualenvs\codementorapi-NkYpsXg3\Lib\site-packages\pydantic\_internal\_model_construction.py", line 202, in __getattr__
    maybe_mock_validator.force_rebuild()
  File "C:\Users\zackp\.virtualenvs\codementorapi-NkYpsXg3\Lib\site-packages\pydantic\_internal\_mock_validator.py", line 47, in force_rebuild
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: Pydantic models should inherit from BaseModel, BaseModel cannot be instantiated directly
```

### Example Code

```Python
from pydantic import BaseModel

class MyModel(BaseModel):
    foo: str
    bar: int

help(MyModel)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: C:\Users\zackp\.virtualenvs\codementorapi-NkYpsXg3\Lib\site-packages\pydantic
               python version: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by hramezani** [comment]
Thanks @ZackPlauche for reporting this 🙏 

It got fixed in https://github.com/pydantic/pydantic/commit/bca9bcdebff68d35ba478c7d68b8e1a38c4a8ca0

**Comment by ZackPlauche** [comment]
@hramezani I just tried it again after pip install --upgrade pydantic. Same error :/

**Comment by hramezani** [comment]
It's not released yet. will be available in next release.

**Comment by ZackPlauche** [comment]
Ahhhh gotcha, cool  😎👍
