### ISSUE TITLE
Field of Type[Union[...]] fails in V2

### ISSUE THREAD

**Issue by giacomorebecchi** [pydantic/pydantic#6815]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic V2 no longer supports annotating a field using `Type` before `Union`. A model with the following field:
```python
Type[Union[str, bytes]]
```

Gives the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 174, in __new__
    complete_model_class(
  File "/home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 449, in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(simplified_core_schema, core_config)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
  SchemaError: Error building "model-fields" validator:
  SchemaError: Field "s":
  SchemaError: Error building "is-subclass" validator:
  TypeError: '_UnionGenericAlias' object cannot be converted to 'PyType'
```

### Example Code

```Python
from typing import Type, Union

import pydantic

class MyModel(pydantic.BaseModel):
    s: Type[Union[str, bytes]]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
install path: /home/ubuntu/mambaforge/envs/***/lib/python3.11/site-packages/pydantic
python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by giacomorebecchi** [comment]
For anyone experiencing the bug, a workaround is defining the field using:
```python
Union[Type[str], Type[bytes]]
```

I still created the issue because I guess this is an unexpected breaking change from V1

**Comment by Kludex** [comment]
It's a bug. Thanks for reporting it @giacomorebecchi 🙏 

We need to solve it on `pydantic-core`.
