### ISSUE TITLE
Pydantic V2 fails to compile with auto-py-to-exe

### ISSUE THREAD

**Issue by eccdbbabcdeee** [pydantic/pydantic#6846]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic V2 fails to compile with auto-py-to-exe.

Windows 11
auto-py-to-exe==2.36.0
pydantic==2.0.3
     
Server starting at http://localhost:55474/index.html
16527 ERROR: An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 283, in get_module_attribute
    return _get_module_attribute(module_name, attr_name)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 403, in wrapped
    return call(function, *args, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\isolated\_parent.py", line 302, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to _get_module_attribute() failed with:
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 279, in _get_module_attribute
    return getattr(module, attr_name)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\pydantic\__init__.py", line 207, in __getattr__    
    return _getattr_migration(attr_name)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\pydantic\_migration.py", line 294, in wrapper      
    raise PydanticImportError(f'`{import_path}` has been removed in V2.')
pydantic.errors.PydanticImportError: `pydantic:compiled` has been removed in V2.

For further information visit https://errors.pydantic.dev/2.0.3/u/import-error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package 
    run_pyinstaller()
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build    
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\building\build_main.py", line 979, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\building\build_main.py", line 901, in build
    exec(code, spec_namespace)
  File "C:\Users\windows-user\AppData\Local\Temp\tmpkzzyophx\BLE.spec", line 7, in <module>
    a = Analysis(
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\building\build_main.py", line 414, in __init__
    self.__postinit__()
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\building\build_main.py", line 577, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 269, in add_script
    self._top_script_node = super().add_script(pathname)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 382, in _safe_import_hook
    return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 429, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_modules = self._safe_import_hook(*import_info, **kwargs)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 369, in _safe_import_hook
    excluded_imports = self._find_all_excluded_imports(source_module.identifier)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\analysis.py", line 357, in _find_all_excluded_imports
    excluded_imports.update(module_hook.excludedimports)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 316, in __getattr__
    self._load_hook_module()
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\depend\imphook.py", line 383, in _load_hook_module
    self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\compat.py", line 612, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pydantic.py", line 22, in <module>
    is_compiled = get_module_attribute('pydantic', 'compiled') in {'True', True}
  File "C:\Users\windows-user\PycharmProjects\some-project\venv\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 285, in get_module_attribute
    raise AttributeError(f"Failed to retrieve attribute {attr_name} from module {module_name}") from e
AttributeError: Failed to retrieve attribute compiled from module pydantic

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
install path: C:\Users\eccdb\PycharmProjects\API\v1-BLE-client-Windows\venv\Lib\site-packages\pydantic
python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22621-SP0
optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
This looks like an error with `auto-py-to-exe` not supporting Pydantic V2.

Please read the exception before creating issues.
