### ISSUE TITLE
Private fields on Models rejected with NameError in 2.1.X

### ISSUE THREAD

**Issue by RS-Credentive** [pydantic/pydantic#6876]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I receive a NameError when importing classes with private attributes in Python 2.1.X. The error appeared as soon as I upgraded to 2.1.0 yesterday evening.

```bash
python 
Python 3.11.4 (main, Jun  7 2023, 19:03:45) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from src.oscal_pydantic.core import datatypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/oscal-pydantic/src/oscal_pydantic/core/datatypes.py", line 128, in <module>
    class Date(RootModel[str]):
  File "/home/vscode/.local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 322, in inspect_namespace
    raise NameError(
NameError: Fields must not use names with leading underscores; e.g., use 'date' instead of '_date'.
```

### Example Code

```Python
class Date(RootModel[str]):
    root: str = Field(
        description="A string representing a 24-hour period with optional time zone.",
        pattern="^(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))|(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30)))(Z|[+-][0-9]{2}:[0-9]{2})?$",
    )

    _date: date = Field(
        description="A date.",
    )
    _timezone: timezone | None = Field(
        description="An optional timezone, expressed as an offset from UTC",
        default=None,
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /home/vscode/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 19:03:45) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.31
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
This is intended for now. See https://github.com/pydantic/pydantic/issues/6745 for details.

**Comment by RS-Credentive** [comment]
Okay - please update documentation! I will submit an issue and PR for the docs.

**Comment by Kludex** [comment]
> Okay - please update documentation! I will submit an issue and PR for the docs.

Oh! Sorry for that! Where is it wrong?

But yeah, PR is more than welcome. Thank you so much! 🙏

**Comment by RS-Credentive** [comment]
https://docs.pydantic.dev/latest/usage/models/#private-model-attributes

Not incorrect per se, but the fact that Fields() cannot be used for private attributes is not clear from reading. I will propose something that seems reasonable.

**Comment by Kludex** [comment]
> I will propose something that seems reasonable.

Thanks 🙏

**Comment by RS-Credentive** [comment]
Done! Thanks for your help!
