### ISSUE TITLE
Field shadows an attribute in parent when using `setattr` in `__pydantic_init_subclass__`

### ISSUE THREAD

**Issue by jheddings** [pydantic/pydantic#6966]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using the example code for V1, the script produces the expected result:

```
type='extra' detail='some other detail'
type='advanced' detail='even more details' data='more data'
```

However, when using the V2 code path, the script produces an error:

```
Traceback (most recent call last):
  File "/.../notional/tmp/v2.py", line 33, in <module>
    class Advanced(Extra, type="advanced"):
  File "/.../notional/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/.../notional/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../notional/.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 154, in collect_model_fields
    raise NameError(
NameError: Field name "type" shadows an attribute in parent "Extra"; you might want to use a different field name with "alias='type'".
```

I believe it is related, but a single subclass has similar symptoms, though the results is a validation error rather than a `NameError`  The following occurs when removing the `Advanced` class, even though the value is set during `__pydantic_init_subclass__`:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Extra
type
  Field required [type=missing, input_value={'detail': 'some other detail'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1/v/missing
```

The issue appears to be using `setattr(...)` in the `__pydantic_init_subclass__` method.

### Example Code

```Python
#!/usr/bin/env python3

from typing import Optional

USE_PYDANTIC_V2 = False

if USE_PYDANTIC_V2:
    from pydantic import BaseModel
else:
    from pydantic.v1 import BaseModel

class Common(BaseModel):
    type: str

    def __init_subclass__(cls, type=None, **kwargs):
        super().__init_subclass__(**kwargs)

        if USE_PYDANTIC_V2 is False:
            setattr(cls, "type", type)
            field = cls.__fields__.get("type")
            field.default = type
            field.required = False

    @classmethod
    def __pydantic_init_subclass__(cls, type=None):
        setattr(cls, "type", type)
        field = cls.model_fields.get("type")
        field.default = type

class Extra(Common, type="extra"):
    detail: Optional[str] = None

class Advanced(Extra, type="advanced"):
    data: str

if __name__ == "__main__":
    one = Extra(
        detail="some other detail"
    )

    two = Advanced(
        data="more data",
        detail="even more details"
    )

    print(one)
    print(two)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: .venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by jheddings** [comment]
After a bit more digging, I'm able to resolve the issue by rebuilding the model whenever `FieldInfo` changes:

```
    @classmethod
    def __pydantic_init_subclass__(cls, type=None):
        field = cls.model_fields.get("type")
        field.default = type
        field.validate_default = True

        cls.model_rebuild(force=True)
```

Is this the expected / correct way to handle things?

**Comment by dmontagu** [comment]
@jheddings I think the way you've done things there is probably the best way to do it.

If you are concerned about this approach breaking in the future, feel free to submit a PR adding a test that ensures your approach to changing the field definition in `__pydantic_init_subclass__` works as expected, at least in that case we won't accidentally break it with other changes in the future.

**Comment by jheddings** [comment]
Thanks for the confirmation!  I'll spend a bit more time at it and see if there is a reasonable test for this.

**Comment by mauro-andre** [comment]
Hi @jheddings, I got the sabe over here. Any updated?

**Comment by mauro-andre** [comment]
@jheddings @dmontagu please help with this error
```
from pydantic import BaseModel


class MainModel(BaseModel):
    attr_main: str
    
    @classmethod
    def __pydantic_init_subclass__(cls):
        for key in cls.model_fields.keys():
            setattr(cls, key, 'NEW VALUE')
            

class One(MainModel):
    attr_one: str
    
    
class Two(One):
    attr_one: str
```
    
error
```
Traceback (most recent call last):
  File "/Users/mauro/dev-projects/pyodmongo/test.py", line 18, in <module>
    class Two(One):
  File "/Users/mauro/dev-projects/pyodmongo/venv_v2/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/Users/mauro/dev-projects/pyodmongo/venv_v2/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mauro/dev-projects/pyodmongo/venv_v2/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 154, in collect_model_fields
    raise NameError(
NameError: Field name "attr_main" shadows an attribute in parent "One"; you might want to use a different field name with "alias='attr_main'".
```

**Comment by jheddings** [comment]
Using `setattr` on the _class_ causes trouble for Pydantic when it builds the model schema.

Are you attempting to update the default value for the field in the class or set it at runtime on an object?

**Comment by mauro-andre** [comment]
@jheddings 
I'm actually trying to dynamically create class variables that have the same name as the attributes.
This technique worked in pydantic V1, so when I set ```setattr(cls, key, 'NEW VALUE')``` in ```__init_subclass__``` I had the following class variable:
```
print(Two.attr_two)
>> NEW VALUE
```

**Comment by jheddings** [comment]
Interesting use case...  I don't know enough about the Pydantic internals to say _why_ it's a problem, but it definitely raises an error when there is a duplicate attribute name in both the class and object.

In my case, I was simply trying to change the default value of a field.  Can you say a bit more about your use case for having the attribute present in the class?  That might help with some workaround suggestions.
