### ISSUE TITLE
Allow inheriting `dataclasses.dataclass` with defaults

### ISSUE THREAD

**Issue by tobni** [pydantic/pydantic#6984]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently, inheriting a pure dataclass to a subclass that is also a `BaseModel` works. This is great, and this feature has been used extensively in v1 in a code base i maintain. v2 seems to have the added feature of not requiring to re-declare the fields, which is awesome.

However, if the dataclass defines a default for a field, it crashes with a `NameError`

```console
Traceback (most recent call last):
...
  File "<input>", line 19, in <module>
  File ".../lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 172, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File ".../lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 400, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File ".../lib/python3.10/site-packages/pydantic/_internal/_fields.py", line 155, in collect_model_fields
    raise NameError(
NameError: Field name "a" shadows an attribute in parent "A"; you might want to use a different field name with "alias='a'".
```

### Example Code

```Python
import pydantic

from dataclasses import dataclass

import pydantic


@dataclass
class A:
    a: None

class B(pydantic.BaseModel, A): # Ok
    pass


@dataclass
class A:
    a: None = None
    

class B(pydantic.BaseModel, A): # Not ok
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: .../lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Mar  3 2022, 12:03:29) [GCC 9.3.0]
                     platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment]
@tobni thank you for the bug report.

I can confirm that the issue reproduces in Pydantic v2.1.1.
