### ISSUE TITLE
`pydantic.mypy` plugin error using `pydantic_settings` `SettingsConfigDict`

### ISSUE THREAD

**Issue by tomtom103** [pydantic/pydantic#6985]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`pydantic` mypy crashes when providing a `model_config` `SettingsConfigDict` within the `BaseSettings` class. `mypy` continues to crash even after commenting out the `model_config` until the virtual environment is rebuilt.

Traceback:
```bash
$ mypy test.py --show-traceback
test.py:3: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.4.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6451, in accept
  File "mypy/nodes.py", line 1139, in accept
  File "mypy/semanal.py", line 1582, in visit_class_def
  File "mypy/semanal.py", line 1667, in analyze_class
  File "mypy/semanal.py", line 1694, in analyze_class_body_common
  File "mypy/semanal.py", line 1777, in apply_class_plugin_hooks
  File "[redacted]/.venv/lib64/python3.8/site-packages/pydantic/mypy.py", line 182, in _pydantic_model_class_maker_callback
    return transformer.transform()
  File "[redacted]/.venv/lib64/python3.8/site-packages/pydantic/mypy.py", line 443, in transform
    self.add_initializer(fields, config, is_settings)
  File "[redacted]/.venv/lib64/python3.8/site-packages/pydantic/mypy.py", line 804, in add_initializer
    base_settings_init_arguments = base_settings_info.names['__init__'].node.arguments
AttributeError: attribute 'names' of 'TypeInfo' undefined
test.py:3: : note: use --pdb to drop into pdb
```

When running the command with `pdb` to print the `base_settings_info` we get the following:
```
-> base_settings_init_arguments = base_settings_info.names['__init__'].node.arguments
(Pdb) base_settings_info
*** AttributeError: attribute '_fullname' of 'TypeInfo' undefined
```

Requirements to reproduce:
```
annotated-types==0.5.0
mypy==1.4.1
mypy-extensions==1.0.0
pydantic==2.1.1
pydantic-core==2.4.0
pydantic-settings==2.0.2
python-dotenv==1.0.0
tomli==2.0.1
typing-extensions==4.7.1
```

mypy config:
```
[tool.mypy]
files = ["api", "tests"]

plugins = [
    "pydantic.mypy"
]
strict = true
```

### Example Code

```Python
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    API_HOST: str = "0.0.0.0"

    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8"
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: [REDACTED]/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Oct 27 2020, 09:13:12)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
                     platform: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by hramezani** [comment]
I've tried your provided code but didn't get the mypy error you've reported.

maybe it's something related to your environment

**Comment by JeanArhancet** [comment]
Hello 👋 ,

 I have the same issue on my project with mypy and 
```
"pydantic[email]==2.1.1",
 "pydantic-settings==2.0.2"
```
on Python 3.11.4.

The first time I run myapp it works fine but when I relaunch several times the error appears:

```
` base_settings_init_arguments = base_settings_info.names['__init__'].node.arguments
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: attribute 'names' of 'TypeInfo' undefined
`
```

**Comment by tomtom103** [comment]
It also happens when I restart it multiple times (usually when there’s a modification to the file from what I’ve noticed)

**Comment by hramezani** [comment]
@JeanArhancet Thanks for replying and creating the PR.

But I still couldn't reproduce the problem with

```
annotated-types==0.5.0
dnspython==2.4.1
email-validator==2.0.0.post2
idna==3.4
mypy==1.4.1
mypy-extensions==1.0.0
pydantic==2.1.1
pydantic-settings==2.0.2
pydantic_core==2.4.0
python-dotenv==1.0.0
tomli==2.0.1
typing_extensions==4.7.1
```

@dmontagu Do you have any idea here?

**Comment by JeanArhancet** [comment]
@hramezani In my PR I also reproduced the issue by adding additional test (https://github.com/pydantic/pydantic/pull/7002/files#diff-a3996a50e4d75365ab9f9aa132a8e25d8f5fa445d9cb10d215b6e31f08d24606R13-R21) 
If you run this tests, do you get an error?

**Comment by ijohn** [comment]
I can confirm that I am hit by this bug also and @JeanArhancet's PR fix it

**Comment by tomtom103** [comment]
Thank you @JeanArhancet for the changes. Much appreciated
