### ISSUE TITLE
regex cannot work from v1 in v2 in fields

### ISSUE THREAD

**Issue by Tamerlan-hash** [pydantic/pydantic#7058]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

i just renamed regex to pattern and i thought it would be work like in v1

```
..\.venv\lib\site-packages\pydantic\_internal\_model_construction.py:173: in __new__
    complete_model_class(
..\.venv\lib\site-packages\pydantic\_internal\_model_construction.py:481: in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(simplified_core_schema, core_config)
E   pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
E     SchemaError: Error building "model-fields" validator:
E     SchemaError: Field "new_password":
E     SchemaError: Error building "str" validator:
E     SchemaError: regex parse error:
E       ^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$
E        ^^^
E   error: look-around, including look-ahead and look-behind, is not supported
```

### Example Code

```Python
from datetime import date

from pydantic import BaseModel, EmailStr
from pydantic.fields import Field


class VerifyCodeByEmailRequest(BaseModel):
    email: EmailStr
    code: str = Field(pattern=r'^[0-9]{4}$')

    class Config:
        anystr_strip_whitespace = True


class RegisterByEmailRequest(VerifyCodeByEmailRequest):
    password: str = Field(pattern="^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$")
    fullname: str | None = None
    username: str
    phone_number: str | None = Field(pattern=r'^\+[0-9]{11}$')
    birth_date: date
    scope: str

    class Config:
        anystr_strip_whitespace = True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core build: profile=release pgo=false mimalloc=true
python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
platform: Windows-10-10.0.22000-SP0
optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by CrowMEV** [comment]
Hello. I have same issue as @Tamerlan-hash .
I try check password:
```py
hashed_password: str = Field(
        ...,
        alias="password",
        min_length=8,
        pattern=r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^\w\s]|.*[_]).",
    )
```
and get this message
```
E   pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
E     SchemaError: Error building "model-fields" validator:
E     SchemaError: Field "hashed_password":
E     SchemaError: Error building "str" validator:
E     SchemaError: regex parse error:
E       ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^\w\s]|.*[_]).
E        ^^^
E   error: look-around, including look-ahead and look-behind, is not supported
```
I don't know how rewrite this pattern to Rust style

**Comment by mrburrito** [comment]
I just ran into this problem with models generated from a pre-existing JSONSchema document. That document defines a regex for a valid S3 Bucket Name as `^(?!xn--.*|.*--ol-s3$)[a-zA-Z0-9][-a-zA-Z0-9]+[a-zA-Z0-9]$`. `jsonschema` validates instances successfully and the datamodel generator ran without issue. It's only when I try to import my data models that I get the error about validating the regex. I'd very much like to use generated models to interact with schema objects instead of writing them by hand or just using `nested["dict"]["access"]["patterns"]`, but this could be a deal breaker -- particularly for schema I don't have control over.

Given that this is a Python library, I'm not sure why you're locking users to Rust's regex implementation -- which leaves out a significant number of capabilities developers in Python, JavaScript, and others have come to expect. At worst, log a warning message that the schema can't be fully validated, but ideally, any regex supported by Python should be supported. That's my expectation when I bring in a Python dependency that works with regular expressions.

**Comment by brian-goo** [comment]
I tried to get my field validated with field_validator and it looks like it works.
hope that the above PR would fix this issue.

```python
class Foo(BaseModel):
    pw: str = Field(min_length=8)

    @field_validator("pw")
    @classmethod
    def regex_match(cls, p: str) -> str:
        re_for_pw: re.Pattern[str] = re.compile(r"your regex")
        if not re_for_pw.match(p):
            raise ValueError("invalid password")
        return p
```

**Comment by sydney-runkle** [comment]
I think this can be closed by the ^^ above merged PR, once we add a migration guide update and check that the docs update was thorough! I'll handle this tmrw 👍

**Comment by nocturn9x** [comment]
I have a piece of code that looks like this:
```py
    return create_model(
        __model_name=model_name,
        __config__=None,
        __base__=(PartialModelMixin, BaseModel),
        __module__="...",
        __validators__=None,
        __cls_kwargs__=None,
        **fields,
    )
```

How can I enable the Python regex engine here? Adding `__config__=ConfigDict(regex_engine="python-re")` does absolutely nothing (and it also requires me to stop using the `__base__` field, which I can't do because it's necessary for my application. Why is it not allowed to use `create_model` with both? I understand the potential for confusion, but at least give me a switch to turn that off? Sometimes there's get off the beaten track you know :))

**Comment by sydney-runkle** [comment]
Hi @nocturn9x,

You'll have to wait for Pydanic v2.5, which should be coming out this week 😄

**Comment by nocturn9x** [comment]
Heh, that makes sense. Many thanks for the swift response :)

**Comment by Kilo59** [comment]
@sydney-runkle 

I still seem to be experiencing this problem on pydantic `2.7.1`

```
pydantic                  2.7.1
pydantic_core             2.18.2
```


```python
import re
from typing import Annotated, Final

from pydantic import Field, TypeAdapter

TEMPLATE_STR_REGEX: Final[re.Pattern] = re.compile(
    r"(?<!\\)\$\{(.*?)\}|(?<!\\)\$([_a-zA-Z][_a-zA-Z0-9]*)"
)

ConfigStr = Annotated[str, Field(..., pattern=TEMPLATE_STR_REGEX)]

ConfigStrTA = TypeAdapter(ConfigStr) # <- failure happens here

print(ConfigStrTA.validate_python("hello ${NAME}"))
```
```
Traceback (most recent call last):
  File "/Users/gabriel/dev/mercury/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 217, in __init__
    validator = _getattr_no_parents(type, '__pydantic_validator__')
  File "/Users/gabriel/dev/mercury/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_validator__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabriel/dev/mercury/v2_types.py", line 12, in <module>
    ConfigStrTA = TypeAdapter(ConfigStr)
  File "/Users/gabriel/dev/mercury/.venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 222, in __init__
    validator = create_schema_validator(
  File "/Users/gabriel/dev/mercury/.venv/lib/python3.10/site-packages/pydantic/plugin/_schema_validator.py", line 49, in create_schema_validator
    return SchemaValidator(schema, config)
pydantic_core._pydantic_core.SchemaError: Error building "str" validator:
  SchemaError: regex parse error:
    (?<!\\)\$\{(.*?)\}|(?<!\\)\$([_a-zA-Z][_a-zA-Z0-9]*)
    ^^^^
error: look-around, including look-ahead and look-behind, is not supported
```

**Comment by sydney-runkle** [comment]
Hi @Kilo59,

You can resolve this by using the `regex_engine='python-re'` config setting:

```py
import re
from typing import Annotated, Final

import regex

from pydantic import Field, TypeAdapter, ConfigDict

TEMPLATE_STR_REGEX: Final[re.Pattern] = re.compile(
    r"(?<!\\)\$\{(.*?)\}|(?<!\\)\$([_a-zA-Z][_a-zA-Z0-9]*)"
)

ConfigStr = Annotated[str, Field(..., pattern=TEMPLATE_STR_REGEX)]

ConfigStrTA = TypeAdapter(ConfigStr, config=ConfigDict(regex_engine='python-re')) # <- success with regex_engine='python-re'

print(ConfigStrTA.validate_python("hello ${NAME}"))
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for constrained-str
  String should match pattern '(?<!\\)\$\{(.*?)\}|(?<!\\)\$([_a-zA-Z][_a-zA-Z0-9]*)' [type=string_pattern_mismatch, input_value='hello ${NAME}', input_type=str]
"""
```
