### ISSUE TITLE
Mypy plugin crashes for pydantic-settings

### ISSUE THREAD

**Issue by bunny-therapist** [pydantic/pydantic#7066]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Minimal example (I am using python 3.9):

One python file, settings.py:
```
import pydantic_settings


class Settings(pydantic_settings.BaseSettings):
    ...
```
and one mypy.ini:
```
[mypy]
plugins = pydantic.mypy
```

Run:
```
pip install pydantic-settings==2.0.2 mypy==1.4.1 pydantic==2.1.1
mypy settings.py
```
That should work fine. However, then edit settings.py in any way, e.g., add a newline (problem seems related to cache somehow; if you delete .mypy_cache, the problem will not appear) and run mypy again:
```
mypy settings.py
```
I then get an internal error. If run mypy with `--show-traceback`, I get
```
settings.py:4: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.4.1
Traceback (most recent call last):
  File "mypy/semanal.py", line 6451, in accept
  File "mypy/nodes.py", line 1139, in accept
  File "mypy/semanal.py", line 1582, in visit_class_def
  File "mypy/semanal.py", line 1667, in analyze_class
  File "mypy/semanal.py", line 1694, in analyze_class_body_common
  File "mypy/semanal.py", line 1777, in apply_class_plugin_hooks
  File "/home/avikstroem/PycharmProjects/mypyBug/venv/lib/python3.9/site-packages/pydantic/mypy.py", line 182, in _pydantic_model_class_maker_callback
    return transformer.transform()
  File "/home/avikstroem/PycharmProjects/mypyBug/venv/lib/python3.9/site-packages/pydantic/mypy.py", line 443, in transform
    self.add_initializer(fields, config, is_settings)
  File "/home/avikstroem/PycharmProjects/mypyBug/venv/lib/python3.9/site-packages/pydantic/mypy.py", line 804, in add_initializer
    base_settings_init_arguments = base_settings_info.names['__init__'].node.arguments
AttributeError: attribute 'names' of 'TypeInfo' undefined
settings.py:4: : note: use --pdb to drop into pdb

```
I am reporting it here since the error seems to come from the mypy pydantic plugin, which I believe is hosted by this project.

I left my Settings class empty to make it a minimal example. Adding fields to it does not change anything.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/avikstroem/PycharmProjects/mypyBug/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun  6 2023, 20:11:21)  [GCC 11.3.0]
                     platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by bunny-therapist** [comment]
Problem appears to have been introduced in 2.1.0 (it is not seen in 2.0.3, but it is seen in 2.1.0).

**Comment by hramezani** [comment]
It's got fixed in https://github.com/pydantic/pydantic/commit/de851548e9588f79c27818a7ac5bc1f3bb6d5b09

and will be released in next release.
