### ISSUE TITLE
Error with only having model_validator mode = "before"

### ISSUE THREAD

**Issue by ecs-jnguyen** [pydantic/pydantic#7092]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello when I run the example code I am getting the following error. However if I add a `@model_validator(mode='after')` decorator it doesn't fail.

```
➜  python example.py                                                          
model_validation_before
Traceback (most recent call last):
  File "/private/var/folders/15/707dwz3155x6cp85ps63qrnh0000gs/T/tmp.QNTkHjBM/example.py", line 14, in <module>
    p = Person(name="Bob")
        ^^^^^^^^^^^^^^^^^^
  File "/private/var/folders/15/707dwz3155x6cp85ps63qrnh0000gs/T/tmp.QNTkHjBM/.venv/lib/python3.11/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Person
  Input should be a valid dictionary or instance of Person [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.1/v/model_type
```

### Example Code

```Python
from pydantic import BaseModel, model_validator


class Person(BaseModel):
    name: str

    @model_validator(mode='before')
    @classmethod
    def model_validation_before(cls, data):
        print("model_validation_before")


if __name__ == "__main__":
    p = Person(name="Bob")
    print(p)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /private/var/folders/15/707dwz3155x6cp85ps63qrnh0000gs/T/tmp.QNTkHjBM/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Aug  9 2023, 15:20:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by TylerGrantSmith** [comment]
Your "before" validator isn't returning anything.

**Comment by Kludex** [comment]
Yeah, as @TylerGrantSmith said, since your "before" validator is returning `None` (implicitly), then there's a validation error.

In the case of "after", it doesn't raise because "after" validators run _after_ the _type validators_ (it runs after checking that "name" is a `str`), so it's also normal it doesn't raise.

You can read more about the validators on the [Before, After, Wrap and Plain validators](https://docs.pydantic.dev/latest/usage/validators/#before-after-wrap-and-plain-validators) section on our documentation.
