### ISSUE TITLE
Unable to use required __init_subclass__ parameters with a generic model

### ISSUE THREAD

**Issue by object-Object** [pydantic/pydantic#7171]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following error occurs when subclassing a generic model which has an `__init_subclass__` method with required arguments. I assume this is because `Model[str]` creates a subclass of `Model`, which calls `__init_subclass__`, but without any custom arguments.

```
Traceback (most recent call last):
  File "c:\Users\redacted\Git\HexMod\doc\test.py", line 15, in <module>
    class SubModel(Model[str], foo="bar"):
                   ~~~~~^^^^^
  File "C:\Users\redacted\Git\HexMod\doc\venv\Lib\site-packages\pydantic\main.py", line 652, in __class_getitem__
    submodel = _generics.create_generic_submodel(model_name, origin, args, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\redacted\Git\HexMod\doc\venv\Lib\site-packages\pydantic\_internal\_generics.py", line 142, in create_generic_submodel
    created_model = meta(
                    ^^^^^
  File "C:\Users\redacted\Git\HexMod\doc\venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 123, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
TypeError: Model.__init_subclass__() missing 1 required positional argument: 'foo'
```

If the generics are removed from the below code, the last line prints `bar` as expected.

My actual use case is a custom tagged union system with the registry pattern, where creating a subclass of the base type adds that subclass to a lookup table (Pydantic's tagged unions weren't flexible enough for my purposes). It might be possible to eg. default to None and raise if the class is actually instantiated, but I'd prefer to keep the current behaviour where Pyright raises a type error if the parameter is omitted.

### Example Code

```Python
from typing import ClassVar, Generic, TypeVar
from pydantic import BaseModel

T = TypeVar("T")

class Model(BaseModel, Generic[T]):
    foo: ClassVar[str]

    def __init_subclass__(cls, foo: str):
        cls.foo = foo

class SubModel(Model[str], foo="bar"):
    pass

print(SubModel.foo) # should print "bar"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.0
        pydantic-core version: 2.6.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: C:\Users\redacted\Git\HexMod\doc\venv\Lib\site-packages\pydantic
               python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment]
@object-Object Thank you for reporting this! I'm able to reproduce the issue.

**Comment by lig** [comment]
This happens because Pydantic creates a real subclass for `Model[str]` which Python itself doesn't.

So, essentially the following code

```py
    class SubModel(Model[str], init_subclass_arg='a value'):
        pass
```

is a rough equivalent to

```py
    class StrModel(Model[str]):
        pass

    class SubModel(StrModel, init_subclass_arg='a value'):
        pass
```

and as there is no `init_subclass_arg` for `StrModel` the corresponding call to `__init_subclass__` will raise the exception.

**Comment by lig** [comment]
There is a workaround. Providing a default value for `init_subclass_arg` avoids teh exception.

Here is a failing test that reproduces this issue

```py
def test_init_subclass_args():
    T = TypeVar('T')

    class Model(BaseModel, Generic[T]):
        class_attr: ClassVar[str]

        def __init_subclass__(cls, init_subclass_arg: str):
            cls.class_attr = init_subclass_arg

    class SubModel(Model[str], init_subclass_arg='a value'):
        pass

    assert SubModel.class_attr == 'a value'
```

and a passing test that uses the workaround

```py
def test_init_subclass_args():
    T = TypeVar('T')

    class Model(BaseModel, Generic[T]):
        class_attr: ClassVar[str]

        def __init_subclass__(cls, init_subclass_arg: Optional[str] = None):
            if init_subclass_arg is None:
                return
            cls.class_attr = init_subclass_arg

    class SubModel(Model[str], init_subclass_arg='a value'):
        pass

    assert SubModel.class_attr == 'a value'

```

**Comment by alexmojaki** [comment]
It looks impossible to solve this without changing behaviour asserted by current tests. For example, this test:

```python
def test_generic_subclass():
    T = TypeVar('T')

    class A(BaseModel, Generic[T]):
        ...

    class B(A[T], Generic[T]):
        ...

    assert B[int].__name__ == 'B[int]'
    assert issubclass(B[int], B)
```

would fail at the last line with `TypeError: issubclass() arg 1 must be a class`. That's what happens when you use Python's generics:

```python
from typing import Generic, TypeVar

T = TypeVar("T")

class Model(Generic[T]):
    pass

print(issubclass(Model[str], Model))  # TypeError
```

because as @lig says, Python doesn't create a real subclass. `Model[str]` in this case is not a class, but an instance of `_GenericAlias` (which itself is not a metaclass).

So I'm guessing this should be closed.

**Comment by object-Object** [comment]
I ended up working around this issue by just removing the generic type parameter from the class, but here are several ideas for *possible* solutions, roughly from least to most complexity and breakage risk:

* Do nothing, close the issue, and ideally mention this restriction in the [generic model docs](https://docs.pydantic.dev/latest/usage/models/#generic-models).
* If it doesn't already exist, add a way to tell if `__init_subclass__` and `__init_pydantic_subclass__` are being called to create a 'real' subclass or a generic submodel. We'd still need to provide default values, but we could eg. add a runtime check to only require an argument if it's not a generic submodel.
* Add another dunder method (eg. `__init_real_pydantic_subclass__`) similar to `__init_pydantic_subclass__`, but which is not called when initializing generic submodels.
* Add a classmethod (eg. `model_subscript`) to create a generic submodel, and forward any extra kwargs to `__init_subclass__` and `__init_pydantic_subclass__`.
  * For example: `class SubModel(Model.model_subscript(str, init_subclass_arg=None), init_subclass_arg="a value"): ...`
* Add a parameter `kwargs: dict[str, Any]` to `__class_getitem__` which could be used to pass args to `__init_subclass__` and `__init_pydantic_subclass__`.
  * For example: `class SubModel(Model[str, dict(init_subclass_arg=None)], init_subclass_arg="a value"): ...`
  * The PEP for [indexing with keyword arguments](https://peps.python.org/pep-0637/) was rejected, so it needs to be a dict argument instead of keyword args.
* Call `super().__init_subclass__` and `__super().__init_pydantic_subclass__` instead, and pass the same arguments as were passed to the generic class when it was created.
* Prevent `__init_subclass__` and/or `__init_pydantic_subclass__` from being called when creating a generic submodel.

**Comment by Viicos** [comment]
Tracking in https://github.com/pydantic/pydantic/issues/6024.
