### ISSUE TITLE
pydantic v2.3.0 __post_init__ not called

### ISSUE THREAD

**Issue by shkgme** [pydantic/pydantic#7255]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It looks like __post_init__ is not called at all.

Output:
`name='pydantic v2.3.0 __post_init__ not called'`

Expected output: 
```
print
name=SarahConor
Traceback (most recent call last):
  File "C:\...\python\...\bug.py", line 13, in <module>
    print(bug.__post_init__())
  File "C:\...\python\...\bug.py", line 9, in __post_init__
    raise Exception(f"exception")  # Never raised
Exception: exception
```

### Example Code

```Python
import pydantic
from pydantic import BaseModel
class Bug(BaseModel):
    name: str = f"pydantic v{pydantic.version.VERSION} __post_init__ not called"
    def __post_init__(self):
        print(f"print")  # Never printed
        self.name = "SarahConor"  # Never applied
        print(f"{self.name}")  # Never printed
        raise Exception(f"exception")  # Never raised
bug = Bug()
print(bug)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=false
install path: C:\...\python\...\venv\Lib\site-packages\pydantic
python version: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by Viicos** [comment]
`__post_init__` is specific to stdlib dataclasses. Instead, you can override the `model_post_init` method of `BaseModel`.
