### ISSUE TITLE
[regression] v2 handling of generic duck-typed fields incompatible with MyPy `disallow_any_generics` option

### ISSUE THREAD

**Issue by mjog** [pydantic/pydantic#7279]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm in the process of upgrading a project to use Pydantic v2 and have run into an issue with v2's implementation of duck typing (using `SerializeAsAny`) values for for fields annotated with generic types.

To avoid raising a `ValidationError`, Pydantic requires the generic type to not have any type parameter specified, but this conflicts with the project's strict approach type annotations, which is enforced using by enabling mypy's [disallow_any_generics](https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_any_generics`) option:

This works in Pydantic v1 and passes MyPy with `disallow_any_generics`:
```
    field: GenericBase[typing.Any]
```

This fails in Pydantic v2 but passes MyPy with `disallow_any_generics`:
```
    field: pydantic.SerializeAsAny[GenericBase[typing.Any]]
```

This works in Pydantic v2, but fails in MyPy with `disallow_any_generics`:

```
    field: pydantic.SerializeAsAny[GenericBase]
```

Of course, this project has a large number such fields.

Executing the minimal example below and running mypy over it gives, respectively:

```
mjog@sable:~/test$ poetry run python3 test-generics.py
{"field":{"attr_base":"test","attr_a":"extra"}}
Traceback (most recent call last):
  File "/home/mjog/test/test-generics.py", line 39, in <module>
    print(RootModel2(
          ^^^^^^^^^^^
  File "/home/mjog/.cache/pypoetry/virtualenvs/test-BvS4MufV-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for RootModel2
field
  Input should be a valid dictionary or instance of GenericBase[Any] [type=model_type, input_value=DerivedA(attr_base='test', attr_a='extra'), input_type=DerivedA]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
mjog@sable:~/test$ poetry run mypy --disallow-any-generics test-generics.py
test-generics.py:23: error: Missing type parameters for generic type "GenericBase"  [type-arg]
Found 1 error in 1 file (checked 1 source file)
```

I expect the MyPy error to occur, I don't expect the Pydantic error to occur.

Note that using a union instead of Any as the type parameter works fine, but I expect Any to work in the same way as not specifying any arguments, and unfortunately I can't use a union in this context since the list of possible subclasses is not known.

### Example Code

```Python
import typing
import pydantic

T = typing.TypeVar('T')
class GenericBase(pydantic.BaseModel, typing.Generic[T]):

    attr_base: T

class DerivedA(GenericBase[str]):

    attr_a: str

class DerivedB(GenericBase[int]):

    attr_b: int


class RootModel1(pydantic.BaseModel):

    # Fails mypy check with disallow_any_generics
    # error: Missing type parameters for generic type "GenericBase"  [type-arg]
    field: pydantic.SerializeAsAny[GenericBase]

class RootModel2(pydantic.BaseModel):

    field: pydantic.SerializeAsAny[GenericBase[typing.Any]]


if __name__ == '__main__':
    # Works fine
    print(RootModel1(
        field = DerivedA(attr_base = 'test', attr_a = 'extra')
    ).model_dump_json())

    # Fails
    # pydantic_core._pydantic_core.ValidationError: 1 validation error for RootModel2
    # field
    #   Input should be a valid dictionary or instance of GenericBase[Any] [type=model_type, input_value=DerivedA(attr_base='test', attr_a='extra'), input_type=SubModelDerivedA]
    print(RootModel2(
        field = DerivedA(attr_base = 'test', attr_a = 'extra')
    ).model_dump_json())
```

### Python, Pydantic & OS Version

```Text
mjog@sable:~$ poetry run python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/mjog/.cache/pypoetry/virtualenvs/mechanistic-BvS4MufV-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
                     platform: Linux-6.2.0-27-generic-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

**Comment by lig** [comment]
@mjog Thank you for the report.

I've managed to get rid of the Pydantic error changing the order of bases in the generic model. This is a known behavior, see https://github.com/pydantic/pydantic/issues/6994#issuecomment-1700411835 for more.

The following test passes on Pydantic 2.3.0

```py
def test_7279():
    import typing

    import pydantic

    T = typing.TypeVar('T')

    class GenericBase(typing.Generic[T], pydantic.BaseModel):
        attr_base: T

    class DerivedA(GenericBase[str]):
        attr_a: str

    class Model1(pydantic.BaseModel):
        field: pydantic.SerializeAsAny[GenericBase]

    class Model2(pydantic.BaseModel):
        field: pydantic.SerializeAsAny[GenericBase[typing.Any]]

    assert Model1(field=DerivedA(attr_base='test', attr_a='extra')).model_dump() == {
        'field': {'attr_a': 'extra', 'attr_base': 'test'}
    }

    assert Model2(field=DerivedA(attr_base='test', attr_a='extra')).model_dump() == {
        'field': {'attr_a': 'extra', 'attr_base': 'test'}
    }
```

**Comment by mjog** [comment]
Thanks for the heads up, but tbh I'd rather go with a `# type: ignore[type-arg]` workaround since a)  the codebases where this is a problem for me all as a convention have placed the generic base last (as in the example above), b) and it's not at all obvious that the ordering of the bases is important when reading or writing impacted code. At least the type comment points out the issue, and I have to change that line anyway to add `SerializeAsAny` in everywhere.

If Pydantic is going to require a specific ordering of a mode's base classes, that needs to be spelled out quote clearly in the docs, because it would be quite surprising. However it would be great to see a proper fix for this so that a specific base class ordering isn't actually necessary.
