### ISSUE TITLE
Models with `datetime.date` field throw RecursionError on definition with `Field`

### ISSUE THREAD

**Issue by sneakers-the-rat** [pydantic/pydantic#7309]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Models with a `date` field cause a `RecursionError` when defined (not instantiated), example below.

The traceback that is emitted starts with:

```
Traceback (most recent call last):
  File "pydantic.py", line 5, in <module>
    class MyModel(BaseModel):
  File "pydantic/_internal/_model_construction.py", line 179, in __new__
    complete_model_class(
  File "pydantic/_internal/_model_construction.py", line 469, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 693, in _generate_schema
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 523, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 523, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 859, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 911, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 1616, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 1580, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 698, in _generate_schema
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 785, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_generate_schema.py", line 379, in _unknown_type_schema
    f'Unable to generate pydantic-core schema for {obj!r}. '
```

And then the looping part seems to be:

```
  File "pydantic/_internal/_repr.py", line 82, in __repr__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/fields.py", line 549, in __repr_args__
    yield 'annotation', _repr.PlainRepr(_repr.display_as_type(self.annotation))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/_internal/_repr.py", line 95, in display_as_type
    return repr(obj)
           ^^^^^^^^^
```

Oddly, when I try and open pdb before the looping part, the recursion error has already been thrown, eg here: https://github.com/pydantic/pydantic/blob/c987bc6398b898d5c9e49606e3acb17b732359e8/pydantic/_internal/_model_construction.py#L405

`class_vars` is returned with the RecursionError as the value for the 'date' key. 

I can't quite get to the bottom of what is happening rn, but this happens with a fresh install and the MWE below, so I don't think it's just me. 

This also seems important - it only happens when it has an explicit `Field` class assigned to it. It doesn't seem to matter what is in the `Field` - all these cause the error

- `date: date = Field()`
- `date: date = Field(default_factory=date.today)`
- `date: Optional[date] = Field(None)`

### Example Code

```Python
from datetime import date
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    date: date = Field()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jonny/Library/Caches/pypoetry/virtualenvs/nwb-schema-language-mgVsfMW0-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  6 2023, 17:36:45) [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-12.6.8-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by hramezani** [comment]
Thanks @sneakers-the-rat for reporting this issue 🙏 
Thanks @Viicos for the reply.
