### ISSUE TITLE
Timedelta as numeric string unparseable?

### ISSUE THREAD

**Issue by AlphaGit** [pydantic/pydantic#7357]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! I've upgraded my FastAPI application to use pydantic 2, and I love how strict it is in some aspects, allowing me to find so many inconsistencies in my code I wasn't even aware of.

Straight to the point: I'm having an issue with numeric query strings that Pydantic cannot parse into timedelta objects.

I believe it is because pydantic does not parse numeric timedelta strings at all, so the query string always makes it into a string.

### Example Code

```Python
from pydantic import BaseModel

class MyClass(BaseModel):
    t: timedelta

# SUCCESS: Expected: t=100 seconds
MyClass.model_validate({'t': 100})
# > MyClass(t=datetime.timedelta(seconds=100))

# FAIL: Expected: t=100 seconds
MyClass.model_validate({'t': '100'})
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/Users/jd/Projects/[REDACTED]/.venv/lib/python3.9/site-packages/pydantic/main.py", line 504, in model_validate
#     return cls.__pydantic_validator__.validate_python(
# pydantic_core._pydantic_core.ValidationError: 1 validation error for MyClass
# t
#   Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='100', input_type=str]
#     For further information visit https://errors.pydantic.dev/2.3/v/time_delta_parsing

# SUCCESS: Expected: t=100 seconds
MyClass.model_validate_json('{"t": 100}')
# > MyClass(t=datetime.timedelta(seconds=100))

# FAIL: Expected: t=100 seconds
MyClass.model_validate_json('{"t": "100"}')
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/Users/jd/Projects/[REDACTED]/.venv/lib/python3.9/site-packages/pydantic/main.py", line 531, in model_validate_json
#     return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for MyClass
# t
#   Input should be a valid duration, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='100', input_type=str]
#     For further information visit https://errors.pydantic.dev/2.3/v/time_delta_parsing
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jd/Projects/[REDACTED]/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Sep 14 2022, 15:53:35)  [Clang 14.0.0 (clang-1400.0.29.102)]
                     platform: macOS-13.5.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi! Glad the migration is going well overall.

The Pydantic v1 -> v2 migration guide provides [this table](https://docs.pydantic.dev/latest/usage/conversion_table/) with information about how Pydantic converts data during validation.

As you can see in the table, if a field is specified as the `timedelta` type and an `int` is provided, that `int` is interpreted as the number of seconds corresponding to the `timedelta`, hence your first example working. The table also illustrates that when you pass a `str` in for a `timedelta` field, it's assumed to be in [ISO8601 format](https://docs.rs/speedate/latest/speedate/). Your second example isn't working because you're expecting the string to be interpreted in seconds.

One potential workaround you could use is the following:
```py
from datetime import timedelta
from typing import Union

from pydantic import BaseModel, field_validator

class MyClass(BaseModel):
    t: timedelta

    @field_validator('t', mode="before")
    @classmethod
    def interpret_t_as_seconds(cls, v: Union[int, str]) -> int:
        try:
            return int(v)
        except ValueError:
            raise ValueError("t must be an int value in seconds")
```

With this logic, all of the test cases you outlined produce:
`MyClass(t=datetime.timedelta(seconds=100))`
