### ISSUE TITLE
Pydantic cannot serialize the field if field using @property annotation

### ISSUE THREAD

**Issue by zhengye1** [pydantic/pydantic#7382]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In V1 I don't get this problem because after I run it I got following output
```{'source': 'randomTest', 'source_uid': None, 'account_id': '123'}```

but in the V2, I got following error
```
$ python PythonTestPydantic.py
Traceback (most recent call last):
  File "C:\Users\zhibo\eip\PythonTestPydantic.py", line 41, in <module>
    print(child.to_dict())
          ^^^^^^^^^^^^^^^
  File "C:\Users\zhibo\eip\PythonTestPydantic.py", line 8, in to_dict
    return jsonable_encoder(self, exclude=exclude)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\python3\Lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    obj_dict = _model_dump(
               ^^^^^^^^^^^^
  File "C:\Program Files\python3\Lib\site-packages\fastapi\_compat.py", line 171, in _model_dump
    return model.model_dump(mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhibo\AppData\Roaming\Python\Python311\site-packages\pydantic\main.py", line 309, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'property'>
```

What I attempt before is change the `property` annotation part to 
```
    def __init__(self):
        self.source_uid = self.account_id
```

That it will falling on ```child = ChildModel(account_id=“123”)``` due to ```ChildModel.__init__() got an unexpected keyword argument 'account_id'```

What I can change the code to make this work?

### Example Code

```Python
from typing import Dict, ClassVar, Optional
from pydantic import Field, BaseModel, ConfigDict
from fastapi.encoders import jsonable_encoder


class ParentModel(BaseModel):
    def to_dict(self, exclude=[]) -> Dict:
        return jsonable_encoder(self, exclude=exclude)

    json = to_dict

    def __repr__(self):
        classname = self.__class__.__name__
        d = jsonable_encoder(self)
        return f"{classname}({d})"

    __str__ = __repr__


class SourceLayer(ParentModel):
    source: str = Field(default="randomTest")
    source_uid: str = Field(description="random source uid", default=None)


class ChildModel(SourceLayer):
    account_id: str = Field(..., description="account id")

    @property
    def source_uid(self):
        print("Getting value ...")
        return self.account_id

child = ChildModel(account_id="123")
print(child.to_dict())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
python version: 3.11.3
```

**Comment by sydney-runkle** [comment]
Hi, and thanks for your question.

In Pydantic V2, we introduced the `@computed_field` decorator. According to the [docs](https://docs.pydantic.dev/latest/usage/computed_fields/):
> Computed fields allow property and cached_property to be included when serializing models or dataclasses. This is useful for fields that are computed from other fields, or for fields that are expensive to compute and should be cached.

So, you can use the `@computed_field` decorator above your `@property` decorator to ensure that your `source_uid` is serialized. Another issue you have here though, is that you can't override a field with a computed field (which you're doing with `source_uid`.

A potential solution would look something like the following:
```py
from pydantic import BaseModel, Field, computed_field


class ParentModel(BaseModel):
    ...


class SourceLayer(ParentModel):
    source: str = Field(default="randomTest")


class ChildModel(SourceLayer):
    account_id: str = Field(..., description="account id")

    @computed_field(description="source uid")
    def source_uid(self) -> str:
        print("Getting value ...")
        return self.account_id

child = ChildModel(account_id="123")
print(child.model_dump())
# > Getting value ...
# > {'source': 'randomTest', 'account_id': '123', 'source_uid': '123'}
```

**Comment by zhengye1** [comment]
but I actually need that `source_uid` field in `SourceLayer`.. any other way?

**Comment by sydney-runkle** [comment]
I think something like this should still meet your needs:

```py
from pydantic import BaseModel, Field


class ParentModel(BaseModel):
    ...


class SourceLayer(ParentModel):
    source: str = Field(default="randomTest")
    source_uid: str = Field(description="random source uid", default=None)


class ChildModel(SourceLayer):
    account_id: str = Field(..., description="account id")

    @model_validator(mode="after")
    def assign_source_uid(self):
        print("Getting value ...")
        self.source_uid = self.account_id
        return self

child = ChildModel(account_id="123")
print(child.model_dump())
# > Getting value ...
# > {'source': 'randomTest', 'account_id': '123', 'source_uid': '123'}
```
