### ISSUE TITLE
An empty string is valid despite min_length 1 and strip_whitespace True

### ISSUE THREAD

**Issue by pgjones** [pydantic/pydantic#7402]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'd like the strip_whitespace to take affect before the min_length is checked - I think this is probably the common expectation.

See also #2315

### Example Code

```Python
>>> from pydantic import BaseModel, Field
>>> from typing import Annotated
>>> class A(BaseModel):
...     a: Annotated[str, Field(min_length=1, strip_whitespace=True)]
... 
>>> A(a=" ")
A(a=' ')
>>> A(a="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for A
a
  String should have at least 1 characters [type=string_too_short, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.3/v/string_too_short
```

### Python, Pydantic & OS Version

```Text
import pydantic.version; print(pydantic.version.version_info())
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by adriangb** [comment]
> this is probably the common expectation

As you probably know being a prolific maintainer yourself, no matter what you think is most common or expected _someone_ will want the opposite or some other variation you never thought of. And this is a case where we can't really change the behavior for backwards compatibility even if we knew there was a general preference for one way or another.

What you can do is choose the order with a bit of hackiness (in the future we'd hope this works without the AfterValidator bit):

```python
from typing import Annotated

from pydantic import AfterValidator, BaseModel, StringConstraints


class A(BaseModel):
    a: Annotated[str, StringConstraints(strip_whitespace=True), AfterValidator(lambda x: x), StringConstraints(min_length=1)]


A(a=' ')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for A
a
  Value should have at least 1 item after validation, not 0 [type=too_short, input_value=' ', input_type=str]
    For further information visit https://errors.pydantic.dev/2.3/v/too_short
"""
```

Since this is a known issue / feature request I'd like to close this issue, let me know if that's alright with you.

**Comment by pgjones** [comment]
I've just noticed that this might be a different issue. I don't think it strips any whitespace,
```
>>> class A(BaseModel):
...     a: Annotated[str, Field(min_length=1, strip_whitespace=True)]
... 
>>> A(a=" ")
A(a=' ')
>>> A(a="A ")
A(a='A ')
```
I think it should?

I didn't know about StringConstraints, thanks. This, `Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]` does exactly what I expect i.e.,
```
>>> class A(BaseModel):
...     a: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]
... 
>>> A(a=" ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for A
a
  String should have at least 1 characters [type=string_too_short, input_value=' ', input_type=str]
    For further information visit https://errors.pydantic.dev/2.3/v/string_too_short
```

Happy to close if I'm just using Field incorrectly.

**Comment by adriangb** [comment]
`strip_whitespace` isn't a keyword argument to `Field` in v2. I'm guessing it's ending up in `kwargs` and being ignored.

**Comment by pgjones** [comment]
Thanks

**Comment by samuelcolvin** [comment]
If we don't already, we should have a warning for any unknown kwargs, which are caught by the catch-all, we're intending to remove it in v3 anyway.
