### ISSUE TITLE
Constructing a traceback.TracebackException from a validation error fails

### ISSUE THREAD

**Issue by eloc3147** [pydantic/pydantic#7421]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When constructing a traceback.TracebackException from an exception traceback containing a pydantic validation error, an AttributeError is raised.

# Expected behavior

Constructing a TracebackException should not fail for any valid exception traceback.

# Actual behavior

Constructing a TracebackException with a exception traceback containing a pydantic validation erorr raises `AttributeError: __pydantic_extra__`

Traceback from my example code:
```
Traceback (most recent call last):
  File "C:\Users\kinno\Desktop\traceback_test.py", line 29, in <module>
    my_instance = MyModel(**data)
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
name
  Field required [type=missing, input_value={'age': 'John Doe'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kinno\Desktop\traceback_test.py", line 29, in <module>
    my_instance = MyModel(**data)
  File "C:\Users\kinno\Desktop\traceback_test.py", line 15, in __exit__
    a = TracebackException(
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\traceback.py", line 359, in extract
    result.append(FrameSummary(
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\traceback.py", line 260, in __init__
    self.locals = {k: repr(v) for k, v in locals.items()} if locals else None
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\traceback.py", line 260, in <dictcomp>
    self.locals = {k: repr(v) for k, v in locals.items()} if locals else None
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\main.py", line 874, in __repr__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\_internal\_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\_internal\_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\main.py", line 881, in __repr_args__
    pydantic_extra = self.__pydantic_extra__
  File "C:\Users\kinno\anaconda3\envs\pydantic_test\lib\site-packages\pydantic\main.py", line 723, in __getattr__
    pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
AttributeError: __pydantic_extra__
```

## Important caveat
This only seems to occur when providing `exc_traceback` to the TracebackException. If `None` is given as `exc_traceback` and only the exception and type are given, then this error does not occur

### Example Code

```Python
from pydantic import BaseModel
from traceback import TracebackException


class MyModel(BaseModel):
    name: str


class CustomErrorCatcher(object):
    def __enter__(self):
        return None

    def __exit__(self, _exception_type, exception, exception_traceback):
        if exception is not None:
            a = TracebackException(
                exc_type=type(exception),
                exc_value=exception,
                exc_traceback=exception_traceback,
                capture_locals=True,
            )
            print(a)

            return True
        return False


with CustomErrorCatcher():
    data = {"age": "John Doe"}
    my_instance = MyModel(**data)

print("Got valid", my_instance)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\kinno\anaconda3\envs\pydantic_test\Lib\site-packages\pydantic
               python version: 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by eloc3147** [comment]
Thanks for the quick fix!

Any idea when a new release will come out? I'm anxious to be able to deploy this in my environment (without resorting to a non PyPI source)
