### ISSUE TITLE
Constrained number types raise TypeError

### ISSUE THREAD

**Issue by goatsweater** [pydantic/pydantic#7544]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using `conint` or `confloat` with any parameters (`ge`, `lt`, etc) raises an error, making it impossible to use for constraining integer values. It doesn't seem to matter what the constrain values are or how many are provided.

The full trace is:

```
Traceback (most recent call last):
  File "C:\pydantic_test.py", line 3, in <module>
    class Model(BaseModel):
  File "C:\pydantic_test.py", line 4, in Model
    myint: conint(ge=1950)
  File "C:\.venv\lib\site-packages\pydantic\types.py", line 160, in conint
    annotated_types.Interval(gt=gt, ge=ge, lt=lt, le=le),
TypeError: Interval() takes no arguments
```

The stack trace is raised at `conint`, but `confloat` raises the same exception.

### Example Code

```Python
from pydantic import BaseModel, conint, confloat

class Model(BaseModel):
    myint: conint(ge=1950, le=2023)
    myfloat: confloat(ge=195.0, le=202.3)

m = Model(myint=2002, myfloat=200.2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\.venv\Lib\site-packages\pydantic
               python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19042-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @goatsweater,

I'm unable to reproduce this issue. When I run the code below, I get the output shown.

```py
from pydantic import BaseModel, conint, confloat


class Model(BaseModel):
    myint: conint(ge=1950, le=2023)
    myfloat: confloat(ge=195.0, le=202.3)

m = Model(myint=2002, myfloat=200.2)
print(repr(m))
#> Model(myint=2002, myfloat=200.2)
```

I also get the expected validation errors when constructing a `Model` instance with invalid `myint` or `myfloat` values.

**Comment by goatsweater** [comment]
I just tried it on a Python 3.10 install and it works fine. I think this may be a Python 3.9 specific problem.

**Comment by sydney-runkle** [comment]
@goatsweater I'm also experiencing this problem with Python 3.9.7. Will look into this further and get back to you :)
