### ISSUE TITLE
Fails to build "definitions" validator when there are multiple members of the same non-trivial type

### ISSUE THREAD

**Issue by battlesnake** [pydantic/pydantic#7649]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When running a program containing a model where more than one of its members have the same type and that type is another model, pydantic fails to build the "definitions" validator.

```
Traceback (most recent call last):
  File "/x.py", line 11, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/dataclasses.py", line 213, in dataclass
    return create_dataclass(_cls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/dataclasses.py", line 204, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 174, in complete_dataclass
    cls.__pydantic_validator__ = validator = create_schema_validator(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/plugin/_schema_validator.py", line 34, in create_schema_validator
    return SchemaValidator(schema, config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Error building "definitions" validator:
  SchemaError: Error building "definitions" validator:
  SchemaError: Duplicate ref: `__main__.Inner:94707826766784`
```

### Example Code

```Python
from pydantic import Field, BaseModel
from pydantic.dataclasses import dataclass


@dataclass
class Inner(BaseModel):
	a: int = 0
	b: int = 0


@dataclass
class Outer(BaseModel):
	a: int = 0
	b: Inner = Field(default_factory=lambda: Inner(a=1, b=2))
	c: Inner = Field(default_factory=lambda: Inner(a=1, b=2))
```

### Python, Pydantic & OS Version

```Text
Issue found in environment:

             pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/mark/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep 23 2023, 14:07:30) [GCC 13.2.1 20230801]
                     platform: Linux-6.1.2-mark-x86_64-with-glibc2.38
             related packages: typing_extensions-4.8.0 pyright-1.1.327 mypy-1.5.1
```

The reproduced via docker for minimal portable example with:

```
             pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep 20 2023, 10:46:56) [GCC 12.2.0]
                     platform: Linux-6.1.2-mark-x86_64-with-glibc2.36
             related packages: typing_extensions-4.8.0
```

Using dockerfile:
```
from python:3.11-slim
run pip install pydantic==2.4.0
copy demo.py /
entrypoint ["/bin/env", "python", "/demo.py"]
```

**Comment by battlesnake** [comment]
Use case: Serialising graphical objects, where one type of graphical objects might have several `Text` items within it (and each of those might have multiple `Font` within it)

**Comment by battlesnake** [comment]
I'm assuming this is a bug, since it seems like a usage many people might try and I find only one result for a google search for `"SchemaError: Duplicate ref:"`

**Comment by hramezani** [comment]
Thanks @battlesnake for reporting this 🙏 

We have released `2.4.1` a couple of hours ago. Could you update and test?

If the problem still exists, please install `pydantic` from the `main` branch and test it.
```
pip uninstall pydantic
pip install -U git+https://github.com/pydantic/pydantic.git@main
```

Please let us know whether it got fixed or not.

**Comment by battlesnake** [comment]
Thanks, that was quick.  `2.4.1` doesn't give that error.  I think we can consider this as fixed.

`2.4.1` gives the same other error as `2.3.0` and below, which is likely my own fault.

I suspect that this is due to me trying to create an optional non-nullable field, which should be initialised via `default_factory`, if not present in the input.

I probably need to read the docs again (just started using `pydantic` a couple of days ago), but is there anything obviously wrong with the line below?

```
    title_style: GraphicTextStyle = Field(default_factory=lambda: GraphicTextStyle())
                                                                  ^^^^^^^^^^^^^^^^^^

  File "/home/mark/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 132, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)

pydantic_core._pydantic_core.ValidationError: 1 validation error for GraphicTextStyle

  Input should be a valid dictionary or instance of GraphicTextStyle [type=model_type, input_value=ArgsKwargs(()), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.4/v/model_type
```

**Comment by battlesnake** [comment]
Re-running my dockerised example using the latest main-branch (`git+https://github.com/pydantic/pydantic.git@main`), it passes also.

**Comment by hramezani** [comment]
Thanks @battlesnake for letting us know. I closed this issue as you confirmed the fix.
