### ISSUE TITLE
Model validation doesn't work with Rust objects

### ISSUE THREAD

**Issue by adam-pawluczuk** [pydantic/pydantic#7665]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello!

It looks like sometimes `.model_validate(from_attributes=True)` (an equivalent of ORM mode from Pydantic V1) doesn't work.

Consider this model:
```py
from pydantic import BaseModel

class CustomObjectIdentifier(BaseModel):
    dotted_string: str
```

I am able to serialize it given the example here:
* https://docs.pydantic.dev/2.3/errors/validation_errors/#model_attributes_type

```py 
class CustomObj:
    def __init__(self, dotted_string):
        self.dotted_string = dotted_string

CustomObjectIdentifier.model_validate(CustomObj("2.5.4.5"), from_attributes=True)
```

So the above works perfectly fine.

Although this is an example which doesn't work, but I think it should:
```py
from cryptography.x509 import NameOID

CustomObjectIdentifier.model_validate(NameOID.SERIAL_NUMBER, from_attributes=True)

# Traceback (most recent call last):
#   File "/Users/apawlucz/src/scripts/pydantic/test_from_orm.py", line 144, in <module>
#     ObjectIdentifier.model_validate(NameOID.SERIAL_NUMBER)
#   File "/Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/pydantic/main.py", line 504, in model_validate
#     return cls.__pydantic_validator__.validate_python(
# pydantic_core._pydantic_core.ValidationError: 1 validation error for ObjectIdentifier
#   Input should be a valid dictionary or instance of ObjectIdentifier [type=model_type, input_value=<ObjectIdentifier(oid=2.5.4.5, name=serialNumber)>, input_type=ObjectIdentifier]
#     For further information visit https://errors.pydantic.dev/2.3/v/model_type
```

Some more details:
```pycon
>> NameOID.SERIAL_NUMBER
<ObjectIdentifier(oid=2.5.4.5, name=serialNumber)>
>> type(NameOID.SERIAL_NUMBER)
<class 'builtins.ObjectIdentifier'>
>> NameOID.SERIAL_NUMBER.dotted_string   # <- This is important, the object contains the expected property
'2.5.4.5'
```

`ObjectIdentifier` normally can be imported as follows:
* `from cryptography.x509 import ObjectIdentifier`

`ObjectIdentifier` is Rust object. So to me it looks like Pydantic is not able to pickup Rust objects correctly.

Do bear in mind the original code was working perfectly fine with Pydantic V1:
```py
from pydantic import BaseModel
from cryptography.x509 import NameOID


class ObjectIdentifier(BaseModel):
    dotted_string: str

    class Config:
        orm_mode = True

ObjectIdentifier.from_orm(NameOID.SERIAL_NUMBER)
# ObjectIdentifier(dotted_string='2.5.4.5')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]
                     platform: macOS-13.6-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by samuelcolvin** [comment]
This works fine for me with 2.3.0, 2.4.0 & 2.4.1

```py
from pydantic import BaseModel
from cryptography.x509 import NameOID


class CustomObjectIdentifier(BaseModel):
    dotted_string: str


m = CustomObjectIdentifier.model_validate(NameOID.SERIAL_NUMBER, from_attributes=True)
print(repr(m))
#> CustomObjectIdentifier(dotted_string='2.5.4.5')
```

**Comment by samuelcolvin** [comment]
I was using 

```
Python 3.11.5
cryptography==41.0.4
```

**Comment by adam-pawluczuk** [comment]
Thank you for extremely quick response!

Indeed, I checked with:
```
cryptography==41.0.0
```

Ant it works now.

Initially I was checking with:
```
cryptography==40.0.2
```

So that was rather `cryptography` bug.
