### ISSUE TITLE
@functools.cache can't use with BaseModel

### ISSUE THREAD

**Issue by wellhowtosay** [pydantic/pydantic#7702]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a class that has heavy init function, so I use decorator @functools.cache, but here is what I got :

Traceback (most recent call last):
  File "/Users/luka.bao/PycharmProjects/draft/test.py", line 55, in <module>
    class Model(BaseModel):
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 184, in __new__
    complete_model_class(
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 481, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/main.py", line 576, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 706, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 525, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 525, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 870, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 923, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1592, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1573, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 798, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <functools._lru_cache_wrapper object at 0x1052e45c0>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type

### Example Code

```Python
from pydantic import BaseModel
import functools

@functools.cache
class Test(BaseModel):
    a: str
    
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
        self.heavy_init()
        
    def heavy_init(self):
        pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/luka.bao/PycharmProjects/draft/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 15:55:47) [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @wellhowtosay,

Thanks for reporting this! Do you get the error upon initialization of a `Test` instance? I wasn't able to reproduce this problem...

Happy to help once we get some more info. Thanks 😄

**Comment by sydney-runkle** [comment]
Closing for now. Happy to reopen if we're able to reproduce this issue / if others are having this issue.
