### ISSUE TITLE
Error during Serialization (`model_dump`)

### ISSUE THREAD

**Issue by vigneshmanick** [pydantic/pydantic#7713]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

During migration of our code from V1 to V2 we encountered the following error .

```
File "/scratch/envs/pydantic-v2/lib/python3.11/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

After some debugging i found two scenarios where the `model_dump` works

1. when `exclude_unset=True` is set
2. or when one of the fields in the base classes is modified from `default=[]` to `default=None` 

```
step_settings: Union[ StepConstant, StepEstimation] = Field(default=[])
```

if the default of the above field is modified to `None` , then the code works.  

The same works without modifications in V1. I have attached the sample code(apologies for the longer file but i  wasn't able to reliably shorten it) that generates the error. 

NOTE: I have also  tried with `model_rebuild` instead of `update_forward_refs` and `model_dump` instead of `dict`. The code below should work in both V1 and V2.

It would be helpful for debugging if there is a more detailed stack trace for the serialization error. It's not directly clear where the issue lies.

Thanks in advance!

### Example Code

```py
# serialization_err.py

from pydantic import BaseModel, Field, PositiveFloat
from typing import ForwardRef, Literal, Union


class Base(BaseModel):
    type: str
    name: str


class BaseSettings(BaseModel):
    geo: str


class CoupledBodySettings(BaseSettings):
    coupled_body: list[BaseSettings] = Field(default=[])


class StepConstant(BaseModel):
    type: Literal["constant"]
    init_step_size: float


class StepEstimation(BaseModel):
    type: Literal["estimation"]
    init_step_size: int


class Body(Base):
    type: Literal["body"]
    settings: BaseSettings
    step_settings: Union[StepConstant, StepEstimation] = Field(default=[])


class CoupledBody(Base):
    type: Literal["coupled_body"]
    parameter_type: Literal["shape"] = Field(default="shape")
    settings: CoupledBodySettings
    step_settings: Union[StepConstant, StepEstimation] = Field(default=[])


class Glue(BaseModel):
    radius: PositiveFloat


class SubBase(BaseModel):
    type: str
    name: str
    glue: Glue


class SubCoupledBody(CoupledBody, SubBase):
    type: Literal["coupled_body"]


class SubBody(Body, SubBase):
    type: Literal["body"]


class NestedBodySettings(BaseSettings):
    nested: list[
        Union[
            SubBody,
            SubCoupledBody,
            ForwardRef("SubNestedBody"),
            ForwardRef("SubNestedSeqBody"),
        ]
    ]


class NestedBody(Base):
    type: Literal["nested"]
    parameter_type: Literal["shape"] = Field(
        default="shape",
    )
    settings: NestedBodySettings
    step_settings: Union[StepConstant, StepEstimation] = Field(default=[])


class NestedSeqBodySettings(NestedBodySettings):
    iterations_per_parameterization: list[int] = Field(default=[1, 1])
    nested_step_settings: Union[StepConstant, StepEstimation] = Field(default=[])


class NestedSeqBody(Base):
    type: Literal["nested_sequential_body"]
    settings: NestedSeqBodySettings
    step_settings: Union[StepConstant, StepEstimation] = Field(
        default=[],
    )


class SubNestedBody(NestedBody, SubBase):
    type: Literal["nested"]


class SubNestedSeqBody(NestedSeqBody, SubBase):
    type: Literal["nested_sequential_body"]


NestedBodySettings.update_forward_refs()
NestedSeqBodySettings.update_forward_refs()


class Base(BaseModel):
    name: str
    param: list[NestedBody | NestedSeqBody]


data = {
    "name": "test",
    "param": [
        {
            "type": "nested",
            "name": "parent_rb",
            "settings": {
                "geo": "plate",
                "nested": [
                    {
                        "type": "body",
                        "name": "child1_rb",
                        "glue": {"radius": 10.0},
                        "settings": {
                            "geo": "bla",
                        },
                    }
                ],
            },
        }
    ],
}

model = Base(**data)
print(model.dict(exclude_unset=False))

```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: /scratch/envs/pydantic-v2/lib/python3.11/site-packages/pydantic
python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
related packages: typing_extensions-4.8.0
```

Update 10/03/23:  Modified the script to be able to run it as a single file

**Comment by sydney-runkle** [comment]
Hi @vigneshmanick,

Thanks for reporting this. I'm a bit confused - I tested your code snippet above in v2.4.2 using `model_rebuild` and `model_dump`, and all is running smoothly.

I wasn't able to recreate the issue you were referring to. Could you please share a code snippet that I can use to reproduce the error? Thanks! 😄

**Comment by vigneshmanick** [comment]
@sydney-runkle  thanks for the response, the code above fails in my machine. I just recreated a new environment with only python and pydantic and i still get the same error

```
/scratch/pydanticv2/orig.py:102: PydanticDeprecatedSince20: The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https:/errors.pydantic.dev/2.4/migration/
  NestedBodySettings.update_forward_refs()
/scratch/pydanticv2/orig.py:103: PydanticDeprecatedSince20: The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https:/errors.pydantic.dev/2.4/migration/
  NestedSeqBodySettings.update_forward_refs()
/scratch/pydanticv2/orig.py:142: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https:/errors.pydantic.dev/2.4/migration/
  print(model.dict(exclude_unset=False))
Traceback (most recent call last):
  File "/scratch/pydanticv2/orig.py", line 142, in <module>
    print(model.dict(exclude_unset=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/miniconda3/envs/tt/lib/python3.11/site-packages/typing_extensions.py", line 2360, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/scratch/miniconda3/envs/tt/lib/python3.11/site-packages/pydantic/main.py", line 963, in dict
    return self.model_dump(
           ^^^^^^^^^^^^^^^^
  File "/scratch/miniconda3/envs/tt/lib/python3.11/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

```

Pydantic Version Info
```
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: /scratch/miniconda3/envs/tt/lib/python3.11/site-packages/pydantic
python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
related packages: typing_extensions-4.8.0'
```

If you need further information please let me know.

**Comment by vigneshmanick** [comment]
Update, i also tested in another machine with a different OS (SUSE 15) and i get the same error

```
conda create -n tt python pydantic
conda activate tt
python test.py
```

```
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: /scratch/tools/miniconda/envs/tt/lib/python3.11/site-packages/pydantic
python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
platform: Linux-5.3.18-150200.24.148-default-x86_64-with-glibc2.26
related packages: typing_extensions-4.8.0
```

**Comment by vigneshmanick** [comment]
@sydney-runkle  i also tested with Windows and can reproduce the error.

#### Version Info

```py
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: C:\Users\test\AppData\Local\Programs\miniconda3\envs\tt\Lib\site-packages\pydantic
python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
related packages: typing_extensions-4.8.0
```

#### Error

```py
Traceback (most recent call last):
  File "C:\Users\test\Projects\scripts\test_pydantic.py", line 135, in <module>
    print(model.dict(exclude_unset=False))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\miniconda3\envs\tt\Lib\site-packages\typing_extensions.py", line 2360, in wrapper
    return arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\miniconda3\envs\tt\Lib\site-packages\pydantic\main.py", line 963, in dict
    return self.model_dump(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\miniconda3\envs\tt\Lib\site-packages\pydantic\main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

```

**Comment by davidhewitt** [comment]
Through aggressive use of the delete key I've narrowed it to this repro:

```python
from pydantic import BaseModel, Field, TypeAdapter
from typing import ForwardRef


class NestedBody(BaseModel):
    nested: ForwardRef("SubNestedBody") | None
    bad_default: BaseModel = Field(default=())


class SubNestedBody(NestedBody):
    ...


# Uncomment this to fix the crash
# NestedBody.model_rebuild()

adapter = TypeAdapter(NestedBody | SubNestedBody)

validated = adapter.validate_python({
    "nested": None,
})
adapter.dump_python(validated)
```

I cannot remove either the `bad_default` or remove the `ForwardRef` from `nested` field. Uncommenting the line I mark above to rebuild `NestedBody`'s model fixes the crash, but emits a bunch of serializer warnings. Overall I suspect there's a bad interaction between forward references and union serialization #6830

**Comment by sydney-runkle** [comment]
So when I run this, I get the following serialization warnings:

```py
from pydantic import BaseModel, Field, TypeAdapter
from typing import ForwardRef, Union


class NestedBody(BaseModel):
    nested: Union[ForwardRef("SubNestedBody"), None]
    bad_default: BaseModel = Field(default=())


class SubNestedBody(NestedBody):
    ...


# Uncomment this to fix the crash
NestedBody.model_rebuild()

adapter = TypeAdapter(Union[NestedBody, SubNestedBody])

validated = adapter.validate_python({
    "nested": None,
})
adapter.dump_python(validated)
"""
UserWarning: Pydantic serializer warnings:
  Expected `Union[NestedBody, definition-ref]` but got `NestedBody` - serialized value may not be as expected
  Expected `BaseModel` but got `tuple` - serialized value may not be as expected
  return self.serializer.to_python(
"""
```

I think the second warning (Expected `BaseModel`...) is fine. If you set `validate_default=True` on `NestedBody`, the validation step fails, which is expected. So I think passing in an invalid default value here is on the user, and it's not a mistake that this serialization warning is raised.

That being said, I think the biggest problem here is how `ForwardRef` types interact with Union types. Looking into a fix for this now...

**Comment by johhnry** [comment]
Hi,

I am having the same issue on `2.4.2`. For now downgrading to `2.4.0` fixes the issue.

**Comment by jamesbraza** [comment]
With Python 3.12.2 and Pydantic 2.6.4:

```python
from typing import Generic, TypeVar

from pydantic import BaseModel, Json

Serializable = BaseModel | Json

TState = TypeVar("TState", bound=Serializable)
TInfo = TypeVar("TInfo", bound=Serializable)


class Frame(BaseModel, Generic[TState, TInfo]):

    state: TState
    info: TInfo | None = None


Frame(state={"hi": 5}).model_dump()
```

I get:

```none
TypeError                                 Traceback (most recent call last)
File ~/code/repo/venv/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py:1621, in GenerateSchema._unsubstituted_typevar_schema.<locals>.<lambda>(x, h)
   1619 schema = self.generate_schema(bound)
   1620 schema['serialization'] = core_schema.wrap_serializer_function_ser_schema(
-> 1621     lambda x, h: h(x), schema=core_schema.any_schema()
   1622 )
   1623 return schema

TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

The above exception was the direct cause of the following exception:

PydanticSerializationError                Traceback (most recent call last)
Cell In[1], line 17
     13     state: TState
     14     info: TInfo | None = None
---> 17 Frame(state={"hi": 5}).model_dump()

File ~/code/repo/venv/lib/python3.12/site-packages/pydantic/main.py:314, in BaseModel.model_dump(self, mode, include, exclude, by_alias, exclude_unset, exclude_defaults, exclude_none, round_trip, warnings)
    281 def model_dump(
    282     self,
    283     *,
   (...)
    292     warnings: bool = True,
    293 ) -> dict[str, Any]:
    294     """Usage docs: https://docs.pydantic.dev/2.6/concepts/serialization/#modelmodel_dump
    295
    296     Generate a dictionary representation of the model, optionally specifying which fields to include or exclude.
   (...)
    312         A dictionary representation of the model.
    313     """
--> 314     return self.__pydantic_serializer__.to_python(
    315         self,
    316         mode=mode,
    317         by_alias=by_alias,
    318         include=include,
    319         exclude=exclude,
    320         exclude_unset=exclude_unset,
    321         exclude_defaults=exclude_defaults,
    322         exclude_none=exclude_none,
    323         round_trip=round_trip,
    324         warnings=warnings,
    325     )

PydanticSerializationError: Error calling function `<lambda>`: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

Seems like the same error

**Comment by pedrohml** [comment]
have anyone explored [union modes](https://docs.pydantic.dev/latest/concepts/unions/#union-modes) to solve the issue ?

**Comment by sydney-runkle** [comment]
Circling back here - I think it's fine that we need the `model_rebuild` here, as the schema of the `nested` field needs to be rebuilt for proper validation / serialization.

I think we're probably building the schema incorrectly for the forwardref.

**Comment by Reskov** [comment]
One more case. I am using [polyfactory](https://github.com/litestar-org/polyfactory) to generate OpenAPI examples of my API.  I enabled `model_construct` option to skip validators of the generated models. Code can be simplified to the following:

```python
from pydantic import ConfigDict, BaseModel, Field


class Child(BaseModel):
    model_config = ConfigDict(defer_build=True)


class JsonSchema(BaseModel):
    my: Child = Field(examples=[Child.model_construct()])


JsonSchema.model_json_schema()
```

This produce `TypeError` on the pydantic 2.8.2

```
    'examples': to_jsonable_python(field_info.examples),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer
```

**Comment by lm970585581** [comment]
I also encounter the same problem when using langchain's tool call

**Comment by eric-easyhealth** [comment]
I had exact same issue here, i'm on packages [openai 1.52.2] the only things i've changes is upgrading the package versions.

  File "/Users/eric/Library/Caches/pypoetry/virtualenvs/askai-JrcHOKOT-py3.12/lib/python3.12/site-packages/fastapi/encoders.py", line 223, in jsonable_encoder
    obj_dict = _model_dump(
               ^^^^^^^^^^^^
  File "/Users/eric/Library/Caches/pypoetry/virtualenvs/askai-JrcHOKOT-py3.12/lib/python3.12/site-packages/fastapi/_compat.py", line 180, in _model_dump
    return model.model_dump(mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/Library/Caches/pypoetry/virtualenvs/askai-JrcHOKOT-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 364, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

**Comment by nanaeaubry** [comment]
We got the same issue as reported about and had to create forward references in our code to solve this.
Doing something like this at the top of the module:
![image](https://github.com/user-attachments/assets/4f520a7d-a28a-4c37-9d7f-fee7b06d526a)


And then setting the forward ref in the parameter typing:
![image](https://github.com/user-attachments/assets/1f6e8a14-be9a-4b81-8c3c-95ccd09f3092)


Has fixed this issue

**Comment by eric-easyhealth** [comment]
Thank you for sharing your solution, @nanaeaubry. I tried using forward ref, but it doesn't seem to work for my situation. It might be due to a different reason.




> We got the same issue as reported about and had to create forward references in our code to solve this. Doing something like this at the top of the module: ![image](https://private-user-images.githubusercontent.com/19919283/381088329-4f520a7d-a28a-4c37-9d7f-fee7b06d526a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTI1OTUsIm5iZiI6MTczMDI1MjI5NSwicGF0aCI6Ii8xOTkxOTI4My8zODEwODgzMjktNGY1MjBhN2QtYTI4YS00YzM3LTlkN2YtZmVlN2IwNmQ1MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAxMzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZDM0ZGUwZDU1NzNlMTJlZTQyZDY5ZmZjOTNhYzg5ZjlkNjZjMmI3ZGZlMmYwOWY3NTU3NDAwY2YxMzBmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X80EHHEN34U7geO4gTVFluT24nzwyArKtMjflZa7DX4)
> 
> And then setting the forward ref in the parameter typing: ![image](https://private-user-images.githubusercontent.com/19919283/381088509-1f6e8a14-be9a-4b81-8c3c-95ccd09f3092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNTI1OTUsIm5iZiI6MTczMDI1MjI5NSwicGF0aCI6Ii8xOTkxOTI4My8zODEwODg1MDktMWY2ZThhMTQtYmU5YS00YjgxLThjM2MtOTVjY2QwOWYzMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDAxMzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NTNlZGNhNDk1MWYwYWNjNGExMTA5M2QyMWMyOTJhY2NmYWU1NDJiNjc0YTM2NjhiZDYxNjRmZGYyMGE4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pyKPXxLKx9zUFtibYCgK9QFxFMUXa3nG6QnfgZi11P8)
> 
> Has fixed this issue

**Comment by johannstark** [comment]
Hello everyone, I just bumped into this very same issue. I'm using `pydantic==2.10.5` on a macOS machine.


Being hours debugging and debugging. For me at least, the problem happens when I try to use `model_dump()` with models with nested models inside. 

Here the model I want to transform into a dictionary:
```python
class CompletionMessage(BaseModel):
    # We must have the user ID at least
    correlation_id: Union[str, None] = uuid.uuid4().hex[:8]
    user_id: Union[str, None] = Field(default="123NoUser", example="573226709573")
    job_type: Union[str, None] = Field(example="job_interview")
    conversation_id: Union[str, None] = Field(default=None, example="2")
    vacancy_id: Union[str, None] = Field(default=None, example="123abc456def")
    company_id: Union[str, None] = Field(default=None, example="C0")
    # Completion requirements
    question_to_ask: Union[str, None] = Field(default=None, example="ask")
    prompt_data: List[ai_message] = Field(
        example=[
            {"role": "system", "content": "Make everyone laugh"},
            {"role": "user", "content": "Hi! tell me a joke"},
        ],
    )
    model: Union[ai_model, None] = Field(
        default=None,
        example={
            "provider": "openai",
            "model": "gpt3.5",
            "temperature": 0.1,
            "max_tokens": 256,
            "json_mode": False,
        },
    )
    model_history: Union[list, None] = Field(
        default=[], example=[{"provider": "openai", "model": "gpt3.5", "attempts": 3}]
    )
    system_parameters: Union[AuditInterviewParams, CurrentQuestionParam, LLMSelectorSystemParams, InterviewParams, dict, None] = Field(
        example={"current_question": "What is your feedback on X?"}
    )
    # Completion response
    attempts: Union[int, None] = Field(default=0, example=0)
    completion_content: Union[str, dict, None] = Field(default=None, example="A joke")
    raw_response: Union[dict, None] = Field(
        default=None, example={"choices": [{"message": {"content": "A joke"}}]}
    )
    conversation_complete: Union[bool, None] = Field(default=None, example=False)
    feedback: Union[bool, None] = Field(default=None, example=False)
    who_end_conversation: Union[str, None] = Field(default=None, example="assistant")
    completion_time: Union[str, None] = Field(
        default=None, example="2022-01-01T00:00:00"
    )
    json_response: Union[bool, None] = Field(default=False, example=False)
    token_usage: Union[dict, None] = Field(
        default=None, example={"prompt": 100, "completion": 100, "total": 200}
    )
    asynchronous: Union[AsynchronousMessage, None] = Field(
        default=None,
        example={
            "enable": False,
            "incoming_topic": "topic1",
            "outgoing_topic": "topic2",
        },
    )
```
Having a simple code to create an object of this class and try `model_dump()` will result in:
```
PydanticSerializationError(Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer')
```

A workaround is to use `dict(object)` And that will throw a dictionary ✨ but the fields composed by other pydantic models will remain pydantic models. As you can see in this screenshot from my pycharm debug console:

message -> a nested pydantic model

<img width="867" alt="image" src="https://github.com/user-attachments/assets/a59f02b8-fa12-4223-b686-6f4247414879" />

We can go deeper by iterating each key, value in the dictionary and apply `dict(value)` but that would hurt a lot 🫠 

Hope my case help anyone to solve this issue 🙏🏻

**Comment by johannstark** [comment]
Update on how i solved the issue: I followed the suggestion from @anchit2000 and it worked ✨ I don't know what is being returned from the OpenAI end, but is garbage, is messing everything up

**Comment by flxdot** [comment]
We also just encountered the issue when trying to handle some performance bottlenecks with deeply nested pydantic models. The data we get can be considered trusted, so we just validate the final complex model.

It seems as if the combination of `list[Union]` and `BaseModel.model_construct()` seems to be the issue in our case:

```python
from __future__ import annotations

from abc import ABC
from typing import Literal

from pydantic import BaseModel, ValidationError
from pydantic.version import version_info


class ChildrenMixin(BaseModel, ABC):

    children: list[ModelUnion]


class ModelA(ChildrenMixin, BaseModel):
    discriminator: Literal["a"]
    attr_a: int


class ModelB(ChildrenMixin, BaseModel):
    discriminator: Literal["b"]
    attr_b: int


ModelUnion = ModelA | ModelB


if __name__ == "__main__":
    print(version_info())

    # build model from trusted source
    working = ModelA.model_construct(
        discriminator="a",
        attr_a=1,
        children=[
            ModelB.model_construct(
                discriminator="b",
                attr_b=2,
                children=[],
            ),
            ModelA.model_construct(
                discriminator="a",
                attr_a=3,
                children=[],
            ),
        ],
    )

    assert working.model_dump()

    # build model from trusted source but forget an attribute
    failing = ModelA.model_construct(
        discriminator="a",
        attr_a=1,
        children=[
            ModelB.model_construct(
                discriminator="b",
                attr_b=2,
                # children=[],
            ),
            ModelA.model_construct(
                discriminator="a",
                attr_a=3,
                children=[],
            ),
        ],
    )

    # this fails with: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
    try:
        failing.model_dump()
    except TypeError as ex:
        assert "MockValSer" in str(ex)

    try:
        failing = ModelA(
            discriminator="a",
            attr_a=1,
            children=[
                ModelB(
                    discriminator="b",
                    attr_b=2,
                    # children=[],
                ),
                ModelA(
                    discriminator="a",
                    attr_a=3,
                    children=[],
                ),
            ],
        )
    except ValidationError:
        print("Raised Validation error as expected")
```


```
             pydantic version: 2.10.6
        pydantic-core version: 2.27.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/felixfanghanel/Nitrex/Code/Qmulus/lib/py_qmulus_drivers/.venv/lib/python3.13/site-packages/pydantic
               python version: 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)]
                     platform: macOS-15.3.1-arm64-arm-64bit-Mach-O
             related packages: pydantic-extra-types-2.10.2 mypy-1.15.0 fastapi-0.115.8 typing_extensions-4.12.2 pydantic-settings-2.8.0
                       commit: unknown
```

**Comment by michaelgmiller1** [comment]
In case it helps anyone else, I encountered this problem serializing a model without `model_rebuild` being called on the sub-models used inside of it. The models were not initialized because we were forking a process via a Python RQ queue.

**Comment by eugenenelou** [comment]
I have a similar problem, `model_dump` works but `pydantic_core.to_json` raises the error

```
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

this happens when using temporal.io, and I guess it could be because the object is passed between processes like @michaelgmiller1 says.

**Comment by Viicos** [comment]
@eugenenelou we are aware of the Temporal.io issue, the underlying problem is described in https://github.com/openai/openai-python/issues/1306#issuecomment-2966267356 and we'll try to figure out a solution soon.

**Comment by Francisco-Reveriano** [comment]
I have this problem with using OpenAI Agents SDK and Deep Research Model 

`# Use env var for API key and set a long timeout
client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"), base_url=os.getenv("OPENAI_BASE_URL"), timeout=1000.0)
set_default_openai_client(client)

class Search_SubAgent_Profile(BaseModel):
    response: str
    "Detailed search response."

research_agent = Agent(
    name="Research Agent",
    model="o4-mini-deep-research",
    tools=[WebSearchTool()],
    instructions="You perform deep empirical research based on the user's question."
)


result = await Runner.run(research_agent, "Research the economic impact of semaglutide on global healthcare systems.")
print(result.final_output)`

**Comment by imaffe** [comment]
@Viicos Hi Viicos, any updates on this issue or is there any workaround we can take ? The thing is we are using pydantic ai 1.0.1 and it's relying on pydantic version 2.11.7 and above. The code works in pydantic version 2.10.6 but breaks once we introduced the pydantic 2.11.7 dependency. Thanks a lot!

EDIT: the error was thrown in temporal as well.
EDIT 2: also we are confused why it works in 2.10.6 but not in 2.11.7

**Comment by mikenerone** [comment]
I ran into this problem with forward references myself, but it was easily solvable by adding an explicit call to the `module_rebuild()` method of the class with the forward reference. For me, at the bottom of my top-level `__init__.py` worked, and that should work for many cases (because that's often the last module to get fully resolved, so the modules involved in the reference cycle should be completely imported and ready). In some situations, though, it might be necessary to find a different strategic place (or even more than one). Keep in mind that it doesn't _have_ to be at the module level, either. As long as it's called before it's ever serialized, it should be fine. It only needs to be called once, in any case.

I'm not positive I had exactly the same issue as everyone else here, but hopefully this will help somebody.
