### ISSUE TITLE
JSON validation of model with SecretStr field fails

### ISSUE THREAD

**Issue by terranjp** [pydantic/pydantic#7720]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

During migration of our codebase to 2.4.2 we encountered the following bug. This was not a bug in 2.3.0!

JSON validation of a model with `SecretStr` field fails:

```python
from pydantic import BaseModel, SecretStr

class Model(BaseModel):
    foo:  SecretStr

model = Model.model_validate_json('{"foo": "a"}')
```

Fails with following error:

```
Traceback (most recent call last):
  File "/Users/tarren.peterson/Library/Application Support/JetBrains/PyCharm2023.2/scratches/pydantic_scratch/pydantic_bug.py", line 6, in <module>
    model = Model.model_validate_json('{"foo": "a"}')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tarren.peterson/Library/Caches/pypoetry/virtualenvs/ea-forecasting-tools-D5CGYiI1-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 530, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.
```

### Example Code

```Python
from pydantic import BaseModel, SecretStr

class Model(BaseModel):
    foo:  SecretStr

model = Model.model_validate_json('{"foo": "a"}')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: /Users/tarren.peterson/Library/Caches/pypoetry/virtualenvs/ea-forecasting-tools-D5CGYiI1-py3.11/lib/python3.11/site-packages/pydantic
python version: 3.11.1 (main, Aug 24 2023, 07:39:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.5.1-arm64-arm-64bit
related packages: fastapi-0.103.0 typing_extensions-4.8.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
Hi @terranjp,

Thanks for reporting this! This does look like a bug, and we'll work on a fix for v2.4.3.
