### ISSUE TITLE
`default_factory` is broken (but `default` works) for inherited dataclass fields

### ISSUE THREAD

**Issue by treykeown** [pydantic/pydantic#7821]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Inherited fields throw an error when using `default_factory`, but confusingly, not when using `default`. Not sure if this is specific to dataclasses in particular.

Error message is provided below:
```
Traceback (most recent call last):
  File "<snip>/scratch.py", line 24, in <module>
    factory_sub = UsesDefaultFactory_Subclass("a")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 132, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for UsesDefaultFactory_Subclass
0
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/int_parsing
notworking2
  Field required [type=missing, input_value=ArgsKwargs(('a',)), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

### Example Code

```Python
from dataclasses import field
from pydantic.dataclasses import dataclass

@dataclass
class UsesDefault:
    working1: int = field(init=False, default=2)

@dataclass
class UsesDefault_Subclass(UsesDefault):
    working2: str

@dataclass
class UsesDefaultFactory:
    notworking1: int = field(init=False, default_factory=lambda: 2)

@dataclass
class UsesDefaultFactory_Subclass(UsesDefaultFactory):
    notworking2: str

if __name__ == "__main__":
    default = UsesDefault()
    default_sub = UsesDefault_Subclass("a")
    factory = UsesDefaultFactory()
    factory_sub = UsesDefaultFactory_Subclass("a")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: <snip>/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Oct  2 2023, 22:40:56) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-13.5.2-arm64-arm-64bit
             related packages: mypy-1.6.0 typing_extensions-4.8.0 fastapi-0.103.2
```

**Comment by PrettyWood** [comment]
Hello @treykeown 
This seems like a bug indeed! In the meantime there is a workaround by using kwargs.
In your example if you do `factory_sub = UsesDefaultFactory_Subclass(y="a")`, it works.

**Comment by fzlzjerry** [comment]
I reproduced this on current main. DataclassArgsValidator uses the schema field index when reading positional arguments and counts every non-keyword-only field, including fields with init=False, so an inherited non-init field consumes a positional slot. I have a focused core fix that assigns positional indices only to init fields while preserving schema and default-factory evaluation order, with regression coverage for both default and default_factory. The full pydantic-core and Pydantic test suites pass. Could a maintainer assign this issue to me so I can submit the PR?

**Comment by Kayvan-Zahiri** [comment]
Could I be assigned to this? I have a fix ready and opened it as #13656 before
reading the assignment rule in CONTRIBUTING, so the bot closed it. Happy to
reopen once I'm assigned.

One thing worth flagging from working on it: the title says `default` works and
only `default_factory` breaks. That was true on 2.4, but on current main both
fail, because the trigger is `init=False` rather than which default is used. It
also has a quieter form than the one reported here, where the argument is
dropped instead of raising:

```python
@dataclass
class P:
    hidden: int = field(init=False, default=99)
    name: str = 'default_name'

P('alice')   # name='default_name', stdlib dataclasses gives 'alice'
```
