### ISSUE TITLE
`RootModel` causes tagged `Unions` with recursion to parse incorrectly

### ISSUE THREAD

**Issue by RedRoserade** [pydantic/pydantic#7907]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I found an issue in Pydantic v2, where if I use a `RootModel` of a tagged `Union` to parse some raw (`dict`) payload, which has recursive definitions in it, some of the resulting objects are parsed incorrectly.

When running [this script](https://github.com/RedRoserade/pydantic-v2-recursive-issue-repro/blob/main/minimal/run.py), which parses the same payload with both a `RootModel` and the concrete model itself (without the top-level union), produces two different results. Parsing with the `RootModel` produces an invalid result, as you can see in the output:

```text
python -m minimal.run
Via RootModel: ParagraphModel(object='block', type='paragraph', nodes=[TextModel(object='text', ranges=[TextItemModel(marks=[EmptyMarkModel(type='empty-mark'), MarkModel(type='external-mark', data=MarkDataModel(value=''))])])])
-----------------
Via ParagraphModel: ParagraphModel(object='block', type='paragraph', nodes=[TextModel(object='text', ranges=[TextItemModel(marks=[EmptyMarkModel(type='empty-mark'), ExternalMarkModel(type='external-mark', data=SuggestionExternalMarkDataModel(type=<ExternalMarkType.SUGGESTION: 'suggestion'>, kind=<TextItemSuggestionKind.REMOVE_TEXT: 'remove_text'>))])])])
-----------------
Traceback (most recent call last):
  File "/Users/val/.pyenv/versions/3.8.15/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/val/.pyenv/versions/3.8.15/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/val/repos/personal/pydantic-v2-slate-demo/minimal/run.py", line 50, in <module>
    main()
  File "/Users/val/repos/personal/pydantic-v2-slate-demo/minimal/run.py", line 46, in main
    assert result_1 == result_2
AssertionError
```

**NOTE**: It is possible to work around this by defining the recursive type _after_ the models.

---

**See https://github.com/RedRoserade/pydantic-v2-recursive-issue-repro for a full explanation and reproduction repository.**

### Example Code

```Python
# See https://github.com/RedRoserade/pydantic-v2-recursive-issue-repro for a full explanation and reproduction repository.
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/val/repos/personal/pydantic-v2-slate-demo/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.15 (default, Nov 21 2022, 11:40:16)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.6-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @RedRoserade,

I haven't had a chance to review all of your code yet, but I'm guessing based on the nature of the problem that this is related to #7487.

Thanks for the report!

**Comment by commonism** [comment]
working
```
             pydantic version: 2.12.4
        pydantic-core version: 2.41.5
          pydantic-core build: profile=release pgo=false
               python version: 3.12.3 (main, Jan  8 2026, 11:30:50) [GCC 13.3.0]
                     platform: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
             related packages: typing_extensions-4.15.0 email-validator-2.3.0
                       commit: unknown
```

```
python3.12 -m minimal.run
Via RootModel: ParagraphModel(object='block', type='paragraph', nodes=[TextModel(object='text', ranges=[TextItemModel(marks=[EmptyMarkModel(type='empty-mark'), ExternalMarkModel(type='external-mark', data=SuggestionExternalMarkDataModel(type=<ExternalMarkType.SUGGESTION: 'suggestion'>, kind=<TextItemSuggestionKind.REMOVE_TEXT: 'remove_text'>))])])])
-----------------
Via ParagraphModel: ParagraphModel(object='block', type='paragraph', nodes=[TextModel(object='text', ranges=[TextItemModel(marks=[EmptyMarkModel(type='empty-mark'), ExternalMarkModel(type='external-mark', data=SuggestionExternalMarkDataModel(type=<ExternalMarkType.SUGGESTION: 'suggestion'>, kind=<TextItemSuggestionKind.REMOVE_TEXT: 'remove_text'>))])])])
-----------------
```
