### ISSUE TITLE
Can't use `|` unions in pydantic on python3.9

### ISSUE THREAD

**Issue by a-recknagel** [pydantic/pydantic#7923]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If you use `from __future__ import annotations`, you can use `|` instead of `typing.Union` on python3.9:
```python
# pipe_unions.py
from __future__ import annotations
import sys
print(sys.version)

class Foo:
    bar: str | None
```
Running `python pipe_unions.py` returns
```
(3, 9, 16)
```
But if the class is a `pydantic` class
```python
# pipe_unions.py
from __future__ import annotations
import pydantic
import sys
print(sys.version)

class Foo(pydantic.BaseModel):
    bar: str | None
```
Running `python pipe_unions.py` crashes with
```
(3, 9, 16)
Traceback (most recent call last):
  File "pipe_unions.py", line 7, in <module>
    class Foo(pydantic.BaseModel):
  File "/home/arne/venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/arne/venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 418, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/arne/venv/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 99, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/home/arne/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/home/arne/venv/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 224, in eval_type_lenient
    return typing._eval_type(value, globalns, localns)  # type: ignore
  File "/home/arne/.pyenv/versions/3.9.16/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/home/arne/.pyenv/versions/3.9.16/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Is it possible to get a fix for this?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/arne/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Feb 27 2023, 16:47:15)  [GCC 11.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @a-recknagel,

Thanks for reporting this. This is the same issue reported in #7873.

I'm going to close this as a duplicate, knowing that we're actively working on a fix for this + will track updates on the above issue 😄.

**Comment by a-recknagel** [comment]
Thanks for finding the dupe, I only searched the issue tracker with 3.9 🤦

**Comment by alexmojaki** [comment]
PR here: https://github.com/pydantic/pydantic/pull/7958
