### ISSUE TITLE
PydanticUserError (all model fields require a type annotation ) raised when Cython

### ISSUE THREAD

**Issue by theodore86** [pydantic/pydantic#7933]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The build process is successful (wheel is proceduced correctly) but when i try to import the class:

The ```to_dict``` is not a field model though.

```console
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from test_lib import TestModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TestModel' from 'test_lib' (/tmp/cython_issue/.venv/lib/python3.10/site-packages/test_lib/__init__.py)
>>> from test_lib.test_file import TestModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/test_lib/test_file.py", line 5, in init test_lib.test_file
    class TestModel(BaseModel):
  File "/tmp/cython_issue/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 104, in __new__
    private_attributes = inspect_namespace(
  File "/tmp/cython_issue/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 370, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `to_dict = <cyfunction TestModel.to_dict at 0x7fe7814f1ff0>`. All model fields require a type annotation; if `to_dict` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.4/u/model-field-missing-annotation
```

### Example Code

```Python
from pydantic import BaseModel
from typing import Dict


class TestModel(BaseModel):
    packages: Dict[str, str]

    def to_dict(self) -> Dict[str, str]:
        return self.packages
```

### Python, Pydantic & OS Version

```Text
Python 3.10.12
Cython 3.0.4
Ubuntu 22.04
Pydantic: 2.4.2
```

**Comment by theodore86** [comment]
Got my answer via: https://github.com/pydantic/pydantic/issues/6670
