### ISSUE TITLE
TypeError raised when using generics in python 3.13

### ISSUE THREAD

**Issue by koviubi56** [pydantic/pydantic#7942]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In python 3.13 when an attribute for a class is defined as any kind of generic the following exception will be raised:
```py
Traceback (most recent call last):
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_fields.py", line 171, in collect_model_fields
    raise AttributeError
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\main.py", line 8, in <module>
    class User(pydantic.BaseModel):
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_model_construction.py", line 183, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_model_construction.py", line 418, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_fields.py", line 174, in collect_model_fields
    field_info = FieldInfo.from_annotation(ann_type)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\fields.py", line 286, in from_annotation
    if _typing_extra.is_annotated(annotation):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 103, in is_annotated
    return origin is not None and lenient_issubclass(origin, Annotated)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic\_internal\_utils.py", line 75, in lenient_issubclass
    return isinstance(cls, type) and issubclass(cls, class_or_tuple)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tibi\AppData\Local\Programs\Python\Python313\Lib\typing.py", line 479, in __subclasscheck__
    raise TypeError(f"{self} cannot be used with issubclass()")
TypeError: typing.Annotated cannot be used with issubclass()
```

### Example Code

```Python
import pydantic


class User(pydantic.BaseModel):
    groups: list[str]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\Tibi\Documents\H\python\pydanticbug\.venv313\Lib\site-packages\pydantic
               python version: 3.13.0a1 (tags/v3.13.0a1:ad056f0, Oct 13 2023, 09:51:17) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @koviubi56,

Thanks for your inquiry! So `pydantic` uses an awesome tool called `pyo3` to connect our Python wrapper with internal rust code, which helps to make the library a TON faster.

Currently, `pyo3` doesn't support alpha versions of Python, like v3.13. Thus, it's not a surprise that there's some wonky behavior when you use v3.13. If you use v3.12, everything should run smoothly 😄.

**Comment by koviubi56** [comment]
Alright. Thank you.
