### ISSUE TITLE
Use `PrivateAttr` with `Annotated` will cause `AttributeError` when getting private attr.

### ISSUE THREAD

**Issue by elonzh** [pydantic/pydantic#7955]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
m._t1=datetime.datetime(2023, 10, 29, 16, 44, 56, 993092)
Traceback (most recent call last):
  File "/home/elonzh/.cache/pypoetry/virtualenvs/unob-hX3-r8Vo-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 738, in __getattr__
    return self.__pydantic_private__[item]  # type: ignore
KeyError: '_t2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/elonzh/workspace/ivysci/unob/debug.py", line 13, in <module>
    print(f"{m._t2=}")
  File "/home/elonzh/.cache/pypoetry/virtualenvs/unob-hX3-r8Vo-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 740, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'TimeAwareModel' object has no attribute '_t2'
```

### Example Code

```Python
from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, PrivateAttr


class TimeAwareModel(BaseModel):
    _t1: datetime = PrivateAttr(default_factory=datetime.now)
    _t2: Annotated[datetime, PrivateAttr(default_factory=datetime.now)]


m = TimeAwareModel()
print(f"{m._t1=}")
print(f"{m._t2=}")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/elonzh/.cache/pypoetry/virtualenvs/unob-hX3-r8Vo-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Nov  1 2022, 19:44:11) [GCC 11.2.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: fastapi-0.103.1 pydantic-settings-2.0.3 email-validator-2.0.0.post2 typing_extensions-4.8.0
```
```

**Comment by sydney-runkle** [comment]
Hi @elonzh,

Thanks for reporting this. Looks like a bug around here:
https://github.com/pydantic/pydantic/blob/46f24cee67c4da80166344076679aeb61d2348cc/pydantic/_internal/_model_construction.py#L375-L384

Specifically, I think we want to pull information from the `ann_type` re `default`, `default_factory` etc.

This is a great first issue for new contributors. I'll mark this as such 😄.

**Comment by tabassco** [comment]
Hi! I'd like a go at this!
I'm a first time contributor but would like to get my feet wet! :)

**Comment by sydney-runkle** [comment]
@tabassco,

Sounds great! I'd be happy to review your work 😄. We're excited for you to contribute 🌟

**Comment by sydney-runkle** [comment]
@tabassco,

Checking the metadata sounds good to me, as I can imagine a case where there's even more info attached to said `PrivateAttr` that we want to preserve 😄
