### ISSUE TITLE
Generic TypedDicts do not resolve type parameters correctly

### ISSUE THREAD

**Issue by NCPlayz** [pydantic/pydantic#7988]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Similar to #7987, TypedDict schema building currently also relies on `typing.get_type_hints`. The main issue for this however is that for TypedDicts:
- `__mro__` does not return the correct method resolution order / bases to resolve type parameters down the inheritance chain, it erases any previous bases, which pydantic solves via the internal `mro()` utility.
- `__annotations__` returns all inherited annotations for a TypedDict, which isn't helpful when you have a Generic TypedDict and need to substitute the type parameters every time they change.
- with TypedDicts you cannot replace the annotation with another unless it is identical.

While I have a PR to fix this behaviour (both retrieving the correct mro and type parameter resolution) for `get_type_hints` at python/cpython#111515, the main reason I wrote that PR was that I found this bug while using pydantic because I wanted to debug this bug but then realised `get_type_hints` didn't support GenericAliases when I tried to find the mismatch in the schema. But after I did all of that I looked at how pydantic was retrieving it, and turns out it used `get_type_hints` too! 😄 

I adapted that PR to work with the pydantic codebase on a branch [here](https://github.com/NCPlayz/pydantic/tree/fix/typeddict-generics) and was just wondering if I needed the go ahead to make the PR or if I needed to make this issue before making the PR or anything.

Traceback for below:
```py
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    TypeAdapter(BarBool).validate_python(expected)
  File "/repos/pydantic/pydantic/type_adapter.py", line 314, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for typed-dict
type
  Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value='type override not respected', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/bool_parsing
```

### Example Code

```Python
T = TypeVar("T")
U = TypeVar("U")


class Foo(TypedDict, Generic[T, U]):
    type: T
    info: U


class Bar(Foo[str, T], Generic[T], total=False):
    value: T

BarBool = Bar[bool]

expected: BarBool = {
    "type": "type override is respected",
    "info": False,
    "value": False,
}
actual = {
    "type": False,
    "value": False,
    "info": "type override not respected",
}
TypeAdapter(BarBool).validate_python(actual)
TypeAdapter(BarBool).validate_python(expected)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2 (main branch at 60c5db6e1ea55d4e5fc13234810d513b3b1b03ae)
        pydantic-core version: 2.11.0
          pydantic-core build: profile=release pgo=true
                 install path: /repos/pydantic/pydantic
               python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
                     platform: Linux
             related packages: mypy-1.1.1 email-validator-2.0.0.post2 typing_extensions-4.7.1 pydantic-extra-types-2.1.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
@NCPlayz,

Feel free to move ahead with the PR creation. I'd be happy to review. Thanks for the thorough issue report - it helps to have it 😄.

**Comment by sydney-runkle** [comment]
Perhaps I'm missing something here. Following [this model](https://docs.pydantic.dev/latest/concepts/models/#generic-models) from the docs re how to create a subclass of a generic model that partially replaces the type params, the below code runs smoothly. It seems a bit confusing to me that you'd use the `T` `TypeVar` in your `Bar` definition...

Definitely lmk if I'm missing something here, I could be misunderstanding your use case.

```py
from typing import TypeVar, Generic
from typing_extensions import TypedDict
from pydantic import TypeAdapter


X = TypeVar("X")
Y = TypeVar("Y")


class Foo(TypedDict, Generic[X, Y]):
    type: X
    info: Y


class Bar(Foo[str, Y], Generic[Y]):
    value: Y


BarBool = Bar[bool]


expected: BarBool = {
    "type": "type override is respected",
    "info": False,
    "value": False,
}
print(TypeAdapter(BarBool).validate_python(expected))
#> {'type': 'type override is respected', 'info': False, 'value': False}
```

**Comment by NCPlayz** [comment]
It's more obvious when inspecting it:
```py
{'computed_fields': [],
 'config': {'title': 'Bar'},
 'fields': {'info': {'metadata': {'pydantic_js_annotation_functions': [<function GenerateSchema._common_field_schema.<locals>.json_schema_update_func at 0x7f45e2724b80>],
                                  'pydantic_js_functions': []},
                     'required': True,
                     'schema': {'metadata': {'pydantic.internal.needs_apply_discriminated_union': False},
                                'type': 'bool'},
                     'type': 'typed-dict-field'},
            'type': {'metadata': {'pydantic_js_annotation_functions': [<function GenerateSchema._common_field_schema.<locals>.json_schema_update_func at 0x7f45e2724540>],
                                  'pydantic_js_functions': []},
                     'required': True,
                     'schema': {'metadata': {'pydantic.internal.needs_apply_discriminated_union': False},
                                'type': 'any'},
                     'type': 'typed-dict-field'},
            'value': {'metadata': {'pydantic_js_annotation_functions': [<function GenerateSchema._common_field_schema.<locals>.json_schema_update_func at 0x7f45e27247c0>],
                                   'pydantic_js_functions': []},
                      'required': True,
                      'schema': {'metadata': {'pydantic.internal.needs_apply_discriminated_union': False},
                                 'type': 'bool'},
                      'type': 'typed-dict-field'}},
 'metadata': {'pydantic.internal.needs_apply_discriminated_union': False,
              'pydantic_js_annotation_functions': [],
              'pydantic_js_functions': [functools.partial(<function modify_model_json_schema at 0x7f45e2668ea0>, cls=<class '__main__.Bar'>)],
              'pydantic_typed_dict_cls': <class '__main__.Bar'>},
 'ref': '__main__.Bar:139938128503376[bool:94329286120256]',
 'type': 'typed-dict'}
```
`type` is actually `any` here which is why it passes. When combined with TypeVar defaults, it will always resolve to use the default instead of the value it's supposed to be replaced by.

**Comment by jploskey** [comment]
Currently running into this issue. Is there any chance this could be picked up again?
