### ISSUE TITLE
fastapi+pydantic: Internal Server Error

### ISSUE THREAD

**Issue by BriskyGates** [pydantic/pydantic#8053]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

First,thank you for your all amazing work, the Pydantic v2 is awesome!

the whole error info of backend:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\routing.py", line 272, in app
    raise RequestValidationError(_normalize_errors(errors), body=body)
fastapi.exceptions.RequestValidationError: [{'type': 'embedding_norm_is_null', 'loc': ('body', 'embedding'), 'msg': "embedding_norm FieldValidationInfo(config={'title': 'RecallDocuModel'}, context=None, data={'query': 'string', 'embedding': '', 'top_k': 10, 'company_list': [], 'industry_list': [], 'limit_company': [], 'sw_industry_dict': SWIndModel(sw_industry_code_level1=[], sw_industry_code_level2=[]), 'time_recv_req': 0.0, 'time_vec_norm': 0.0}, field_name='embedding_norm') is null", 'input': '', 'ctx': {'embedding_norm': FieldValidationInfo(config={'title': 'RecallDocuModel'}, context=None, data={'query': 'string', 'embedding': '', 'top_k': 10, 'company_list': [], 'industry_list': [], 'limit_company': [], 'sw_industry_dict': SWIndModel(sw_industry_code_level1=[], sw_industry_code_level2=[]), 'time_recv_req': 0.0, 'time_vec_norm': 0.0}, field_name='embedding_norm')}}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 322, in jsonable_encoder
    data = dict(obj)
TypeError: 'pydantic_core._pydantic_core.ValidationInfo' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 327, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\starlette\middleware\exceptions.py", line 88, in __call__
    response = await handler(request, exc)
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\exception_handlers.py", line 25, in request_validation_exception_handler
    content={"detail": jsonable_encoder(exc.errors())},
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 301, in jsonable_encoder
    jsonable_encoder(
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "D:\code_project\vene_all\cicc_report_project\lib\site-packages\fastapi\encoders.py", line 330, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'pydantic_core._pydantic_core.ValidationInfo' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

the whole result of frontend:
Internal Server Error

expect the result of frontend(something just like this in pydantic v1):
("detail":[["loc":["body","id"],"msg":"value is not a valid integer","type":"type_error.integer")])

### Example Code

```Python
class RecallDocuModel(BaseModel):
    query: str = Field(..., description='query文本')
    embedding: str = Field("", description='')
    embedding_norm: Any = Field("", description='', alias='embedding')

    @field_validator("embedding_norm", mode='after')
    def check_embedding_norm(cls, v, values):
        if not v:
            raise PydanticCustomError(
                "embedding_norm_is_null",
                "embedding_norm {embedding_norm} is null",
                {"embedding_norm": values},
            )            # raise NotImplementedError('embedding not null')
        # print(v,type(v),len(v))
        # assert len(v)==0
        begin_time = time.time()
        print(f'begin_vector_norm {begin_time}')
        array = v.split(',')
        array = list(map(float, array))
        array = normalize_vector(array)
        print(f'end_vector_norm {time.time() - begin_time}')
        return array
        pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: D:\code_project\vene_all\cicc_report_project\Lib\site-packages\pydantic
               python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by Viicos** [comment]
You shouldn't use `PydanticCustomError`, instead raise a `ValueError`:

https://docs.pydantic.dev/latest/errors/errors/

https://docs.pydantic.dev/latest/concepts/validators/#field-validators

**Comment by samuelcolvin** [comment]
Thanks for the kind words.

This is a question not a bug, please use discussions for questions.

The last argument to the field validator is `info` not `values`. 

You need to use `info.data`, not `values`, see https://docs.pydantic.dev/latest/api/pydantic_core_schema/#pydantic_core.core_schema.ValidationInfo
