### ISSUE TITLE
Input wont be casted when using Literal instead of int

### ISSUE THREAD

**Issue by VirtualNonsense** [pydantic/pydantic#8104]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey!
I stumbled across something that appears to be a parsing issue. When using a Literal instead of an int, the input will not be cast properly before validating.

Here is the output from the skript bellow.
```shell
{'working_field': '7', 'broken_field': '6'}
Traceback (most recent call last):
  File "C:\Users\USER\Repositories\intern\Python\pydantic_tests\bug.py", line 18, in <module>
    t = ExampleClass(**parser["test"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.virtualenvs\pydantic_tests\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ExampleClass
broken_field
  Input should be 5, 6, 7 or 8 [type=literal_error, input_value='6', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/literal_error
```

### Example Code

```Python
import configparser
from typing import Literal

from pydantic import Field, BaseModel


class ExampleClass(BaseModel):
    working_field: int = Field(8, le=8, ge=5)
    broken_field: Literal[5, 6, 7, 8] = Field(8)


if __name__ == '__main__':
    parser = configparser.ConfigParser()
    parser.read_string("[test]\n"
                       "working_field = 7\n"
                       "broken_field = 6")
    print(dict(parser["test"]))
    t = ExampleClass(**parser["test"])
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\USER\.virtualenvs\pydantic_tests\Lib\site-packages\pydantic
               python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @VirtualNonsense,

This is the expected behavior. A `literal_error` is raised in this case. You can read more about that type of error [in the docs](https://docs.pydantic.dev/latest/errors/validation_errors/#literal_error).

Here's more detail on that error, for your example
```py
from pprint import pprint
from typing import Literal

from pydantic import Field, BaseModel, ValidationError


class ExampleClass(BaseModel):
    working_field: int = Field(8, le=8, ge=5)
    broken_field: Literal[5, 6, 7, 8] = Field(8)


t_data = {'working_field': 7, 'broken_field': '6'}
try:
    t = ExampleClass.model_validate(t_data, strict=False)
except ValidationError as e:
    pprint(e.errors())
    """
    [
        {
            'ctx': {'expected': '5, 6, 7 or 8'},
            'input': '6',
            'loc': ('broken_field',),
            'msg': 'Input should be 5, 6, 7 or 8',
            'type': 'literal_error',
            'url': 'https://errors.pydantic.dev/2.5/v/literal_error'
        }
    ]
    """
```

If you still want this input to be valid, you can design a custom validator to do attempt type-coercion. Let me know if you have any questions!
