### ISSUE TITLE
`core_schema.union_schema()` matters order in custom type after 2.5.0

### ISSUE THREAD

**Issue by hard-coders** [pydantic/pydantic#8127]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I declared a new type using `__get_pydantic_core_schema__,` and it worked fine before updating 2.5.0.

I think `core_schema.union_schema()` is affected by its orders. An error also changes when changing `core_schema.no_info_plain_validator_function()` orders.

### Example Code

```Python
from collections.abc import Callable
from typing import Any

from pydantic import BaseModel
from pydantic_core import core_schema


class SomeModel(BaseModel):
    key: str


class T:
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: Callable[[Any], core_schema.CoreSchema],
    ) -> core_schema.CoreSchema:
        def validate_from_some_model(v: SomeModel) -> dict:
            assert v.key is not None
            return {"key": v.key}

        def validate_from_dict(v: dict) -> dict:
            assert v.get("key") is not None
            return v

        python_schema = core_schema.union_schema(
            [
                core_schema.no_info_plain_validator_function(validate_from_dict),
                core_schema.no_info_plain_validator_function(validate_from_some_model),
            ]
        )

        return core_schema.json_or_python_schema(
            json_schema=python_schema,
            python_schema=core_schema.union_schema(
                [
                    python_schema,
                    core_schema.is_instance_schema(dict),
                ]
            ),
        )


class Bar(BaseModel):
    bar: T


# python repl
>>> Bar(bar={"key": "key"})  # ok
Bar(bar={'key': 'key'})
>>> Bar(bar=SomeModel(key="key"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/spike/Library/Caches/pypoetry/virtualenvs/pydantic-bug-ALq1cXaj-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
  File "/Users/spike/examples/pydantic-bug/bug.py", line 24, in validate_from_dict
    assert v.get("key") is not None
           ^^^^^
  File "/Users/spike/Library/Caches/pypoetry/virtualenvs/pydantic-bug-ALq1cXaj-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SomeModel' object has no attribute 'get'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/spike/Library/Caches/pypoetry/virtualenvs/pydantic-bug-ALq1cXaj-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @hard-coders,

Actually, the issue here is quite similar to that mentioned in #8111.

Your custom validator is raising an `AttributeError` instead of an `AssertionError`. The previous behavior from `2.4.2` and earlier was actually incorrectly handling the `AttributeError` that was being raised. The behavior as it is now is more correct, but this fix explains why your code no longer worked. You can make the following change so that everything will work as expected:

```py
from typing import Any, Callable

from pydantic import BaseModel
from pydantic_core import core_schema


class SomeModel(BaseModel):
    key: str


class T:
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: Callable[[Any], core_schema.CoreSchema],
    ) -> core_schema.CoreSchema:
        def validate_from_some_model(v: SomeModel) -> dict:
            assert v.key is not None
            return {"key": v.key}

        def validate_from_dict(v: dict) -> dict:
            assert isinstance(v, dict)  # <-- note the extra `assert` here
            assert v.get("key") is not None
            return v

        python_schema = core_schema.union_schema(
            [
                core_schema.no_info_plain_validator_function(validate_from_dict),
                core_schema.no_info_plain_validator_function(validate_from_some_model),
            ]
        )

        return core_schema.json_or_python_schema(
            json_schema=python_schema,
            python_schema=core_schema.union_schema(
                [
                    python_schema,
                    core_schema.is_instance_schema(dict),
                ]
            ),
        )


class Bar(BaseModel):
    bar: T


assert Bar(bar={"key": "key"})  == Bar(bar={'key': 'key'})
assert Bar(bar=SomeModel(key="key")) == Bar(bar={'key': 'key'})
```

**Comment by hard-coders** [comment]
Thanks @sydney-runkle !
I read #8111, and now I understand it's not a bug but a feature. In addition, your suggestion and #8111 help a lot :)
