### ISSUE TITLE
Parse default value of ImportString

### ISSUE THREAD

**Issue by dolfinus** [pydantic/pydantic#8128]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There is mentioned in documentation:

> A known limitation: setting a default value to a string won't result in validation (thus evaluation). This is actively being worked on.

As of pydantic 2.5.0 the issue is still present. And I don't see any open issue or pull request related to this. 

[Here](https://github.com/pydantic/pydantic/pull/6456) I see an workaround like:
```python
from pydantic import BaseModel, ImportString

class MyModel(BaseModel):
  module = ImportString.import_string('os.path')  # equivalent to `module = os.path`
```

Which does not work:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in ImportStringModel
AttributeError: type object 'ImportString' has no attribute 'import_string'
```

ImportString also does not support passing import string as constructor argument:
```python
>>> ImportString('os.path')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ImportString() takes no arguments
```

The only working workaround I get is this:
```python
from pydantic import BaseModel, ImportString, validator

class MyModel(BaseModel):
    attr: ImportString = ""

    @validator("attr", always=True, pre=True)
    def _default_sttr_value(cls, value):
        if value:
            return value

        import math
        return math.cos

assert MyModel().attr == math.cos
assert MyModel(attr="math.sin").attr == math.sin

```

### Example Code

```Python
import math
from pydantic import BaseModel, ImportString

class MyModel(BaseModel):
  attr: ImportString = "math.cos"

assert MyModel().attr == "math.cos"  # not parsed
assert MyModel(attr="math.sin").attr == math.sin  # parsed
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/maxim/Repo/horizon/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
                     platform: Linux-6.6.0-1-MANJARO-x86_64-with-glibc2.38
             related packages: mypy-1.7.0 pydantic-settings-2.0.3 fastapi-0.103.2 typing_extensions-4.7.1
```

**Comment by sydney-runkle** [comment]
Hi @dolfinus,

You can use the `validate_default` flag to resolve this issue.

```py
import math
from pydantic import BaseModel, Field, ImportString

class MyModel(BaseModel):
  attr: ImportString = Field(default="math.cos", validate_default=True)

assert MyModel().attr == math.cos  # parsed
assert MyModel(attr="math.sin").attr == math.sin  # parsed
```

**Comment by dolfinus** [comment]
Could you please update documentation to include this?

**Comment by sydney-runkle** [comment]
Sure thing!

**Comment by dolfinus** [comment]
> could you please open a PR with this change to the docs?

#8386
