### ISSUE TITLE
Instantiating a nested model with `dict` raises `TypeError`

### ISSUE THREAD

**Issue by dvnatanael** [pydantic/pydantic#8183]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When upgrading from pydantic 2.4.2 to 2.5.1, model fields of type `BaseModel | Literal[True]` or `BaseModel | Literal[False]` can no longer be instantiated using a model `dict`.

```
Traceback (most recent call last):
  File ".../test.py", line 10, in <module>
    Bar(foo={"x": 42})
  File ".../.pyenv/versions/test-pydantic25/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
TypeError: unhashable type: 'dict'
```

### Example Code

```Python
from pydantic import BaseModel
from typing import Literal

class Foo(BaseModel):
    x: int

class Bar(BaseModel):
    foo: Foo | Literal[True]

Bar(foo={"x": 42})  # TypeError: unhashable type: 'dict'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: .../.pyenv/versions/3.11.6/envs/test-pydantic25/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Nov 21 2023, 10:15:54) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @dvnatanael,

This does look like a bug introduced by our most recent minor release. Thanks for reporting this. We'll look into a fix to get out with our next patch release.
