### ISSUE TITLE
Failed model_validate_json() with annotation dict[Literal[...], ...]

### ISSUE THREAD

**Issue by imacat** [pydantic/pydantic#8189]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi.  The attached example code works with Pydantic 2.4, but not 2.5.  model_validate_json() complaints that the keys are invalid, while actually they are valid.

```
(venv) % ./pydantic-test.py
Traceback (most recent call last):
  File "/home/imacat/Dropbox/home/src/pydantic-test/./pydantic-test.py", line 13, in <module>
    FieldMap.model_validate_json(json.dumps(obj))
  File "/home/imacat/Dropbox/home/src/pydantic-test/venv/lib/python3.11/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 3 validation errors for FieldMap
map.a.[key]
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='a', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
map.b.[key]
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='b', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
map.c.[key]
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='c', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
```

### Example Code

```Python
#! env python3
import json
from typing import Literal
from pydantic import BaseModel


class FieldMap(BaseModel):
    map: dict[Literal["a", "b", "c"], str]


obj = {"map": {"a": "A", "b": "B", "c": "C"}}
FieldMap.model_validate(obj)
FieldMap.model_validate_json(json.dumps(obj))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/imacat/Dropbox/home/src/pydantic-test/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  1 2023, 11:46:00) [GCC 10.2.1 20210110]
                     platform: Linux-5.10.0-26-amd64-x86_64-with-glibc2.31
             related packages: typing_extensions-4.8.0
```

**Comment by Viicos** [comment]
Duplicate: https://github.com/pydantic/pydantic/issues/8133

**Comment by sydney-runkle** [comment]
Yep, fix should be released with `2.5.2` soon 👍

**Comment by mehran66** [comment]
@sydney-runkle I upgraded to version 2.5.2, but still get this error when using `model_validate_json()` . Here is the error that I get:

  return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
  NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.
  
  I am not getting such error when using version 2.4

**Comment by sydney-runkle** [comment]
@mehran66,

Do you have `pydantic-core==2.14.5` installed? You'll need that version for the fix.

**Comment by mehran66** [comment]
I ram running this inside a docker. When having pydantic 2.5.2, it failed while it is working just fine with version 2.4

**Comment by sydney-runkle** [comment]
What version of `pydantic-core` do you have installed?

**Comment by mehran66** [comment]
root@d77c1c843e61:/home/model-server# pip show pydantic
Name: pydantic
Version: 2.5.2

root@d77c1c843e61:/home/model-server# pip show pydantic-core
Name: pydantic_core
Version: 2.14.5

**Comment by sydney-runkle** [comment]
Hmm,

Using those two versions, the code above runs just fine for me. Could you provide the code snippet with which you're experiencing issues?

**Comment by mehran66** [comment]
I simply get an error wherever I have `model_validate_json` and the issue get resolved if I use `model_validate(json.load())` instead.

**Comment by sydney-runkle** [comment]
@mehran66,

Could you please provide a reproducible code snippet with a minimal example?

**Comment by mehran66** [comment]
Unfortunately I cannot share my data b/c it is proprietary and when I run `model_validate_json` on a simple json data, it works fine.

**Comment by sydney-runkle** [comment]
Unfortunately, it's hard for us to help you if we don't have an example of the issue you're facing. Could you come up with a minimal example not using your proprietary data?

**Comment by rbavery** [comment]
@sydney-runkle I'm also getting the same error, I have a reproducible example.


```
from pydantic import BaseModel, Field, FilePath, AnyUrl
from typing import Optional, List, Tuple, Dict, Literal, Any
from uuid import uuid4
import numpy as np
import re

# Pydantic Models
class TensorSignature(BaseModel):
    name: Optional[str] = None
    dtype: Any = Field(...)
    shape: Tuple[int, ...] | List[int] = Field(...)

class ModelSignature(BaseModel):
    inputs: List[TensorSignature]
    outputs: List[TensorSignature]
    params: Optional[Dict[str, int | float | str]] = None

    class Config:
        arbitrary_types_allowed = True

class RuntimeConfig(BaseModel):
    environment: str

class S3Path(AnyUrl):
    allowed_schemes = {'s3'}
    user_required = False
    max_length = 1023
    min_length = 8

    @classmethod
    def validate_s3_url(cls, v):
        if not v.startswith('s3://'):
            raise ValueError('S3 path must start with s3://')
        return v

    @classmethod
    def validate_bucket_name(cls, v):
        if not v:
            raise ValueError('Bucket name cannot be empty')
        return v

    @classmethod
    def validate_key(cls, v):
        if '//' in v:
            raise ValueError('Key must not contain double slashes')
        return v.strip('/')

class ModelArtifact(BaseModel):
    path: S3Path | FilePath | str = Field(...)
    additional_files: Optional[Dict[str, FilePath]] = None

    class Config:
        arbitrary_types_allowed = True

class ClassMap(BaseModel):
    class_to_label_id: Dict[str, int]

    @property
    def label_id_to_class(self) -> Dict[int, str]:
        return {v: k for k, v in self.class_to_label_id.items()}

class ModelMetadata(BaseModel):
    signatures: ModelSignature
    artifact: ModelArtifact
    id: str = Field(default_factory=lambda: uuid4().hex)
    class_map: ClassMap
    runtime_config: Optional[RuntimeConfig] = None
    name: str
    ml_model_type: Optional[str] = None
    ml_model_processor_type: Optional[Literal["cpu", "gpu", "tpu", "mps"]] = None
    ml_model_learning_approach: Optional[str] = None
    ml_model_prediction_type: Optional[Literal["object-detection", "classification", "segmentation", "regression"]] = None
    ml_model_architecture: Optional[str] = None

    class Config:
        arbitrary_types_allowed = True

# Functions to create, serialize, and deserialize ModelMetadata
def create_metadata():
    input_sig = TensorSignature(name='input_tensor', dtype='float32', shape=(-1, 13, 64, 64))
    output_sig = TensorSignature(name='output_tensor', dtype='float32', shape=(-1, 10))
    model_sig = ModelSignature(inputs=[input_sig], outputs=[output_sig])
    model_artifact = ModelArtifact(path="s3://example/s3/uri/model.pt")
    class_map = ClassMap(class_to_label_id={
        'Annual Crop': 0, 'Forest': 1, 'Herbaceous Vegetation': 2, 'Highway': 3,
        'Industrial Buildings': 4, 'Pasture': 5, 'Permanent Crop': 6,
        'Residential Buildings': 7, 'River': 8, 'SeaLake': 9
    })
    return ModelMetadata(name="eurosat", class_map=class_map, signatures=model_sig, artifact=model_artifact, ml_model_processor_type="cpu")

def metadata_json(metadata: ModelMetadata) -> str:
    return metadata.model_dump_json(indent=2)

def model_metadata_json_operations(json_str: str) -> ModelMetadata:
    return ModelMetadata.model_validate_json(json_str)

# Running the functions end-to-end
metadata = create_metadata()
json_str = metadata_json(metadata)
model_metadata = model_metadata_json_operations(json_str)

print("Model Metadata Name:", model_metadata.name)
```

```
Traceback (most recent call last):
  File "/home/rave/work/dlm-extension/stac_model/model_metadata.py", line 100, in <module>
    model_metadata = model_metadata_json_operations(json_str)
  File "/home/rave/work/dlm-extension/stac_model/model_metadata.py", line 95, in model_metadata_json_operations
    return ModelMetadata.model_validate_json(json_str)
  File "/home/rave/miniforge3/lib/python3.10/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.
```

This used to work for me recently, I could save JSON out and validate it even when using the TensorInfo or S3Path model.

**Comment by Jylpah** [comment]
FYI @rbavery , @mehran66 
I am getting the same error message when using a custom type with a `RootModel`. I am not certain is it related, but since this issue is closed, I created a new one #8455
