### ISSUE TITLE
validation error on enum union

### ISSUE THREAD

**Issue by felixgao** [pydantic/pydantic#8238]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am not sure if fi am using the library correct or there is a better way to do this.  I am working on some code that require a field from the basemodel to have an union of enum types.   The exact enum type depends on the subclass of the basemodel that it needs when it created at run time.  

When I try to add the enum either as a union type of the basemodel or changing the type of the enum in a derived classes, I am encountering the following error. 

```
Traceback (most recent call last):
  File "/Users/ggao/test-enum/test.py", line 55, in <module>
    t2 = DataModelA(name="name", enum=EnumB.B1, value="value")
  File "/Users/ggao/test-enum/.venv/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DataModelA
enum
  Value error, Invalid enum value: B1 [type=value_error, input_value=<EnumB.B1: 'B1'>, input_type=EnumB]
    For further inform
```

### Example Code

```Python
from enum import Enum
from pydantic import BaseModel, field_validator


class EnumA(str, Enum):
    A1 = "A1"
    A2 = "A2"
    
class EnumB(str, Enum):
    B1 = "B1"
    B2 = "B2"
    
class EnumC(str, Enum):
    C1 = "C1"
    C2 = "C2"
    

class BaseDataModel(BaseModel):
    name: str
    enum: EnumA | EnumB | EnumC 
    
    
class DataModelA(BaseDataModel):
    value: str
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumA):
        if enum in EnumA:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")
    
class DataModelB(BaseDataModel):
    value: str
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumB):
        if enum in EnumB:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")

class DataModelC(BaseDataModel):
    value: str
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumC):
        if enum in EnumC:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")

if __name__ == '__main__':
    t1 = DataModelA(name="name", enum=EnumA.A1, value="value")
    t2 = DataModelA(name="name", enum=EnumB.B1, value="value")
    t3 = DataModelA(name="name", enum=EnumC.C1, value="value")
    
    print(t1)
    print(t2)
    print(t3)
```

I also tried this variant and having the same problem

```python
from enum import Enum
import enum
from pydantic import BaseModel, field_validator


class EnumA(str, Enum):
    A1 = "A1"
    A2 = "A2"
    
class EnumB(str, Enum):
    B1 = "B1"
    B2 = "B2"
    
class EnumC(str, Enum):
    C1 = "C1"
    C2 = "C2"
    

class BaseDataModel(BaseModel):
    name: str
    
    
class DataModelA(BaseDataModel):
    value: str
    enum: EnumA
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumA):
        if enum in EnumA:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")
    
class DataModelB(BaseDataModel):
    value: str
    enum: EnumB
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumB):
        if enum in EnumB:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")

class DataModelC(BaseDataModel):
    value: str
    enum: EnumC
    
    @field_validator("enum", mode="before")
    def validate_enum(cls, enum: EnumC):
        if enum in EnumC:
            return enum
        raise ValueError(f"Invalid enum value: {enum}")

if __name__ == '__main__':
    t1 = DataModelA(name="name", enum=EnumA.A1, value="value")
    t2 = DataModelA(name="name", enum=EnumB.B1, value="value")
    t3 = DataModelA(name="name", enum=EnumC.C1, value="value")
    
    print(t1)
    print(t2)
    print(t3)
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/ggao/test-enum/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Jan 30 2023, 13:16:28) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.5.2-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
@felixgao,

Do you experience this same problem using version `2.5.2`? We added some fixes with `Enum` types recently...

**Comment by sydney-runkle** [comment]
@felixgao,

I'm guessing this is what you're looking for. Looks like you had some errors with the types you were initializing at the end of your snippet.

```py
from typing import Union

from enum import Enum
from pydantic import BaseModel, field_validator


class EnumA(str, Enum):
    A1 = "A1"
    A2 = "A2"


class EnumB(str, Enum):
    B1 = "B1"
    B2 = "B2"


class EnumC(str, Enum):
    C1 = "C1"
    C2 = "C2"


class BaseDataModel(BaseModel):
    name: str
    enum: Union[EnumA, EnumB, EnumC]


class DataModelA(BaseDataModel):
    value: str
    enum: EnumA


class DataModelB(BaseDataModel):
    value: str
    enum: EnumB


class DataModelC(BaseDataModel):
    value: str
    enum: EnumC


if __name__ == '__main__':
    t1 = DataModelA(name="name", enum=EnumA.A1, value="value")
    t2 = DataModelB(name="name", enum=EnumB.B1, value="value")
    t3 = DataModelC(name="name", enum=EnumC.C1, value="value")

    print(t1)
    #> name='name' enum=<EnumA.A1: 'A1'> value='value'
    print(t2)
    #> name='name' enum=<EnumB.B1: 'B1'> value='value'
    print(t3)
    #> name='name' enum=<EnumC.C1: 'C1'> value='value'
```

**Comment by felixgao** [comment]
oh yea thanks for catching that brain fart.
