### ISSUE TITLE
Methods dynamically decorated with `validate_call` raises `TypeError` when accessed 

### ISSUE THREAD

**Issue by tibdex** [pydantic/pydantic#8245]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Decorating a method manually with `@validate_call` works fine but decorating one dynamically raises the following error when accessing the method from the class (not an instance):

```python
Traceback (most recent call last):
  File "/Users/.../test/test.py", line 20, in <module>
    assert Foo.baz
  File "/Users/.../test/.venv/lib/python3.9/site-packages/pydantic/_internal/_validate_call.py", line 123, in __get__
    return objtype.__getattribute__(objtype, self._name)  # type: ignore
TypeError: attribute name must be string, not 'NoneType'
```

I'm not sure how much related to #8146 this is.

### Example Code

```Python
from pydantic import validate_call


class Foo:
    @validate_call
    def bar(self, value: str) -> str:
        return f"bar-{value}"

    def baz(self, value: str) -> str:
        return f"baz-{value}"


Foo.baz = validate_call(Foo.baz)

foo = Foo()
assert foo.bar("qux") == "bar-qux"
assert foo.baz("qux") == "baz-qux"

assert Foo.bar
assert Foo.baz  # Raises `TypeError: attribute name must be string, not 'NoneType'`
assert hasattr(Foo, "baz")  # Raises too.
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=false
                 install path: /Users/.../test/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Nov  9 2023, 15:24:25)  [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: mypy-1.6.1 typing_extensions-4.6.1
```

**Comment by sydney-runkle** [comment]
@tibdex,

Thanks for reporting this. Should be a pretty easy fix. I'll fix this tomorrow 🐛!

**Comment by jusexton** [comment]
I know you said you'd tackle this tomorrow @sydney-runkle but looked like a simple and fun fix. I went ahead and created a PR, I hope that's alright.

I'm not super knowledgeable on custom python descriptors so if there is a better solution than the one presented in the PR let me know!
