### ISSUE TITLE
Unable to create an instance for a model that uses alias in the field

### ISSUE THREAD

**Issue by alamathe1** [pydantic/pydantic#8287]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using alias in an Pydantic model is throwing error. The reason for including `alias` is to ensure it works for the usage in:

```
runtime_manifest = {
    "schema-version":"1.0",
    "name":"Random",
    "version":"1.0",
    "type":"synthetic-sensor",
    "asset":"lib.so"
}

temp = Manifest(**runtime_manifest)
print(temp)
```

### Example Code

```Python
import typing
import pydantic



class Manifest(pydantic.BaseModel):
    schema_version: typing.Optional[str] = pydantic.Field(alias="schema-version")
    name: str
    version: str
    type_: str = pydantic.Field(alias="type")
    asset: str


manifest = Manifest(
    schema_version="1.0",
    name="Random",
    version="1.0",
    type="synthetic-sensor",
    asset="lib.so"
)


print(manifest)
```

### Python, Pydantic & OS Version

```Text
Python 3.9.6
Pydantic 2.5.2
macOS Ventura 13.6

10:11:01 lamathe@3c22fb02d71a Desktop → python3 pydan.py
Traceback (most recent call last):
  File "/Users/lamathe/Desktop/pydan.py", line 14, in <module>
    runtime_manifest = Manifest(
  File "/Users/lamathe/Library/Python/3.9/lib/python/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Manifest
schema-version
  Field required [type=missing, input_value={'schema_version': '1.0',...sor', 'asset': 'lib.so'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

**Comment by sydney-runkle** [comment]
@alamathe1,

You can do one of the following:

```py
import typing
import pydantic



class Manifest(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(populate_by_name=True)  # <-- this

    schema_version: typing.Optional[str] = pydantic.Field(alias="schema-version")
    name: str
    version: str
    type_: str = pydantic.Field(alias="type")
    asset: str


manifest = Manifest(
    schema_version="1.0",
    name="Random",
    version="1.0",
    type="synthetic-sensor",
    asset="lib.so"
)


print(manifest)
```

or 

```py
import typing
import pydantic



class Manifest(pydantic.BaseModel):
    schema_version: typing.Optional[str] = pydantic.Field(alias="schema-version")
    name: str
    version: str
    type_: str = pydantic.Field(alias="type")
    asset: str


manifest = Manifest(
    schema-version="1.0",  # <-- this
    name="Random",
    version="1.0",
    type="synthetic-sensor",
    asset="lib.so"
)


print(manifest)
```
