### ISSUE TITLE
`RecursionError` while using nested model with references to parent

### ISSUE THREAD

**Issue by mstechly** [pydantic/pydantic#8310]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have implemented a hierarchical tree-like object, where each `Operation` has both `parent` and `children`.
When I try to run the example code, I get the following error:

```
Traceback (most recent call last):
  File "/Users/mstechly/Documents/code/2023-11-30-serialization/knifey/pydantic_test.py", line 30, in <module>
    op_1 == op_2
  File "/Users/mstechly/.pyenv/versions/2023-11-30-serialization/lib/python3.10/site-packages/pydantic/main.py", line 873, in __eq__
    and self.__dict__ == other.__dict__
  File "/Users/mstechly/.pyenv/versions/2023-11-30-serialization/lib/python3.10/site-packages/pydantic/main.py", line 873, in __eq__
    and self.__dict__ == other.__dict__
  File "/Users/mstechly/.pyenv/versions/2023-11-30-serialization/lib/python3.10/site-packages/pydantic/main.py", line 873, in __eq__
    and self.__dict__ == other.__dict__
  [Previous line repeated 280 more times]
  File "/Users/mstechly/.pyenv/versions/2023-11-30-serialization/lib/python3.10/site-packages/pydantic/main.py", line 864, in __eq__
    if isinstance(other, BaseModel):
  File "/Users/mstechly/.pyenv/versions/2023-11-30-serialization/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 226, in __instancecheck__
    return hasattr(instance, '__pydantic_validator__') and super().__instancecheck__(instance)
  File "/Users/mstechly/.pyenv/versions/3.10.10/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```
The thing that's causing the issues is this: `child.parent = self` , as if I comment it out it all works.
However, the serialization with `model_dump` works well (see `exclude=True`).

### Example Code

```Python
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field

class Operation(BaseModel):
    name: str
    parent: Optional["Operation"] = Field(exclude=True, default=None)
    children: Dict[str, "Operation"] = Field(default_factory=dict)

    def __init__(self, **data: dict[str, Any]):
        super().__init__(**data)
        for child in self.children.values():
                child.parent = self


def example_operation():
    child_1_op = Operation(name="child_1")
    child_2_op = Operation(name="child_2")

    my_op = Operation(
        name="root",
        children={"child_1": child_1_op, "child_2": child_2_op},
    )

    return my_op


if __name__ == "__main__":
    op_1 = example_operation()
    op_2 = example_operation()
    op_1 == op_2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /Users/mstechly/.pyenv/versions/3.10.10/envs/2023-11-30-serialization/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Oct  6 2023, 13:57:03) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.3-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 mypy-1.7.1
```
```

**Comment by alexmojaki** [comment]
Standard dataclasses do the same:

```python
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class A:
    child: A = None
    parent: A = None


def make_a():
    a = A(A())
    a.child.parent = a
    return a


print(make_a() == make_a())
```

Also plain dictionaries:

```python
def make_d():
    parent = {}
    child = {'parent': parent}
    parent['child'] = child
    return parent


print(make_d() == make_d())
```

This isn't something that I see easily changing in Pydantic. In the meantime you can define your own `__eq__` on the model:

```python
    def __eq__(self, other):
        return self.name == other.name and self.children == other.children
```

**Comment by andresliszt** [comment]
I think this is not a pydantic issue, there is an infinite reference in your class definition, if you try taking out the `BaseModel` you won't get an error here 

```python
class Operation:
    def __init__(self, name, parent = None, children = dict()):
        self.name = name
        self.parent = parent
        self.children = children
        for child in self.children.values():
                child.parent = self

def example_operation():
    child_1_op = Operation(name="child_1")
    child_2_op = Operation(name="child_2")

    my_op = Operation(
        name="root",children={"child_1": child_1_op, "child_2": child_2_op},
    )
    return my_op

op_1 = example_operation()
op_2 = example_operation()
op_1 == op_2

op_1 == op_2 # False

```
you will get `False` without problems because the default `__eq__` uses the `is` operator, but if you try to access to the attributes you will see the recursion

`op_1.children['child_1'].parent.children['child_1'].parent # You can follow this pattern as many times you want`

**Comment by mstechly** [comment]
Fair enough, thanks!
I was wondering if it would make sense to add some functionality in `pydantic` that would allow to exclude certain fields when running `__eq__`? This might be rare enough case that it doesn't make sense though.

**Comment by sydney-runkle** [comment]
Hi @mstechly,

I think you're correct, this is a rare enough use case that I don't think it makes sense to change the `__eq__` behavior.
