### ISSUE TITLE
Error with double wrapping `TypeAliasType`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8317]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

see example

### Example Code

```Python
import typing_extensions
from pydantic import RootModel


Bar = typing_extensions.TypeAliasType('Bar', int)


class Foo(RootModel):
    root: typing_extensions.TypeAliasType('Bar', Bar)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 26 2023, 13:55:09) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.1-arm64-arm-64bit
             related packages: pyright-1.1.335 typing_extensions-4.8.0 fastapi-0.104.1 mypy-1.7.0 email-validator-2.1.0.post1
```

**Comment by rijenkii** [comment]
Similar error, but without `RootModel` and without explicit `TypeAliasType`:
```python
Python 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel
>>> class _Foo1(BaseModel):
...   foo: int
... 
>>> type Foo = _Foo1
>>> class Bar(BaseModel):
...   foo: Foo
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/.../lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 501, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 408, in clean_schema
    schema = validate_core_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 585, in validate_core_schema
    return _validate_core_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.model-fields.fields.foo.schema.definition-ref.ref
  Extra inputs are not permitted [type=extra_forbidden, input_value='__main__.Foo:140500916668112', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```

**Comment by mfisher87** [comment]
Same problem here; `PlotDoyColumn` cannot use the new PEP695 type alias keyword, or I receive an error (at bottom)

```python
type PlotColumn[T] = Annotated[list[T], MinLen(1), MaxLen(366)]                                                                            
type PlotDoyValue = Annotated[int, Ge(1), Le(366)]                                                                                         
PlotDoyColumn = PlotColumn[PlotDoyValue]                                                                                                   
type PlotPointValue = float | None                                                                                                         
PlotPointColumn = PlotColumn[PlotPointValue]
```


```
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.schema.model.schema.model-fields.fields.day_of_water_year.schema.definition-ref.ref
  Extra inputs are not permitted [type=extra_forbidden, input_value='snow_today_webapp_ingest...yColumn:140452253157952', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```

**Comment by Viicos** [comment]
Fixed on `main`, I believe as per https://github.com/pydantic/pydantic/pull/10809.
