### ISSUE TITLE
`TypeAliasType` ref `KeyError`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8320]
See https://github.com/samuelcolvin/FastUI/compare/pydantic-ref-bug?expand=1

To reproduce:
* check that out
* install deps
* run `python -c 'import fastui'`

Exception:

```traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/samuel/code/fastui/src/python-fastui/fastui/__init__.py", line 11, in <module>
    class FastUI(pydantic.RootModel):
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 501, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 405, in clean_schema
    schema = _discriminated_union.apply_discriminators(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_discriminated_union.py", line 60, in apply_discriminators
    return simplify_schema_references(_core_utils.walk_core_schema(schema, inner))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 480, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 431, in walk_core_schema
    return f(schema.copy(), _dispatch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 476, in count_refs
    recurse(definitions[ref], count_refs)
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 207, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 464, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 210, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 219, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 207, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 464, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 210, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 254, in handle_list_schema
    schema['items_schema'] = self.walk(items_schema, f)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 207, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/samuel/code/fastui/env311/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 476, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: 'fastui.components.AnyComponent:4401377552'
```

**Comment by dmontagu** [comment]
More minimal reproductions:

-------

```python
import typing_extensions as _te

from pydantic import BaseModel, TypeAdapter


class Div(BaseModel):
    type: _te.Literal['Div'] = 'Div'
    components: 'AnyComponent'


AnyComponent = _te.TypeAliasType('AnyComponent', Div)

TypeAdapter(AnyComponent)
```
```
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
definitions.definitions.1.definition-ref.ref
  Extra inputs are not permitted [type=extra_forbidden, input_value='__main__.AnyComponent:4346368048', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```

-------

```python
import typing_extensions as _te

from pydantic import BaseModel, TypeAdapter, Field


class Div(BaseModel):
    type: _te.Literal['Div'] = 'Div'
    components: 'AnyComponent'


AnyComponent = _te.TypeAliasType('AnyComponent', _te.Annotated[Div, Field(discriminator='type')])

TypeAdapter(AnyComponent)
```
```
  File "/Users/davidmontague/Programming/pydantic/pydantic/pydantic/_internal/_core_utils.py", line 476, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: '__main__.AnyComponent:4337067376'
```

Looks to be an issue with recursive type aliases that are (or contain as union cases) BaseModels.

**Comment by dmontagu** [comment]
Changing `pydantic._internal._core_utils.validate_core_schema` to
```python
from pydantic_core import SchemaError

def validate_core_schema(schema: CoreSchema) -> CoreSchema:
    if 'PYDANTIC_SKIP_VALIDATING_CORE_SCHEMAS' in os.environ:
        return schema
    try:
        return _validate_core_schema(schema)
    except SchemaError as e:
        pretty_print_core_schema(schema)
        raise
```
You can see:
```python
{
    'type': 'definitions',
    'schema': {
        'type': 'definition-ref',
        'schema_ref': '__main__.AnyComponent:4307210288'
    },
    'definitions': [
        {
            'type': 'model',
            'cls': <class '__main__.Div'>,
            'schema': {
                'type': 'model-fields',
                'fields': {
                    'components': {
                        'type': 'model-field',
                        'schema': {
                            'type': 'definition-ref',
                            'schema_ref': '__main__.AnyComponent:4307210288'
                        }
                    }
                },
                'model_name': 'Div'
            },
            'ref': '__main__.Div:4313912816'
        },
        {
            'type': 'definition-ref',
            'schema_ref': '__main__.Div:4313912816',
            'ref': '__main__.AnyComponent:4307210288'
        }
    ]
}
```

The issue is:
```python
        {
            'type': 'definition-ref',
            'schema_ref': '__main__.Div:4313912816',
            'ref': '__main__.AnyComponent:4307210288'
        }
```
Right now, in `pydantic-core`, we don't allow definition-ref schemas to have refs, but I don't currently see any reason this should be a problem in principle. I'm not sure if it would address everything or just reveal other issues but it seems reasonable to me to support.

**Comment by samuelcolvin** [comment]
I'm getting the same while trying to use a ref for `AnyEvent`:

```py
AnyEvent = TypeAliasType('AnyEvent', Annotated[Union[PageEvent, GoToEvent, BackEvent, AuthEvent], Field(discriminator='type')])
```

[here](https://github.com/pydantic/FastUI/blob/6b7c7cba5250eaf044bc312199fd877878334087/src/python-fastui/fastui/events.py#L35) gives me the same error.

**Comment by dmontagu** [comment]
@samuelcolvin I've pushed branches called `dmontagu/support-indirect-definition-refs` to both pydantic and pydantic-core:

* https://github.com/pydantic/pydantic/compare/dmontagu/support-indirect-definition-refs
* https://github.com/pydantic/pydantic-core/compare/dmontagu/support-indirect-definition-refs

I didn't test extensively, but using both of those branches together seems to resolve this issue, at least it prevents the error on import and some basic validation seemed to work.

I didn't check the JSON schema, etc., and I won't be surprised if we need to do a bit more work, but let me know if this seems to be on the right track.
