### ISSUE TITLE
FastAPI fails with Internal Server Error /openapi.json due to PydanticInvalidForJsonSchema

### ISSUE THREAD

**Issue by BigNerd** [pydantic/pydantic#8328]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The code given below terminates FastAPI with pydantic.errors.PydanticInvalidForJsonSchema
when requesting the URL http://0.0.0.0:5001/docs

The full server log is here:

```
Starting application, once loaded, access at http://127.0.0.1:5001
INFO:     Started server process [8333]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
INFO:     127.0.0.1:50706 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50706 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:50706 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/pythonProject/venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/pythonProject/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/pythonProject/venv/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/applications.py", line 1061, in openapi
    return JSONResponse(self.openapi())
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/applications.py", line 1033, in openapi
    self.openapi_schema = get_openapi(
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/openapi/utils.py", line 475, in get_openapi
    field_mapping, definitions = get_definitions(
  File "/pythonProject/venv/lib/python3.8/site-packages/fastapi/_compat.py", line 227, in get_definitions
    field_mapping, definitions = schema_generator.generate_definitions(
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 377, in generate_definitions
    self.generate_inner(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/main.py", line 603, in __get_pydantic_json_schema__
    return __handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 526, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 212, in modify_model_json_schema
    json_schema = handler(schema_or_field)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 1323, in model_schema
    json_schema = self.generate_inner(schema['schema'])
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 1415, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 1226, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 544, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 2012, in json_schema_update_func
    json_schema = {**handler(core_schema_or_field), **json_schema_update}
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 1294, in model_field_schema
    return self.generate_inner(schema['schema'])
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 552, in generate_inner
    json_schema = current_handler(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 509, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 956, in function_plain_schema
    return self._function_schema(schema)
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 921, in _function_schema
    return self.handle_invalid_for_json_schema(
  File "/pythonProject/venv/lib/python3.8/site-packages/pydantic/json_schema.py", line 2074, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'no-info', 'function': functools.partial(<bound method DataFrame.pydantic_validate of <class 'pandera.typing.pandas.DataFrame'>>, schema_model=SimpleSchema)})

For further information visit https://errors.pydantic.dev/2.5/u/invalid-for-json-schema
```

### Example Code

```Python
import pandera as pa
import uvicorn
from pydantic import BaseModel
from fastapi import FastAPI
from pandera.typing import DataFrame, Series


app = FastAPI()


class SimpleSchema(pa.DataFrameModel):
    str_col: Series[str] = pa.Field(unique=True)


class TestRequest(BaseModel):
    df: DataFrame[SimpleSchema]


@app.post("/test")
def test(request: TestRequest):
    return "OK"


def main():
    uvicorn.run(app, host="0.0.0.0", port=5001)


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.5.2
             pydantic-core version: 2.14.5
             pydantic-core build: profile=release pgo=false
             install path: /pythonProject/venv/lib/python3.8/site-packages/pydantic
              python version: 3.8.12 (default, Feb 22 2022, 09:26:30)  [Clang 13.0.0 (clang-1300.0.29.3)]
             platform: macOS-11.6-x86_64-i386-64bit
             related packages: pydantic-extra-types-2.1.0 typing_extensions-4.8.0 pydantic-settings-2.1.0 fastapi-0.104.1 email-validator-2.1.0.post1
```

### installed packages (pip freeze output):
annotated-types==0.6.0
anyio==3.7.1
attrs==23.1.0
black==23.11.0
certifi==2023.11.17
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
dnspython==2.4.2
email-validator==2.1.0.post1
exceptiongroup==1.2.0
fastapi==0.104.1
frictionless==4.40.8
h11==0.14.0
httpcore==1.0.2
httptools==0.6.1
httpx==0.25.2
idna==3.6
importlib-metadata==7.0.0
importlib-resources==6.1.1
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
markdown-it-py==3.0.0
marko==2.0.2
MarkupSafe==2.1.3
mdurl==0.1.2
multimethod==1.10
mypy-extensions==1.0.0
numpy==1.24.4
orjson==3.9.10
packaging==23.2
pandas==2.0.3
pandera==0.17.2
pathspec==0.11.2
petl==1.7.14
pkgutil_resolve_name==1.3.10
platformdirs==4.1.0
pydantic==2.5.2
pydantic-extra-types==2.1.0
pydantic-settings==2.1.0
pydantic_core==2.14.5
Pygments==2.17.2
python-dateutil==2.8.2
python-dotenv==1.0.0
python-multipart==0.0.6
python-slugify==8.0.1
pytz==2023.3.post1
PyYAML==6.0.1
referencing==0.32.0
requests==2.31.0
rfc3986==2.0.0
rich==13.7.0
rpds-py==0.13.2
shellingham==1.5.4
simpleeval==0.9.13
six==1.16.0
sniffio==1.3.0
starlette==0.27.0
stringcase==1.2.0
tabulate==0.9.0
text-unidecode==1.3
tomli==2.0.1
typeguard==4.1.5
typer==0.9.0
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
ujson==5.8.0
urllib3==2.1.0
uvicorn==0.24.0.post1
uvloop==0.19.0
validators==0.22.0
watchfiles==0.21.0
websockets==12.0
wrapt==1.16.0
zipp==3.17.0

**Comment by sydney-runkle** [comment]
@BigNerd,

Thanks for reporting this. This is due to the fact that your TestRequest model isn't able to generate a json schema. See more details [here](https://docs.pydantic.dev/latest/api/errors/#pydantic.errors.PydanticInvalidForJsonSchema) re the error that you're getting.

See the [`customzing json schema`](https://docs.pydantic.dev/dev/concepts/json_schema/#withjsonschema-annotation) section of the docs re how to resolve this issue.

**Comment by BigNerd** [comment]
Thank you, I was previously assuming it is a bug because it used to work in earlier versions of pydantic and pandera. Anyway, thanks to your help I was now able to figure out after some trial and error, how it can work. Here is my solution in case it might help others, too.

```
from fastapi import FastAPI

import pandera as pa
from pandera.typing import DataFrame, Series

from pydantic import BaseModel, WithJsonSchema
from typing_extensions import Annotated

import uvicorn


app = FastAPI()


class SimpleSchema(pa.DataFrameModel):
    col_1: Series[str]
    col_2: Series[str]


MyDataFrame = Annotated[
    DataFrame[SimpleSchema],
    WithJsonSchema({
        "type": "object",
        "properties": {
            "col_1": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "description": "this is column 1"
            },
            "col_2": {
                "type": "array",
                "items": {
                    "type": "string"
                },
                "description": "this is column 2"
            }
        },
        "description": "this is a data frame"
    })
]


class TestRequest(BaseModel):
    df: MyDataFrame


@app.post("/test")
def test(request: TestRequest):
    return "OK"


def main():
    uvicorn.run(app, host="0.0.0.0", port=5001)


if __name__ == "__main__":
    main()
```
