### ISSUE TITLE
tests/test_validators.py::test_annotated_validator_builtin fails on pypy3.10 on Gentoo

### ISSUE THREAD

**Issue by mgorny** [pydantic/pydantic#8433]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When running tests on PyPy3.10, on Gentoo, I'm getting the following test failure:

```pytb
$ python -m pytest -vv tests/test_validators.py::test_annotated_validator_builtin
========================================================= test session starts =========================================================
platform linux -- Python 3.10.13[pypy-7.3.13-final], pytest-7.4.3, pluggy-1.3.0 -- /tmp/pydantic/.venv/bin/python
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=pytest_benchmark.timers.monotonic disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=True warmup_iterations=100000)
rootdir: /tmp/pydantic
configfile: pyproject.toml
plugins: benchmark-4.0.0, examples-0.0.10
collected 1 item                                                                                                                      

tests/test_validators.py::test_annotated_validator_builtin FAILED                                                               [100%]

============================================================== FAILURES ===============================================================
__________________________________________________ test_annotated_validator_builtin ___________________________________________________

    def test_annotated_validator_builtin() -> None:
        """https://github.com/pydantic/pydantic/issues/6752"""
        TruncatedFloat = Annotated[float, BeforeValidator(int)]
        DateTimeFromIsoFormat = Annotated[datetime, BeforeValidator(datetime.fromisoformat)]
    
        class Model(BaseModel):
            x: TruncatedFloat
            y: DateTimeFromIsoFormat
    
>       m = Model(x=1.234, y='2011-11-04T00:05:23')
E       TypeError: 'ValidationInfo' object cannot be interpreted as an integer

tests/test_validators.py:75: TypeError
======================================================= short test summary info =======================================================
FAILED tests/test_validators.py::test_annotated_validator_builtin - TypeError: 'ValidationInfo' object cannot be interpreted as an integer
========================================================== 1 failed in 1.11s ==========================================================
```

I see that the test passed on CI, so I'm wondering if you could help me figure out why it's failing on this system.

I can reproduce it on 2.5.3 and 19fa86cbfcc7b64c5d59c04c38fa80b497f275a2.

### Example Code

```Python
# in a fresh venv
pip install . pytest pytest-benchmark pytest-examples cloudpickle dirty-equals
python -m pytest -vv tests/test_validators.py::test_annotated_validator_builtin
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0a1
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=false
                 install path: /tmp/pydantic/pydantic
               python version: 3.10.13 (f1607341da97ff5a1e93430b6e8c4af0ad1aa019, Dec 07 2023, 19:21:52) [PyPy 7.3.13 with GCC 13.2.1 20231014]
                     platform: Linux-6.6.8-gentoo-dist-x86_64-AMD_Ryzen_5_3600_6-Core_Processor-with-glibc2.38
             related packages: typing_extensions-4.9.0
                       commit: 19fa86cb
```

**Comment by mgorny** [comment]
Hmm, apparently it's one of the changes we backported from hg. Plain 7.3.13 passes, nightly fails.

CC @mattip, @cfbolz

I can try bisecting it later. It's one of the following commits:

```
6c0a48bf492 add hidden_applevel to _contextvars.Context.run
82ef72c55b9 #4034 make the construction arguments of builtin types more introspectable
f322176e705 #4036: pattern matching classes now use the full isinstance machinery, calling __instancecheck__ too.
25010efff72 typo
c5b1f0207da handle pathlib.path in PyUnicode_FSDecoder, PyUnicode_FSDecoder (issue _3168)
a789b1f3cd3 #4032 LIST_EXTEND bytecode should just let all exceptions through if the second argument is iterable
54dbc8d3079 remove extraneous print from _ssl (issue 4010_)
```

**Comment by mattip** [comment]
On CPython 3.10 and PyPy3.10 7.3.13 `signature(int)` raises
```
>>> from inspect import signature
>>> signature(int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/inspect.py", line 3254, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "/usr/lib/python3.10/inspect.py", line 3002, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib/python3.10/inspect.py", line 2536, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'int'>
```
but on latest PyPy3.10 HEAD it returns
```
>>>> from inspect import signature
>>>> signature(int)
<Signature (x=<no value>, /, base=<no value>)>
```

which then returns `True` from [inspect_validator](https://github.com/pydantic/pydantic/blob/19fa86cbfcc7b64c5d59c04c38fa80b497f275a2/pydantic/_internal/_decorators.py#L515)
 rather than `False`.

The change probably came from 82ef72c55b9

**Comment by mgorny** [comment]
@mattip, thanks. Indeed, reverting that one makes the test pass again.

**Comment by mattip** [comment]
Note that if [this issue](https://github.com/python/cpython/issues/107161) gets fixed, this test will fail on CPython as well. I think the test is faulty, but I cannot figure out what it is meant to do.

**Comment by sydney-runkle** [comment]
Marking as stale for now, and doesn't seem high prio enough to leave open. Feel free ping me if you see a good reason to reopen.
