### ISSUE TITLE
model_validate_json(model_dump_json()) fails on NotImplementedError when using a custom type

### ISSUE THREAD

**Issue by Jylpah** [pydantic/pydantic#8455]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
pydantic version: 2.5.3
pydantic-core version: 2.14.6
```

I have tried to implement `ObjectId` field type using type annotations based on a [SO post](https://stackoverflow.com/questions/76686888/using-bson-objectid-in-pydantic-v2). However, when I try to `model_validate_json()` the JSON generated by `model_dump_json()`, `pydantic` throws a confusing error message:

```
Traceback (most recent call last):
  File "/home/jylpah/src/pydantic-exportables/tests/pydanticv2_bug.py", line 67, in <module>
    neighbours2 := JSONNeighbours.model_validate_json(neighbours.model_dump_json())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jylpah/src/pydantic-exportables/.venv/lib/python3.11/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.

```

I have managed to isolate the issue a bit: 
1. If I use `json.loads()` to parse the JSON string and pass it to `model_validate()`, it all works fine. 
2. If I remove the custom `PyObjectId` type from the `Idx` type alias (see the example below), it all works fine. 

This might be just a case myself implementing the `PyObjectId` the wrong way, but I just can't find a way forward (other than using `json.loads()`) 

The issue have have something in common to the issues reported by [@mehran66](https://github.com/pydantic/pydantic/issues/8189#issuecomment-1823465499) and [@rbavery](https://github.com/pydantic/pydantic/issues/8189#issuecomment-1848226486) in a (closed) issue #8189. 

### Example Code

```Python
from pydantic import (
    BaseModel,
    RootModel,
    Field,
    InstanceOf,
    AfterValidator,
    PlainSerializer,
    WithJsonSchema,
)
from typing import List, Dict, Union, Annotated, Any
from bson.objectid import ObjectId
import json


def validate_object_id(v: Any) -> ObjectId:
    if isinstance(v, ObjectId):
        return v
    if ObjectId.is_valid(v):
        return ObjectId(v)
    raise ValueError("Invalid ObjectId")


PyObjectId = Annotated[
    InstanceOf[ObjectId],
    AfterValidator(validate_object_id),
    PlainSerializer(lambda x: str(x), return_type=str),
    WithJsonSchema({"type": "string"}, mode="serialization"),
]

Idx = Union[str, int, PyObjectId]  # <== PyObjectId in Idx causes the error


class JSONParent(BaseModel):
    name: str
    years: int = 37

    @property
    def index(self) -> Idx:
        """return backend index"""
        return self.name


class JSONNeighbours(RootModel[Dict[Idx, JSONParent]]):
    root: Dict[Idx, JSONParent] = Field(default_factory=dict)


parents: List[JSONParent] = list()
parents.append(JSONParent(name="Erik", years=41))
parents.append(JSONParent(name="Mia", years=36))

neighbours: JSONNeighbours = JSONNeighbours()

for parent in parents:
    neighbours.root[parent.index] = parent

print(neighbours.model_dump_json())

# This one works
assert (
    neighbours2 := JSONNeighbours.model_validate(
        json.loads(neighbours.model_dump_json())
    )
) is not None, "creating a model from loaded json dict failed"

# This one does not work
assert (
    neighbours2 := JSONNeighbours.model_validate_json(neighbours.model_dump_json())
) is not None, "creating a model from JSON dump failed"
```

### Python, Pydantic & OS Version

```Text
% python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/jylpah/src/pydantic-exportables/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 mypy-1.8.0
```

**Comment by Jylpah** [comment]
It seems the error araises from using `InstanceOf[ObjectId]` in the type annotation. I followed another guidance in the same [SO post](https://stackoverflow.com/questions/76686888/using-bson-objectid-in-pydantic-v2) and created a `PyObjectId` class instead of trying to shortcut with the type annotation only. 

This works: 

```
from typing import Any
from bson import ObjectId
from pydantic_core import core_schema
from pydantic import BaseModel


class PyObjectId(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, _source_type: Any, _handler: Any
    ) -> core_schema.CoreSchema:
        return core_schema.json_or_python_schema(
            json_schema=core_schema.str_schema(),
            python_schema=core_schema.union_schema(
                [
                    core_schema.is_instance_schema(ObjectId),
                    core_schema.chain_schema(
                        [
                            core_schema.str_schema(),
                            core_schema.no_info_plain_validator_function(cls.validate),
                        ]
                    ),
                ]
            ),
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda x: str(x)
            ),
        )

    @classmethod
    def validate(cls, value) -> ObjectId:
        if not ObjectId.is_valid(value):
            raise ValueError("Invalid ObjectId")

        return ObjectId(value)

# Usage

class ObjectIdTest(BaseModel):
    id: Annotated[PyObjectId, Field(default_factory=ObjectId)] = PyObjectId()
    name: str = Field(default=..., alias="n")
```

I am closing the issue. 

PS. It would be great if Pydantic came with "native" `ObjectId` support. I guess Mongo + Pydantic is quite a common combo.
