### ISSUE TITLE
JSON schema generation fails for `ByteSize`  type and raises `core_schema.PlainValidatorFunctionSchema` error

### ISSUE THREAD

**Issue by morian** [pydantic/pydantic#8480]
### Discussed in https://github.com/pydantic/pydantic/discussions/8176

Using the latest Pydantic 2 version from git, this minimal example fails to generate a JSON schema:
```python
from pydantic import BaseModel, ByteSize

class File(BaseModel):

    name: str
    length: ByteSize

print(File.model_json_schema())
```

This prevents FastAPI from generating its OpenAPI schema when this type of field is in use.
Here is the python backtrace that I get with the code above:
```shell
Traceback (most recent call last):
  File "/tmp/pydantic/debug.py", line 8, in <module>
    print(File.model_json_schema())
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/main.py", line 386, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 2153, in model_json_schema
    return schema_generator_instance.generate(cls.__pydantic_core_schema__, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 406, in generate
    json_schema: JsonSchemaValue = self.generate_inner(schema)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 545, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 519, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/main.py", line 604, in __get_pydantic_json_schema__
    return __handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 519, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_generate_schema.py", line 217, in modify_model_json_schema
    json_schema = handler(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 502, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 1320, in model_schema
    json_schema = self.generate_inner(schema['schema'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 545, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 502, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 1412, in model_fields_schema
    json_schema = self._named_required_fields_schema(named_required_fields)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 1223, in _named_required_fields_schema
    field_json_schema = self.generate_inner(field).copy()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 545, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 537, in new_handler_func
    json_schema = js_modify_function(schema_or_field, current_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_generate_schema.py", line 2066, in json_schema_update_func
    json_schema = {**handler(core_schema_or_field), **json_schema_update}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 502, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 1291, in model_field_schema
    return self.generate_inner(schema['schema'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 545, in generate_inner
    json_schema = current_handler(schema)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/_internal/_schema_generation_shared.py", line 36, in __call__
    return self.handler(__core_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 502, in handler_func
    json_schema = generate_for_schema_type(schema_or_field)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 953, in function_plain_schema
    return self._function_schema(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 918, in _function_schema
    return self.handle_invalid_for_json_schema(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morian/projects/lab/pydantic/pydantic/json_schema.py", line 2069, in handle_invalid_for_json_schema
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'with-info', 'function': <bound method ByteSize._validate of <class 'pydantic.types.ByteSize'>>})

For further information visit https://errors.pydantic.dev/2.6/u/invalid-for-json-schema
```

**Comment by geospackle** [comment]
@sydney-runkle 

Happy to pick this up!
