### ISSUE TITLE
Unable to use a List of Union for a Field

### ISSUE THREAD

**Issue by shadycuz** [pydantic/pydantic#8532]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm trying to create a field `Pipeline: List[Union[DatabaseConfig, NvcoreConfig]]` where `DatabaseConfig` and `NvcoreConfig` are both pydantic models. 

I'm trying with a config file that only contains a `DatabaseConfig`. I have tried the `DatabaseConfig` on it's own and it works fine with no validation errors. 

```python3
database_config = config_settings["Pipeline"][0]

print(database_config) # print what you would expect

db = DatabaseConfig(**database_config)

print(db.pprint()) # This just pretty prints the model as a dict. 
```

But when I try the example... the `Pipeline` field is `[None]`. I'm not sure why. 

I also discovered that trying to change the union_mode results in even more errors. 

For example:
```python3
class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Union[DatabaseConfig, NvcoreConfig]] = Field(union_mode="left_to_right")
```
results in the following error:
```
File "/workspaces/nvcloud/nvcloud/config/models/nvcore.py", line 970, in <module>
    class NvcorePipelineConfig(BaseModel):
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 541, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 541, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 951, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1626, in _apply_annotations
    res = self._get_prepare_pydantic_annotations_for_known_type(source_type, tuple(annotations))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1607, in _get_prepare_pydantic_annotations_for_known_type
    res = gen(obj, annotations, self._config_wrapper.config_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_std_types_schema.py", line 411, in sequence_like_prepare_pydantic_annotations
    _known_annotated_metadata.check_metadata(metadata, _known_annotated_metadata.SEQUENCE_CONSTRAINTS, source_type)
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_known_annotated_metadata.py", line 408, in check_metadata
    raise TypeError(
TypeError: The following constraints cannot be applied to typing.List[typing.Union[nvcloud.config.models.database.DatabaseConfig, nvcloud.config.models.nvcore.NvcoreConfig]]: 'union_mode'
```
same error with "smart" mode.

### Example Code

```Python
class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Union[DatabaseConfig, NvcoreConfig]]

config_settings = {
  "Pipeline": [
     {
       "Stackname": "pipeline-database-test"
       "SnapshotARN": "xxxxx"
     }
  ]
}

try:
    pipeline = NvcorePipelineConfig(**config_settings)
except ValidationError as e:
    click.echo(e)
    raise click.Abort()

print(pipeline.Pipeline) # This prints [None]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 18:32:58) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: mypy-1.7.0 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
@shadycuz,

Please provide a code sample that we can run start to end (with imports and class definitions for `DatabaseConfig` and `NvcoreConfig`.

I made some assumptions about the structures of the aforementioned models - here's a basic example proving that this logic should work.

```py
from typing import List, Union

from pydantic import BaseModel, ValidationError

class DatabaseConfig(BaseModel):
    DatabaseField: str

class NvcoreConfig(BaseModel):
    Stackname: str
    SnapshotARN: str


class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Union[DatabaseConfig, NvcoreConfig]]


config_settings = {
    "Pipeline": [
        {
            "DatabaseField": "test",
        },
        {
            "Stackname": "test",
            "SnapshotARN": "test",
        },
    ]
}

try:
    pipeline = NvcorePipelineConfig(**config_settings)
except ValidationError as e:
    print(e)

print(pipeline.Pipeline)
#> [DatabaseConfig(DatabaseField='test'), NvcoreConfig(Stackname='test', SnapshotARN='test')]
```

Closing this issue for now. Happy to help you debug your code if you send a MRE.

**Comment by shadycuz** [comment]
@sydney-runkle Sharing the code will be kinda hard. It's Model inheritance all the way down. So I would end up having to share many files of code. 

Could it have something to do with https://docs.pydantic.dev/latest/concepts/validators/#using-validation-context-with-basemodel-initialization ? We use that and its given some problems in the past. 

I will attempt to put together an MRE.

**Comment by shadycuz** [comment]
@sydney-runkle an MRE was easier to produce then I expected:

```
(.venv) vscode ➜ /workspaces/nvcloud (add_pipelines) $ cat test.py 
from typing import List, Union

from pydantic import BaseModel, Field


class StackA(BaseModel):
    SomeProp: str


class StackB(BaseModel):
    AnotherProp: str


class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Union[StackA, StackB]] = Field(union_mode="left_to_right")


config_settings = {
    "Pipeline": [
        {"SomeProp": "SomeValue"},
    ],
}


pipeline = NvcorePipelineConfig(**config_settings)
(.venv) vscode ➜ /workspaces/nvcloud (add_pipelines) $ python3 test.py 
Traceback (most recent call last):
  File "/workspaces/nvcloud/test.py", line 14, in <module>
    class NvcorePipelineConfig(BaseModel):
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 541, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 541, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 951, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1626, in _apply_annotations
    res = self._get_prepare_pydantic_annotations_for_known_type(source_type, tuple(annotations))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1607, in _get_prepare_pydantic_annotations_for_known_type
    res = gen(obj, annotations, self._config_wrapper.config_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_std_types_schema.py", line 411, in sequence_like_prepare_pydantic_annotations
    _known_annotated_metadata.check_metadata(metadata, _known_annotated_metadata.SEQUENCE_CONSTRAINTS, source_type)
  File "/workspaces/nvcloud/.venv/lib/python3.11/site-packages/pydantic/_internal/_known_annotated_metadata.py", line 408, in check_metadata
    raise TypeError(
TypeError: The following constraints cannot be applied to typing.List[typing.Union[__main__.StackA, __main__.StackB]]: 'union_mode'
```

**Comment by shadycuz** [comment]
@sydney-runkle So it's 2 seperate issues. 

- The first issue is around setting the `Field` `union_mode`
- The second issue is around `pipeline.Pipeline` being `[None]`

For the second issue, I have narrowed it down to a single model that doesn't work. All the other models work. 

The inheritance looks like this: AbstractStackConfig --> StackConfig --> DevOpsStackConfig --> (NvcoreConfig and DatabaseConfig)

I have tried all the parent classes and they all work. So `Pipeline: List[Union[NvcoreConfig, DevOpsStackConfig]]` works but as soon as I add `DatabaseConfig` it doesn't work. So I'm confident the problem is in there. 

Could multiple Inheritance be an issue? 

`class DatabaseConfig(DevOpsStackConfig, ReusableDatabaseConfig):`

I would feel better emailing this file instead of pasting it here.

**Comment by sydney-runkle** [comment]
@shadycuz,

Here's a solution to your first question:

```py
from typing import Annotated, List, Union

from pydantic import BaseModel, Field


class StackA(BaseModel):
    SomeProp: str


class StackB(BaseModel):
    AnotherProp: str


class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Annotated[Union[StackA, StackB], Field(union_mode="left_to_right")]]


config_settings = {
    "Pipeline": [
        {"SomeProp": "SomeValue"},
    ],
}

config = NvcorePipelineConfig(**config_settings)
print(config)
#> Pipeline=[StackA(SomeProp='SomeValue')]
```

Note specifically the use of `Annotated` to attach the `Field` to the `Union` and not the `List`.

As for your second issue, what's the validation error that you're getting?

**Comment by shadycuz** [comment]
@sydney-runkle I didn't see the `Annotated` part in the documentation when I was looking up the Union stuff. Maybe I missed it? Do you know why it is needed? 

> As for your second issue, what's the validation error that you're getting?
No error just when I print `pipeline.Pipeline` it is a list of None which is wrong. 

For my second issue, I finally found what is causing it. It's a model_validator? With mode=after? Here is a new MRE:
```
(.venv) vscode ➜ /workspaces/nvcloud (add_pipelines) $ cat test.py 
from typing import List, Union

from pydantic import BaseModel, Field, model_validator


class StackA(BaseModel):
    SomeProp: str

    @model_validator(mode="after")
    def validate_some_prop(self):
        print("Validating SomeProp")


class StackB(BaseModel):
    AnotherProp: str


class NvcorePipelineConfig(BaseModel):
    Pipeline: List[Union[StackA, StackB]]


config_settings = {
    "Pipeline": [
        {"SomeProp": "SomeValue"},
    ],
}


pipeline = NvcorePipelineConfig(**config_settings)

print(pipeline.Pipeline)
(.venv) vscode ➜ /workspaces/nvcloud (add_pipelines) $ python3 test.py 
Validating SomeProp
[None]
```

But if you comment out the model_validator... it works? I don't know why.

**Comment by shadycuz** [comment]
@sydney-runkle I'm not returning `self` from the model validators.... lets close this issue and pretend it never happened 🙃

**Comment by sydney-runkle** [comment]
> @sydney-runkle I didn't see the Annotated part in the documentation when I was looking up the Union stuff. Maybe I missed it? Do you know why it is needed?

https://docs.pydantic.dev/dev/concepts/types/#composing-types-via-annotated

Annotated types help us to attach metadata to types very specifically - this section of our docs should help you better understand them!
