### ISSUE TITLE
create_model fails to use type annotation of typing.Annotated

### ISSUE THREAD

**Issue by trippersham** [pydantic/pydantic#8534]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using `create_model` fails with an "A non-annotated attribute" error when using an annotation created with typing.Annotated. This same annotation works as expected when used to define a field as a subclass of BaseModel. The difference in behavior is apparent in the FieldInfo of the two examples; in the BaseModel subclass example the field's FieldInfo annotation is `bool`, whereas in the `create_model` example the field's FieldInfo annotation is `NoneType`.

### Example Code

```Python
from typing import Annotated

from pydantic import BaseModel, create_model
from pydantic.fields import Field

annotated = Annotated[bool, Field(alias="field_alias", description="this is a description")]

print(annotated)
# typing.Annotated[typing.Optional[bool], FieldInfo(annotation=NoneType, required=True, alias='field_alias', alias_priority=2, description='this is a description')]

class Model(BaseModel):
    field: annotated

print(Model.model_fields)
# {'field': FieldInfo(annotation=bool, required=True, alias='field_alias', alias_priority=2, description='this is a description')}

create_model('CreatedModel', field=annotated)
# pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `field = typing.Annotated[bool, FieldInfo(annotation=NoneType, required=True, alias='field_alias', alias_priority=2, description='this is a description')]`. All model fields require a type annotation; if `field` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
               python version: 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.2.1-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0
```

**Comment by sydney-runkle** [comment]
@trippersham,

Thanks for suggesting this. I'm going to mark this as a feature request - this isn't something we've supported in the past afaik, so it's something we'll have to add.

Also marking as `help wanted` if anyone wants to work on this 😄.

**Comment by trippersham** [comment]
Thanks @sydney-runkle for the re-categorization. I saw this pattern used in the [dyntamic JSON Schema to Pydantic Model generator](https://github.com/c32168/dyntamic/blob/main/src/dyntamic/factory.py) and assumed (incorrectly!) that this was a regression.

**Comment by wannieman98** [comment]
Hello, wanted to work on this issue if nobody is currently working on it. But wanted to get the problem and expected outcome straightened out. 

```
from typing import Annotated

from pydantic import BaseModel, create_model
from pydantic.fields import Field

annotated = Annotated[bool, Field(alias="field_alias", description="this is a description")]
```
Given the `annotated`,

```
create_model('CreatedModel', field=annotated)
```
should behave equally as
```
create_model('CreatedModel', field=(bool, FieldInfo(alias="field_alias", description="this is a description"))
```

However, the current behavior seems that it is unable to interpret the field type and assuming it is a `NoneType`?

**Comment by sydney-runkle** [comment]
@wannieman98,

That's correct. We're excited for you to contribute! Ping me whenever you have a PR you'd like me to review :), or if you have any more questions.

**Comment by simonw** [comment]
I'm seeing the following error trying to use Pydantic with the Python 3.13 alpha:

```
Traceback (most recent call last):
  File "/tmp/3.13.0a3/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/plugins.py", line 37, in <module>
    mod = importlib.import_module(plugin)
          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.13.0a3/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/llm/default_plugins/openai_models.py", line 7, in <module>
    import openai
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/types/__init__.py", line 5, in <module>
    from .image import Image as Image
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/types/image.py", line 5, in <module>
    from .._models import BaseModel
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/openai/_models.py", line 408, in <module>
    class FinalRequestOptions(pydantic.BaseModel):
    ...<59 lines>...
            model_construct = construct
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 178, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_model_construction.py", line 452, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_fields.py", line 214, in collect_model_fields
    field_info = FieldInfo.from_annotated_attribute(ann_type, default)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/fields.py", line 372, in from_annotated_attribute
    if _typing_extra.is_annotated(annotation):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_typing_extra.py", line 103, in is_annotated
    return origin is not None and lenient_issubclass(origin, Annotated)
                                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/tmp/3.13.0a3/lib/python3.13/site-packages/pydantic/_internal/_utils.py", line 76, in lenient_issubclass
    return isinstance(cls, type) and issubclass(cls, class_or_tuple)
                                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.13.0a3/lib/python3.13/typing.py", line 486, in __subclasscheck__
    raise TypeError(f"{self} cannot be used with issubclass()")
TypeError: typing.Annotated cannot be used with issubclass()
```
Could it be that this issue needs addressing for compatibility with Python 3.13?

Full steps to reproduce in this issue comment:
- https://github.com/simonw/llm/issues/436#issuecomment-1992678618

**Comment by sydney-runkle** [comment]
We haven't added support for Python 3.13 yet (to my knowledge), so I wouldn't say that this issue is unique in that sense.
