### ISSUE TITLE
Standard complex number not supported!?

### ISSUE THREAD

**Issue by AntoineD** [pydantic/pydantic#8555]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems that the standard number type `complex` is not supported.

The code example below yields:
```
Traceback (most recent call last):
  File "/opt/pycharm-community/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 541, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 541, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 951, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1654, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 1635, in inner_handler
    schema = self._generate_schema(obj)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 727, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 814, in match_type
    return self._unknown_type_schema(obj)
  File "/home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'complex'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.5/u/schema-for-unknown-type
```

### Example Code

```Python
from pydantic import BaseModel

class Model(BaseModel):
     number: complex
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/ad/gemseo-oss/.tox/py39/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Dec 18 2023, 00:00:00)  [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
                     platform: Linux-6.6.9-200.fc39.x86_64-x86_64-with-glibc2.38
             related packages: typing_extensions-4.9.0
```

**Comment by samuelcolvin** [comment]
I've always wondered when someone would ask this, now that have.

PR welcome to support it.

**Comment by AntoineD** [comment]
> I've always wondered when someone would ask this, now that have.
> 
> PR welcome to support it.

I may try to do this, should this be on pydantic-core side?

**Comment by sydney-runkle** [comment]
@AntoineD,

It will require changes to both `pydantic` and `pydantic-core`. You'll have to construct the schema for the type in `pydantic`, then build validation and serialization logic in `pydantic-core`.

**Comment by stealthBanana** [comment]
Hi, this is the workaround that I use:

```
from typing_extensions import Annotated

from pydantic import PlainValidator, PlainSerializer


Complex = Annotated[
    complex,
    PlainValidator(lambda x: x if isinstance(x, complex)
                   else complex(x.get('real', x.get('imag')))),
    PlainSerializer(lambda x: {'real': x.real, 'imag': x.imag}, return_type=dict)
]
```

Is there a better way to do this ?

**Comment by changhc** [comment]
Hi @sydney-runkle, I'm interested in working on this issue and looking into the codebase now. While I ramp up myself, I'd like to discuss some design details with you.

Since there is no official consensus on how a complex number should be serialised, I'm thinking of expressing it as a dictionary with two keys, `real` and `imag`, which matches the field names of the `complex` type in python.

The goal is to make something like this example work:
```py
import pydantic

from pydantic import BaseModel

class Model(BaseModel):
    number: complex

m = Model(number=complex(1, 2))
assert repr(m) == "Model(number=(1+2j))"
assert m.dict() == {'number': complex(1, 2)}
assert m.json() == '{"number":{"real":1,"imag":2}}'
...
```

Does this make sense?

**Comment by sydney-runkle** [comment]
@changhc,

Thanks for your interest. That approach sounds great! I'd recommend using V2 syntax though, so you'll want to use `model_dump` and `model_dump_json`.

**Comment by mikeleppane** [comment]
> Hi @sydney-runkle, I'm interested in working on this issue and looking into the codebase now. While I ramp up myself, I'd like to discuss some design details with you.

Hey @changhc, is this still WIP? 

Just checking that, in case it's not, this would be an interesting task to work on.

**Comment by changhc** [comment]
Hi @mikeleppane, yes it's still WIP. I have some functioning code right now, but I'm still checking if I missed out anything.
