### ISSUE TITLE
string constraints are applied after pattern

### ISSUE THREAD

**Issue by dhofstetter** [pydantic/pydantic#8577]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi guys,
I found out that string constraints (like `to_lower`or `strip_whitespace` are applied after a defined pattern check.

I.m.o that doesn't make sense, as operations like `to_lower`or `strip_whitespace` would make a string eventually starting to match the pattern.
See the code example below to get an idea what I mean.

Is there a special reason for the order of operations?

### Example Code

```Python
from typing import Annotated

from pydantic import GetPydanticSchema, TypeAdapter, ValidationError
from pydantic_core import PydanticCustomError, core_schema


class MyStringType(str):
    @classmethod
    def from_string(cls, v: str) -> "MyStringType":
        if not v.startswith("my"):
            raise PydanticCustomError("invalid_format")
        return MyStringType(v)


MyString = Annotated[
    MyStringType,
    # Expectation is, that whitespace and to_lower are applied before the pattern, as
    # the string might match a pattern after going through the strip and lowercase process?!
    GetPydanticSchema(
        lambda tp, handler: core_schema.no_info_after_validator_function(
            MyString.from_string, handler(core_schema.str_schema(
                to_lower=True, strip_whitespace=True, min_length=1, pattern=r"^my.*$",
            ))
        )
    ),
]

adapter = TypeAdapter(MyString)

assert adapter.validate_python("mystring") == "mystring"   # OK
assert adapter.validate_python("mystring ") == "mystring"  # OK
try:
    assert adapter.validate_python(" MYSTRING") == "mystring"  # NOK
except ValidationError as e:
    print(e)
    '''
    1 validation error for function-after[from_string(), constrained-str]
        String should match pattern '^my.*$' [type=string_pattern_mismatch, input_value=' MYSTRING', input_type=str]
            For further information visit https://errors.pydantic.dev/2.5/v/string_pattern_mismatch
    '''
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /Users/dh/Development/yio/yio/yio-fastapi-utils/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: fastapi-0.108.0 typing_extensions-4.8.0 mypy-1.8.0 pydantic-settings-2.1.0 pydantic-extra-types-2.3.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
Hi @dhofstetter,

Thanks for the example + question. Here's a snippet from the `pydantic-core` string validation logic that shows the order in which string constraints are checked / applied:

https://github.com/pydantic/pydantic-core/blob/4da7192ffc104cd6c424d102bc1c9c5bfdad543e/src/validators/string.rs#L75-L142.

As to the motivation behind this ordering, I think the thought is that after the length + pattern checks, you can standardize the string to some extend with settings like `to_lower`, etc.

I see your argument re having these transformations take place before the pattern check. However, changing this behavior now would constitute a breaking change for many users. One workaround that you could use in the meantime would be to use a validator with mode set to `before` to preprocess your data.

@samuelcolvin, is this something that we'd consider changing in V3, or are we set on this order of validation checks + transformations for strings?

**Comment by sydney-runkle** [comment]
Alright, marking this with the `change` and `V3` tags, as I think this is something we could at least revisit for V3.

I don't think that changing the default (current behavior) would be a great idea, though I can see an argument for supporting customization of the order in which string constraints are applied 🚀

**Comment by samuelcolvin** [comment]
I see the argument for changing it, but it's a very annoying breaking change to understand, so my instinct is we don't change this, even in a major update.

As for the reason - my guess is that the best explanation is "because that's how it was first done" and there hasn't been a strong (enough) argument to change it.

**Comment by dhofstetter** [comment]
@samuelcolvin Thanks for your explanation. My strong argument is simply: That writing a pattern that accepts leading/and trailing whitespace is not a big deal, but makes the regex pattern even harder to understand. The same is for to_upper and lower, writing a pattern accepting both if I just want one, creates a pattern that is harder to understand

@sydney-runkle Thanks for digging into it and providing such a detailed response.

**Conclusio**
I totally agree, that changing how things were first implemented is a strong argument. But from my point of view, v2 introduced a lot of "breaking" changes. And if one hits yourself by accident (meaning that your own codebase is affected by that change) its personally considered as annoying ;)
So I thing a nice way would be to define the order of StringConstraints by using some list of literals maybe.

BR Daniel

**Comment by HansBrende** [comment]
@dhofstetter I can think of one pretty compelling reason not to change it:

Changing it as you suggest would make any OpenAPI schema generated from your model _WRONG_, since the pattern included in that schema would no longer necessarily match strings that your model supports.

**Comment by dhofstetter** [comment]
> @dhofstetter I can think of one pretty compelling reason not to change it:
> 
> Changing it as you suggest would make any OpenAPI schema generated from your model _WRONG_, since the pattern included in that schema would no longer necessarily match strings that your model supports.

May you provide an example? I guess I don't get your point.

**Comment by SDAravind** [comment]
> I see the argument for changing it, but it's a very annoying breaking change to understand, so my instinct is we don't change this, even in a major update.
> 
> As for the reason - my guess is that the best explanation is "because that's how it was first done" and there hasn't been a strong (enough) argument to change it.

see below, lowercase/uppercase is set to true and strip whitespaces is set to true. Intrestingly, we see the second part of email is always lowercase. This is very strange behavior. Though, I can exclude strip_whitespace as EmailStr takes care of striping whitespaces. 

I'm bit confused when to use and not to use `strip_whitespace`. Should we use `strip_whitespace` with others params?

```python
from pydantic import BaseModel, EmailStr, StringConstraints
from typing import Annotated

EStr = Annotated[EmailStr, StringConstraints(to_lower=True, strip_whitespace=True)]


class Foo(BaseModel):
    email: EStr


Foo(bar="uSeR@ExAmPlE.com")
>>>  Foo(bar='uSeR@example.com')
```

**Comment by sydney-runkle** [comment]
@SDAravind,

Hmph, that looks like a bug, feel free to open a new issue with that report!

**Comment by sydney-runkle** [comment]
Interesting case showcasing the bug:

```py
from pydantic import BaseModel, EmailStr, StringConstraints
from typing import Annotated


class Foo(BaseModel):
    foo: EmailStr
    bar: Annotated[EmailStr, StringConstraints(to_lower=True)]
    baz: Annotated[EmailStr, StringConstraints(to_lower=True, strip_whitespace=True)]
    # foo: NEmail


print(repr(
    Foo(
        foo=" uSeR@ExAmPlE.com ",
        bar=" uSeR@ExAmPlE.com ",
        baz=" uSeR@ExAmPlE.com  "
    )
))
#> Foo(foo='uSeR@example.com', bar='user@example.com', baz='uSeR@example.com')
```

**Comment by sydney-runkle** [comment]
Aha, the culprit:

```
{
    'type': 'model',
    'cls': <class '__main__.Foo'>,
    'schema': {
        'type': 'model-fields',
        'fields': {
            'foo': {
                'type': 'model-field',
                'schema': {
                    'function': {'type': 'no-info', 'function': <bound method EmailStr._validate of <class 'pydantic.networks.EmailStr'>>},
                    'schema': {'type': 'str'},
                    'type': 'function-after'
                }
            },
            'bar': {
                'type': 'model-field',
                'schema': {
                    'type': 'chain',
                    'steps': [
                        {
                            'function': {'type': 'no-info', 'function': <bound method EmailStr._validate of <class 'pydantic.networks.EmailStr'>>},
                            'schema': {'type': 'str'},
                            'type': 'function-after'
                        },
                        {'type': 'str', 'to_lower': True}
                    ]
                }
            },
            'baz': {
                'type': 'model-field',
                'schema': {
                    'type': 'chain',
                    'steps': [
                        {
                            'function': {'type': 'no-info', 'function': <bound method EmailStr._validate of <class 'pydantic.networks.EmailStr'>>},
                            'schema': {'type': 'str'},
                            'type': 'function-after'
                        },
                        {'type': 'str', 'strip_whitespace': True}
                    ]
                }
            }
        },
        'model_name': 'Foo'
    },
    'ref': '__main__.Foo:4822756464'
}
```

**Comment by angely-dev** [comment]
@sydney-runkle and @samuelcolvin you are saying that fixing/implementing this would introduce a breaking change, but this was the way it worked with Pydantic V1. Here is an MRE taken from the [official doc](https://docs.pydantic.dev/2.8/api/types/#pydantic.types.constr):

# Working example using Pydantic V1

```py
from pydantic import BaseModel, constr                                                             
                                                                                                   
class Foo(BaseModel):                                                                              
    bar: constr(strip_whitespace=True, to_upper=True, regex=r'^[A-Z]+$')                           
                                                                                                   
                                                                                                   
foo = Foo(bar='  hello  ')                                                                         
print(foo)
#> bar='HELLO'
```

# Same (failing) example using Pydantic V2

```py
from pydantic import BaseModel, constr

class Foo(BaseModel):
    bar: constr(strip_whitespace=True, to_upper=True, pattern=r'^[A-Z]+$')


foo = Foo(bar='  hello  ')
print(foo)
```

```
Traceback (most recent call last):
  File "/tmp/wksp/pattern.py", line 7, in <module>
    foo = Foo(bar='  hello  ')
  File "/tmp/wksp/venv/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
bar
  String should match pattern '^[A-Z]+$' [type=string_pattern_mismatch, input_value='  hello  ', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/string_pattern_mismatch
```

**Please note the above code is taken from the official doc and throws an error, whereas the doc says it prints `HELLO`:**

![image](https://github.com/user-attachments/assets/622a0951-fe10-4357-8b62-491905cbd047)

**Comment by sydney-runkle** [comment]
Note, I've updated the docs: https://github.com/pydantic/pydantic/pull/10071

**Comment by angely-dev** [comment]
Thanks @sydney-runkle for updating the docs.

May we have a statement about the regression? It seems there is a contradiction. Pydantic 2 introduced a breaking change by executing constraints **after** checking the pattern, whereas it was the opposite in Pydantic 1. So I failed to see how @samuelcolvin's point is valid:

> I see the argument for changing it, but it's a very annoying breaking change to understand, so my instinct is we don't change this, even in a major update. As for the reason - my guess is that the best explanation is **"because that's how it was first done"** and there hasn't been a strong (enough) argument to change it.

**Yes, but in Pydantic 1, it was first done the opposite way:** constraints are applied **before** the pattern ([source code](https://github.com/pydantic/pydantic/blob/v1.10.17/pydantic/types.py#L428-L429)). And Pydantic 2 broke the behavior anyway.

Maybe this breaking change from V1 to V2 was intended, but the Migration Guide from V1 to V2 does not highlight it.

**Comment by sydney-runkle** [comment]
> Maybe this breaking change from V1 to V2 was intended, but the Migration Guide from V1 to V2 does not highlight it.

Indeed, looks like behavior did change from V1 -> V2 here. PRs welcome updating the migration guide with some info on this.

We've tagged this with the `v3` tag as something worth revisiting then. Thanks for your feedback!

I'll also note, you can try out our experimental [pipeline api](https://docs.pydantic.dev/latest/concepts/experimental/#pipeline-api) in order to easily customize string constraint application :).

**Comment by angely-dev** [comment]
I think we could highlight it in the [#changes-to-validators](https://docs.pydantic.dev/latest/migration/#changes-to-validators) section, by referencing the pipeline api as an alternative (which looks promising, I will experience it in our code). Thanks for answering.

**Comment by angely-dev** [comment]
So I was preparing the code snippet for the docs and just tested two alternatives:

## Using `AfterValidator`

```py
from pydantic import BaseModel, StringConstraints
from pydantic.functional_validators import AfterValidator
from typing_extensions import Annotated

class Foo(BaseModel):
    bar: Annotated[
        str,
        AfterValidator(lambda s: s.strip().upper()), 
        StringConstraints(pattern=r'^[A-Z]+$')
    ]

foo = Foo(bar='  hello  ')
print(foo)  # prints bar='HELLO'
```

Because we use an `AfterValidator`, we still benefit of the Pydantic internal type checking. Also, the order matters, e.g.:

```py
class Foo(BaseModel):             
    # here the AfterValidator is placed after the StringConstraints                                                                 
    bar: Annotated[str, StringConstraints(pattern=r'^[A-Z]+$'), AfterValidator(my_validator)]

foo = Foo(bar='   hello   ')
# ValidationError: String should match pattern '^[A-Z]+$' [type=string_pattern_mismatch, input_value='   hello   ', input_type=str]
```

I was thinking to mention this solution in the PR as an alternative to what was working in Pydantic V1.

## Using Experimental API

### Using `transform` (working)

```py
from pydantic import BaseModel
from pydantic.experimental.pipeline import validate_as
from typing_extensions import Annotated

class Foo(BaseModel):
    bar: Annotated[
        str,
        validate_as(str)
        .transform(lambda s: s.strip().upper())
        .str_pattern(r'^[A-Z]+$')
    ]

foo = Foo(bar='  hello  ')
print(foo)  # prints: bar='HELLO'
```

### Using `str_strip` and `str_upper` (not working)

```py
from pydantic import BaseModel
from pydantic.experimental.pipeline import validate_as
from typing_extensions import Annotated

class Foo(BaseModel):
    bar: Annotated[
        str,
        validate_as(str)
        .str_strip()
        .str_upper()
        .str_pattern(r'^[A-Z]+$')
    ]

foo = Foo(bar='  hello  ')
print(foo)
```

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
bar
  String should match pattern '^[A-Z]+$' [type=string_pattern_mismatch, input_value='  hello  ', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/string_pattern_mismatch
```

Surprisingly, unless I missed something, the last solution does not work. I thought the validators where here executed in order, so I expected it to work.

**Comment by adriangb** [comment]
> Surprisingly, unless I missed something, the last solution does not work. I thought the validators where here executed in order, so I expected it to work.

This is a bit of a gotcha. We do intend to make them execute in order BUT in this case we just leave it up to pydantic-core which does not have an order.

Two options:
1. Now that we have an API on the Pydantic side that allows specifying order in a sane way (`Field(...)` did not) we can refactor pydantic-core to respect the order (e.g. by having `StringValidator { ..., constraints: Vec<StringConstraint>, ...}` where `enum StringConstraint { Pattern(String, MinLen(usize), ... }`.
2. In Pydantic check if there is already a constraint on the schema and if so fall back to the Python constraint application just to preserve order.

@sydney-runkle up to you which path to go down

**Comment by sydney-runkle** [comment]
Related: https://github.com/pydantic/pydantic-core/pull/825

**Comment by sydney-runkle** [comment]
Closing the PR as stale for now, but whoever decides to pick this up should reference https://github.com/pydantic/pydantic-core/pull/825 regarding an attempt + its challenges

**Comment by angely-dev** [comment]
I was going to recreate a PR properly (since I didn't fully follow the contribution guide in #10159) to update the docs but, again, don't you find the breaking change strange? I don't want to be a bother but how do we conceptually justify this:

---

In Pydantic V1, string constraints were applied in this order ([source](https://github.com/pydantic/pydantic/blob/v1.10.17/pydantic/types.py#L427-L431)):

```
strict
strip_whitespace
upper
lower
min_length
max_length
regex
```

In Pydantic V2, string constraints are applied in this order ([source](https://github.com/pydantic/pydantic-core/blob/v2.23.0/src/validators/string.rs#L75-L147)):

```
strict
strip_whitespace
min_length
max_length
pattern (replaced "regex")
lower
upper
```
---

Especially, `strip_whitespace` is executed before `pattern`, meaning text transformation is conceptually accepted to be applied before the pattern, except for `lower` and `upper`, for some reason?
