### ISSUE TITLE
Strict mode rejects valid types

### ISSUE THREAD

**Issue by Dreamsorcerer** [pydantic/pydantic#8604]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In this example, it requires a list even though I didn't ask for a list.

### Example Code

```Python
>>> TypeAdapter(Sequence[int]).validate_python((), strict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 239, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for json-or-python[json=list[int],python=chain[is-instance[Sequence],function-wrap[sequence_validator()]]]
  Input should be a valid list [type=list_type, input_value=(), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
```

### Python, Pydantic & OS Version

```Text
2.5.3
```

**Comment by sydney-runkle** [comment]
@Dreamsorcerer,

Thanks for reporting this! This does look like a bug. What version of `pydantic` are you using?

**Comment by Dreamsorcerer** [comment]
I tested a couple of versions, it's still present on latest version.

**Comment by sydney-runkle** [comment]
@Dreamsorcerer,

I've opened a PR with a potential fix, we'll get a fix for this into 2.7!

**Comment by sydney-runkle** [comment]
@Dreamsorcerer,

Merged the PR :) should be fixed on main now.
