### ISSUE TITLE
Unexpected KeyError occured when calling `create_model` with a `type`-type field which is defined in the same module

### ISSUE THREAD

**Issue by anci3ntr0ck** [pydantic/pydantic#8633]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When create a model by calling `create_model`, there is no `__qualname__` in the model's `namespace`. According to the following code in `pydantic._internal._model_construction`, a KeyError will be raised when adding a type-type (defined in the same module) field
```python
# pydantic._internal._model_construction
def inspect_namespace(
    ...
    # line 331
    for var_name, value in list(namespace.items()):
        if var_name == 'model_config':
            continue
        elif (
            isinstance(value, type)
            and value.__module__ == namespace['__module__']
            and value.__qualname__.startswith(namespace['__qualname__'])
        ):
    ...
```
Maybe Adding `namespace["__qualname__"] = __model_name` into `create_model` can easily solve this? I don't have much idea.

### Example Code

```Python
from pydantic import create_model, BaseModel


class A:
    pass

class StaticModel(BaseModel):
    a_cls: type[A] = A  # this works fine


DynamicModel = create_model("DynamicModel", a_cls=(type[A], A))
"""
Traceback (most recent call last):
  File "path\to\test.py", line 8, in <module>
    DynamicModel = create_model("DynamicModel", a_cls=(type[A], A))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path\to\.venv\Lib\site-packages\pydantic\main.py", line 1490, in create_model
    return meta(
           ^^^^^
  File "path\to\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "path\to\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 337, in inspect_namespace
    and value.__qualname__.startswith(namespace['__qualname__'])
                                      ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '__qualname__'
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0b1
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: path\to\.venv\Lib\site-packages\pydantic
               python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.22000-SP0
             related packages: fastapi-0.109.0 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@anci3ntr0ck,

Thanks for reporting this. I think the issue can be solved by simply adding a check on the existence of the `__qualname__` in the namespace, like this:

```py
elif (
    isinstance(value, type)
    and value.__module__ == namespace['__module__']
    and namespace.get('__qualname__')
    and value.__qualname__.startswith(namespace['__qualname__'])
):
```

Would you be interested in opening a PR with a test + this fix? Thanks for bringing this issue to our attention 👍.

**Comment by anci3ntr0ck** [comment]
@sydney-runkle Sure. Very glad to be a contributor to this great library 😆!
I'll work on this soon 👌.
