### ISSUE TITLE
`__pydantic_extra__` type hint incompatible with `from __future__ import annotations`

### ISSUE THREAD

**Issue by tjsmart** [pydantic/pydantic#8647]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

According to [the docs](https://docs.pydantic.dev/latest/concepts/models/#extra-fields) validation can be added for extra fields by added a type hint for `__pydantic_extra__` this works fine but breaks if the user has `from __future__ import annotations`.

Using the provided "Example Code" I get the following traceback:
```
Traceback (most recent call last):
  File "/tmp/pydantic/noworky.py", line 6, in <module>
    class Foo(BaseModel, extra="allow"):
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 182, in __new__
    complete_model_class(
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 491, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/main.py", line 578, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 468, in generate_schema
    schema = self._generate_schema(obj)
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 700, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 722, in _generate_schema_inner
    return self._model_schema(obj)
  File "/tmp/pydantic/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in _model_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: The type annotation for `__pydantic_extra__` must be `Dict[str, ...]`

For further information visit https://errors.pydantic.dev/2.5/u/schema-for-unknown-type
```

Here's the relevant snippet from the [pydantic source](https://github.com/pydantic/pydantic/blob/b785d5b1db4eccb922dd2bf17faea5fc842e6a57/pydantic/_internal/_generate_schema.py#L542):
```python
                    extras_annotation = cls.__annotations__.get('__pydantic_extra__', None)
                    if extras_annotation is not None:
                        tp = get_origin(extras_annotation)
                        if tp not in (Dict, dict):
                            raise PydanticSchemaGenerationError(
                                'The type annotation for `__pydantic_extra__` must be `Dict[str, ...]`'
                            )
```

In the case of using `from __future__ import annotations`, `extra_annotation` will be the string `dict[str, int]` so we raise the schema generation error.

### Example Code

```Python
from __future__ import annotations

class Foo:
    __pydantic_extra__: dict[str, int]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/pydantic/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0
```

**Comment by sydney-runkle** [comment]
@alexmojaki,

Could you please take a look at this issue when you have a chance? Thanks!
