### ISSUE TITLE
ValidationError with Generic BaseModel, evan when passing correct type

### ISSUE THREAD

**Issue by PJ-Schulz** [pydantic/pydantic#8660]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When i am running the example code, I get a ValidationError:

```
Traceback (most recent call last):
  File "/home/philipp/repos/foobar/abcd.py", line 19, in <module>
    model = BatteryModel(mode="Idle", power=power)
  File "/home/philipp/repos/foobar/.venv/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for BatteryModel
power
  Input should be a valid dictionary or instance of Measurement[Union[float, int]] [type=model_type, input_value=Measurement[Union[float, ...]](value=4235, unit='W'), input_type=Measurement[Union[float, int]]]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
```

In my BatteryModel, I say that power is of Type Measurement, where the value can either be a float or an int.

When I am use the variable power, which is an instance of type `Measurement[Union[float, int]]`  for the parameter power, I get a ValidationError.

The error says, that the input must either be a dictionary or instance of `Measurement[Union[float, int]]`. And there you can see my input_value is an instance of `Measurement[Union[float, int]]`

Where is the problem and how to fix it?

Converting the power object back into a dict to pass it to BatteryModel can not be the solution.

### Example Code

```Python
from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel

T = TypeVar('T')


class Measurement(BaseModel, Generic[T]):
    value: T
    unit: str


class BatteryModel(BaseModel):
    mode: Literal['Idle', 'Charge', 'Discharge']
    power: Measurement[float | int]


power = Measurement[Union[float, int]](value=4235, unit="W")
model = BatteryModel(mode="Idle", power=power)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/philipp/repos/foobar/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jul  6 2022, 10:42:25) [GCC 9.4.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
             related packages: pyright-1.1.349 typing_extensions-4.9.0
```

**Comment by sydney-runkle** [comment]
@PJ-Schulz,

I'm not entirely sure of why this works, but looks like if you're consistent with whether or not you use `Union[float, int]` vs `float | int`, things work as expected:

```py
from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel

T = TypeVar('T')


class Measurement(BaseModel, Generic[T]):
    value: T
    unit: str


class BatteryModel(BaseModel):
    mode: Literal['Idle', 'Charge', 'Discharge']
    power: Measurement[Union[float, int]]


power = Measurement[Union[float, int]](value=4235, unit="W")
model = BatteryModel(mode="Idle", power=power)
```
or

```py
from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel

T = TypeVar('T')


class Measurement(BaseModel, Generic[T]):
    value: T
    unit: str


class BatteryModel(BaseModel):
    mode: Literal['Idle', 'Charge', 'Discharge']
    power: Measurement[float | int]


power = Measurement[float | int](value=4235, unit="W")
model = BatteryModel(mode="Idle", power=power)
```

**Comment by sydney-runkle** [comment]
This is a bit of an odd case. I'd be curious to know why the consistency matters in regards to style of union definition here, if anyone knows!

Going to close this as resolved though, given that there's an easy to implement solution :).

**Comment by PJ-Schulz** [comment]
@sydney-runkle, thanks for your help.

The message in the traceback is confusing in the case that it expects a type and gets exactly that, but still raises an error.

**Comment by sydney-runkle** [comment]
@PJ-Schulz,

Indeed. Perhaps this error shouldn't happen at all. I think the reason for this behavior is the following inconsistency:

```
>>> type(typing.Union[int, float])
<class 'typing._UnionGenericAlias'>
>>> type(int | float)
<class 'types.UnionType'>
```

That being said, we could utilize the `origin_is_union` function from `pydantic` to fix this behavior. Something somewhere is likely checking types too strictly. I'll reopen this as a bug 👍
