### ISSUE TITLE
RootModel __lt__, __gt__, etc

### ISSUE THREAD

**Issue by tstdin** [pydantic/pydantic#8662]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

RootModel does not delegate the methods `__lt__`, `__gt__`, etc. to the underlying type.

In my example code, I am defining `MyDate` model, which accepts only specific date format (`%d-%b-%Y`).

Ideally `RootModel` should use `__lt__`, `__gt__`, `__le__`, `__ge__` from the underlying type. Only the `__eq__` works as expected.

```py
>>> MyDate.from_str('01-Jan-2024') == MyDate.from_str('02-Jan-2024')
False
>>> MyDate.from_str('01-Jan-2024') == MyDate.from_str('01-Jan-2024')
True
>>> MyDate.from_str('01-Jan-2024') < MyDate.from_str('01-Jan-2024')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'MyDate' and 'MyDate'
>>> 
>>> MyDate.from_str('01-Jan-2024') > MyDate.from_str('01-Jan-2024')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'MyDate' and 'MyDate'
>>> MyDate.from_str('01-Jan-2024') <= MyDate.from_str('01-Jan-2024')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<=' not supported between instances of 'MyDate' and 'MyDate'
>>> MyDate.from_str('01-Jan-2024') >= MyDate.from_str('01-Jan-2024')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>=' not supported between instances of 'MyDate' and 'MyDate'
```

### Example Code

```Python
from datetime import date, datetime
# from functools import total_ordering

from pydantic import RootModel, field_serializer


# @total_ordering
class MyDate(RootModel[date]):
    root: date

    @field_serializer("root")
    def serialize_root(self, root, _info):
        return self.__str__()

    def __str__(self):
        return self.root.strftime(r"%d-%b-%Y")

    @classmethod
    def from_str(cls, date: str) -> "MyDate":
        return cls(
            datetime.strptime(date, r"%d-%b-%Y").date()
        )

    # def __lt__(self, other: "MyDate"):
    #     return self.root < other.root

    # def __eq__(self, other: "MyDate"):
    #     return self.root == other.root
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/tom/git/test/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
                     platform: Linux-6.6.13-200.fc39.x86_64-x86_64-with-glibc2.38
             related packages: typing_extensions-4.9.0 email-validator-2.1.0.post1 pydantic-settings-2.1.0 mypy-1.8.0 typing_extensions-4.9.0 email-validator-2.1.0.post1 pydantic-settings-2.1.0 mypy-1.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@tstdin,

Thanks for your request. I'd consider this a behavioral change that might be significant enough that it has to wait until V3, but I'm not 100% sure.

Let's see what @samuelcolvin thinks tomorrow morning.

**Comment by sydney-runkle** [comment]
Alright, upon further discussion, we think that it makes the most sense for overrides like these to reside in user code, where you can subclass `RootModel` and override the definitions of functions like `__lt__`, etc based on your use case.

Happy coding!
