### ISSUE TITLE
CustomType not working as expected (with arrow)

### ISSUE THREAD

**Issue by rumbarum** [pydantic/pydantic#8737]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying making  custom type, inherit arrow for replacing datetime. 

I referenced this [official-docs](https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types) and  [davidhewitt's answer](https://github.com/pydantic/pydantic/issues/8086#issuecomment-1840164547).

I almost made them, instance.model_dump_json()  works, but instance.model_dump(mode='json') not worked as expected.

### Example Code

```Python
from typing import Any

from pydantic import (
    BaseModel,
    GetCoreSchemaHandler,
    GetJsonSchemaHandler,
    ValidationError,
)
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema
from typing_extensions import Annotated


class _ArrowPydanticV2(arrow.Arrow):
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:
        def validate_by_arrow(value) -> arrow.Arrow:
            try:
                arr = arrow.get(value)
                return arr
            except Exception as e:
                raise ValidationError(f"Arrow could not parse {value!r}: {e!r}")

        json_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(validate_by_arrow),
            ]
        )
        python_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(validate_by_arrow),
            ]
        )

        json_schema["serialization"] = core_schema.plain_serializer_function_ser_schema(
            lambda instance: instance.format("YYYY-MM-DD HH:mm:ss.SSSSSSZZ")
        )
        python_schema["serialization"] = core_schema.plain_serializer_function_ser_schema(
            lambda instance: instance
        )

        return core_schema.json_or_python_schema(
            json_schema=json_schema,
            python_schema=python_schema,
        )

    @classmethod
    def __get_pydantic_json_schema__(
        cls, _core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        return handler(core_schema.date_schema())


ArrowPydanticV2 = Annotated[arrow.Arrow, _ArrowPydanticV2]


class Model(BaseModel):
    datetime: ArrowPydanticV2


m = Model(datetime="2024-02-06 11:38:18+00:00")
print(m)
print(m.datetime)
print(m.model_dump(mode="python"))
print(m.model_dump_json())
>>>
datetime=<Arrow [2024-02-06T11:38:18+00:00]>
2024-02-06T11:38:18+00:00
{'datetime': <Arrow [2024-02-06T11:38:18+00:00]>}
{"datetime":"2024-02-06 11:38:18.000000+00:00"}

print(m.model_dump(mode="json"))
>>>
Traceback (most recent call last):
  File "/Users/rumbarum/sig/slash-server/services/fastapi/kernel/pydantic_thing/custom_type.py", line 112, in <module>
    print(m.model_dump(mode="json"))
  File "/Users/rumbarum/sig/slash-server/.venv/lib/python3.10/site-packages/pydantic/main.py", line 314, in model_dump
    return self.__pydantic_serializer__.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'arrow.arrow.Arrow'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/rumbarum/sig/slash-server/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Dec 26 2023, 17:37:51) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.1.2-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 email-validator-1.3.0 mypy-1.8.0 pydantic-settings-2.1.0 fastapi-0.103.2
                       commit: unknown
```

**Comment by rumbarum** [comment]
I am not sure this is correct way, 
this is working CustomType for Arrow.

Am I doing correctly?

```
from typing import Any

from pydantic import (
    BaseModel,
    GetCoreSchemaHandler,
    GetJsonSchemaHandler,
    ValidationError,
    WrapSerializer,
)
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema
from typing_extensions import Annotated


class _ArrowPydanticV2(arrow.Arrow):
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:
        def validate_by_arrow(value) -> arrow.Arrow:
            try:
                arr = arrow.get(value)
                return arr
            except Exception as e:
                raise ValueError(f"Arrow can not parse")

        json_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(validate_by_arrow),
            ]
        )
        python_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(validate_by_arrow),
            ]
        )

        def arrow_serialization(value: Any, _, info) -> str | arrow.Arrow:
            if info.mode == "json":
                return value.format("YYYY-MM-DDTHH:mm:ss.SSSSSSZZ")
            return value

        return core_schema.json_or_python_schema(
            json_schema=json_schema,
            python_schema=python_schema,
            serialization=wrap_serializer_function_ser_schema(arrow_serialization, info_arg=True),
        )

    @classmethod
    def __get_pydantic_json_schema__(
        cls, _core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        return handler(core_schema.date_schema())

class Model(BaseModel):
    datetime: ArrowPydanticV2

# test
m = Model(datetime="2024-02-06 11:38:18+00:00")
print(m)
print(m.datetime)
print(m.model_dump(mode="python"))
print(m.model_dump_json())
print(m.model_dump(mode="json"))

>>>

datetime=<Arrow [2024-02-06T11:38:18+00:00]>
2024-02-06T11:38:18+00:00
{'datetime': datetime.datetime(2024, 2, 6, 11, 38, 18, tzinfo=tzoffset(None, 0))}
{"datetime":"2024-02-06 11:38:18.000000+00:00"}
{'datetime': '2024-02-06T11:38:18Z'}

**Comment by sydney-runkle** [comment]
@rumbarum,

Yes, that looks right! You could also do the following, slightly more compact version. Feel free to use the `__get_pydantic_json_schema__` as well if you want.

```py
from typing import Any

import arrow

from pydantic import (
    BaseModel,
    GetCoreSchemaHandler,
    GetJsonSchemaHandler,
)
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema
from typing_extensions import Annotated


class ArrowPydanticV2(arrow.Arrow):
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:
        
        def validate_by_arrow(value) -> arrow.Arrow:
            try:
                arr = arrow.get(value)
                return arr
            except Exception as e:
                raise ValueError(f"Arrow can not parse")

        def arrow_serialization(value: Any, _, info) -> str | arrow.Arrow:
            if info.mode == "json":
                return value.format("YYYY-MM-DDTHH:mm:ss.SSSSSSZZ")
            return value   

        return core_schema.no_info_after_validator_function(
            function=validate_by_arrow,
            schema=core_schema.str_schema(),
            serialization=core_schema.wrap_serializer_function_ser_schema(arrow_serialization, info_arg=True),
        )

class Model(BaseModel):
    datetime: ArrowPydanticV2

# test
m = Model(datetime="2024-02-06 11:38:18+00:00")
print(m)
print(m.datetime)
print(m.model_dump(mode="python"))
print(m.model_dump_json())
print(m.model_dump(mode="json"))
```

**Comment by rumbarum** [comment]
This is complete version for Custom ArrowPydantic with pydanticV2.
Now, IDE can guess correct type.

```python
from typing import Any, Annotated

import arrow
from pydantic import (
    GetCoreSchemaHandler,
    GetJsonSchemaHandler
)
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema

from pydantic import BaseModel

class ArrowSchema:
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:
        def validate_by_arrow(value) -> arrow.Arrow:
            try:
                arr = arrow.get(value)
                return arr
            except Exception as e:
                raise ValueError(f"Arrow can not parse")

        def arrow_serialization(value: arrow.Arrow, _, info) -> str | arrow.Arrow:
            if info.mode == "json":
                # impl your json serialization logic
                return value.isoformat()
            return value

        return core_schema.no_info_before_validator_function(
            function=validate_by_arrow,
            schema=core_schema.union_schema(
                [
                    core_schema.str_schema(),
                    core_schema.datetime_schema(),
                    core_schema.is_instance_schema(arrow.Arrow),
                ]
            ),
            serialization=core_schema.wrap_serializer_function_ser_schema(
                arrow_serialization, info_arg=True
            ),
        )
     
     # this is important for FastAPI user!
    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        json_schema = handler(core_schema)
        json_schema = handler.resolve_ref_schema(json_schema)
        # for custom OpenAPI Scheme
        json_schema["title"] = "timestamp"
        json_schema["examples"] = ["2024-01-01 13:38:18.000+00:00"]
        json_schema["type"] = "string"
        json_schema["format"] = "datetime"
        return json_schema

ArrowPydantic = Annotated[ arrow.Arrow, ArrowSchema]

class Model(BaseModel):
    data : ArrowPydantic

m = Model(data="2024-02-06 11:38:18+00:00")
print(m)
print(m.data)
print(m.model_dump(mode="python"))
print(m.model_dump_json())
print(m.model_dump(mode="json"))
```
