### ISSUE TITLE
AliasGenerator causes computed_field to throw an error when generating schema 

### ISSUE THREAD

**Issue by soggychips** [pydantic/pydantic#8768]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using an AliasGenerator within a ConfigDict's `alias_generator` property, computed_field decorators cause errors when Pydantic tries to generate the schema.

Using the `Box` example from the [computed fields doc page](https://docs.pydantic.dev/latest/concepts/fields/#the-computed_field-decorator), and adding the AliasGenerator simply breaks it. Removing the computed_field allows the alias generator to work perfectly fine.

Traceback looks like the following:

```
Traceback (most recent call last):
  File "/Users/soggy/Developer/pyt/pydantic_test.py", line 4, in <module>
    class Box(BaseModel):
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 501, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 761, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 576, in _model_schema
    self._computed_field_schema(d, decorators.field_serializers)
  File "/Users/soggy/.pyenv/versions/pyt/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1641, in _computed_field_schema
    raise TypeError(f'alias_generator {alias_generator} must return str, not {alias.__class__}')
TypeError: alias_generator AliasGenerator(alias=None, validation_alias=<function Box.<lambda> at 0x10dd48040>, serialization_alias=None) must return str, not <class 'NoneType'>```

### Example Code

```Python
from pydantic import BaseModel, computed_field, ConfigDict, AliasGenerator, AliasChoices


class Box(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=AliasGenerator(
            validation_alias=lambda field_name: AliasChoices(
                field_name.lower(),
                field_name.upper(),
                field_name.title(),
                field_name.capitalize(),
            )
        ),
    )

    width: float
    height: float
    depth: float
    extra_field: str | None

    @computed_field
    def volume(self) -> float:
        return self.width * self.height * self.depth


if __name__ == "__main__":
    b = Box(WIDTH=1, Height=2, depth=3, Extra_Field="extra")
    print(b.model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/soggy/.pyenv/versions/3.12.1/envs/pyt/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Jan 16 2024, 08:20:41) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-13.6-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@soggychips,

Thanks for reporting this bug! Seems like this would be a pretty good first issue. Any interest in contributing a fix?

**Comment by soggychips** [comment]
Hi,

I see the code that was added, but the new class method (`_apply_alias_generator_to_field_info`) is not being called with the same example from above, as the same error is being raised.

Line 557 in _generate_schema.py calls `self._common_field_schema` only in the truthy result of the if statement, yet the example I gave reaches the else, which calls `self._computed_field_schema`, which does not apply the new check.

If i pass an empy `alias` into the AliasGenerator, no error is thrown, but if only `validation_alias` is passed (as in the example code I provided), the same issue stands.

I think `_computed_field_schema` needs to have the same logic you've added, especially considering the comment at 1629 (_generate_schema.py), which states:

```
# Handle alias_generator using similar logic to that from
# pydantic._internal._generate_schema.GenerateSchema._common_field_schema,
# with field_info -> d.info and name -> d.cls_var_name
```

**Comment by soggychips** [comment]
Hi,

My apologies. I haven't cloned the repository as standalone.

I thought this was pushed to the latest version of pydantic on pypi. 

Any idea when this change will go live?

Thanks!

**Comment by sydney-runkle** [comment]
@soggychips,

No worries. It'll definitely get released in 2.7, which will be in mid-March. Perhaps we could include this in 2.6.2, which will hopefully be this week. I'll keep you updated!

**Comment by ryancausey** [comment]
@sydney-runkle I just ran into this issue. Is there any plan to release a patch release for this fix earlier than "mid-march"?

**Comment by sydney-runkle** [comment]
@ryancausey,

I'm hoping to do a 2.6.4 patch release with some discriminated union bug fixes either late this week or early next week, and I can pull this change in as well!
