### ISSUE TITLE
URL validation of length done before parsing

### ISSUE THREAD

**Issue by BlackVoid** [pydantic/pydantic#8817]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a user inputs a URL that's not URL encoded it passes the validation of max length n, after storing the value in the database the validation fails due to the url encoding increasing the URL length. I think the expected behavior would be to either keep the URL as the user wrote it, or to validate the length based on the encoded URL.

Right now I end up in a situation where I think the validation enforcing the max length, but I end up with a URL that fails the validation on output which is not desirable.

### Example Code

```Python
from typing import Optional, Annotated

from pydantic import BaseModel, UrlConstraints
from pydantic_core import Url

HttpsUrl = Annotated[Url, UrlConstraints(max_length=34, allowed_schemes=['https'])]


class MyModel(BaseModel):
    url: Optional[HttpsUrl] = None

MyModel.model_validate({"url": "https://google.com/1234"})
url = "https://example.com/?q={\"data\": 1}"
print(f"Before: {len(url)=} {url=}")  # Before: len(url)=34 url='https://example.com/?q={"data": 1}'
m = MyModel.model_validate({"url": url})  # Successful
print(f"After: {len(m.url.unicode_string())=} {m.url.unicode_string()=}")  # After: len(m.url.unicode_string())=40 m.url.unicode_string()='https://example.com/?q={%22data%22:%201}'
MyModel.model_validate({"url": m.url.unicode_string()})  # Fails


"""
Traceback (most recent call last):
  File ".../test.py", line 17, in <module>
    MyModel.model_validate({"url": m.url.unicode_string()})  # Fails
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
url
  URL should have at most 34 characters [type=url_too_long, input_value='https://example.com/?q={%22data%22:%201}', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/url_too_long
"""
```

### Python, Pydantic & OS Version

```Text
% python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/xx/.local/share/virtualenvs/xyz/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@BlackVoid,

Thanks for raising this issue. As of right now, changing this behavior would be a breaking change. I'd recommend using a custom after validator if you want the url length to be validated after encoding.

I'll mark this with a `V3` tag so that we can revisit it later if this gets enough traction / support.
