### ISSUE TITLE
Initializing a field with a model instance

### ISSUE THREAD

**Issue by aleksey925** [pydantic/pydantic#8884]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, please help me solve the following problem. Validation fails if I try to initialize a field with a model instance, rather than a dictionary with raw data.

Traceback
```
Traceback (most recent call last):
  File "/Users/alexey/PycharmProjects/temp/temp9.py", line 27, in <module>
    msg = MyMessageEnvelope(
          ^^^^^^^^^^^^^^^^^^
  File "/Users/alexey/PycharmProjects/temp/venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MessageEnvelope[BodyVer1[Body]]
body
  Input should be a valid dictionary or instance of BodyVer1[Body] [type=model_type, input_value=BodyVer1(ver_1_0_0=Body(user_uid='user_uid')), input_type=BodyVer1]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type
```

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T")
V = TypeVar("V")


class BodyVer1(BaseModel, Generic[T]):
    model_config = ConfigDict(populate_by_name=True)

    ver_1_0_0: T = Field(alias="1.0.0")


class MessageEnvelope(BaseModel, Generic[V]):
    id: str  # noqa: A003
    producer: str
    body: V
    created_at: float = Field(description="Timestamp in seconds")


class Body(BaseModel):
    user_uid: str = 'user_uid'


MyMessageEnvelope = MessageEnvelope[BodyVer1[Body]]
msg = MyMessageEnvelope(
    id='id',
    producer='producer',
    body=BodyVer1(ver_1_0_0=Body(user_uid='user_uid')),
    created_at=0.0
)
print(msg)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.2
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/alexey/PycharmProjects/temp/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 12 2024, 11:20:56) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@aleksey925,

Sure thing. There are two approaches you could take here. The first is that you could explicitly parametrize the `BodyVer1` instance that you're creating, like follows:

```py
from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T")
V = TypeVar("V")


class BodyVer1(BaseModel, Generic[T]):
    model_config = ConfigDict(populate_by_name=True)

    ver_1_0_0: T = Field(alias="1.0.0")


class MessageEnvelope(BaseModel, Generic[V]):
    id: str  # noqa: A003
    producer: str
    body: V
    created_at: float = Field(description="Timestamp in seconds")


class Body(BaseModel):
    user_uid: str = 'user_uid'


MyMessageEnvelope = MessageEnvelope[BodyVer1[Body]]
msg = MyMessageEnvelope(
    id='id',
    producer='producer',
    body=BodyVer1[Body](ver_1_0_0=Body(user_uid='user_uid')),
    created_at=0.0
)
print(repr(msg))
#> MessageEnvelope[BodyVer1[Body]](id='id', producer='producer', body=BodyVer1[Body](ver_1_0_0=Body(user_uid='user_uid')), created_at=0.0)
```

The second is that you could create a subclass of `BodyVer1` parametrized with body, then use that as your constructor. For example:

```py
from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field

T = TypeVar("T")
V = TypeVar("V")


class BodyVer1(BaseModel, Generic[T]):
    model_config = ConfigDict(populate_by_name=True)

    ver_1_0_0: T = Field(alias="1.0.0")


class MessageEnvelope(BaseModel, Generic[V]):
    id: str  # noqa: A003
    producer: str
    body: V
    created_at: float = Field(description="Timestamp in seconds")


class Body(BaseModel):
    user_uid: str = 'user_uid'

class BodyVer1Parametrized(BodyVer1[Body]):
    pass

MyMessageEnvelope = MessageEnvelope[BodyVer1Parametrized]
msg = MyMessageEnvelope(
    id='id',
    producer='producer',
    body=BodyVer1Parametrized(ver_1_0_0=Body(user_uid='user_uid')),
    created_at=0.0
)
print(repr(msg))
#> MessageEnvelope[BodyVer1Parametrized](id='id', producer='producer', body=BodyVer1Parametrized(ver_1_0_0=Body(user_uid='user_uid')), created_at=0.0)
```

Hope this helps! Let me know if you have any additional follow up questions.

**Comment by sydney-runkle** [comment]
Yeah, we have some commentary in the generic models section of the docs about isinstance irregularities!
