### ISSUE TITLE
AssertionError when calling BaseModel.schema_json()

### ISSUE THREAD

**Issue by hsteinhaus** [pydantic/pydantic#8896]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pyndantic is asking me to report this trivial bug, so I do :smiley: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/holger-local/.local/lib/python3.12/site-packages/pydantic/main.py", line 1287, in schema_json
    cls.model_json_schema(by_alias=by_alias, ref_template=ref_template),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/holger-local/.local/lib/python3.12/site-packages/pydantic/main.py", line 391, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/home/holger-local/.local/lib/python3.12/site-packages/pydantic/json_schema.py", line 2176, in model_json_schema
    assert '__pydantic_core_schema__' in cls.__dict__, 'this is a bug! please report it'
AssertionError: this is a bug! please report it
```

### Example Code

```Python
from pydantic import BaseModel
BaseModel.schema_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/.local/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
                     platform: Linux-6.7.5-200.fc39.x86_64-x86_64-with-glibc2.38
             related packages: fastapi-0.109.2 pydantic-settings-2.2.1 typing_extensions-4.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@hsteinhaus,

Thanks for reporting this. `schema_json()`, or the new (not deprecated) version of said function `model_json_schema()` are meant to be called on subclasses of `BaseModel`, not `BaseModel` itself.

Marking this as resolved.

**Comment by hsteinhaus** [comment]
@sydney-runkle Yes, it is completely clear that calling `model_json_schema()` make not a lot of sense. 

However, when iterating a module conaining user models, that can easily happen by accident. And an "Assertion failed, this is a bug, please report" might not be the adequate response to the user.

**Comment by sydney-runkle** [comment]
Reopening, we can add a more descriptive error for the case when it's being called on `BaseModel`.
