### ISSUE TITLE
validate_call misses validations

### ISSUE THREAD

**Issue by lpgros** [pydantic/pydantic#8929]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In this example:

```python
>>> from collections.abc import Collection
>>> from pydantic import ConfigDict, validate_call
>>>
>>> @validate_call(config=ConfigDict(strict=True, arbitrary_types_allowed=True),)
... def my_test(a_collection: Collection[str],):
...     print(type(a_collection), a_collection)
...
>>> my_test({1,2,3,})
<class 'set'> {1, 2, 3}
>>> my_test([1,2,3])
<class 'list'> [1, 2, 3]
>>>
```

you can see that Pydantic's `validate_call` completely missed validating the `str` vs `int` (content of the collections).

Confirming that it works with, for example, a `Set`:
```python

>>> @validate_call(config=ConfigDict(strict=True, arbitrary_types_allowed=True),)
... def my_test(a_set: Set[str],):
...     print(type(a_set), a_set)
...
>>> my_test({1,2,3,})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".virtualenvs/env3/lib/python3.12/site-packages/pydantic/validate_call_decorator.py", line 58, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".virtualenvs/env3/lib/python3.12/site-packages/pydantic/_internal/_validate_call.py", line 81, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 3 validation errors for my_test
0.0
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
0.1
  Input should be a valid string [type=string_type, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
0.2
  Input should be a valid string [type=string_type, input_value=3, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
>>>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=false
                 install path: .virtualenvs/env3/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Feb 21 2024, 09:32:09) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-x86_64-i386-64bit
             related packages: email-validator-2.0.0.post2 pyright-1.1.350 typing_extensions-4.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@lpgros,

Pydantic doesn't natively offer support for the `Collection` type, which is why you have to use `arbitrary_types_allowed=True` in the config. If you want to add support for validating this type, you'll have to use a custom validator, or implement `__get_pydantic_core_schema__` on a custom subclass of `Collection`.

Marking as closed, as this is expected behavior, given the lack of support for this type.
