### ISSUE TITLE
Using an attribute containing the word "field" causes pydantic.errors.PydanticUserError: A non-annotated attribute was detected

### ISSUE THREAD

**Issue by ryancausey** [pydantic/pydantic#8938]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am attempting to define a model that has a field named "field_errors". This results in a `pydantic.errors.PydanticUserError` being raised. I've tracked this down to what appears to be an undocumented limitation on model field names: if the name of the field contains the word "field", in any location, this error is raised. Here is an example traceback:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rccausey/.cache/pypoetry/virtualenvs/user-api-Hi7dQLFB-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 93, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/home/rccausey/.cache/pypoetry/virtualenvs/user-api-Hi7dQLFB-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 406, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `field = <class 'str'>`. All model fields require a type annotation; if `field` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.7/u/model-field-missing-annotation
```

Is this in the documentation somewhere and I just missed it, or is this a bug?

### Example Code

```Python
from pydantic import BaseModel

class Foo(BaseModel):
    field: str
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0a1
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/rccausey/.cache/pypoetry/virtualenvs/user-api-Hi7dQLFB-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul 20 2023, 18:33:17) [GCC 11.3.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by ryancausey** [comment]
Never mind, this was user error after all. I was accidentally using `field = str` instead of `field: str` when defining the field.
