### ISSUE TITLE
Optional Decimal fields cause ValueError with constraints `max_digits` / `decimal_places` 

### ISSUE THREAD

**Issue by Cielquan** [pydantic/pydantic#8999]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Fields of type `decimal.Decimal | None` with either or both constraints `max_digits` / `decimal_places` cause a `ValueError: Unknown constraint max_digits` exception.

This is easily reproduced in the [documentation](https://docs.pydantic.dev/latest/concepts/fields/#decimal-constraints). You just need to tweak the `precise` field's type to `Decimal | None` and run the example. You will get this Traceback:

```
pydantic version: v2.6.4, pydantic-core version: v2.16.3
Traceback (most recent call last):
  File "", line 6, in 
  File "/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File "/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 742, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 563, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 563, in 
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 906, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1071, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1765, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1848, in new_handler
    schema = self._apply_single_annotation(schema, annotation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1785, in _apply_single_annotation
    inner = self._apply_single_annotation(inner, metadata)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1807, in _apply_single_annotation
    maybe_updated_schema = _known_annotated_metadata.apply_known_metadata(metadata, schema.copy())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pydantic/_internal/_known_annotated_metadata.py", line 184, in apply_known_metadata
    raise ValueError(f'Unknown constraint {constraint}')
ValueError: Unknown constraint max_digits
```

### Example Code

```Python
from decimal import Decimal

from pydantic import BaseModel, Field


class Foo(BaseModel):
    precise: Decimal | None = Field(max_digits=5, decimal_places=2)
```

### Python, Pydantic & OS Version

This is my local maschine:

```Text
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/admin-riedelc/projects/swlp-main/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
                     platform: Linux-6.5.0-25-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0 pydantic-settings-2.2.1 fastapi-0.110.0 mypy-1.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @Cielquan,

Try this:

```py
from decimal import Decimal

from pydantic import BaseModel, Field

from typing_extensions import Annotated


class Foo(BaseModel):
    precise: Annotated[Decimal, Field(max_digits=5, decimal_places=2)] | None
```

That should resolve the issue!

**Comment by Cielquan** [comment]
Hi @sydney-runkle, thanks for the fast reply. Yes, the fix works.

A while back the usage of `Annotated` in pydantic models caused issues with fastapi. But it luckily seems to be fixed now.

**Comment by Bardamusic** [comment]
@sydney-runkle for this creates a required field and I get the error Foo->precise: Field required

class Foo(BaseModel):
    precise: Annotated[Decimal, Field(max_digits=5, decimal_places=2)] | None
   
Instead with this
 
class Foo(BaseModel):
    precise: Optional[Annotated[Decimal, Field(max_digits=5, decimal_places=2)]] = None
   
It works, but I am not sure if that's intended

**Comment by sydney-runkle** [comment]
@Bardamusic,

Yep, your second approach works too. I'll correct my recommendation to this, if you want it to be optional:

```py
from decimal import Decimal

from pydantic import BaseModel, Field

from typing_extensions import Annotated


class Foo(BaseModel):
    precise: Annotated[Decimal, Field(max_digits=5, decimal_places=2)] | None = None


f = Foo()
```
