### ISSUE TITLE
GenerateSchema.match_type doesn't support classes inherited from str

### ISSUE THREAD

**Issue by NothisIm** [pydantic/pydantic#9006]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm extensively using classes derived from `str` with some additional fields added for convenience. While used in Pydantic models, such classes are treated fine by v1, however v2 throws an error.

<details>
<summary>Error output</summary>

```
Traceback (most recent call last):
...
  File "<input>", line 10, in <module>
  File ".../lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File ".../lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 759, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 572, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 572, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 923, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1045, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1747, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1728, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 851, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 397, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class '__main__.StrChild'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
```
</details>

I checked the code, it's [this line](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_generate_schema.py#L759) that causes the issue. Something as simple as changing it to `if str in obj.__bases__` solves the problem.

 I was going to open a PR, but went through the doc on contributing first - and here I am, creating an issue and volunteering to fix it (probably would be better for all primitive types, not only `str`) 🙂 

### Example Code

```Python
from pydantic import BaseModel

class StrChild(str):
    pass

class Model(BaseModel):
    field: StrChild
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
               python version: 3.11.6 (main, Oct  2 2023, 20:14:46)
                     platform: macOS-14.3-x86_64-i386-64bit
```

**Comment by sydney-runkle** [comment]
@NothisIm,

Thanks for your well thought out feature request. It's my understanding that we purposefully don't automatically handle subclasses of known types (see this PR for example, which ensures that doesn't happen: https://github.com/pydantic/pydantic/pull/5737).

I'll consult with the team regarding the reasoning behind this decision. I think that the workaround with the custom schema definitions is the best way forward, for now! Closing as resolved, but I'll reopen if it turns out we'd consider a change!

**Comment by sydney-runkle** [comment]
Ah ok, so a bit more clarification. 2 of the major reasons why we can't do this are:

1. If you inherit from multiple stdlib types (known types), we can't necessarily know what behavior is desired / expected, or what validation logic to use
2. You can easily change the behavior of such a class, say by adding a custom constructor, which is difficult to detect / respond to.

In sum, there are some non-trivial cases that are difficult to define correct behavior for without some sort of opt-in from users.

**Comment by NothisIm** [comment]
thanks a lot for your replies 🙇‍♀️ 
I will stick to the workaround for now
