### ISSUE TITLE
Docs examples can't be run

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#9012]
Trying to run examples in the docs gives

```py
Error starting Python: PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 349, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 444, in add_requirement_inner
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 312, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'pydantic==2.7.0a1'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```
This is caused by 
https://github.com/pydantic/pydantic/blob/534a446032adaa7576f7ac7aa9c2c41d55695d7f/pydantic/version.py#L6

I think we just need another way to detect the latest version.

**Comment by sydney-runkle** [comment]
I took a brief look at this. Might be a bit difficult, due to the fact that `micropip` doesn't support installs from git (and this is only failing on the `dev` branch of the docs, where we pull from `main`...

That being said, this is where the issue needs to be fixed: https://github.com/pydantic/pydantic/blob/5c8afe65a69d9fb127c32fbf288156d7c13da346/docs/plugins/main.py#L78-L87

**Comment by tselepakis** [comment]
Probably this is not totally related but I had a similar issue when I was trying the examples of logfire. The example looks like this:
```python
# /// script
# dependencies = ["logfire", "pydantic_ai_slim[openai]"]
# ///

# This example demonstrates Pydantic AI running with OpenAI!

from pydantic_ai import Agent
import logfire

# configure logfire
logfire.configure(token='__YOUR_LOGFIRE_WRITE_TOKEN__')
logfire.instrument_pydantic_ai()

agent = Agent('openai:gpt-4o')

result = await agent.run(
    'How does pyodide let you run Python in the browser? (short answer please)'
)

print(f'output: {result.output}')
```

and fails with the following error:
```bash
Traceback (most recent call last):
  File "/tmp/pydantic_run/_prepare_env.py", line 104, in prepare_env
    await micropip.install(install_dependencies, keep_going=True)
  File "/lib/python3.12/site-packages/micropip/package_manager.py", line 146, in install
    return await install(
           ^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/install.py", line 56, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'pydantic-core==2.33.2'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
```

I suppose this is because the pydantic-core version in pyodide is 2.27.2.
https://pyodide.org/en/stable/usage/packages-in-pyodide.html

**Comment by JonathanWindell** [comment]
Hi, I've read through the issue and the analysis by @sydney-runkle. As this is still open and unassigned, I'd like to try and tackle it. I'll start by setting up the environment to reproduce the problem locally if this hasn't already been solved?

**Comment by Viicos** [comment]
@tselepakis are you referring about the example that can run on pydantic.run? It works fine on my end.

**Comment by tselepakis** [comment]
Yes @Viicos I was referring to pydantic.run but I checked it again and it works us you said. I am not sure which was the pyodide version when I was having this issue. The [current version](https://pyodide.org/en/stable/project/changelog.html#version-0-27-2) has a fix regarding pydantic-core:

_Upgraded pydantic to 2.10.5 and fixed a version mismatch with pydantic_core [#5368](https://github.com/pyodide/pyodide/pull/5368)_
