### ISSUE TITLE
Private model attributes handled incorrectly by type checkers

### ISSUE THREAD

**Issue by TeeSeal** [pydantic/pydantic#9048]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

While private model attributes are handled correctly by pydantic at runtime as described in https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes, it seems that type checkers still require private model attributes to be provided when instantiating a model.

For the example code provided, both Mypy and Pyright/Pylance show this problem:
<img width="662" alt="image" src="https://github.com/pydantic/pydantic/assets/14080148/cb72c030-0136-414d-8faf-0f063d7bb34f">
<img width="639" alt="image" src="https://github.com/pydantic/pydantic/assets/14080148/e82bdb4c-064c-4612-ac95-4ed3b950b46a">

The code runs just fine regardless of the type checker complaining.

On the flip side, attempting to actually specify the private attribute when instantiating keeps the type checker satisfied, but causes a runtime error.
```py
thing = MyModel(_private_attr="bar")

# Traceback (most recent call last):
#   File "*/.venv/lib/python3.9/site-packages/pydantic/main.py", line 746, in __getattr__
#     return self.__pydantic_private__[item]  # type: ignore
# KeyError: '_private_attr'
# 
# The above exception was the direct cause of the following exception:
# 
# Traceback (most recent call last):
#   File "*/test.py", line 9, in <module>
#     print(thing._private_attr)
#   File "*/.venv/lib/python3.9/site-packages/pydantic/main.py", line 748, in __getattr__
#     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
# AttributeError: 'MyModel' object has no attribute '_private_attr'
```

I'm not familiar with the inner workings of pydantic, but my assumption is that this happens because private attributes are being added to the `__init__` function signature of the model, which should not be the case (I think?). 

### Example Code

```Python
from pydantic import BaseModel


class MyModel(BaseModel):
    _private_attr: str


thing = MyModel()
print(thing.model_dump())
```

### Python, Pydantic & OS Version

```Text
Python: 3.9.18
pydantic: 2.6.3
OS: macOS 14.2.1 (23C71)
```

**Comment by TeeSeal** [comment]
I've done some more digging.

Just to confirm that the issue is not with the VSCode extension I performed the check with mypy directly and getting the same problem.
```
.venv ❯ mypy test.py
test.py:8: error: Missing named argument "_private_attr" for "MyModel"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by TeeSeal** [comment]
I looked into how the signatures are build built for the models and everything seems to check out.https://github.com/pydantic/pydantic/blob/a3b7214a1d6ac8e32c29e9d4436ea6a9e253ead7/pydantic/_internal/_model_construction.py#L570-L573

Using `inspect.signature` on the model returns the correct signature without the private attributes.
```py
from inspect import signature

from pydantic import BaseModel


class MyModel(BaseModel):
    _private_attr: str


print(signature(MyModel)) # () -> None
```

This begs the question of where are the type checkers pulling their signatures from?

**Comment by mvernacc** [comment]
@TeeSeal I ran into the same issue. Since https://github.com/pydantic/pydantic/pull/9293 was merged, I was now able to solve the pyright issue by marking the attribute as a `PrivateAttr`:

```python
from pydantic import BaseModel, PrivateAttr


class MyModel(BaseModel):
    _private_attr: str = PrivateAttr()


thing = MyModel()
print(thing.model_dump())
```

**Comment by TeeSeal** [comment]
@mvernacc 
> I ran into the same issue. Since #9293 was merged, I was now able to solve the pyright issue by marking the attribute as a `PrivateAttr`:

Thanks. Yeah using `PrivateAttr()` does make it behave as intended. However, the documentation still suggests that it should be usable without https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes
```python
from datetime import datetime
from random import randint

from pydantic import BaseModel, PrivateAttr


class TimeAwareModel(BaseModel):
    _processed_at: datetime = PrivateAttr(default_factory=datetime.now)
    _secret_value: str

    def __init__(self, **data):
        super().__init__(**data)
        # this could also be done with default_factory
        self._secret_value = randint(1, 5)


m = TimeAwareModel()
print(m._processed_at)
#> 2032-01-02 03:04:05.000006
print(m._secret_value)
#> 3
```

I'll try to have a look deeper at how PrivateAttr is handled and try to apply the same logic for regular underscore attributes, see if that fixes it.

**Comment by Viicos** [comment]
Closing as per https://github.com/pydantic/pydantic/issues/9048#issuecomment-2294362155.

**Comment by quentin-ag** [comment]
Since this is the only place where I found a solution for this problem, here is an extra piece of information for future readers: while the [accepted solution](https://github.com/pydantic/pydantic/issues/9048#issuecomment-2294362155) worked for me, the following – supposedly equivalent – code still triggers the `call-arg` error from `mypy`.

```python
from typing import Annotated

from pydantic import BaseModel, PrivateAttr

class MyModel(BaseModel):
    _private_attr: Annotated[str, PrivateAttr()] # only difference with solution

thing = MyModel()
print(thing.model_dump())
```
This was tested only with pydantic 2.3.0.

**Comment by Viicos** [comment]
@quentin-ag static type checkers _do not_ understand annotated metadata. Read more [here](https://docs.pydantic.dev/latest/concepts/fields/#the-annotated-pattern).
