### ISSUE TITLE
incomplete ValidationError when validating nested models with validate_default=True

### ISSUE THREAD

**Issue by dlax** [pydantic/pydantic#9051]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following example uses a model with a field that is also a model, with a field with a default value, and using ` validate_default=True`. When default values fail validation (e.g. after checking the environment or so), the `ValidationError` is missing some `errors` entries and that the ones referring to nested models errors have a wrong `loc`.

### Example Code

```Python
from typing import Annotated
import pydantic

class BaseModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(validate_default=True)

class S(BaseModel):
    s_id: Annotated[int, pydantic.Field(ge=3)] = 2

class M(BaseModel):
    m_id: Annotated[int, pydantic.Field(ge=2)] = 1
    s: Annotated[S, pydantic.Field(default_factory=S)]  # FAIL
    # s: Annotated[S, pydantic.Field(default_factory=dict)]  # Works!

# Trying to validate an empty object, thus using default values, shows that
# the ValidationError is missing an error (about M.m_id) and that
# the "loc" entry of M.s.s_id is incorrectly set to "s_id":
>>> M.model_validate({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.11/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for S
s_id
  Input should be greater than or equal to 3 [type=greater_than_equal, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/greater_than_equal

# As compared to validating with explicit default values:
>>> M.model_validate(obj)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.venv/lib/python3.11/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for M
m_id
  Input should be greater than or equal to 2 [type=greater_than_equal, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/greater_than_equal
s.s_id
  Input should be greater than or equal to 3 [type=greater_than_equal, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/greater_than_equal


# Same with pytest

expected_errors = [
    (("m_id",), "Input should be greater than or equal to 2"),
    (("s", "s_id"), "Input should be greater than or equal to 3"),
]


def test_model_defaults() -> None:  # FAIL
    with pytest.raises(pydantic.ValidationError) as cm:
        M.model_validate({})
    assert [(e["loc"], e["msg"]) for e in cm.value.errors()] == expected_errors


def test_model() -> None:  # PASS
    obj = {"m_id": 1, "s": {"s_id": 2}}
    with pytest.raises(pydantic.ValidationError) as cm:
        M.model_validate(obj)
    assert [(e["loc"], e["msg"]) for e in cm.value.errors()] == expected_errors
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/denis/src/dalibo/pglift/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
                     platform: Linux-6.1.0-18-amd64-x86_64-with-glibc2.36
             related packages: pydantic-settings-2.2.1 typing_extensions-4.10.0 mypy-1.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@dlax,

Thanks for reporting this. I don't think this is actually a bug - the behavior you're seeing is the same as that which you get if you don't validate the default values, but instead pass in the same invalid values to the constructor:

```py
import json
from typing import Annotated

import pydantic

class BaseModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(validate_default=True)

class S(BaseModel):
    s_id: Annotated[int, pydantic.Field(ge=3)] = 2

class M(BaseModel):
    m_id: Annotated[int, pydantic.Field(ge=2)] = 1
    s: Annotated[S, pydantic.Field(default_factory=S)]  # FAIL
    # s: Annotated[S, pydantic.Field(default_factory=dict)]  # Works!

try:
    s = S()
except pydantic.ValidationError as e:
    print(json.dumps(e.errors(include_url=False), indent=2))
"""
[
  {
    "type": "greater_than_equal",
    "loc": [
      "s_id"
    ],
    "msg": "Input should be greater than or equal to 3",
    "input": 2,
    "ctx": {
      "ge": 3
    }
  }
]
"""

try:
    m = M()
except pydantic.ValidationError as e:
    print(json.dumps(e.errors(include_url=False), indent=2))
"""
[
  {
    "type": "greater_than_equal",
    "loc": [
      "s_id"
    ],
    "msg": "Input should be greater than or equal to 3",
    "input": 2,
    "ctx": {
      "ge": 3
    }
  }
]
"""

# let's consider the case without default values (and without validating them)
class S(pydantic.BaseModel):
    s_id: Annotated[int, pydantic.Field(ge=3)]

class M(pydantic.BaseModel):
    m_id: Annotated[int, pydantic.Field(ge=2)]
    s: S

try:
    s = S(s_id=2)
except pydantic.ValidationError as e:
    print(json.dumps(e.errors(include_url=False), indent=2))
"""
[
  {
    "type": "greater_than_equal",
    "loc": [
      "s_id"
    ],
    "msg": "Input should be greater than or equal to 3",
    "input": 2,
    "ctx": {
      "ge": 3
    }
  }
]
"""

try:
    m = M(m_id=1, s=S(s_id=2))
except pydantic.ValidationError as e:
    print(json.dumps(e.errors(include_url=False), indent=2))
"""
[
  {
    "type": "greater_than_equal",
    "loc": [
      "s_id"
    ],
    "msg": "Input should be greater than or equal to 3",
    "input": 2,
    "ctx": {
      "ge": 3
    }
  }
]
"""
```

What's happening in both of these cases is that validation is failing on the construction of the `S` model for the `s` field, and so validation terminates at that point.
