### ISSUE TITLE
__future__  annotations with typing.ClassVar

### ISSUE THREAD

**Issue by gswifort** [pydantic/pydantic#9069]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a base model with `typing.ClassVar` variables defined is imported from another module with a `from __future__ import annotations` header, the inheriting model raises an exception like this:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\package\module_2.py", line 9, in <module>
    A()
  File ".\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\pydantic\_internal\_mock_val_ser.py", line 47, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `A` is not fully defined; you should define `typing`, then call `A.model_rebuild()`.
```

but works fine with model fields.

### Example Code

```Python
# module_1.py
from __future__ import annotations
import typing
from pydantic import BaseModel

class Base(BaseModel):
    CONST: typing.ClassVar[str] = "a"


# module_2.py
from .module_1 import Base

class A(Base):
    pass

if __name__ == "__main__":
    A()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
pydantic-core version: 2.16.3
pydantic-core build: profile=release pgo=true
python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
related packages: typing_extensions-4.10.0
```

**Comment by sydney-runkle** [comment]
@gswifort,

Huh, thanks for reporting this. That's definitely odd. I think @alexmojaki might know what's going on here, let's see what he thinks!
