### ISSUE TITLE
SecretStr fields report in plaintext when there is a validation error

### ISSUE THREAD

**Issue by signebedi** [pydantic/pydantic#9139]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a pydantic model that represents the data passed by the client at the point of account creation, see example code. This is a FastAPI application with a frontend. When there are validation errors (in the case below, the password verification field was not passed), however, the model reports the SecretStr back in plaintext:

Here's an example error:

{"detail":[{"type":"missing","loc":["body","verify_password"],"msg":"Field required","input":{"username":"jimmy","email":"jimmy@example.com", "password":"My_Password123!","opt_out":false},"url":"https://errors.pydantic.dev/2.6/v/missing"}]}

### Example Code

```Python
class CreateUserRequest(BaseModel):
    username: str = Field(..., min_length=4, max_length=100)
    # Added a little syntactic salt with the SecretStr, see https://stackoverflow.com/a/65277859/13301284
    password: SecretStr = Field(..., min_length=8)
    verify_password: SecretStr = Field(..., min_length=8)
    email: EmailStr
    opt_out: bool = False

    @validator('username')
    def username_pattern(cls, value):
        pattern = re.compile(config.USERNAME_REGEX)
        if not pattern.match(value):
            raise ValueError(config.USERNAME_HELPER_TEXT)
        return value.lower()
        
    @validator('password', 'verify_password', pre=True, each_item=False)
    def password_pattern(cls, value):
        # Since value is now of type SecretStr, we need to get its actual value
        password = value.get_secret_value() if isinstance(value, SecretStr) else value
        pattern = re.compile(config.PASSWORD_REGEX)
        if not pattern.match(password):
            raise ValueError(config.PASSWORD_HELPER_TEXT)
        return value

    @validator('verify_password', always=True)
    def passwords_match(cls, v, values, **kwargs):
        if 'password' in values and v.get_secret_value() != values['password'].get_secret_value():
            raise ValueError('Passwords do not match')
        return v
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: {redacted}/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.15.0-94-generic-x86_64-with-glibc2.31
             related packages: pydantic-settings-2.2.1 typing_extensions-4.10.0 fastapi-0.110.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Ah yes this is a bit odd. We offer the `hide_input_in_errors` flag, but that's a manual setting that has to be enabled. I'll leave this open as a bug for now.

**Comment by sydney-runkle** [comment]
Chatted with the team about this one - not high priority enough given that there's a setting that can be enabled at runtime to prevent this. Going to remove this from our v2.10 milestone. Happy to consider a PR if anyone digs into this further.

**Comment by Rogdham** [comment]
Currently, [the documentation on `SecretStr`](https://docs.pydantic.dev/2.10/api/types/#pydantic.types.SecretStr) (and friends) states:

> A string used for storing sensitive information that you do not want to be visible in logging or tracebacks.

While I understand where it comes from, it contradicts the fact that the sensitive information is visible in tracebacks.

I would say that this issue is at least worthy of a documentation change. Perhaps mentioning the workaround?

---

I have simplified the example for further reference:

```py
from pydantic import BaseModel, SecretStr

class User(BaseModel):
    name: str
    secret: SecretStr

data = {"secret": "123"}
User.model_validate(data)
```

```
Traceback (most recent call last):
  File "/redacted/run.py", line 10, in <module>
    User.model_validate(data)
  File "/redacted/env/lib/python3.12/site-packages/pydantic/main.py", line 627, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
name
  Field required [type=missing, input_value={'secret': '123'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
```

**Comment by StuartBertram** [comment]
It looks like there's a disconnect between "hide input in errors *when exception is about this field*" and "hide the input for this field from all error output".

Presumably a `ConfigDict` on the `User` class would hide the input from any errors (although I've not tested with missing fields). But it's annoying to have to define that on every single model that you create!
