### ISSUE TITLE
Error when parsing a string as an integer

### ISSUE THREAD

**Issue by hlloreda** [pydantic/pydantic#9165]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In the previous stable release (pydantic version: `2.6.4`, pydantic-core version: `2.16.3`), the example code was working, but I'm facing this error with the latest version (`2.7.0b1`).
```
Traceback (most recent call last):
  File "/home/hugo/PycharmProjects/pythonProject3/main.py", line 9, in <module>
    TestModel(**{'b': '000001', 'a': '1'})
  File "/home/hugo/PycharmProjects/pythonProject3/venv/lib/python3.11/site-packages/pydantic/main.py", line 175, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TestModel
b
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='000001', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
```

### Example Code

```Python
import pydantic


class TestModel(pydantic.BaseModel):
    a: int
    b: int | None = None


TestModel(**{'b': '000001', 'a': '1'})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0b1
        pydantic-core version: 2.18.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/hugo/PycharmProjects/pythonProject3/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 28 2024, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
                     platform: Linux-6.7.10-200.fc39.x86_64-x86_64-with-glibc2.38
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@hlloreda,

Thanks for reporting this. We're looking into this issue and will work on a fix before we release 2.7!
