### ISSUE TITLE
Typing __pydantic_extra__ raises error if `from __future__ import annotations` present

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [pydantic/pydantic#9186]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Overriding the type annotation for `__pydantic_extra__` raises an exception if type annotations are strings (as per `from __future__ import annotations`).

This issue might be related to #8102.

Error after running below example code (plus a few lines of comment so the first line number doesn't match):

```
C:\Test > python test.py
Traceback (most recent call last):
  File "C:\Test\test.py", line 20, in <module>
    class Model(BaseModel):
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 183, in __new__
    complete_model_class(
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 759, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 543, in _model_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: The type annotation for `__pydantic_extra__` must be `Dict[str, ...]`

For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
```

### Example Code

```Python
from __future__ import annotations #  <- both work if removed, both fail if present

from typing import Dict

from pydantic import BaseModel, ConfigDict

# class with built-in dict
class Model(BaseModel):
    __pydantic_extra__: dict[str, int]

    model_config = ConfigDict(extra="allow")

# same with Dict
class Model2(BaseModel):
    __pydantic_extra__: Dict[str, int]

    model_config = ConfigDict(extra="allow")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.2
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\Test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: typing_extensions-4.10.0
```

**Comment by zEdS15B3GCwq** [comment]
Updated pydantic to 2.6.2. The error persists:

```
C:\Test\labnirs2snirf\snirf ❯ python test.py
Traceback (most recent call last):
  File "C:\Test\test.py", line 19, in <module>
    class Model(BaseModel):
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 183, in __new__
    complete_model_class(
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 742, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Test\.venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 534, in _model_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: The type annotation for `__pydantic_extra__` must be `Dict[str, ...]`

For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
```

**Comment by zEdS15B3GCwq** [comment]
So, it seems that the culprit is `get_origin()`:

https://github.com/pydantic/pydantic/blob/8aeac1a4c61b084ebecf61b38bb8d3e80884dc33/pydantic/_internal/_generate_schema.py#L546

I haven't spent a lot of time looking at the code, but if this is `typing.get_origin()`, then the problem is that it returns None if the type is a string:

```Python
>>> get_origin("dict[str, int]")
# None
>>> get_origin(dict[str, int])
<class 'dict'>
```
