### ISSUE TITLE
unhashable type: 'AliasPath' raised from BaseModel.model_construct()

### ISSUE THREAD

**Issue by jessemyers-lettuce** [pydantic/pydantic#9239]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This issue appears to be a regression in `2.7.0`; we did not see this issue in our code with `2.6.4`

Traceback:

```sh
Traceback (most recent call last):
  File "/path/to/main.py", line 9, in <module>
    example = Example.model_construct(value="value")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/pydantic/main.py", line 228, in model_construct
    elif field.validation_alias is not None and field.validation_alias in values:
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'AliasPath'
```

### Example Code

```Python
#!/usr/bin/env python3
from pydantic import AliasPath, BaseModel, Field

class Example(BaseModel):
    value: str = Field(validation_alias=AliasPath("data", "value"))


if __name__ == "__main__":
    example = Example.model_construct(value="value")
    assert example.value == "value"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
pydantic-core version: 2.18.1
pydantic-core build: profile=release pgo=true
install path: /path/to/.venv/lib/python3.12/site-packages/pydantic
python version: 3.12.2 (main, Feb 13 2024, 20:25:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
platform: macOS-14.4.1-arm64-arm-64bit
related packages: typing_extensions-4.11.0
commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @jessemyers-lettuce,

This is fixed on main by https://github.com/pydantic/pydantic/pull/9223. We'll do a patch release with this fix early next week!
