### ISSUE TITLE
Serialize ObjectId data in Dict[str,Any] type hint does not work

### ISSUE THREAD

**Issue by trertert** [pydantic/pydantic#9247]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to serialize dict[str,Any] type hint field when value is ObjectId，it is work well in pydantic v1,but in v2, it do not work, how to resolve it. Please help...

### Example Code

```Python
from typing import Any
from pydantic import BaseModel, ConfigDict
from bson import ObjectId

BaseModel.model_config["json_encoders"] = {ObjectId: str}


class UserModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    name: str
    id: ObjectId
    details: dict[str, Any]


user = UserModel(
    name='merry',
    id=ObjectId('6617c91f6eaef2815469ae69'),
    details={
        'id': ObjectId('6617c91f6eaef2815469ae69'),
        'password': 'xxx',
        'gender': 'female',
        'age': 18,
    },
)

print(user.model_dump_json(serialize_as_any=True))
```

- output
```
Traceback (most recent call last):
  File "/app/dev_dir/aa.py", line 20, in <module>
    print(user.model_dump_json(serialize_as_any=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/pydantic/main.py", line 379, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'bson.objectid.ObjectId'>
apppython dev_dir/aa.py
Traceback (most recent call last):
  File "/app/dev_dir/aa.py", line 23, in <module>
    print(user.model_dump_json(serialize_as_any=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/pydantic/main.py", line 379, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'bson.objectid.ObjectId'>
apppython dev_dir/aa.py
Traceback (most recent call last):
  File "/app/dev_dir/aa.py", line 25, in <module>
    print(user.model_dump_json(serialize_as_any=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/pydantic/main.py", line 379, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'bson.objectid.ObjectId'>
```
```


### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=false
                 install path: /root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 15 2023, 02:54:18) [GCC 12.2.1 20220924]
                     platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with
             related packages: pydantic-extra-types-2.6.0 mypy-1.9.0 fastapi-0.110.1 pydantic-settings-2.2.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by trertert** [comment]
#8426

**Comment by sydney-runkle** [comment]
@trertert,

Right, you're using an arbitrary type that `pydantic` doesn't know how to serialize. In the meantime, I'd recommend adding a custom type like the one added here, where you specify the core schema: https://github.com/pydantic/pydantic-extra-types/pull/151/files.

In the long term, we'll probably add support for this type in `pydantic-extra-types`, so you could just import it directly from there. Marking as resolved!

**Comment by HazyFish** [comment]
How exactly should I workaround the issue? I'm having the exact same problem where `ObjectId` within a `dict` does not work.

**Comment by meako689** [comment]
@HazyFish I did not find better workaround, than coercing obj-id's to str on serialization.

```
    @field_validator("details", mode="before")
    def fix_obj_id(cls, value: dict[str, Any]) -> dict[str, Any]:
        for k, v in value.items():
            if isinstance(v, ObjectId):
                value[k] = str(v)
        return value
```

**Comment by sydney-runkle** [comment]
You could use a [`PlainSerializer`](https://docs.pydantic.dev/latest/api/functional_serializers/#pydantic.functional_serializers.PlainSerializer) with `PlainSerializer(lambda v: str(v)`
