### ISSUE TITLE
Error: RuntimeError: Unable to apply constraint strict to schema function-after

### ISSUE THREAD

**Issue by Ryaningli** [pydantic/pydantic#9257]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following code, error reported after execution：

`
Traceback (most recent call last):
  File "E:\store\Testing\testing\test8.py", line 10, in <module>
    class Foo(BaseModel):
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_model_construction.py", line 202, in __new__
    complete_model_class(
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_model_construction.py", line 539, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\main.py", line 607, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 750, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 577, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 913, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1078, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1817, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1900, in new_handler
    schema = self._apply_single_annotation(schema, annotation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1859, in _apply_single_annotation
    maybe_updated_schema = _known_annotated_metadata.apply_known_metadata(metadata, schema.copy())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic\_internal\_known_annotated_metadata.py", line 298, in apply_known_metadata
    raise RuntimeError(f'Unable to apply constraint {constraint} to schema {schema_type}')
RuntimeError: Unable to apply constraint strict to schema function-after
`

### Example Code

```Python
from enum import Enum
from typing import Annotated
from pydantic import ConfigDict, Strict, BaseModel


class SomeEnum(int, Enum):
    SOME_KEY = 1


class Foo(BaseModel):
    model_config = ConfigDict(strict=True, use_enum_values=True)
    foo: Annotated[SomeEnum, Strict(strict=False)]


f = Foo(foo=SomeEnum.SOME_KEY)
print(f.foo)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\16699\.virtualenvs\Testing-fdkT3PoQ\Lib\site-packages\pydantic
               python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: fastapi-0.110.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Ryaningli,

Ah, thanks for the report. Definitely looks like a bug, likely related to the migration of our enum validation to `rust`. Will look into a fix for this for a patch release!

**Comment by sydney-runkle** [comment]
Looks like it's only a problem when we have `use_enum_values` in the config.
