### ISSUE TITLE
Providing `None` for a mandatory `enum.IntFlag` field no longer raises a `ValidationError` but a `ValueError`

### ISSUE THREAD

**Issue by cklmln** [pydantic/pydantic#9260]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Providing `None` for a mandatory `enum.IntFlag` field no longer raises a `ValidationError` but a `ValueError`.

Running the example below with pydantic-2.7.0, pydantic-core-2.18.1 gives:
```
Traceback (most recent call last):
  File "xxx\scratch_16.py", line 18, in <module>
    m = MyModel(flags=None)
        ^^^^^^^^^^^^^^^^^^^
  File "xxx\.venv312\Lib\site-packages\pydantic\main.py", line 175, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "xxx\Python312\Lib\enum.py", line 1409, in _missing_
    raise ValueError(
ValueError: None is not a valid MyFlags

Process finished with exit code 1
```

Running the example with pydantic 2.6.4, pydantic_core 2.16.3 gives:
```
1 validation error for MyModel
flags
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/int_type

Process finished with exit code 0
```
as expected.

### Example Code

```Python
from enum import IntFlag

from pydantic import BaseModel, Field, ValidationError


class MyFlags(IntFlag):
    OFF = 0
    ON = 1


class MyModel(BaseModel):
    flags: MyFlags = Field(
        default=MyFlags(0),
    )


try:
    m = MyModel(flags=None)
except ValidationError as exc:
    print(exc)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: xxx\.venv312\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.110.1 mypy-1.9.0 pydantic-extra-types-2.6.0 pydantic-settings-2.2.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@cklmln,

Thanks for reporting this. I'm guessing this is related to our new `enum` validator implementation in rust. Adding this to the 2.7 fixes milestone!

**Comment by sydney-runkle** [comment]
Looks like we're just not catching this error before the enum constructor itself raises:

```py
from enum import IntFlag

from pydantic import BaseModel, Field, ValidationError


class MyFlags(IntFlag):
    OFF = 0
    ON = 1


class MyModel(BaseModel):
    flags: MyFlags = Field(
        default=MyFlags(0),
    )


try:
    m = MyModel(flags=None)
except ValidationError as exc:
    print(exc)
    """
    Traceback (most recent call last):
    File "/Users/programming/pydantic_work/pydantic/test.py", line 18, in <module>
        m = MyModel(flags=None)
    File "/Users/programming/pydantic_work/pydantic/pydantic/main.py", line 176, in __init__
        self.__pydantic_validator__.validate_python(data, self_instance=self)
    File "/Users/programming/anaconda3/envs/pydantic_env/lib/python3.10/enum.py", line 943, in _missing_
        raise ValueError("%r is not a valid %s" % (value, cls.__qualname__))
    ValueError: None is not a valid MyFlags
    """

IntFlag(None)
"""ValueError: None is not a valid IntFlag"""
```

Looking into this more now...
