### ISSUE TITLE
BaseModel.schema_json() throws AssertionError

### ISSUE THREAD

**Issue by straz** [pydantic/pydantic#9261]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In pydantic 2.6.3, python 3.11.6:

Calling `BaseModel.schema_json()` raises `AssertionError: this is a bug! please report it`

### Example Code

```Python
>>> from pydantic import BaseModel
>>> BaseModel.schema_json()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/straz/Library/Python/3.11/lib/python/site-packages/pydantic/main.py", line 1287, in schema_json
    cls.model_json_schema(by_alias=by_alias, ref_template=ref_template),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/straz/Library/Python/3.11/lib/python/site-packages/pydantic/main.py", line 391, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/straz/Library/Python/3.11/lib/python/site-packages/pydantic/json_schema.py", line 2176, in model_json_schema
    assert '__pydantic_core_schema__' in cls.__dict__, 'this is a bug! please report it'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: this is a bug! please report it
```

### Python, Pydantic & OS Version

```Text
% python3 -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/straz/Library/Python/3.11/lib/python/site-packages/pydantic
               python version: 3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: fastapi-0.110.0 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by Viicos** [comment]
This was raised here: https://github.com/pydantic/pydantic/issues/8896

And improved here: https://github.com/pydantic/pydantic/pull/8928

**Comment by sydney-runkle** [comment]
Yep, thanks @Viicos!
