### ISSUE TITLE
StrEnum isn't coerced into str when used with a Literal

### ISSUE THREAD

**Issue by JesseDeLoore** [pydantic/pydantic#9276]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using a type of string Literals, passing a StrEnum value is not coerced to the string value of the enum.
In v1 this worked.
It could be a configuration issue, but if so I'm not sure which one.

### Example Code

```Python
from typing import Literal
import enum

import pydantic
from pydantic import ConfigDict


class Alphabet(enum.StrEnum):
    Z = "Z"
    Y = "Y"
    X = "X"

class TheBestLetters(pydantic.BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    value: Literal["C", "X"]

print(TheBestLetters(value="C"))
print(TheBestLetters(value=Alphabet.X))

outputs

value='C'
Traceback (most recent call last):
  File "C:\Users\ZD6189\AppData\Roaming\JetBrains\PyCharm2024.1\scratches\test_pydantic_enums_2.py", line 18, in <module>
    print(TheBestLetters(value=Alphabet.X))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZD6189\.venv\geco-311\Lib\site-packages\pydantic\main.py", line 175, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TheBestLetters
value
  Input should be 'C' or 'X' [type=literal_error, input_value=<Alphabet.X: 'X'>, input_type=Alphabet]
    For further information visit https://errors.pydantic.dev/2.7/v/literal_error

expected output:

value='C'
value='X'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\ZD6189\.venv\geco-311\Lib\site-packages\pydantic
               python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: email-validator-1.3.1 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@JesseDeLoore,

If you inherit from `str` in your `Animal` type, all works as expected:

```py
from enum import Enum
from pydantic import BaseModel, Field
import numpy as np


class Animal(str, Enum):

    dog = "dog"
    cat = "cat"


class ModelStr(BaseModel):
    animal: str = Field(..., description="A type of animal")


class ModelEnum(BaseModel):
    animal: Animal = Field(..., description="A type of animal")


numpy_array = np.array(["cat", "dog"])

# this works
ModelStr(animal=numpy_array[0])

# this works
ModelEnum(animal=numpy_array[0])
```

**Comment by sydney-runkle** [comment]
@JesseDeLoore,

Thanks for the question. This behavior makes sense to me - the `use_enum_values` logic only applies to fields of `enum` types. If you need to work around this, you could do:

```py
from typing import Literal
from enum import Enum
import pydantic
from pydantic import ConfigDict


class Alphabet(str, Enum):
    Z = "Z"
    Y = "Y"
    X = "X"

class TheBestLetters(pydantic.BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    value: Literal["C", "X"]

print(TheBestLetters(value="C"))
print(TheBestLetters(value=Alphabet.X.value))

"""
value='C'
value='X'
"""
```

Or, use a custom validator for that field. If you make it an `enum` type instead of `Literal`, you could get the behavior you're expecting.

Closing as resolved, as I don't think this is something we're going to change in the near term.

**Comment by JesseDeLoore** [comment]
Thanks for the answer.
The workaround you provide does indeed work in the simple test case provided.
In our actual use-case the enum is coming from a SQLAlchemy model fed into the model_validate(...), so there is no opportunity to apply that workaround.

What doesn't make sense to me is that StrEnum is very close to being a string and literally casting it to a string actually solves the issue. 
`print(TheBestLetters(value=str(Alphabet.X)))`
Outputs 
`value='X'`

In light of all the other smart coercion Pydantic does it feels weird that such a simple type cast isn't done automatically and requires workarounds.
