### ISSUE TITLE
TypeError: typing.ClassVar[int] is not valid as type argument

### ISSUE THREAD

**Issue by tworedz** [pydantic/pydantic#9374]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, Pydantic Team!

I got issues with ClassVar and optional values. This reproduces only with `ClassVar[int] | None` as type annotation.

I can claim, that it works with usual dataclasses:
```python
from __future__ import annotations

import typing

# from pydantic import dataclasses
import dataclasses


@dataclasses.dataclass
class BaseClass:
    a: typing.ClassVar[int] | None

```

```
Traceback (most recent call last):
  File "/Users/tworedz/workspace/example.py", line 8, in <module>
    @dataclasses.dataclass
     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/dataclasses.py", line 250, in dataclass
    return create_dataclass(_cls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/dataclasses.py", line 241, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 119, in complete_dataclass
    set_dataclass_fields(cls, types_namespace, config_wrapper=config_wrapper)
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 81, in set_dataclass_fields
    fields = collect_dataclass_fields(cls, types_namespace, typevars_map=typevars_map, config_wrapper=config_wrapper)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py", line 296, in collect_dataclass_fields
    ann_type = _typing_extra.eval_type_lenient(dataclass_field.type, types_namespace, cls_localns)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 238, in eval_type_lenient
    return eval_type_backport(value, globalns, localns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 254, in eval_type_backport
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 395, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 905, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 1398, in __or__
    return Union[self, right]
           ~~~~~^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 379, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 502, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 715, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 715, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/tworedz/.pyenv/versions/3.11.9/lib/python3.11/typing.py", line 189, in _type_check
    raise TypeError(f"{arg} is not valid as type argument")
TypeError: typing.ClassVar[int] is not valid as type argument

```

### Example Code

```Python
from __future__ import annotations

import typing

from pydantic import dataclasses


@dataclasses.dataclass
class BaseClass:
    a: typing.ClassVar[int] | None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/tworedz/Library/Caches/pypoetry/virtualenvs/project-p4xqsbJ--py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, May  1 2024, 19:18:55) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: mypy-1.10.0 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Viicos** [comment]
`a: typing.ClassVar[int] | None` means it is either a class variable if it is an `int` or an instance variable if it is `None`, which doesn't really make sense.

You probably meant to do `a: typing.ClassVar[int | None]`

**Comment by tworedz** [comment]
Thanks!
