### ISSUE TITLE
Cannot use `str` as argument to PlainSerializer

### ISSUE THREAD

**Issue by aphedges** [pydantic/pydantic#9447]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

[`PlainSerializer`](https://docs.pydantic.dev/2.7/api/functional_serializers/#pydantic.functional_serializers.PlainSerializer) does not accept the built-in object [`str`](https://docs.python.org/3.12/library/stdtypes.html#str) as its `func` argument. I previously reported this as #8967, and it was reported fixed in #9031 / 5c8afe65a69d9fb127c32fbf288156d7c13da346. However, the newly added test uses `float` instead of `str` as the argument to `PlainSerializer`, but `float` does not trigger this bug.

I have included a stack trace of the thrown exception below:

<details>
<summary>Stack trace</summary>

```python
Traceback (most recent call last):
  File "/Users/ahedges/Downloads/test.py", line 6, in <module>
    class Demo(BaseModel):
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 202, in __new__
    complete_model_class(
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 539, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/main.py", line 626, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 502, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 753, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 580, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 916, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1081, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1820, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1902, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/functional_serializers.py", line 74, in __get_pydantic_core_schema__
    info_arg=_decorators.inspect_annotated_serializer(self.func, 'plain'),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/test/lib/python3.12/site-packages/pydantic/_internal/_decorators.py", line 596, in inspect_annotated_serializer
    sig = signature(serializer)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/3.12.3/lib/python3.12/inspect.py", line 3310, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/3.12.3/lib/python3.12/inspect.py", line 3054, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ahedges/.pyenv/versions/3.12.3/lib/python3.12/inspect.py", line 2635, in _signature_from_callable
    raise ValueError(
ValueError: no signature found for builtin type <class 'str'>
```

</details>

### Example Code

```Python
from typing import Annotated

from pydantic import BaseModel, PlainSerializer


class Demo(BaseModel):
    # Commented-out line below works
    # value: Annotated[str, PlainSerializer(lambda x: str(x))]
    value: Annotated[str, PlainSerializer(str)]
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/ahedges/.pyenv/versions/3.12.3/envs/test/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, May  9 2024, 15:37:42) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-13.6.6-x86_64-i386-64bit
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Viicos** [comment]
Unlike `float`, `str` (and a bunch of builtin types) doesn't have a `__text_signature__` attribute. I'll look into this issue soon

**Comment by aphedges** [comment]
Now that the commit with the fix has been released, I've tested it out and can confirm the bug is solved. Thank you very much!
