### ISSUE TITLE
Ignored Validation and Environment Variables Overriding Init Arguments

### ISSUE THREAD

**Issue by imanshafiei540** [pydantic/pydantic#9516]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm using Pydantic v2 and BaseSettings to read from environment variables. I encountered two problems here. I already posted my issue on the `pydantic-settings` page (https://github.com/pydantic/pydantic-settings/issues/293), but since it's probably a problem with Pydantic, I'm rewriting everything here.

1. Validation should not be ignored even if `extra="allow"` and `populate_by_name=True`
2. Init variables should be prioritized over environment variables.

### Example Code

```Python
from pydantic import Field, StrictStr
from pydantic_settings import BaseSettings, SettingsConfigDict

class MySettings(BaseSettings):
    api_key: StrictStr = Field(..., alias="TEST_API_KEY")
    aws_region: StrictStr = Field(..., alias="AWS_REGION")

    model_config = SettingsConfigDict(extra="allow", populate_by_name=True)

print(MySettings().model_dump())
print(MySettings(api_key="ANOTHER_API_KEY_TO_OVERRIDE").model_dump())
print(MySettings(api_key=111).model_dump())

# First Issue
# Actual Outputs with model_config = SettingsConfigDict(extra="allow", populate_by_name=True)
# {'api_key': 'TEST_API_KEY_VALUE', 'aws_region': 'us-east-1'}
# {'api_key': 'ANOTHER_API_KEY_TO_OVERRIDE', 'aws_region': 'us-east-1'}

# {'api_key': 111, 'aws_region': 'us-east-1'}
# Expected for the last one: ValidationError

# Second Issue
# Actual Outputs with model_config = SettingsConfigDict(extra="ignore", populate_by_name=True)
# {'api_key': 'TEST_API_KEY_VALUE', 'aws_region': 'us-east-1'}
# {'api_key': 'TEST_API_KEY_VALUE', 'aws_region': 'us-east-1'}
# {'api_key': 'TEST_API_KEY_VALUE', 'aws_region': 'us-east-1'}
# Expected: to be able to override with alias
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
pydantic-core version: 2.18.2
pydantic-core build: profile=release pgo=true
install path: /Users/iman.shafiei/Workspace/EDA/skyfox-client/.venv/lib/python3.11/site-packages/pydantic
python version: 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]
platform: macOS-14.4.1-arm64-arm-64bit
related packages: mypy-1.10.0 typing_extensions-4.12.0 pydantic-settings-2.2.1
commit: unknown
```

**Comment by timtylin** [comment]
To add more context to this, things just seem wonky in general if you accidentally provide both the field and the alias when deserializing:

```py
>>> MySettings.validate({"foo":1,"foo_alias":"a"})
MySettings(foo='a', foo=1)
>>> MySettings.validate({"foo":1,"foo_alias":"a"}).model_dump()
{'foo': 1}
>>> MySettings.validate({"foo":1,"foo_alias":"a"}).model_dump_json()
'{"foo":"a","foo":1}'
```

Even in cases where everything passes validation:

```py
>>> MySettings.validate({"foo":"a","foo_alias":"b"})
MySettings(foo='b', foo='a')
>>> MySettings.validate({"foo":"a","foo_alias":"b"}).model_dump()
{'foo': 'a'}
>>> MySettings.validate({"foo":"a","foo_alias":"b"}).model_dump_json()
'{"foo":"b","foo":"a"}'
```

This is with 2.7.3

**Comment by sydney-runkle** [comment]
@imanshafiei540,

Thanks for reporting this. I do feel like we could either:

1. Handle this better
2. Document the expected behavior

**Comment by saulbein** [comment]
Encountered the same issue, though in my case we are using the default `extra="forbid"` which either makes the model validation fail or the type checks complain:
```python
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    my_var: str = Field("", validation_alias="MY_OTHER_VAR")
    class Config:
        populate_by_name=True # works the same whether this is set or not
        extra="forbid"

MyModel(my_var="foo")  # Extra inputs are not permitted [type=extra_forbidden, input_value='foo', input_type=str]
MyModel(MY_OTHER_VAR="foo") # mypy: Unexpected keyword argument "MY_OTHER_VAR" for "MySettings"
```
Environment:
```
pydantic 2.7.1   
pydantic-core 2.18.2         
pydantic-settings 2.2.1
```

Any known workarounds that would both satisfy mypy and not fail in this case?

**Comment by imanshafiei540** [comment]
@saulbein I'm a bit confused about your use case.

I'm trying to get an output with `model_dump()`:

```py
a = MyModel(my_var="foo")
print(a.model_dump())

b = MyModel(MY_OTHER_VAR="bar")
print(b.model_dump())
```

With `populate_by_name = True`, the output is expected for both cases and I'm not getting `Extra inputs are not permitted`:
```py
{'my_var': 'foo'}
{'my_var': 'bar'}
```

With `populate_by_name = False`, again I think the output is expected and you should get the validation error for the first case and no issue with the second one.

```
1 validation error for MyModel
my_var
  Extra inputs are not permitted [type=extra_forbidden, input_value='foo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/extra_forbidden

{'my_var': 'bar'}
```


However, for both cases I'm getting the `mypy==1.10.0` error as well.

`error: Unexpected keyword argument "MY_OTHER_VAR" for "MyModel"  [call-arg]`

`mypy.ini`

```ini
[mypy]
plugins = pydantic.mypy
```

Without `extra = Forbid`, `mypy` is not complaining.

Not sure, but it could be related to this one: https://github.com/pydantic/pydantic/issues/3923
It is also worth creating a new issue if it does not exist already.

The issue I've opened here is mostly about the type validation.

Let me know if I've missed something.
Thanks.

**Comment by imanshafiei540** [comment]
@sydney-runkle Could you elaborate more on those two options you provided?

Do you have something specific in mind by "Handle this better"?

And I'm not sure that the use case I provided is expected for this part ("Document the expected behavior") that you mentioned.

I haven't started investigating the `Pydantic` source code to find the main cause, but I'm happy to work on this if you have anything in mind.

Thank you.

**Comment by saulbein** [comment]
@imanshafiei540 my issue is the alias priority over the property name confusion - just that with `extra = "forbid"` it highlights how the non-alias name is not expected in the constructor even though it's expected in the type plugin.

In your example, the problem is that one of the arguments you pass is ignored (set to a different attribute than intended), while it mine it straight up fails the validation due to the difference in extra handling. 

Since this is undocumented behaviour, I don't know if the constructor is supposed to have both names available to be set or this is a typing issue with the plugin not accounting for aliases. If this is indeed the expected behaviour, then #3923 is closer to my issue.

**Comment by sersorrel** [comment]
This is particularly frustrating/odd with pydantic-settings. My settings model has a field `dry_run` with alias `dry-run`; if I include `dry-run = true` in the config file, then I cannot pass `--dry-run=true` or `--dry-run=false` on the command line. But if the config file instead contains `dry_run = true`, then I _can_ override that with `--dry-run=true` or `--dry-run=false`.

**Comment by imanshafiei540** [comment]
> This is particularly frustrating/odd with pydantic-settings. My settings model has a field `dry_run` with alias `dry-run`; if I include `dry-run = true` in the config file, then I cannot pass `--dry-run=true` or `--dry-run=false` on the command line. But if the config file instead contains `dry_run = true`, then I _can_ override that with `--dry-run=true` or `--dry-run=false`.

@sersorrel I've tried reproducing your issue but haven't been able to. Would you mind providing a sample script and some details about reproducing it? Thanks!

**Comment by sersorrel** [comment]
Sure. Say you have a `src/pkg/__main__.py`:

```python
import os

from pydantic import (
    AliasGenerator,
    AliasChoices,
    ConfigDict,
)
from pydantic.alias_generators import to_snake
from pydantic_settings import (
    BaseSettings,
    PydanticBaseSettingsSource,
    TomlConfigSettingsSource,
    SettingsConfigDict,
)

MODEL_CONFIG = ConfigDict(
    alias_generator=AliasGenerator(
        validation_alias=lambda s: AliasChoices(s, to_snake(s).replace("_", "-")),
    ),
)

class Settings(BaseSettings):
    model_config = MODEL_CONFIG | SettingsConfigDict(
        toml_file="config.toml",
        cli_parse_args=True,
    )

    dry_run: bool = False

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
        *args,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        return super().settings_customise_sources(
            settings_cls,
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
        ) + (TomlConfigSettingsSource(settings_cls),)


settings = Settings()

print("dry-run mode:", settings.dry_run)
```

Then if your `config.toml` contains `dry-run = true`, you will not be able to override this:

```
$ poetry run python -m pkg --dry-run=false
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/me/pkg/src/pkg/__main__.py", line 49, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "/Users/me/pkg/.venv/lib/python3.12/site-packages/pydantic_settings/main.py", line 144, in __init__
    super().__init__(
  File "/Users/me/pkg/.venv/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
dry-run
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden
```

but if the config file instead contains `dry_run = true` with an underscore, it works fine:

```
$ poetry run python -m pkg --dry-run=false
dry-run mode: False
```

**Comment by Viicos** [comment]
I don't know if we change anything regarding the initial report (at least in V2). However, https://github.com/pydantic/pydantic/issues/9516#issuecomment-2151053494 is definitely confusing.

Ideally, it shouldn't be possible to provide both the field name and alias (when both are allowed, by setting `validate_by_name` — `validate_by_alias` being `True` by default). One could argue the one _not_ taking priority can go in extra, but then this leads to the inconsistencies described when serializing.

**Comment by katomaso** [comment]
Well, the behaviour got even weirder

```python
from typing import Annotated

import pydantic

class Message(pydantic.BaseModel):
    sensor_id: Annotated[str, pydantic.Field(alias="sensor ID")]

Message(
    sensor_id="1234"
)
```

Outputs
```
Traceback (most recent call last):
  File ...
    Message(
  File".../.venv/lib/python3.12/site-packages/pydantic/main.py", line 263, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Message
sensor ID
  Field required [type=missing, input_value={'sensor_id': '1234'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
```

When expected is simply  `Message(sensor_id="1234")`


```
Python 3.12.13
pydantic==2.13.4
pydantic-extra-types==2.11.1
pydantic-settings==2.13.1
pydantic_core==2.46.4
```
