### ISSUE TITLE
Failed to create model with two generic parameters when Typevar.default is set

### ISSUE THREAD

**Issue by dmorgoon** [pydantic/pydantic#9519]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Having:
- T1 = TypeVar('T1')
- T2 = TypeVar('T2', default=str)
- class GenModel(BaseModel, Generic[T1, T2])
- class DerivedModel(BaseModel[int])

DerivedModel failed to create with error:
```
Traceback (most recent call last):
  File "/home/user/projects/pydantic_generic_test/test.py", line 13, in <module>
    class DerivedModel(GenModel[int]):
                       ~~~~~~~~^^^^^
  File "/home/user/projects/pydantic_generic_test/.venv/lib/python3.11/site-packages/pydantic/main.py", line 689, in __class_getitem__
    _generics.check_parameters_count(cls, typevar_values)
  File "/home/user/projects/pydantic_generic_test/.venv/lib/python3.11/site-packages/pydantic/_internal/_generics.py", line 380, in check_parameters_count
    raise TypeError(f'Too {description} parameters for {cls}; actual {actual}, expected {expected}')
TypeError: Too few parameters for <class '__main__.GenModel'>; actual 1, expected 2
```

For now the only way to fix it that I found is to rewrite DerivedModel as
```
class DerivedModel(GenModel[int, T2], Generic[T2]):
    pass
```

or
```
class DerivedModel(GenModel[int, str]):
    pass
```

but it kind of makes TypeVar.default useless.

### Example Code

```Python
from pydantic import BaseModel
from typing_extensions import Generic, TypeVar

T1 = TypeVar('T1')
T2 = TypeVar('T2', default=str)


class GenModel(BaseModel, Generic[T1, T2]):
    a: T1
    b: T2


class DerivedModel(GenModel[int]):
    pass
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/projects/pydantic_generic_test/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
                     platform: Linux-6.1.0-18-amd64-x86_64-with-glibc2.36
             related packages: typing_extensions-4.12.0
                       commit: unknown


$ python -c 'from importlib.metadata import version; print(version("typing_extensions"))'
4.12.0

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by sydney-runkle** [comment]
Hi @dmorgoon,

Thanks for your question. Indeed, you'll have to still use one of the `DerivedModel` signatures that you listed above. You can read more about inheritance with generics in our docs [here](https://docs.pydantic.dev/latest/concepts/models/#generic-models).

We also have a section that talks about how the `default` value takes effect during validation and serialization. Closing this as not planned for now, but feel free to let me know if you have any other questions!
