### ISSUE TITLE
`include` and `exclude` are not passed to field serializer contexts

### ISSUE THREAD

**Issue by azmeuk** [pydantic/pydantic#9538]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `model_dump` with `include` and/or `exclude`, I would expect the parameters to be available in the field serializer `SerializationInfo` object, like it is for model serializers.

However, it seems `info.include` and `info.exclude` are always empty.
Is it intentional? If so I could not find documentation about this behavior.

### Example Code

```Python
>>> from pydantic import BaseModel, field_serializer, SerializationInfo
>>> from typing import Any
>>> class Foo(BaseModel):
...     bar : str
...     @field_serializer("bar")
...     def ser_bar(value: Any, info:SerializationInfo):
...         if not info.include:
...             raise ValueError("no include")
...         return value
>>> Foo(bar="baz").model_dump(include={"bar"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eloi/.virtualenvs/pydantic-scim2-dlnh/lib/python3.12/site-packages/pydantic/main.py", line 347, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `ser_bar`: ValueError: no include
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/eloi/.virtualenvs/pydantic-scim2-dlnh/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]
                     platform: Linux-6.9.2-arch1-1-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.0 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@azmeuk,

Thanks for reporting this. Definitely looks like a bug - probably in `pydantic-core`. PRs welcome with a fix - should be a good first issue!

**Comment by nix010** [comment]
@sydney-runkle I think I know what to do with this one. Can you assign me ?

**Comment by sydney-runkle** [comment]
ahhhh @davidhewitt,

Thanks so much for the clarification here. That makes a lot of sense. Closing as resolved.
