### ISSUE TITLE
Frequent occurrence of attributes without errors

### ISSUE THREAD

**Issue by zdlay** [pydantic/pydantic#9600]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After deploying Flask using Gunicorn, I used pydantic and accessed some properties in the class in the postinit method, but encountered an error message indicating that the property does not exist, but it does exist. This issue is still occasional and not always present

使用gunicorn部署flask后，我使用pydantic，并且在post_init方法中访问类中的某些属性但是出现报错，提示属性不存在，但是属性是存在的，并且此问题还是偶尔性的并不是每次都会出现

### Example Code

```Python
from pydantic import ConfigDict, Field, field_serializer
from typing import Optional
from framework import BaseEntity

class ShopCart(BaseEntity):
    """购物车实体"""

    model_config = ConfigDict(from_attributes=True)

    goods_id: Optional[int] = Field(default=None, description='商品ID')
    sku_id: Optional[int] = Field(default=None, description='商品SKU ID')
    thumb_url: Optional[str] = Field(default=None, description='商品缩略图')
    goods_title: Optional[str] = Field(default=None, description='商品标题')
    spec_desc: Optional[str] = Field(default=None, description='规格描述')
    quantity: Optional[int] = Field(default=None, description='数量')
    appid: Optional[str] = Field(default=None, description='应用ID')
    user_id: Optional[int] = Field(default=None, description='用户ID')

    ids: Optional[typing.Union[str, typing.List[int]]] = Field(default=None, description='ID列表')
    goods: Optional[Goods] = Field(default=None, description='商品')
    sku: Optional[GoodsSku] = Field(default=None, description='商品SKU')

    def model_post_init(self, __context: typing.Any) -> None:
        # Error in this
        if self.ids and isinstance(self.ids, str):
                self.ids = ConvertUtils.text_to_list(self.ids)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: D:\develop\anaconda3\envs\glow\Lib\site-packages\pydantic
               python version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by zdlay** [comment]
Traceback (most recent call last):
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/flask/views.py", line 113, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/root/maosheng-saas/framework/core/resource/resource.py", line 106, in dispatch_request
    res = func(**kwargs)
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/root/maosheng-saas/app_application/authentication.py", line 183, in wrapper
    return func(*args, **kwargs)
  File "/root/maosheng-saas/maosheng_api/shop_cart_controller.py", line 36, in get
    total, data = self.service.list_vo(entity, wrapper)
  File "/root/maosheng-saas/shop_application/service/cart_service.py", line 75, in list_vo
    return super().list_vo(entity, wrapper)
  File "/root/maosheng-saas/framework/core/service/service.py", line 104, in list_vo
    return count, self.service_serialize(models)
  File "/root/maosheng-saas/framework/core/service/service.py", line 386, in service_serialize
    return [self.service_serialize(item) for item in obj]
  File "/root/maosheng-saas/framework/core/service/service.py", line 386, in <listcomp>
    return [self.service_serialize(item) for item in obj]
  File "/root/maosheng-saas/framework/core/service/service.py", line 376, in service_serialize
    return self.entity_class.model_validate(obj, context=dict(source='service'))
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/pydantic/main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
  File "/root/maosheng-saas/framework/core/entity/entity.py", line 55, in model_post_init
    super().model_post_init(__context)
  File "/root/maosheng-saas/framework/core/entity/base.py", line 25, in model_post_init
    self.sub_model_post_init(__context)
  File "/root/maosheng-saas/shop_application/entity/goods_sku_entity.py", line 34, in sub_model_post_init
    if self.specs and len(self.specs) > 0:
  File "/root/anaconda3/envs/saas/lib/python3.9/site-packages/pydantic/main.py", line 767, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'GoodsSku' object has no attribute 'specs'
