### ISSUE TITLE
@field_serializer("*") is not compatible with @computed_field when expecting FieldSerializationInfo

### ISSUE THREAD

**Issue by bonauer-pf** [pydantic/pydantic#9683]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

PR #9001 added support for wildcard `field_serializer` functions, similar to how they exist for `field_validator`s.

For wildcard field serializers, it generally makes sense to include the `pydantic.FieldSerializationInfo` parameter, so you can access the field_name or serialization mode.

However, when a `@computed_field` is present on the same model class, this generates an error:

`pydantic.errors.PydanticUserError: field_serializer on computed_field does not use info signature` ([see source](https://github.com/pydantic/pydantic/blob/ff51bc0b3e594778a7728c8f503c2827ce95f71a/pydantic/_internal/_decorators.py#L580-L583))

Please make those two features compatible. We have a "generic serialization handler" declared in a base class, and this limitation means that no child classes can ever make use of computed fields.

Accessing the field name and serialization mode makes sense even for computed fields, could this be supported?

### Example Code

```Python
import pydantic
from typing import Any

class MyModel(pydantic.BaseModel):

    other_field: int = 42

    @pydantic.computed_field
    @property
    def my_field(self) -> str:
        return "foo"

    @pydantic.field_serializer("*")
    def my_field_serializer(self, value: Any, info: pydantic.FieldSerializationInfo) -> Any:
        print(f"{info.field_name} = {value}")
        return value
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
               python version: 3.10.12 (main, Apr 22 2024, 22:00:51) [GCC 11.4.0]
                     platform: Linux-6.5.0-10040-tuxedo-x86_64-with-glibc2.35
             related packages: fastapi-0.103.1 typing_extensions-4.12.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@bonauer-pf,

Thanks for reporting this bug. We'll work to get this fixed!

**Comment by sydney-runkle** [comment]
@ornariece,

Any interest in having a go with this one?

**Comment by nix010** [comment]
I can take this one.

**Comment by ornariece** [comment]
@sydney-runkle @nix010 🙏

**Comment by sydney-runkle** [comment]
@nix010,

Go for it. My thought was, we can try to add support for serialization info to computed fields. If that doesn't work, we'll have to find another approach!

**Comment by sydney-runkle** [comment]
Marking as resolved, given the merged PR in `pydantic-core`. This should be fixed in v2.9!

**Comment by CharlesPerrotMinotHCHB** [comment]
Hi! Any timeline for that release?

**Comment by sydney-runkle** [comment]
Yep - next week! You can use `pydantic-core` v2.23.0 with `pydantic`'s `main` branch if you want the changes now :).

**Comment by CharlesPerrotMinotHCHB** [comment]
Awesome thanks!

**Comment by CharlesPerrotMinotHCHB** [comment]
Hey @sydney-runkle, unfortunately this isn't fixed with Pydantic 2.9.0.
I can still totally reproduce the issue described in the first post.

Used a minimalistic pyproject.toml.
```[project]
name = "pydtest"
requires-python = ">=3.12"

[tool.poetry]
authors = ["Me"]
description = ""
name = "pydtest"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
pydantic = "^2.9.0"
python = "^3.12"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
```

Error I get:
```
cperrotminot@CharlesPM-M1Pro-HCHB pydtest % poetry run python pydtest/test.py 
Traceback (most recent call last):
  File "/Users/cperrotminot/Workspace/promo_applications/platform/aggregator/pydtest/pydtest/test.py", line 6, in <module>
    class MyModel(pydantic.BaseModel):
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 223, in __new__
    complete_model_class(
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 568, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/main.py", line 670, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 741, in _model_schema
    self._computed_field_schema(d, decorators.field_serializers)
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1973, in _computed_field_schema
    return_type_schema = self._apply_field_serializers(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2218, in _apply_field_serializers
    is_field_serializer, info_arg = inspect_field_serializer(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cperrotminot/Library/Caches/pypoetry/virtualenvs/pydtest-KNE1Tm0Q-py3.12/lib/python3.12/site-packages/pydantic/_internal/_decorators.py", line 591, in inspect_field_serializer
    raise PydanticUserError(
pydantic.errors.PydanticUserError: field_serializer on computed_field does not use info signature

For further information visit https://errors.pydantic.dev/2.9/u/field-serializer-signature
```

**Comment by nix010** [comment]
@sydney-runkle Just got some air after a busy while. I just checked it again. There's a check that raise the error, the problem will go away if that block removed.
What do you think ? Don't remmeber there was a check when I was working on it. 
https://github.com/pydantic/pydantic/blob/204e109691c69583e656c6e16a62ad79da2f59b9/pydantic/_internal/_decorators.py#L590-L593

**Comment by sydney-runkle** [comment]
> What do you think ? Don't remmeber there was a check when I was working on it.

I'd say let's remove the check + add full support! Thanks! Welcome back 🥳

**Comment by sydney-runkle** [comment]
Fixed by https://github.com/pydantic/pydantic/pull/10390

**Comment by CharlesPerrotMinotHCHB** [comment]
Any chance of when this could be released @sydney-runkle ?

**Comment by sydney-runkle** [comment]
@CharlesPerrotMinotHCHB,

Will probably have to wait for v2.10, which we're planning to release in late October. You can install from `main` in the meantime, if you'd like this change ASAP.

If there's high demand, we could do another patch with this fix, but probably not for another week or two, as we'd want to bundle in any remaining 2.9 fixes.

**Comment by CharlesPerrotMinotHCHB** [comment]
Totally makes sense, thank you @sydney-runkle!
There is a workaround using `field_validator`, so I'd say it's not that urgent.
