### ISSUE TITLE
Installing 2.7.4 with Poetry is not installing the dependencies

### ISSUE THREAD

**Issue by CF-FHB-X** [pydantic/pydantic#9699]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to install Pydantic==2.7.4 with Poetry (`poetry add pydantic`), it does not install the dependencies (`annotated-types`, `pydantic-core`, and `typing-extensions`). This was tested with the latest version of Poetry (1.8.3) and Python 3.11.5. Installing `pydantic==2.7.3`, though, does install the deps. Also, `pip install pydantic==2.7.4` works as expected.

### Python, Pydantic & OS Version

```Text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\.venv\Lib\site-packages\pydantic\version.py", line 26, in version_info
    import pydantic_core._pydantic_core as pdc
ModuleNotFoundError: No module named 'pydantic_core'
```

**Comment by CF-FHB-X** [comment]
Gah - Poetry's cache was the issue _again_ (ran into similar issue with another unrelated package right after this one). Clearing Poetry's cache seems to have fixed the issue. Sorry!
