### ISSUE TITLE
error: look-around, including look-ahead and look-behind, is not supported

### ISSUE THREAD

**Issue by ning0818** [pydantic/pydantic#9729]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have seen someone raise this issue in my previous issue, but the PR in it did not solve my problem.

### Example Code

```Python
Project:https://github.com/2331892928/AMEN-GoEdge-User_backEnd
Erroecode:

/www/wwwroot/cdn-user-end/main.py:12: DeprecationWarning: `regex` has been depreacated, please use `pattern` instead from Controller.UserService import app as UserService Traceback (most recent call last): File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__') File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 119, in _getattr_no_parents raise AttributeError(attribute) AttributeError: __pydantic_core_schema__ During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/www/wwwroot/cdn-user-end/main.py", line 12, in <module> from Controller.UserService import app as UserService File "/www/wwwroot/cdn-user-end/Controller/UserService.py", line 17, in <module> async def registerUser(request1: Request, File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 944, in decorator self.add_api_route( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 883, in add_api_route route = route_class( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 513, in __init__ self.dependant = get_dependant(path=self.path_format, call=self.endpoint) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 261, in get_dependant type_annotation, depends, param_field = analyze_param( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 444, in analyze_param field = create_response_field( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/utils.py", line 99, in create_response_field return ModelField(**kwargs) # type: ignore[arg-type] File "<string>", line 6, in __init__ File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/_compat.py", line 109, in __post_init__ self._type_adapter: TypeAdapter[Any] = TypeAdapter( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 264, in __init__ self._init_core_attrs(rebuild_mocks=False) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 142, in wrapped return func(self, *args, **kwargs) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 285, in _init_core_attrs self._validator = create_schema_validator( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/plugin/_schema_validator.py", line 50, in create_schema_validator return SchemaValidator(schema, config) pydantic_core._pydantic_core.SchemaError: Error building "str" validator: SchemaError: regex parse error: ^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$ ^^^ error: look-around, including look-ahead and look-behind, is not supported /www/wwwroot/cdn-user-end/main.py:12: DeprecationWarning: `regex` has been depreacated, please use `pattern` instead from Controller.UserService import app as UserService Traceback (most recent call last): File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__') File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 119, in _getattr_no_parents raise AttributeError(attribute) AttributeError: __pydantic_core_schema__ During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/www/wwwroot/cdn-user-end/main.py", line 12, in <module> from Controller.UserService import app as UserService File "/www/wwwroot/cdn-user-end/Controller/UserService.py", line 17, in <module> async def registerUser(request1: Request, File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 944, in decorator self.add_api_route( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 883, in add_api_route route = route_class( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/routing.py", line 513, in __init__ self.dependant = get_dependant(path=self.path_format, call=self.endpoint) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 261, in get_dependant type_annotation, depends, param_field = analyze_param( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 444, in analyze_param field = create_response_field( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/utils.py", line 99, in create_response_field return ModelField(**kwargs) # type: ignore[arg-type] File "<string>", line 6, in __init__ File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/fastapi/_compat.py", line 109, in __post_init__ self._type_adapter: TypeAdapter[Any] = TypeAdapter( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 264, in __init__ self._init_core_attrs(rebuild_mocks=False) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 142, in wrapped return func(self, *args, **kwargs) File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/type_adapter.py", line 285, in _init_core_attrs self._validator = create_schema_validator( File "/www/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydantic/plugin/_schema_validator.py", line 50, in create_schema_validator return SchemaValidator(schema, config) pydantic_core._pydantic_core.SchemaError: Error building "str" validator: SchemaError: regex parse error: ^(?:(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])).*$ ^^^ error: look-around, including look-ahead and look-behind, is not supported
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.0a1
pydantic-core version: 2.18.4
pydantic-core build: profile=release pgo=true
install path: /ww/server/pyporject_evn/cdn-user-end_venv/lib/python3.10/site-packages/pydant python version: 3.10.0 (default, Jun 19 2024,08:44:18) [GCC 9.4.0]
Docker
ic
platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.31
related packages: fastapi-0.111.0 typing_extensions-4.12.2
commit: unknown
```

**Comment by ning0818** [comment]
ErrorCode: 
![Screenshot_20240622_131132](https://github.com/pydantic/pydantic/assets/117955401/0d1a0cd7-b4ba-420e-b04f-ebe9c7f5240d)

**Comment by sydney-runkle** [comment]
Hi,

I'd recommend changing this https://github.com/2331892928/AMEN-GoEdge-User_backEnd/blob/2afa05f98d2263e716feb8d1e71aa7aaecfbaf0b/Controller/UserService.py#L22

To use `pattern` instead of `regex`. Also, you can experiment with the `regex_engine` config setting.

https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.regex_engine

Closing as resolved for now. If you're still experiencing issues, please open an issue with a minimal reproducible example!

**Comment by GPla** [comment]
For people who might stumble across this.
I had this issue with the following model and regex:

```python
class PasswordForm(BaseForm):
    new_password: SecretStr = Field(
        description='New password.',
        min_length=6,
        max_length=24,
        pattern=r'^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).$',
    )
```

Switching to `python-re` solved the issue:

```python
model_config = ConfigDict(regex_engine='python-re')
```
