### ISSUE TITLE
`TypeError: _eval_type() got an unexpected keyword argument 'type_params'` on Python 3.12.3 with pydantic 2.8.0b1

### ISSUE THREAD

**Issue by natehardison** [pydantic/pydantic#9780]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Python 3.12 doesn't have support for the `type_params` keyword argument in `typing._eval_type`:

```
$ python fail.py
Traceback (most recent call last):
  File "/Users/nateh/fail.py", line 4, in <module>
    class SimpleModel(BaseModel):
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 200, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 469, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py", line 132, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 228, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 240, in eval_type_lenient
    return eval_type_backport(value, globalns, localns)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 260, in eval_type_backport
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _eval_type() got an unexpected keyword argument 'type_params'
```

Code for `fail.py` is any `BaseModel` class with at least one member (see example code section below)

### Example Code

```Python
from pydantic import BaseModel


class SimpleModel(BaseModel):
    s: str
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.0b1
        pydantic-core version: 2.20.0
          pydantic-core build: profile=release pgo=true
                 install path: /Users/nateh/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr 15 2024, 17:43:11) [Clang 17.0.6 ]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@natehardison,

Thanks for catching that. Working on a fix now! Looks like we had a ` >= 3.12` check instead of a `3.13` check...

**Comment by natehardison** [comment]
thank you for the fast fix!

**Comment by sydney-runkle** [comment]
@natehardison,

Sure thing! We'll have v2.8 out on Monday with this fix, but you should be able to pull from `main` and get things working once we merge the above PR :).

**Comment by sydney-runkle** [comment]
If a decent number of folks seem to be running into this with the beta, I can also do a v2.8.0b2. Let's just see in the next 24h or so!
