### ISSUE TITLE
`validate_assignment=False` has no effect

### ISSUE THREAD

**Issue by baggiponte** [pydantic/pydantic#9807]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It appears that setting `model_config = Config(validate_assignment=False)` doesn't work. Reprex below:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/private/tmp/test/test.py", line 11, in <module>
    settings = Settings(a=None)
               ^^^^^^^^^^^^^^^^
  File "/private/tmp/test/.venv/lib/python3.11/site-packages/pydantic/main.py", line 192, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
a
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class Settings(BaseModel):
    a: str = "foo"

    model_config = ConfigDict(validate_assignment=False)


if __name__ == "__main__":
    settings = Settings(a=None)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.0
        pydantic-core version: 2.20.0
          pydantic-core build: profile=release pgo=true
                 install path: /private/tmp/test/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr 15 2024, 17:28:11) [Clang 17.0.6 ]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: pydantic-settings-2.3.4 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@baggiponte,

Thanks for reporting this. Definitely a bug. Will roll out a fix for v2.8.1!

**Comment by sydney-runkle** [comment]
@baggiponte,

Thanks for your question. This is actually the expected behavior - `validate_assignment` refers to validation when an instance attribute is changed **after** initialization.

So:

```py
from pydantic import BaseModel, ConfigDict


class Settings(BaseModel):
    a: str = "foo"

    model_config = ConfigDict(validate_assignment=False)


if __name__ == "__main__":
    settings = Settings(a=None)
```

Is expected to error.

```py
from pydantic import BaseModel, ConfigDict


class Settings(BaseModel):
    a: str = "foo"

    model_config = ConfigDict(validate_assignment=False)


settings = Settings()
print(repr(settings))
#> Settings(a='foo')

settings.a = None
print(repr(settings))
#> Settings(a=None)
```

Doesn't fail, because the assignment isn't validated.

**Comment by baggiponte** [comment]
Oh shoot, thanks! Is there a way I can disable validation on instance?
