### ISSUE TITLE
Optional[datetime] creates field annotation of None when name is datetime

### ISSUE THREAD

**Issue by fraser-langton** [pydantic/pydantic#9907]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Seems that using datetime as a field name with a datetime type doesn't work :)

```shell
Traceback (most recent call last):
  File "C:\Users\fraser\Render\render-services\temp.py", line 17, in <module>
    bm = BrokenModel(datetime=datetime.now())
  File "C:\Users\fraser\.virtualenvs\render-services-IYdnVPWc\lib\site-packages\pydantic\main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for BrokenModel
datetime
  Input should be None [type=none_required, input_value=datetime.datetime(2024, 7, 17, 9, 13, 40, 756332), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.8/v/none_required
```

### Example Code

```Python
from datetime import datetime
from typing import Optional

from pydantic import BaseModel


class WorkingModel(BaseModel):
    not_datetime: Optional[datetime] = None


class BrokenModel(BaseModel):
    datetime: Optional[datetime] = None


wm = WorkingModel(not_datetime=datetime.now())

print(BrokenModel.model_fields["datetime"])
# annotation=NoneType required=False default=None

bm = BrokenModel(datetime=datetime.now())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
               python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: fastapi-0.111.0 mypy-1.8.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by fraser-langton** [comment]
further debugging 

```python
class BrokenModel(BaseModel):
    datetime: Optional[datetime] = Field(None)
    int: Optional[int]
    date: Optional[date]
```

```shell
Traceback (most recent call last):
  File "C:\Users\fraser\Render\render-services\temp.py", line 7, in <module>
    class BrokenModel(BaseModel):
  File "C:\Users\fraser\Render\render-services\temp.py", line 8, in BrokenModel
    datetime: Optional[datetime] = Field(None)
  File "c:\users\fraser\appdata\local\programs\python\python38\lib\typing.py", line 261, in inner
    return func(*args, **kwds)
  File "c:\users\fraser\appdata\local\programs\python\python38\lib\typing.py", line 364, in __getitem__
    arg = _type_check(parameters, "Optional[t] requires a single type.")
  File "c:\users\fraser\appdata\local\programs\python\python38\lib\typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Optional[t] requires a single type. Got FieldInfo(annotation=NoneType, required=False, default=None).

```

**Comment by fraser-langton** [comment]
temp fix

```python
from datetime import datetime
from typing import Union

from pydantic import BaseModel

class BrokenModel(BaseModel):
    datetime: Union[datetime, None]

bm = BrokenModel(datetime=datetime.now())
```

**Comment by Viicos** [comment]
This is the same issue as: https://github.com/pydantic/pydantic/issues/7327, https://github.com/pydantic/pydantic/issues/8240, https://github.com/pydantic/pydantic/issues/7309 (see https://github.com/pydantic/pydantic/issues/6646#issuecomment-1633970358 for an explanation).

See also https://github.com/pydantic/pydantic/issues/9093#issuecomment-2017437245, related.

**Comment by sydney-runkle** [comment]
^^ closing as resolved, thanks @Viicos
