### ISSUE TITLE
Validation error: 'str' instances not allowed as a Sequence value

### ISSUE THREAD

**Issue by adriamontoto** [pydantic/pydantic#9915]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

The validate_call decorator from Pydantic raises a validation error when a string is passed as a Sequence. According to the Python documentation, a string is a sequence type, but Pydantic's validation does not currently allow 'str' instances to be considered valid for a Sequence.

It happens with ```from collections.abc import Sequence``` and ```from typing import Sequence```.

### Example Code

```Python
from collections.abc import Sequence
from random import SystemRandom
from typing import Annotated, TypeVar

from pydantic import Field, validate_call

T = TypeVar('T')


@validate_call
def random_choice(sequence: Annotated[Sequence[T], Field(min_length=1)]) -> T:
    return SystemRandom().choice(seq=sequence)


print(isinstance('string', Sequence))  # >>> True
print(random_choice('string'))

# Traceback (most recent call last):
#   File "<your_script>.py", line 24, in <module>
#     print(random_choice('string'))
#           ^^^^^^^^^^^^^^^^^^^^^^^
#   File "<your_pydantic_path>\validate_call_decorator.py", line 60, in wrapper_function
#     return validate_call_wrapper(*args, **kwargs)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "<your_pydantic_path>\_validate_call.py", line 96, in __call__
#     res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# pydantic_core._pydantic_core.ValidationError: 1 validation error for random_choice
# 0
#   'str' instances are not allowed as a Sequence value [type=sequence_str, input_value='string', input_type=str]
#
```

#### Windows Machine
```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
install path:
python version: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
platform: Windows-10-10.0.22631-SP0
related packages: mypy-1.10.1 typing_extensions-4.12.2
commit: unknown
```

#### Linux Machine
```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
install path:
python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
related packages: typing_extensions-4.12.0
commit: unknown
```

**Comment by sydney-runkle** [comment]
In the docs, we've outlined the fact that we don't support strings as sequences:

https://docs.pydantic.dev/latest/api/standard_library_types/#strings
