### ISSUE TITLE
PydanticSerializationError on IPv4Network (Standard Library Type)

### ISSUE THREAD

**Issue by angely-dev** [pydantic/pydantic#9957]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The issue happens when opening the `openapi.json` file generated by FastAPI. But I think this is related to the way Pydantic V2 (de)serializes  objects.

It works on Pydantic V1 but fails on Pydantic V2.

It may be related to:

* https://github.com/pydantic/pydantic/pull/7625
* https://github.com/tiangolo/fastapi/discussions/10097
* https://github.com/tiangolo/fastapi/issues/10321
* https://github.com/tiangolo/fastapi/discussions/11489 (unanswered)

# Working example on Pydantic V1

```py
from fastapi import FastAPI
from ipaddress import IPv4Network
from pydantic import BaseModel, conint
from typing import List

app = FastAPI()

class PrefixListEntry(BaseModel):
    prefix: IPv4Network
    ge: conint(ge=1, le=32) | None = None
    le: conint(ge=1, le=32) | None = None

class PrefixListAdd(BaseModel):
    name: str
    entries: List[PrefixListEntry]

    class Config:
        schema_extra = {
            'example': {
                'name': 'my-prefixlist',
                 'entries': [
                     PrefixListEntry(prefix='10.0.1.1'),
                     PrefixListEntry(prefix='10.0.2.0/24', ge=26, le=31)
                 ] 
            }
        }

@app.post('/prefixlist')
def post_entry(entry: PrefixListAdd):
    pass
```

```sh
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 1.10.0
            pydantic compiled: True
                 install path: /tmp/wksp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```sh
$ uvicorn --reload api:app
INFO:     Will watch for changes in these directories: ['/tmp/wksp']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [194811] using WatchFiles
INFO:     Started server process [194813]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

Now go to: http://localhost:8000/openapi.json

Log:

```
INFO:     127.0.0.1:58772 - "GET /openapi.json HTTP/1.1" 200 OK
```

# Same (failing) example on Pydantic V2

```py
from fastapi import FastAPI
from ipaddress import IPv4Network
from pydantic import BaseModel, conint
from typing import List

app = FastAPI()

class PrefixListEntry(BaseModel):
    prefix: IPv4Network
    ge: conint(ge=1, le=32) | None = None
    le: conint(ge=1, le=32) | None = None

class PrefixListAdd(BaseModel):
    name: str
    entries: List[PrefixListEntry]

    model_config = {
        'json_schema_extra': {
            'examples': [
                {
                    'name': 'my-prefixlist',
                    'entries': [
                        PrefixListEntry(prefix='10.0.1.1').model_dump(),                 # note that I have to use model_dump()
                        PrefixListEntry(prefix='10.0.2.0/24', ge=26, le=31).model_dump() # note that I have to use model_dump()
                    ] 
                }
            ]
        }
    }

@app.post('/prefixlist')
def post_entry(entry: PrefixListAdd):
    pass
```

```sh
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/wksp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 fastapi-0.111.1
                       commit: unknown
```

```sh
$ uvicorn --reload api:app
INFO:     Will watch for changes in these directories: ['/tmp/wksp']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [194455] using WatchFiles
INFO:     Started server process [194457]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

Now go to: http://localhost:8000/openapi.json

Log and error:

```
INFO:     127.0.0.1:46822 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/tmp/wksp/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/tmp/wksp/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1009, in openapi
    return JSONResponse(self.openapi())
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/applications.py", line 981, in openapi
    self.openapi_schema = get_openapi(
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/openapi/utils.py", line 530, in get_openapi
    return jsonable_encoder(OpenAPI(**output), by_alias=True, exclude_none=True)  # type: ignore
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/encoders.py", line 223, in jsonable_encoder
    obj_dict = _model_dump(
  File "/tmp/wksp/venv/lib/python3.10/site-packages/fastapi/_compat.py", line 179, in _model_dump
    return model.model_dump(mode=mode, **kwargs)
  File "/tmp/wksp/venv/lib/python3.10/site-packages/pydantic/main.py", line 364, in model_dump
    return self.__pydantic_serializer__.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'ipaddress.IPv4Network'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/wksp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-41-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 fastapi-0.111.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@angely-dev,

Are you able to come up with a purely pydantic MRE? The following reduced example seems to be working alright:

```py
from ipaddress import IPv4Network
from pydantic import BaseModel
from typing import List
import json

class PrefixListEntry(BaseModel):
    prefix: IPv4Network

class PrefixListAdd(BaseModel):
    name: str
    entries: List[PrefixListEntry]

    model_config = {
        'json_schema_extra': {
            'examples': [
                {
                    'name': 'my-prefixlist',
                    'entries': [
                        PrefixListEntry(prefix='10.0.1.1').model_dump_json(),
                        PrefixListEntry(prefix='10.0.2.0/24').model_dump_json()
                    ] 
                }
            ]
        }
    }

print(json.dumps(PrefixListAdd.model_json_schema(), indent=2))
"""
{
  "$defs": {
    "PrefixListEntry": {
      "properties": {
        "prefix": {
          "format": "ipv4network",
          "title": "Prefix",
          "type": "string"
        }
      },
      "required": [
        "prefix"
      ],
      "title": "PrefixListEntry",
      "type": "object"
    }
  },
  "examples": [
    {
      "entries": [
        "{\"prefix\":\"10.0.1.1/32\"}",
        "{\"prefix\":\"10.0.2.0/24\"}"
      ],
      "name": "my-prefixlist"
    }
  ],
  "properties": {
    "name": {
      "title": "Name",
      "type": "string"
    },
    "entries": {
      "items": {
        "$ref": "#/$defs/PrefixListEntry"
      },
      "title": "Entries",
      "type": "array"
    }
  },
  "required": [
    "name",
    "entries"
  ],
  "title": "PrefixListAdd",
  "type": "object"
}
"""
```

**Comment by angely-dev** [comment]
I am not able to come up with a purely pydantic MRE. It seems I incorrectly assumed the error was from Pydantic Core. I looked at the stack trace and saw the `model_dump` failed on the [`OpenAPI` model defined by FastAPI](https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/models.py#L429). I guess I have to create a discussion/problem in the FastAPI repo.

The example you gave is not really sufficient since it adds double quotes:

```sh
  "examples": [
    {
      "entries": [
        "{\"prefix\":\"10.0.1.1/32\"}",
        "{\"prefix\":\"10.0.2.0/24\"}"
      ],
      "name": "my-prefixlist"
    }
  ],
```

![image](https://github.com/user-attachments/assets/5315da0d-fbb3-4bf0-aa54-8a577ab57289)

Apart from that, why do I have to call `model_dump` or `model_dump_json` on model instances in the examples? That wasn't the case in Pydantic V1, is it also related to how FastAPI dump objects?

Thanks!

**Comment by angely-dev** [comment]
See https://github.com/tiangolo/fastapi/discussions/11885 hoping this won't be ignored.
