### ISSUE TITLE
KeyError when inhering from a self-referencing generic model

### ISSUE THREAD

**Issue by rizar** [pydantic/pydantic#9969]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have this very short code snippet below that crashes with `KeyError`, see stack trace. Should be self-explanatory. Looks like a bug. 

```
python .local/my_issue2.py
/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
Traceback (most recent call last):
  File "/home/toolkit/dist/research-pyllmd/.local/my_issue2.py", line 11, in <module>
    class M2(M1[str]):
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 205, in __new__
    complete_model_class(
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 544, in complete_model_class
    schema = gen_schema.clean_schema(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 448, in clean_schema
    schema = simplify_schema_references(schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 463, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 414, in walk_core_schema
    return f(schema.copy(), _dispatch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 209, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 337, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 447, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 200, in _walk
    schema = self._schema_type_to_method[schema['type']](schema.copy(), f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 209, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 197, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: '__main__.M1:27570992[str:8801856]'
```

### Example Code

```Python
from __future__ import annotations
from typing import Generic, TypeVar
from pydantic.generics import GenericModel

X = TypeVar("X")

class M1(GenericModel, Generic[X]):
    foo: str
    bar: M1[X] | None
    
class M2(M1[str]):
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/toolkit/.conda/envs/tapes/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
                     platform: Linux-5.15.0-1040-nvidia-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 fastapi-0.111.0
                       commit: unknown
```

**Comment by kc0506** [comment]
The bug can be reproduced with the following code:
```python
class M1(BaseModel, Generic[X]):
    bar: M1[X]

class M2(M1[str]):  # KeyError
    pass
```
However, if you explicitly define `bar`, the error goes away:
```python
class M1(BaseModel, Generic[X]):
    bar: M1[X]

class M2(BaseModel):  # No Error
    bar: M1[str]
```

After some investigation, I found that the issue seems to lie in the `complete_model_class(M2, ...)` function. After [generating the core schema](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_model_construction.py#L534), the `bar` field in the `schema` has a `schema_ref` pointing to `M1[str]`, as shown below:
```python
# schema
{
    "cls": <class '__main__.M2'>,
    "schema": {
        "fields": {
            "bar": {
                "schema": {
                    "schema_ref": "__main__.M1:2404800474016[str:140713537539888]",
                    "type": "definition-ref",
                },
                "type": "model-field",
            }
        },
        "model_name": "M2",
        "type": "model-fields",
    },
    "type": "model",
}
```

However, if you dump `gen_schema.defs.definition`, you'll notice that the definition of `M1[str]` is missing:
```python
# gen_schema.defs.definition
{
    "__main__.M2:2404792268160": ...
}
```
This causes an error in subsequent code. You can verify this by manually adding the definition of `M1[str]` to `M2`:
```python
class M2(M1[str]):
    foo: M1[str]
```
In this case, the error disappears.

The definition of `M1` is missing from the definition dictionary because `M2.model_fields['bar']` is:
```python
FieldInfo(annotation=PydanticRecursiveRef, required=True)
```
This means that during the generation, the schema of `bar` will be a single `definition_reference_schema` without generating the full definition and updating the definition dictionary afterwards ([see here](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_generate_schema.py#L857)).

But why does this happen? The `bar` field of `M2` does not have any annotation; it is inherited from `M1[str]`. When `M1[str]` is being created, the type of the `bar` field is set to `PydanticRecursiveRef`, so the `bar` field of `M2` also has an annotation of `PydanticRecursiveRef`.

I'm not entirely sure how to fix this. It seems necessary to generate the schema of `M1[str]` when generating that of `M2`. Perhaps re-evaluation, as seen [in this case](https://github.com/pydantic/pydantic/blob/main/pydantic/_internal/_generate_schema.py#L1170), is needed, but it doesn't seem that this can be done trivially with `PydanticRecursiveRef`.

**Comment by sydney-runkle** [comment]
@kc0506,

Thanks for the great analysis here. I think fixing this problem will close a few issues that are currently open. I have time later this week to take an in depth look here, and I've got my head pretty deep in the schema gen process, so hopefully that'll help.

I'll report back here when I take a closer look.

**Comment by sydney-runkle** [comment]
Hmm, pushing this to my queue for next week - definitely something we want to try to fix for v2.9 by the end of August, though!

**Comment by pchabros** [comment]
Is it the same issue?

This:
```py
class Node(BaseModel, Generic[T]):
    value: T
    children: "Nodes[T]"

Nodes = RootModel[Node[T]]
```
gives error:
```
  File "/nix/store/6w6pnrrqsfij5rhw1qz78fpczaw33702-python3.12-pydantic-2.8.2/lib/python3.12/site-packages/pydantic/_internal/_core_utils.py", line 459, in count_refs
    recurse(definitions[ref], count_refs)
            ~~~~~~~~~~~^^^^^
KeyError: '__main__.Node:275371408[int:139958701343744]'
```
This works:
```py
class Node(BaseModel, Generic[T]):
    value: T
    children: RootModel["Node[T]"]
```
